### ISSUE TITLE
Personen, Orte, Im Anton anzeigen, dass Sie im Projekt verwendet werden? 

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#10]

**Comment by feggimann** [comment]
Die Referenz wird immer folgendermassen gesetzt:
- Akteure: im Feld "Geschichte intern" Verweis "Reisetagebücher JCF, Tagebuch [1794, 1825, 1851]"
- Orte: im Feld "Kommentar" Verweis "Reisetagebücher JCF, Tagebuch [1794, 1825, 1851]"
Nachzulesen im Wiki unter [Registerdaten](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/wiki/Registerdaten-(Entit%C3%A4ten))
