### ISSUE TITLE
Lizenz: Internet Archive Screenshot

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#101]
Ich habe für https://archives.georgfischer.com/objects/129913 einen Screenshot aus einem Werk auf archive.org (https://archive.org/details/ironsteeltownind0000munf/page/20/mode/2up) gemacht. Ist das erlaubt? Wie sieht das mit der Lizenz aus?

**Comment by ChristopherZoller-Blundell** [comment]
Es kommt darauf an... Archive.org erlaubt normalerweise Downloads, wenn ein Werk nicht unter Schutz steht. Da hier kein Download verfügbar ist, würde das darauf hindeuten, dass es einen Schutz gibt. Der Screenshot zeigt jedoch einen Stammbaum. Im Allgemeinen können genealogische Werke wie ein Stammbaum nicht urheberrechtlich geschützt werden, da sie eine Zusammenstellung von Fakten enthalten, die für die Öffentlichkeit zugänglich sind (Rotherham Town Archives). Sollte es eine Kontroverse geben - eine umstrittene väterliche Linie oder etwas in der Art, dass der Versuch eines Gelehrten war, ein heiss umstrittenes historiographisches Problem zu lösen - dann könnte das einen Grund für ein Urheberrecht geben. Die Walker-Familie von Rotherham steht jedoch nicht in einem solchen Fokus. Auch das Layout und die Wahl des Designs des Baumes sind nicht originell, sondern entsprechen eher der Standardform. Daher würde ich sagen, dass der Screenshot in Ordnung und wieder verwendbar ist, solange die Quelle korrekt zitiert wird. Mein einziger Kritikpunkt wäre die Qualität des digitalen Bildes. Ich habe versucht, es Schwarz-Weiss zu machen und die Schatten zu entfernen (werde ich dir per E-Mail schicken).

**Comment by ChristopherZoller-Blundell** [comment]
Nein, das glaube ich nicht. Es ist technisch gesehen im öffentlichen Bereich und auf der Website zugänglich (wenn auch mit Einschränkungen), aber das bedeutet nicht, dass das Buch, das 2003 veröffentlicht wurde, gemeinfrei ist. Der Verlag Sutton ist immer noch im Geschäft. Ich werde noch etwas mehr recherchieren und mich dann bei dir melden wenn ich mehr weiss.

**Comment by ChristopherZoller-Blundell** [comment]
Das muss ich noch einmal genauer untersuchen. Vorläufig ja, aber ich bin mir nicht 100%ig sicher.
