### ISSUE TITLE
Recherche/Lizenzfrage: Stadtarchiv Schaffhausen

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#102]
Ich habe das Bild vom Schwabentor von 1846 heruntergeladen (http://www.stadtarchiv-schaffhausen.ch/online_archivp/daten/sharch3_d5.php?startSequence=1&level1_ID=9&level2_ID=19&level3_ID=353&level4_ID=2155 , 02.06.04/03). Bezüglich den Lizenzen finde ich hier aber nichts. Kann es sein, dass es nicht in der Public Domain ist?

**Comment by ChristopherZoller-Blundell** [comment]
Der Schöpfer des Bildes ist seit mehr als 100 Jahren tot, so dass das Werk nicht mehr urheberrechtlich geschützt ist. Die Frage der Public Domain hängt hier jedoch vom Ersteller des Scans ab - es geht um die Wiederverwendung der Bilddaten. Um sicherzugehen, würde ich empfehlen, Kontakt mit dem Stadtarchiv aufzunehmen.

**Comment by vrukavina** [comment]
Ich merke gerade, dass das Bild sowieso zu klein ist, und daher die Qualität schlecht. Ich muss wie ein anderes nehmen.
Aber vielen Dank für die ausführlich Antwort.
