### ISSUE TITLE
Recherche: Huntsmans Gussstahlmanufaktur zu Attercliffe und Huntsmans Hammerschmiede (ID 1805 und 1687)

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#103]
Es stellt sich die Frage, ob diese zwei Ortschaften dieselben sind oder nicht. Ich habe das Gefühl, dass es sich um zwei verschiedene Werke handelt, zumal Huntsmans Attercliffe Werk nicht am Fluss lag, und daher nicht mit Wasserkraft betrieben wurdem wie das TB 1851 für ID 1687 beschreibt.

**Comment by vrukavina** [comment]
Dieses Gefühl habe ich auch, aber die eindeutigen Beweise fehlen zur Zeit noch. Ich würde vorschlagen, dass wir vorerst beide Orte behalten. Vielleicht wird es in den anderen TBs mehr Info geben.
