### ISSUE TITLE
Recherche: Zeitangaben Querung Ärmelkanal

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#104]
Im TB 1814 S. 206-207: Fischer besteigt am 12. September 1814 "Morgens um acht Uhr" bei Dover das Schiff nach Calais. Er erreicht das andere Ufer "Um elf Uhr und zwanzig Minuten des gleichen Vormittags", nach einer Überfahrt von nicht ganz vierthalb Stunden". 

Ohne Zeitumstellung hätte die Überfahrt gemäss Zeitangaben von acht Uhr und elf Uhr zwanzig Minuten drei Stunden 20 betragen. Hat sich Fischer bei den vierthalb Stunden geirrt?

**Comment by vrukavina** [comment]
Laut Wikipedia würde "vierthalb" drei Ganze und ein halbes bedeuten, was wiederum stimmen würde.
Zitat aus Wikipedia:
"In diesem alten Zählsystem ging es nach anderthalb mit dritthalb (zweieinhalb, d. h. „das erste und das zweite zur Gänze, das dritte zur Hälfte“) und vierthalb (dreieinhalb) weiter.
Dasselbe wird auch in Deutsches Wörterbuch von Jacob Grimm und Wilhelm Grimm genannt: siehe https://woerterbuchnetz.de/?sigle=DWB&lemid=GV08820#0

**Comment by ChristopherZoller-Blundell** [comment]
Ich denke, dass 3 Stunden 20 Minuten gemeint ist (und auch sehr plausibel ist). Calais ist 21,5 Seemeilen von Dover entfernt, was eine durchschnittliche Schiffsgeschwindigkeit von 6 oder 7 Knoten bedeuten würde, was für einen Dampfer oder ein Schiff unter Segel zu dieser Zeit üblich war.

**Comment by NicolauLutz** [comment]
Danke für die Hinweise. Habe im Text mit einer <note> erläutert.
