### ISSUE TITLE
Oxygen: Sonderzeichen nicht angezeigt

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#105]
Im TB 1825 kommt ein griechisches Wort vor (ANTEXNHHKA, Seite 63 im Word). In Oxygen, wie auch hier, werden der erste und viertletzte Buchstabe nicht richtig angezeigt. Wie kann ich das umgehen?

**Comment by ottosmops** [comment]
Ich habe das Word-File nicht. Kannst Du bitte einen Screenshot machen.

**Comment by vrukavina** [comment]
Natürlich!
![TB1825_griech](https://user-images.githubusercontent.com/102786242/195784564-ef36b34d-e774-443f-8bb3-726076f0ac66.jpg)

**Comment by vrukavina** [comment]
Wie sieht es hier aus? Gibt es eine Möglichkeit die fehlenden Zeichen korrekt einblenden zu lassen?

**Comment by NicolauLutz** [comment]
Verwandtes Problem: Bruckzeichen (1/2, etc)

**Comment by ottosmops** [comment]
ANTEXNHΘHKA

**Comment by NicolauLutz** [comment]
Formel in TB 1814 S. 158: 1^2/(1/4)^2 x 15/2 x 50 = 120 x 50 = 6000

**Comment by ottosmops** [comment]
Können wir hier schliessen?
