### ISSUE TITLE
Recherche: Langnose - Ort? Wo?

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#106]
In TB 1825 schreibt Fischer:
> das Schiff die Wellen, und ehe wir daran dachten, befanden wir uns schon auf der Seehöhe vor Langnose, und die Küsten Albions lagen wie eine unermessliche Mappe ausgebreitet vor uns.

Es handelt sich wahrscheinlich um einen Ortsnamen, aber so geschrieben konnte ich den Ort nicht finden.

**Comment by ChristopherZoller-Blundell** [comment]
War das Schiff in dem Tagebuch auf der Irischen See unterwegs? Wenn ja, dann könnte es sich dabei um Langness handeln, eine Halbinsel auf der Isle of Mann.

**Comment by ChristopherZoller-Blundell** [comment]
Es könnte sich auch um einen Irrtum handeln und er meinte Dungeness.

**Comment by vrukavina** [comment]
Es scheint wohl wieder ein Fall für eine Fussnote zu sein. Vielen Dank für deine Interpretationen!
