### ISSUE TITLE
fehlende Datierungen in GFD

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#107]
Bei der Bildersammlung in GFD fehlen noch einige Datierungen. Ist es möglich, diese zu ergänzen? Was haben wir besprochen betr. Datierungen b.c.?

![grafik](https://user-images.githubusercontent.com/92036071/197988710-3a8d8f44-2118-4257-9603-097354fdf066.png)

![grafik](https://user-images.githubusercontent.com/92036071/197988744-c97634f0-5c72-48ac-9ec7-ab8e25b41c45.png)

**Comment by vrukavina** [comment]
Betreffend Angaben vor Christus haben wir nichts festgelegt. Ich habe die Zeitangabe dann in die Beschreibung genommen. Kann man das in Anton überhaupt festhalten?

Bei den restlichen werde ich versuchen mindestens eine Zeitspanne anzugeben.

**Comment by feggimann** [comment]
Daten vor Christus: Felder leerlassen. Andere erledigt
