### ISSUE TITLE
Fatal Error bei Bearbeitung eines Keywords

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#108]
https://archives.georgfischer.com/keywords/8665

Ich klickte auf "bearbeiten" und erhielt die "Fatal Error" Nachricht.

**Comment by NicolauLutz** [comment]
Es funktioniert wieder.

**Comment by ottosmops** [comment]
Da war glaube ich nur kurz die Verbindung nicht da
