### ISSUE TITLE
Anton: ID neu belegen funktioniert teilweise nicht

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#111]
Ich habe bei den Ortsschlagworten die ID 1690 (https://archives.georgfischer.com/places/1690) neu belegt. Den Namen, die Stadt etc. konnte ich anpassen, aber die Änderungen in den Feldern "Beschreibung" und "Kommentar" scheint Anton nicht akzeptieren zu wollen. Nach dem Speichern werden wieder die Angaben von früher (zu Le Locle) angezeigt.

**Comment by vrukavina** [comment]
Das Problem tritt auch bei anderen Antoneinträgen auf. Änderungen in diesen zwei Feldern werden nicht abgespeichert.

**Comment by vrukavina** [comment]
Bei neu erstellten Einträgen werden diese zwei Felder nun gar nicht angezeigt.

**Comment by feggimann** [comment]
@ottosmops Andreas, kannst du dir das anschauen? Danke!

**Comment by feggimann** [comment]
@vrukavina Valerija, testest du bitte auch die entsprechenden Felder bei den Akteuren und Sachschlagwörtern? (Geschichte/Geschichte intern und Description)

**Comment by vrukavina** [comment]
Bei den Akteuren und Sachschlagwörtern funktioniert alles bestens.

**Comment by ottosmops** [comment]
Danke, ich mache mich dran

**Comment by ottosmops** [comment]
@vrukavina  Kannst Du bitte nochmal alles testen. 

Man kann jetzt die Koordinaten von Hand eingeben. Dabei habe ich kleinere Umbauten gemacht, weshalb das noch nicht funktionierte.

**Comment by vrukavina** [comment]
Funktioniert nun wieder einwandfrei. Vielen Dank!
