### ISSUE TITLE
Anton: Fehlermeldung bei Koordinaten

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#114]
Wenn ich bereits bestehende und mit Koordinaten/geonames versehene Einträge bearbeite und die Änderungen abspeichern will, kommt folgende Fehlermeldung:
![Webaufnahme_1-11-2022_111524_archives georgfischer com](https://user-images.githubusercontent.com/102786242/199212174-bf081c7e-81d3-45af-8b8a-b65fbbe9422f.jpeg)

**Comment by ottosmops** [comment]
Ich vermute, dass keine negativen Zahlen zulässig sind. Ich schaue es mir an. Welcher Ort ist das denn?

**Comment by vrukavina** [comment]
Dachte ich mir auch. Wenn man das Minus wegnimmt, stimmen dann aber die Koordinaten nicht..
Das ist Wednesbury.
Vielen Dank!

**Comment by ottosmops** [comment]
Kannst Du die mal umdrehen.

**Comment by vrukavina** [comment]
Nun wird aber ein falscher Ort auf der Karte angezeigt (in der Nordsee).

**Comment by ottosmops** [comment]
gefixt; beim Abspeichern, hat er dann noch das minus entfernt
