### ISSUE TITLE
TEI Publisher/Annotationen: Endloses Laden der Vorschläge

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#115]
Ich wollte bei meinem TB 1825 ausprobieren, ob ich ein paar Orte schon einmal taggen kann. Beim Anklicken lädt dann die Seite einfach endlos lange und es geschieht nichts.
![Bildschirmfoto 2022-11-01 um 12 09 55](https://user-images.githubusercontent.com/102786242/199220444-6956abb1-a1d3-4963-bd99-21bcb06471f3.png)

**Comment by ottosmops** [comment]
Kannst Du nochmal probieren

**Comment by vrukavina** [comment]
Funktioniert wieder. Danke!
