### ISSUE TITLE
Itinerar/Anton: Für genaue Adressen Ortseinträge erstellen oder nicht?

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#116]
IM TB 1825 schreibt JCF auf S. 108:
> Bald nach neun Uhr des Morgens ging ich nach Oxford road, um das Haus No. 50 aufzusuchen, wo ich einen lieben Landsmann und überhaupt mehrere Freunde und Bekannte aus der Schweiz anzutreffen oder zu erfragen hoffte. Mit Schwierigkeit fand ich das Haus, in dieser beinahe eine Meile langen Strasse, traf aber, weil jeder schon an seinem Berufsgeschäfte war, Niemand an.

Nehmen wir auch genaue Adressen als Orteinträge auf? Im Itinerar wäre dann Oxford Road, Haus Nr. 50 als Präzisierung nebst Oxford Road angezeigt. Wie wichtig ist diese zusätzliche Information in diesem Fall? (Es scheint sich auch nicht um ein historisches, resp. leicht recherchierbares Gebäude zu handeln.)

**Comment by NicolauLutz** [comment]
Falls sich die Nummerierung an der Oxford Street nicht geändert hat (das könnte man recherchieren), dann kann wohl das heutige Gebäude als Koordinatenpunkt verwendet werden.

**Comment by vrukavina** [comment]
Lösungsvorschlag FE (Sitzung vom 8. November): Beide als separate Ortseinträge aufnehmen.
