### ISSUE TITLE
Schib: Bezeichnung für Indigene, Religionsangehörige etc.

### ISSUE THREAD

**Issue by HelenaBarteld** [GF-Corporate-Archives/gf-johann-conrad-fischer#125]
Einträge in Namensliste von Schib, die Land oder geografischem Raum zugeordnet werden können, werden in Ortsliste erfasst (z.B. Araber>Arabische Halbinsel; Türken>Türkei, Dänen>Dänemark etc.).

Wie werden die folgenden Fälle gelöst:
- Inkas
- Indianer
- Juden

**Comment by vrukavina** [comment]
@HelenaBarteld Könntest du bitte hier noch den Entscheid/die Lösung aufschreiben und das Issue schliessen?

**Comment by feggimann** [comment]
- Inkas erledigt > Inkareich Place ID 2151
- Indianer: bereits abgedekt mit Keyword 8502 (Wachsfiguren Indianer). Falls darüber hinaus notwendig, als Akteur aufnehmen (ich würde eher weglassen)
- Juden: als Akteur ID aufnehen

**Comment by HelenaBarteld** [comment]
Juden ID 8275
