### ISSUE TITLE
Text TB 1851: Errata nicht klar

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#130]
Im TB 1851 steht auf S. 66:

> [...] , und von ihm weg den Kaiserl. Oestr. Commissair, Herr v. Buschek, auf seinem Bureau, 43, Clarges Street, Picadilly, um das Nöthige wegen dem Versehen im Catalog, Ausstellungsgegenstände von meinem Sohn betr., Herrn Georg Fischer in Hainfeld, zu besprechen.

Bei der Auflistung der Errata steht:

> — 	66, Z. 15 v. u., lies „Hainfeld betreffend“.

Wo würdet ihr das hinzufügen? Was müsste man wegnehmen?
Bsp. Bei "Ausstellungsgegenstände von meinem Sohn Hainfeld betreffend? Ausstellungsgegenstände Hainfeld betreffend, ... ? im Catalog Hainfeld betreffend, Ausstellungsgegenstände von meinem Sohn betr., ..?

**Comment by NicolauLutz** [comment]
Ich hätte gesagt: "Ausstellungsgegenstände von meinem Sohn, Herrn Georg Fischer in Hainfeld betreffend, zu besprechen"
