### ISSUE TITLE
Geonames: fehlende Koordinate und Karte, trotz Verlinkung mit geonames

### ISSUE THREAD

**Issue by HelenaBarteld** [GF-Corporate-Archives/gf-johann-conrad-fischer#131]
Die folgenden Orten konnte ich zwar verlinken mit geonames, es fehlt ihnen allerdings die Koordinate und die Karte.
ID 2035 (Nil)
ID 2017 (New Providence)
ID 2011 (Mersey)
ID 1970 (Chateau de Fontainebleau)
ID 1966 (Illyrien)

Bei diesen zwei ist der Link von geonames nicht anwählbar.
ID 2009 (Marseille)
ID 1942 (Elba)

**Comment by ottosmops** [comment]
Für Marseille (und vermutlich auch Elba) bekomme ich eine Fehlermeldung (in der Browser Console). Der Fehler ist vermutlich aufwändig zu finden.

**Comment by NicolauLutz** [comment]
Weitere IDs ohne Karte:
ID 2027: Regent's Park

**Comment by HelenaBarteld** [comment]
Weiter IDs ohne Karte:
ID 2062: Seine
ID 2051: Petersdom (Rom)
ID 2064: Kathedrale von Saint-Denis (Paris)
ID 2067: Theben
ID 2078: Yorkshire

**Comment by HelenaBarteld** [comment]
Weiter IDs ohne Karte:
ID 2090: Katharinenkloster
ID 2091: Sinai

**Comment by HelenaBarteld** [comment]
Koordinaten für Elba und Marseille wurden manuell gesetzt.

**Comment by ottosmops** [comment]
Elba habe ich auf Geonames korrigiert

**Comment by NicolauLutz** [comment]
Weitere Problem-IDs:

- ID 2099 Highhate Hill

**Comment by ottosmops** [comment]
Was ist das Problem? Geonames ist doch schon verlinkt?

**Comment by HelenaBarteld** [comment]
Weiter IDs verlinkt aber ohne Karte:
Amerika 250
Schloss Brahehus 1508
Katharinenkirche 1518

**Comment by HelenaBarteld** [comment]
Geonames verlinkt, keine Karte:
Grossbritannien 402
Yorkshire 2078
Regentʼs Park 2027
Highgate Hill 2099

**Comment by HelenaBarteld** [comment]
Bei allen IDs Koordinaten manuell eingegeben.
