### ISSUE TITLE
Recherche/Anton: TB 1825, S. 234: Fabrik für hämmerbares Gusseisen

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#133]
Ich kann diese Fabrik nicht eindeutig identifizieren. Einerseits könnte es die bereits auf S. 85-86 erwähnte Malleable iron factory (ID 1858) oder aber eine andere, bspw. Manufaktur von Schmelztigeln? (S. 233), Gussstahl Manufaktur von Atwood? (S. 230)?
Im Text steht nur, dass JCF bereits einmal dort war.
@NicolauLutz Gibt es vielleicht in deinem TB 1825-1827 Hinweise dazu?

**Comment by NicolauLutz** [comment]
Mir scheint, dass es dieselbe von S. 85-86 ist. Möglicherweise auch dieselbe vom TB 1814, S. 79-80.

**Comment by vrukavina** [comment]
Hast du diese dann beim TB 1814 als Ortseintrag aufgenommen? Ich kann sie auf Anton nicht finden/identifizieren.

**Comment by NicolauLutz** [comment]
Nein ich hatte sie nicht aufgenommen. Falls du sie aufnimmst, tagge ich sie
im TB 1814.

Am Di., 22. Nov. 2022 um 14:06 Uhr schrieb vrukavina <
***@***.***>:

**Comment by vrukavina** [comment]
Ich habe sie als ID 1858 aufgenommen.
