### ISSUE TITLE
ID 7790: In welchem Tagebuch?

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#139]
Beim Eintrag ist nicht ganz klar in welchem TB der Akteur erwähnt wird. In jenem von 1814 und 1825 oder jeweils nur in einem dieser zwei?

**Comment by HelenaBarteld** [comment]
Das ist ein Fehler von mir. Nur 1814, ich habe es verbessert.
