### ISSUE TITLE
Schib: Pluralformen im Sachregister

### ISSUE THREAD

**Issue by HelenaBarteld** [GF-Corporate-Archives/gf-johann-conrad-fischer#143]
Manche Wörter gibt Schib im Sachregister in der Pluralform an z.B. Antiquitäten, Backsteine, Banknoten, Braunkohlen. Sollen sie genauso  übernommen werden?

**Comment by vrukavina** [comment]
Meiner Meinung nach ja. In der Einzahl hört es sich für mich persönlich ein wenig determiniert und komisch an.
Ausserm gibt es in der Datenbank bereits auch Schlagwörter in der Pluralform.
Wir werden dies aber bestimmt noch nächsten Dienstag besprechen.

**Comment by HelenaBarteld** [comment]
Pluralwörter im Sachregister Schibs werden auch in der Datenbank als Pluralform aufgenommen.
