### ISSUE TITLE
Schib: Sachregistereinträge in anderen Sprachen

### ISSUE THREAD

**Issue by HelenaBarteld** [GF-Corporate-Archives/gf-johann-conrad-fischer#144]
Wie soll ich mit Einträgen auf Französisch umgehen z.B. Acajou (Mahagoni)? Ins Beschreibungsfeld "Auch Acajou (fr)" und für das Lable (de) die deutsche Übersetzung?
Einträge auf Englisch ins Lable (en) und eine deutsche Übersetzung ins Lable (de) ?

**Comment by NicolauLutz** [comment]
Ich hätte es so gemacht wie du vorschlägst. Gerade beim Französischen handelt es sich manchmal um einen Fachbegriff oder technischen Begriff, da kann man vorgehen wie bei Synonymen ("Auch xxx.")

**Comment by HelenaBarteld** [comment]
Label (de) die deutsche Bezeichnung (selber) übersetzen. In der Beschreibung dann die bei Fischer vorkommenden Schreibvarianten erwähnen.
