### ISSUE TITLE
Schib: was ist ein Bassetwerk S. 85

### ISSUE THREAD

**Issue by HelenaBarteld** [GF-Corporate-Archives/gf-johann-conrad-fischer#145]
Wird im Zusammenhang mit Drehstühlen erwähnt.

**Comment by ChristopherZoller-Blundell** [comment]
Ich vermute, er meint eine Werkstatt für die Produktion von Musikinstrumenten. Ein Basset ist ein altes Musikinstrument, das in der Form zwischen Blockflöte, Klarinette und Saxophon-Prototyp lag. In seinem Tagebuch von 1794 erwähnt er auch eine Bassett-Drehbank - eine kleine Drehbank, die zum Drechseln von Holz verwendet werden kann, um Bauteile für das Instrument herzustellen.  Ich habe den Begriff "Basset-Drehbank" bei niemand anderem als Fischer finden können. "Drehstühlen" in Verbindung mit Basset könnte vielleicht ein anderes Wort dafür sein.

**Comment by HelenaBarteld** [comment]
Auf separater Liste (Dropbox)
