### ISSUE TITLE
Anton: Akteurstyp bei Göttern und Mythenfiguren Vereinheitlichen

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#146]
Einheitlich als Person oder nicht als Person darstellen.
<img width="1234" alt="Screen Shot 2022-12-01 at 15 56 02" src="https://user-images.githubusercontent.com/92101460/205085179-6b326b40-82f2-44ce-bfea-1da86754be23.png">

**Comment by vrukavina** [comment]
Die Angabe fehlt auch bei ein paar wenigen anderen Einträgen. Ich vermute, dass es sich um einen "Flüchtigkeitsfehler" handelt. Ich habe es jetzt bei den Göttern verbessert.
