### ISSUE TITLE
Recherche: Familie Sanderson in Sheffield

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#148]
Personen:
- Charles Sanderson (7538)
- Charles Sandersons Stahlgiesserei (7587)
- Mrs. Sanderson (7588)
- John Sanders (7945)

Orte: 
- Charles Sandersons Stahlgiesserei (Sharrow Vale) (1678)
- Sandersons Gussstahlfabrik (West Street) (2096)

JCF hat mit den Familienmitgliedern ab 1825 zu tun. Abklären, welche Personen er wann und wo trifft.

**Comment by vrukavina** [comment]
Die Orte wurden zusammengelegt. Die ID 1678 (TB 1851) wurde gelöscht.
1851 trifft Fischer ausschliesslich Charles und seine Frau.
