### ISSUE TITLE
Apostrophe 

### ISSUE THREAD

**Issue by ottosmops** [GF-Corporate-Archives/gf-johann-conrad-fischer#151]
Actors:
469
454
1117
7982
4546
7403
6974
6236
7944
1174
6705
7583
7456
8046

**Comment by ottosmops** [comment]
Places:
1205
1632
1700
1710
1715
1758
1796
1847
2027
2089
2095
2105

**Comment by HelenaBarteld** [comment]
Bei den Places sind die Anführungszeichen durch Apostrophe ersetzt. Bei den Actors sieht es nach einer Änderung so aus (Foto). Das sollte wohl nicht so sein? Ich habe dort deshalb bis jetzt nichts ausser in der ID 469 ersetzt.
![Apostrophe_Actors](https://user-images.githubusercontent.com/117972183/207805267-525caa72-cdd1-4998-ba39-70c8aa61ff60.png)

**Comment by ottosmops** [comment]
Du hast dort einen [Gravis](https://de.wikipedia.org/wiki/Gravis_(Typografie)) bzw. ein  [Backticket](https://en.wikipedia.org/wiki/Backtick) verwendet. 

Man muss einen echten [Apostroph](https://en.wikipedia.org/wiki/Apostrophe) nehmen.

Der Backtick kennzeichnet in Markdown (das wir ja auch verwenden) "Quellcode". Damit können z.B. Tags hier im Github ausgezeichnet werden: `<tag>` ohne Backtick wäre der gar nicht zu sehen.
