### ISSUE TITLE
TEI: Orte auf dem Itinerar taggen wenn kein geeignetes Wort existiert?

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#155]
"Den 7ten October 1827. Diesen Morgen unterhielt ich mich mit dem jungen Herrn Gott über die Veränderung der Sitten und (108) Gewohnheiten, welche seit dreissig Jahren auch in dem Norden Englands, unerachtet der noch grössern Abgeschiedenheit von dem übrigen Europa, und der noch mindern Berührung mit dessen Continent, statt gefunden."

Wir wissen, dass sich diese Szene in Leeds abgespielt haben muss, weil JCF ein paar Seiten zuvor erwähnt, dass er nach Leeds reist, und weil Gott in Leeds beheimatet ist. Aber es fehlt ein Wort, mit dem der Ort in diesem Satz gekennzeichnet werden könnte. 

Was tun?

**Comment by NicolauLutz** [comment]
@ottosmops : Wie war das mit Geisterworten oder Anchors?

**Comment by ottosmops** [comment]
Sachanmerkung mit Ort einfügen

**Comment by feggimann** [comment]
inzwischen erledigt
