### ISSUE TITLE
Doppelter Eintrag: Schwedisches Eisen und Schwedisches Gusseisen

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#156]
ID 8989 und ID 9008.

**Comment by HelenaBarteld** [comment]
Ist im Schib unter zwei separaten Einträgen, mit unterschiedlichen Seitenzahlen.

**Comment by NicolauLutz** [comment]
Nicht neu Belegen, sondern lassen, und bei Recherche nochmals draufschauen.
#
Auch Frage nach "verwaisten" Schib-Keywords, die von uns nicht in den Texten getaggd werden.
