### ISSUE TITLE
Annotations: "Vorkommen im Text" - nur Ergebnisse der gleichen Seite angezeigt

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#157]
Zurzeit wird nur das Vorkommen des Wortes auf der gleichen Seite angezeigt.
Sollten aber nicht alle Erwähnungen im gesamten Text vorgeschlagen werden? Das wäre super und noch effizienter..

**Comment by ottosmops** [comment]
@wolfgangmm geht das einfach? Ich dachte, dass das schon so ist.

**Comment by vrukavina** [comment]
Heute funktioniert's.
