### ISSUE TITLE
Annotations: Problem bei in Oxygen im Itinerar kodierten Orten

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#162]
Ich habe das Itinerar wie gewohnt in Oxygen kodiert und die Orte dort getaggt. In Annotations wird der Tag zwar erkannt, aber die Verknüpfung zu Anton scheint zu fehlen.
Ist das normal so?

**Comment by vrukavina** [comment]
![Screenshot 2022-12-13 095016](https://user-images.githubusercontent.com/102786242/207270220-ad511997-3205-4118-81e2-1bf69e128856.png)

**Comment by vrukavina** [comment]
Im TEI Publisher getaggte Orte sehen normalerweise so aus: 
![Screenshot 2022-12-13 095144](https://user-images.githubusercontent.com/102786242/207270728-13b5d040-d5c4-4606-ae49-a2e80481e1ab.png)

**Comment by ottosmops** [comment]
Wie sieht die ID aus?

**Comment by vrukavina** [comment]
ID 1861

**Comment by ottosmops** [comment]
Der Ort kommt von der API https://archives.georgfischer.com/api/places/1861 

Warum er nicht angezeigt wird, weiss ich nicht. Wenn Du den Tag löschst und nochmal tagst im annotations, geht es auch nicht?

Ansonsten würde ich hier kein Problem für die finale Edition sehen.
