### ISSUE TITLE
GFD: 3/76 Bild ersetzen durch Skizze in der "Nouvelle Architecture Hydraulique"?

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#164]
https://archives.georgfischer.com/objects/130164

Auch wenn es ein tolles Bild ist, stellt es die Dampfmaschine dar, wie sie erst nach dem Umbau von 1857 bestand. 

@ChristopherZoller-Blundell: Ich bin wegen dem Newsletter darauf gekommen und habe kurz das Digitalisat der "Nouvelle Architecture Hydraulique" auf Gallica durchgeblättert: es scheint eine Skizze der ursprünglichen Chaillot-Dampfmaschine, wie sie Fischer gesehen hat, darin zu sein. Könnten wir vieleicht im Januar scannen...

**Comment by ChristopherZoller-Blundell** [comment]
@NicolauLutz Das können wir gerne zusammen anschauen und im Januar scannen!

**Comment by feggimann** [comment]
@NicolauLutz @ChristopherZoller-Blundell macht ihr das noch? wenn ja, bitte grad am Montag erledigen, sonst Issue schliessen. Danke.

**Comment by ChristopherZoller-Blundell** [comment]
Das Prony-Bild ist sehr technisch und vermittelt nicht den gleichen Eindruck von Grösse wie das aktuelle Bild, das Menschen zeigt, die die Maschine besuchen. Aus diesem Grund wird das Prony-Bild nicht verwendet werden.
