### ISSUE TITLE
TB 1845: Kleine Skizzen im Text

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#165]
- S. 28

<img width="422" alt="Screen Shot 2022-12-16 at 14 23 42" src="https://user-images.githubusercontent.com/92101460/208107915-a1f97cff-c440-440d-9b93-9881eabd19eb.png">

- S. 37

<img width="441" alt="Screen Shot 2022-12-16 at 14 24 34" src="https://user-images.githubusercontent.com/92101460/208108054-e71fef86-1285-4793-bd1b-4765d50aa908.png">

- S. 52

<img width="435" alt="Screen Shot 2022-12-16 at 14 25 51" src="https://user-images.githubusercontent.com/92101460/208108279-79433081-cdec-43f3-af64-d8a4899babf4.png">

**Comment by vrukavina** [comment]
Wir haben diese bis jetzt immer als Bild eingebunden.

**Comment by NicolauLutz** [comment]
Bilder in Bilderordner Hochgeladen.
