### ISSUE TITLE
Oxygen: Ungewöhnliche Brüche im TB 1845

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#167]
- S. 39: "um die Röhre des Modells, die eine Länge von circa 60 Fuss bei einem Durchmesser von circa 5/4“ inwendige Bohrung"
- S. 70: "das Dutzend Rasiermesser, die zu religiösem Gebrauch für die Türken nur einmal dienen dürfen, aber die Klinge übrigens wie ein anderes Rasiermesser mit seiner Schaale versehen ist, um 22 kr. Münz = 26 2/5 Rolta verkauft wird."

**Comment by ottosmops** [comment]
Einfach manuell korrigieren?

**Comment by ottosmops** [comment]
Obwohl eine einheitliche Darstellung evtl. besser ist, auch wenn im Einzelfall nicht so hübsch.
