### ISSUE TITLE
Recherche: Personenname, Bezeichnung?

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#168]
Im TB 1825 kommt auf der Seite 29-30 folgender Satz vor:
"Ich übersetzte meinem Reisegefährten getreulich die Worte des ehrlichen Jaks, sie schienen ihn aber nicht sonderlich zu erbauen."
Ist hier wohl der Name Jack gemeint? Oder eine Berufs-/Personenbezeichnung?

**Comment by vrukavina** [comment]
Die Textstelle lautet wie folgt: 
"Lächerlich, aber karakteristisch, war die Bezeichnung des Ludwigsritters von dem Bootsmann, der uns von dem Strumer an das Land brachte. „Tell that Gentleman (er wandte sich an mich, weil ich vorher englisch mit ihm gesprochen) with that little silverlit on his coat that i shall get a coach ready for him if the wants one.“ (Ich solle dem Herrn mit dem kleinen Bischen Silber am Rock sagen, dass wenn er eine Kutsche wolle, so werde er ihm sie verschaffen.) Ich übersetzte meinem Reisegefährten getreulich die Worte des ehrlichen Jaks, sie schienen ihn aber nicht sonderlich zu erbauen."

Kann es sein, dass JCF hier den Bootsman als einen Dieb bezeichnet indem er ihn mit dem "Honest Jack" (https://en.wikipedia.org/wiki/Jack_Sheppard) gleichsetzt?

@ChristopherZoller-Blundell Was meinst du Chris?

**Comment by ChristopherZoller-Blundell** [comment]
Du hast Recht, dass Fischer mit seiner ursprünglichen Formulierung "ehrlichen Jaks" "Honest Jack" meinte, aber er bezeichnet den Mann damit nicht als Dieb. Ein "ehrlicher Jack" war eine andere Bezeichnung für einen Matrosen - "Jack" ist hier eine Abkürzung für "Jack Tar" (https://de.wikipedia.org/wiki/Jack_Tar). Honest Jack Tars hatten den Ruf, etwas grob und direkt in ihrer Ausdrucksweise zu sein - plain and simple. "Ehrlich / ehrlich" ist hier, denke ich, sehr wörtlich zu nehmen. Der Matrose hatte keine Ahnung, was das silberne Symbol des Ludwigsritters war, nur dass es ein wichtig aussehendes Stück Silber war, und so wollte er den Mann entsprechend behandeln und vermutete, dass er einer Typ war, der vielleicht eine spezielle Kutsche für seine weiteren Reisen nach der Landung organisiert haben wollte. Vielleicht ist "Lächerlich, aber karakteristisch" hier die für Fischer typische britische Ehrerbietung gegenüber Dingen, die als äussere Symbole des sozialen Ranges angesehen werden?

**Comment by vrukavina** [comment]
Deine Interpretation und Recherche passen natürlich noch besser. Ich bin immer wieder erstaunt und froh, was du alles so weisst/herausfindest. Vielen Dank!
@feggimann Jack Tar ist, wie John Bull auch, eine Allegorie. Nämlich des Matrosen, aber auch der Marine allgemein. Wollen wir ihn als Akteuren aufnehmen? Oder nur eine Fussnote setzen? Oder beides, damit der Vergleich mit Jack Tar wirklich klar ist?
