### ISSUE TITLE
Recherche TB 1825: Jäciturnität

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#171]
S. 77: "[...] die Jäciturnität dieser Insulaner ist wirklich ungemein, und wenn von jedem unnützen Wort soll Rechenschaft gegeben werden, so haben sie in dieser Hinsicht am jüngsten Tag wahrscheinlich weniger zu verantworten, als ihre Nachbarn jenseits des Wassers."

**Comment by NicolauLutz** [comment]
Druckfehler: Taciturnität = Schweigsamkeit (aus dem Lat.)

**Comment by vrukavina** [comment]
Und so banal ist es. :) Vielen Dank!
