### ISSUE TITLE
Recherche TB 1825: Schriften von Owen

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#178]
S. 179: "Es könnte aber allen gelingen, wenn man nur wollte, erwiederte er; haben Sie die Schriften von Owen gelesen ? — Ich sagte, ich kenne Herrn Owen persönlich, schätze seine Philantropie, aber gelesen habe ich von ihm nichts. "

Welche Schriften könnten hier gemeint sein?

**Comment by NicolauLutz** [comment]
Dem Kontext gemäss, insb. die Aussage "Dieses Blatt enthält alles, was erforderlich ist, um die Menschen glücklich zu machen", handelte es sich wohl um eine der allgemeineren philosophischen Werke von Owen: "A New View of Society" (1813/1816) oder "An Explanation of the Cause of Distress which pervades the civilised parts of the world" (1823). Da sie aber nicht im Text erwähnt werden, würde ich sie nicht als Keywords aufnehmen, sondern in einer Note auf die Möglichkeit hinweisen, dass es sich um diese Texte handelt. Ideengeschichtlich ist diese Passage äusserst interessant und auch wichtig für das Verständnis von Fischers intellektuellem Milieu.

**Comment by NicolauLutz** [comment]
Mit der Passage auf S. 190 liesse sich die Schrift glaube ich eruieren.

**Comment by vrukavina** [comment]
Die Informationen auf der Seite 190 genügen doch nicht zur genauen Identifizierung der Schrift, da "A New Society" mehrere Aufsätze beinhaltet und gewisse Themengebiete bei beiden Werken anzutreffen sind. Eine Fussnote scheint mir hier deshalb auch am passendsten.
Vielen Dank für deine Hilfe!
