### ISSUE TITLE
Recherche TB 1825: Was sind Schlaghäspeln?

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#179]
S. 182-183:

> Die Temperatur mag 28° Reaumur gewesen sein, und sie wird weder durch eigentliche Luft noch Dampfheitzung, sondern directe durch den Contact der Zimmerluft, mit vier sehr weiten (27) und die ganze Länge des Zimmers durchlaufenden eisernen Röhren erhalten; also eigentliche Oefen. Gleich neben diesem befand sich das Zimmer mit den Schlaghäspeln, wo das Garn von den Spulen abgehaspelt und die Strangen aufgewunden werden, deren Grösse der Contour bestimmt, wovon dann eine gewisse Anzahl einen Bündel von 15 Pfund bilden."

**Comment by ottosmops** [comment]
https://de.wikipedia.org/wiki/Haspel
