### ISSUE TITLE
Anton: Akteure: Methode zur Eintragung vorchristlicher Lebensdaten

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#18]
Beispiel: https://archives.georgfischer.com/actors/7396

**Comment by ottosmops** [comment]
Geht derzeit nicht und es ist ziemlich aufwändig das zu implementieren.

**Comment by feggimann** [comment]
Datumsfelder leerlassen und Lebensdaten im Biografienfeld eintragen
