### ISSUE TITLE
Dubletteneinträge Actors

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#186]
Bitte folgende IDs überprüfen, ob Dubletten, und bereinigen:

- Beck, Johann Jacob // Beck, Hans Jakob (ID 439 // 7773)
- Bramall // Brammall (ID 7708 // 7788)
- Foad // Food (ID 7833 // 8020)
- Holzapfel // Holtzapffel (ID 7563 // 7564 // 7860)
- Johnson div. (ID 7593 // 7537 // 7885 // 7886)
- Jones div. (ID 7874 // 7875 // 8084)
- LÀrchevêque // Laschevec (ID 7403 // 7428)
- von Engström // von Engeström (ID 7408 // 7825)

**Comment by vrukavina** [comment]
- Beck, Johann Jacob ID 439 beibehalten.
- Bram(m)all: @NicolauLutz würdest du beide beibehalten? (ID 7708 - Familie; ID 7788 - Person)
- ID 7833 beibehalten; Food als alternativen Namen angegeben.
- ID 7563 (Körperschaft) und ID 7564 (Person) beibehalten, Hozlapfel als alternativen Namen angegeben.
- @NicolauLutz ID 7593 und 7885 könnten die gleiche Person sein, oder? Die restlichen IDs würde ich so belassen.
- Alle Jones beibehalten. Es handelt sich hier nicht um Dubletten.
- L'archevêque war Bildhauer. Von Laschevec soll JCF jedoch ein Gemälde gesehen haben. Es kann sein, dass es sich um die gleiche Person handelt, aber mit Sicherheit kann man das nicht sagen.
- @NicolauLutz von Engeström und von Engström - wahrscheinlich dieselbe Person?

Neu zu besetzen: ID 7773, ID 8020, ID 7860

**Comment by NicolauLutz** [comment]
- Bramal ID 7788 würde ich mal beibehalten. evtl. findet man zur Person während der Recherche etwas. Habe aber bei ID 7708 den Schib-Vermerk beigefügt.
- Johnson: ID 7593 ist ein Sheffield-Fabrikant, ID 1775 ist ein London-Fabrikant. Möglicherweise dieselbe Person, aber solange ein positiver Beleg fehlt, würde ich beide separat belassen.
-  Engström: ID 7825 neu besetzen.
