### ISSUE TITLE
Dubletteneinträge Places

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#187]
Bitte folgende IDs überprüfen, ob Dubletten, und bereinigen:

- Eisengiesserei… ID 2085 // 1860 // 1952
- Perkins Dampfmaschinen… ID 1850 // 2095
- Visingsö: ID 1509 // 1967

**Comment by vrukavina** [comment]
Die verschiedenen Eisengiessereien können leider (noch) nicht klar identifiziert werden. Vielleicht liefert das TB 1825-1827 noch Informationen.
Bei den Manufakturen von Perkins, handelt es sich um Werke, die an zwei verschiedenen Adressen/Standorten waren.
Bei Visingsö handelt es sich um eine Dublette: ID 1509 beibehalten, aber den Typ wechseln. Es ist eine Insel, also Typ "Parks, Flächen,..." wählen.

**Comment by NicolauLutz** [comment]
Die IDs 1850 und 2095 zu Perkins Dampfmaschinenfabriken sind zwei verschiedene Fabriken. Perkins wechselte im Zeitraum 1825-1827 seinen Produktionsstandort.
