### ISSUE TITLE
Anton: Inkas und Azteken?

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#194]
Im TB 1845 erwähnt Fischer die Inkas und die Azteken. Wie sollen wir diese Völker taggen? Als Akteure, Orte, oder Sachschlagworte?

**Comment by ChristopherZoller-Blundell** [comment]
"Inkas" und "Azteken" sind Sammelbezeichnungen für die Menschen aus verschiedenen Kulturen und mit unterschiedlichen ethnischen Zugehörigkeiten, die unter den Reichen mit diesen Namen lebten. Da Reiche geografische Phänomene sind, würde ich sagen, dass "Orte" am besten geeignet wäre in diesem Fall. In welchem Zusammenhang bezieht er sich auf sie?

**Comment by feggimann** [comment]
S. Wiki:
![grafik](https://user-images.githubusercontent.com/92036071/212081667-c85e3d5b-0d21-4fc2-9944-282d60df7663.png)

**Comment by HelenaBarteld** [comment]
Wir hatten noch keine Lösung dazu, offenes Issue (125).

**Comment by NicolauLutz** [comment]
@ChristopherZoller-Blundell Es geht um Artifakte der Azteken und Inkas.

**Comment by NicolauLutz** [comment]
Neue Ortstags: Inkareich und Atztekenreich
