### ISSUE TITLE
Recherche: T & S in Sheffield == Turton & Sons?

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#196]
TB 1845 S. 65: Fischer besucht in Sheffield "die Herren T….. & S.., Gussstahl- und Feilenfabrikanten". Könnte es sich um Turton & Sons handeln, die er 1851 besucht, und mit denen er "in freundschaftlichen Verhältnissen" stand?

**Comment by ChristopherZoller-Blundell** [comment]
Ich glaube schon. Im Grace's Guide to British Industrial History gibt es ein Profil von Turton and Sons mit Abbildungen von Plakaten, die bestätigen, dass sie Feilen hergestellt haben: https://www.gracesguide.co.uk/Thomas_Turton_and_Sons
