### ISSUE TITLE
Anführungszeichen TB 1851, S. 57

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#198]
Auf S. 57 gibt es drei Anführungszeichen, aber nur zwei Schlusszeichen. Ist das im Original schon so? Ich würde das stillschweigend korrigieren.

**Comment by vrukavina** [comment]
Ja, ist im Original schon so. Ich passe es im Oxygen und in der clean-Version des Textes an. Die Übersetzerin, falls sie es schon nicht automatisch gemacht hat, wirst du darauf aufmerksam machen, nehme ich an.
Vielen Dank für den Hinweis!
