### ISSUE TITLE
Anführungszeichen mit Guillemets ersetzen

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#200]
Bitte die bisherigen „Anführungszeichen“ überall durch «Guillemets» ersetzen:

Zeichen alt: „
Zeichen neu: «

Zeichen alt: “
Zeichen neu: »

Geht mit Suchen/Ersetzen recht schnell. Soweit ich gesehen habe, sind es nur wenige Stellen je Tagebuch:
- 1794: 2 Stellen
- 1814: 39 Stellen
- 1825: 8 Stellen
- 1851: 36 bzw. 37 Stellen
andere TB noch nicht überprüft.

**Comment by vrukavina** [comment]
1851 korrigiert

**Comment by NicolauLutz** [comment]
1794 und 1814 Korrigiert

**Comment by NicolauLutz** [comment]
1825-1827 auch korrigiert

**Comment by NicolauLutz** [comment]
und 1845

**Comment by vrukavina** [comment]
1825 korrigiert

**Comment by NicolauLutz** [comment]
Alle TBs mit Guillemets versehen.
