### ISSUE TITLE
Recherche: Johann Friedrich Wilhelm oder Johannes Friedrich Müller

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#202]
S. 172: "[...] zimmer waren mit kostbaren Gemälden ganz bedeckt, unter denen (einzeln als Kupferstich) Müllers unübertreffliche Madonna hervorstach [...]".

Meiner Meinung nach ist es, trotz des beinahe identischen Namens, nicht der Kupferstecher/Maler Müller (ID 7912), wie bei Schib angegeben.
Viel plausibler wäre es, anzunehmen, dass es der Herr Müller (ID 8243) war.
Seht ihr das auch so?

**Comment by ChristopherZoller-Blundell** [comment]
Die Art und Weise, wie Fischer über das Kunstwerk schreibt und dabei fast voraussetzt, dass der Leser weiss, um welchen Müller und welchen Kupferstich es sich handelt, deutet für mich darauf hin, dass es zu seiner Zeit ein berühmtes Werk war. Da der Müller mit der ID 8243 für eine Madonna berühmt war, denke ich, dass du Recht hast.

**Comment by vrukavina** [comment]
ID 8243 beibehalten; ID 7912 gelöscht, da der Akteur in keinem Tagebuch vorkommt.
