### ISSUE TITLE
Places ID 2147 Rheinischer Hof

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#203]
Hotel in Köln, aber Land und Geonames für Ghent. Bitte korrigieren

**Comment by vrukavina** [comment]
Land wurde angepasst. Georeferenzierung kann erst gelöscht/ersetzt werden, wenn wir das Hotel identifiziert, resp. die Koordinaten ungefähr rekonstruit haben.
Solche Fälle werden auch in die Liste mit den geonames-Problemfällen aufgenommen werden.
