### ISSUE TITLE
Introduction: Besuch oder Empfehlungssschreiben?

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#204]
TB 1825, S. 155-156: "Den 25. Diesen Morgen erhielt ich von Herrn Lee eine Introduction an Herrn Y., Associé in dem grossen Eisenwerk und der Gussstahlfabrik zu H. O. nahe bei Birmingham; schrieb einen grossen Brief an Herrn Lee zurück; nahm einen Platz in der Diligence auf morgen nach Leeds, und beschloss den Abend mit Einpacken."

Ich bin mir nicht mehr ganz sicher, ob hier Fischer dem Herrn Y. durch Lee physisch vorgestellt wurde oder es sich nur um ein Schreiben handelt, da er am Nachmittag/Abend einen Brief an Lee _zurück_ schreibt.

**Comment by ChristopherZoller-Blundell** [comment]
Ich denke, dass es um ein Schreiben handelt. https://en.wikipedia.org/wiki/Letter_of_introduction

**Comment by NicolauLutz** [comment]
Ich denke auch, dass es sich um ein Empfehlungsschreiben handelt.
