### ISSUE TITLE
gfa-keywords-8481 google Link

### ISSUE THREAD

**Issue by ottosmops** [GF-Corporate-Archives/gf-johann-conrad-fischer#206]
Der Google Link in der Quellen führt nicht auf die Seite des Buches und führt zu einem Fehler im TEI. Ich würde keine Links auf Google Books verwenden. Wenn auf https://archive.org/details/principlesofmech02weisiala

**Comment by NicolauLutz** [comment]
Bei mir funktioniert der Link (Firefox).

**Comment by feggimann** [comment]
Das ist auch eine Grundsatzfrage. Besprechen wir an der nächsten Sitzung. Die Linkangabe müsste sowieso noch umgeschrieben werden. Die Quellenangaben in allen Keywords sind noch nicht bereinigt und vereinheitlicht.

**Comment by feggimann** [comment]
erledigt
