### ISSUE TITLE
Liste der Keyword-Types 

### ISSUE THREAD

**Issue by ottosmops** [GF-Corporate-Archives/gf-johann-conrad-fischer#21]
englisch – deutsch

**Comment by feggimann** [comment]
Deutsch:
- Ereignis
- Objekt
- Masseinheit, Währung
- Sammlung, Kunstwerk
- Verfahren, Prozess, Technik 
- anderes/diverses

Englisch:
- Event
- Object
- Unit of Measurement, Currency
- Collection, Artwork
- Method, Process, Technology 
- other/miscellaneous

**Comment by ottosmops** [comment]
Sollte nun online sein, bitte überprüfen und issue bei Erfolg schliessen.

**Comment by feggimann** [comment]
hat geklappt, alles ok, danke!
