### ISSUE TITLE
Fehlerhaft ausgezeichnete orgNames

### ISSUE THREAD

**Issue by ottosmops** [GF-Corporate-Archives/gf-johann-conrad-fischer#210]
Folgende actors sind in der Datenbank Körperschaften, in den Texten aber mit persName getaggt:

```xml
<orgs-encoded-as-person count="19">
    <org-referenced-as-persName ref="gfa-actors-1081" count-refs="1"/>
    <org-referenced-as-persName ref="gfa-actors-7482" count-refs="1"/>
    <org-referenced-as-persName ref="gfa-actors-7508" count-refs="1"/>
    <org-referenced-as-persName ref="gfa-actors-7536" count-refs="2"/>
    <org-referenced-as-persName ref="gfa-actors-7537" count-refs="1"/>
    <org-referenced-as-persName ref="gfa-actors-7542" count-refs="2"/>
    <org-referenced-as-persName ref="gfa-actors-7563" count-refs="1"/>
    <org-referenced-as-persName ref="gfa-actors-7566" count-refs="4"/>
    <org-referenced-as-persName ref="gfa-actors-7569" count-refs="1"/>
    <org-referenced-as-persName ref="gfa-actors-7571" count-refs="4"/>
    <org-referenced-as-persName ref="gfa-actors-7578" count-refs="3"/>
    <org-referenced-as-persName ref="gfa-actors-7608" count-refs="5"/>
    <org-referenced-as-persName ref="gfa-actors-7612" count-refs="1"/>
    <org-referenced-as-persName ref="gfa-actors-7686" count-refs="1"/>
    <org-referenced-as-persName ref="gfa-actors-7687" count-refs="1"/>
    <org-referenced-as-persName ref="gfa-actors-7688" count-refs="1"/>
    <org-referenced-as-persName ref="gfa-actors-7699" count-refs="1"/>
    <org-referenced-as-persName ref="gfa-actors-7706" count-refs="4"/>
    <org-referenced-as-persName ref="gfa-actors-7712" count-refs="1"/>
</orgs-encoded-as-person>
```

Bitte in den Daten korrigieren.

**Comment by NicolauLutz** [comment]
Wäre es möglich, die Fälle für ein schnelleres Korrigieren auf die jeweiligen Tagebücher zurückzuführen?

**Comment by feggimann** [comment]
Lasst es uns am Dienstag besprechen.

**Comment by ottosmops** [comment]
Hier die vollständige Liste:

```
<result>
    <places count="17">
        <missing-register-data ref="1598"/>
        <missing-register-data ref="gfa-place-20"/>
        <missing-register-data ref="-gfa-places-89"/>
        <missing-register-data ref="gfa-keywords-1784"/>
        <missing-register-data ref="gfa-keywords-1785"/>
        <missing-register-data ref="gfa-keywords-1786"/>
        <missing-register-data ref="gfa-keywords-1880"/>
        <missing-register-data ref="gfa-keywords-1758"/>
        <missing-register-data ref="gfa-places-"/>
        <missing-register-data ref="gfa-places1265"/>
        <missing-register-data ref="gfa-keywords-462"/>
        <missing-register-data ref="gfa-keywords-1815"/>
        <missing-register-data ref="gfa-keywords-1816"/>
        <missing-register-data ref="gfa-palces-142"/>
        <missing-register-data ref="gfa-places-xxxx"/>
        <missing-register-data ref="gfa-places2085"/>
        <missing-register-data ref="1760"/>
    </places>
    <persons count="30">
        <missing-register-data ref="gfa-acttors-7492"/>
        <missing-register-data ref="gfa-actors-7563"/>
        <missing-register-data ref="gfa-actors-7571"/>
        <missing-register-data ref="gfa-actors-7686"/>
        <missing-register-data ref="gfa-actors-7566"/>
        <missing-register-data ref="gfa-actors-7687"/>
        <missing-register-data ref="gfa-actors-7688"/>
        <missing-register-data ref="gfa-actors-7569"/>
        <missing-register-data ref="gfa-actors-7699"/>
        <missing-register-data ref="gfa-actors-7578"/>
        <missing-register-data ref="gfa-actors-7542"/>
        <missing-register-data ref="gfa-actors-7536"/>
        <missing-register-data ref="gfa-actors-7537"/>
        <missing-register-data ref="gfa-actors-8089"/>
        <missing-register-data ref="gfa-actors-7546"/>
        <missing-register-data ref="gfa-keywords-7723"/>
        <missing-register-data ref="gfa-actors-"/>
        <missing-register-data ref="gfa-actors-7712"/>
        <missing-register-data ref="gfa-actors-7729"/>
        <missing-register-data ref="gfa-actors-7608"/>
        <missing-register-data ref="gfa-actors-7612"/>
        <missing-register-data ref="gfa-actors-1081"/>
        <missing-register-data ref="gfa-actors-7508"/>
        <missing-register-data ref="gfa-actors-7482"/>
        <missing-register-data ref="gfa-keywords-7535"/>
        <missing-register-data ref="gfa-actors-7929"/>
        <missing-register-data ref="gfa-keywords-7517"/>
        <missing-register-data ref="gfa-actors-7706"/>
        <missing-register-data ref="gfa-actors-7707"/>
        <missing-register-data ref="gfa-actors-7708"/>
    </persons>
    <orgs count="1">
        <missing-register-data ref="gfa-actors-8090"/>
    </orgs>
    <keywords count="7">
        <missing-register-data ref="gfa-keywords-"/>
        <missing-register-data ref="gfa-kewyords-8482"/>
        <missing-register-data ref="gfa-keywords-1773"/>
        <missing-register-data ref="gfa-keywords-8630-2757"/>
        <missing-register-data ref="gfa-actors-7446"/>
        <missing-register-data ref="gfa-actors-7728"/>
        <missing-register-data ref="gfa-keywords"/>
    </keywords>
</result>
```

**Comment by ottosmops** [comment]
Wenn Ihr den ganzen Ordner in z.B. Visual Studio code öffnet, solltet ihr die Stellen mit Suchen schnell haben.

**Comment by vrukavina** [comment]
<missing-register-data ref="gfa-place-20"/> verbessert im TB 1825: "gfa-places-20"

**Comment by vrukavina** [comment]
Im TB 1851 gewesen und korrigiert:
gfa-actors-7569
gfa-actors-7578
gfa-actors-7542
gfa-actors-7536
gfa-actors-7537
gfa-actors-7612
gfa-actors-1081
gfa-actors-7508
gfa-actors-7482

**Comment by vrukavina** [comment]
@ottosmops Wie gehen wir mit Familien um? z.B. ID 8090 (Familie Gott).
Sollte da <personGrp> verwendet werden? Oder <persName> zusammen mit <surname>?

**Comment by vrukavina** [comment]
> verbessert im TB 1825: "gfa-places-20"

auch noch im TB 1825 gewesen und korrigiert:
-gfa-places-89
gfa-actors-8089
gfa-actors-7929
gfa-actors-8090

**Comment by vrukavina** [comment]
> Hier die vollständige Liste:
> 
> ```
> <result>
>     <places count="17">
>         <missing-register-data ref="1598"/>
>         <missing-register-data ref="gfa-place-20"/>
>         <missing-register-data ref="-gfa-places-89"/>
>         <missing-register-data ref="gfa-keywords-1784"/>
>         <missing-register-data ref="gfa-keywords-1785"/>
>         <missing-register-data ref="gfa-keywords-1786"/>
>         <missing-register-data ref="gfa-keywords-1880"/>
>         <missing-register-data ref="gfa-keywords-1758"/>
>         <missing-register-data ref="gfa-places-"/>
>         <missing-register-data ref="gfa-places1265"/>
>         <missing-register-data ref="gfa-keywords-462"/>
>         <missing-register-data ref="gfa-keywords-1815"/>
>         <missing-register-data ref="gfa-keywords-1816"/>
>         <missing-register-data ref="gfa-palces-142"/>
>         <missing-register-data ref="gfa-places-xxxx"/>
>         <missing-register-data ref="gfa-places2085"/>
>         <missing-register-data ref="1760"/>
>     </places>
>     <persons count="30">
>         <missing-register-data ref="gfa-acttors-7492"/>
>         <missing-register-data ref="gfa-actors-7563"/>
>         <missing-register-data ref="gfa-actors-7571"/>
>         <missing-register-data ref="gfa-actors-7686"/>
>         <missing-register-data ref="gfa-actors-7566"/>
>         <missing-register-data ref="gfa-actors-7687"/>
>         <missing-register-data ref="gfa-actors-7688"/>
>         <missing-register-data ref="gfa-actors-7569"/>
>         <missing-register-data ref="gfa-actors-7699"/>
>         <missing-register-data ref="gfa-actors-7578"/>
>         <missing-register-data ref="gfa-actors-7542"/>
>         <missing-register-data ref="gfa-actors-7536"/>
>         <missing-register-data ref="gfa-actors-7537"/>
>         <missing-register-data ref="gfa-actors-8089"/>
>         <missing-register-data ref="gfa-actors-7546"/>
>         <missing-register-data ref="gfa-keywords-7723"/>
>         <missing-register-data ref="gfa-actors-"/>
>         <missing-register-data ref="gfa-actors-7712"/>
>         <missing-register-data ref="gfa-actors-7729"/>
>         <missing-register-data ref="gfa-actors-7608"/>
>         <missing-register-data ref="gfa-actors-7612"/>
>         <missing-register-data ref="gfa-actors-1081"/>
>         <missing-register-data ref="gfa-actors-7508"/>
>         <missing-register-data ref="gfa-actors-7482"/>
>         <missing-register-data ref="gfa-keywords-7535"/>
>         <missing-register-data ref="gfa-actors-7929"/>
>         <missing-register-data ref="gfa-keywords-7517"/>
>         <missing-register-data ref="gfa-actors-7706"/>
>         <missing-register-data ref="gfa-actors-7707"/>
>         <missing-register-data ref="gfa-actors-7708"/>
>     </persons>
>     <orgs count="1">
>         <missing-register-data ref="gfa-actors-8090"/>
>     </orgs>
>     <keywords count="7">
>         <missing-register-data ref="gfa-keywords-"/>
>         <missing-register-data ref="gfa-kewyords-8482"/>
>         <missing-register-data ref="gfa-keywords-1773"/>
>         <missing-register-data ref="gfa-keywords-8630-2757"/>
>         <missing-register-data ref="gfa-actors-7446"/>
>         <missing-register-data ref="gfa-actors-7728"/>
>         <missing-register-data ref="gfa-keywords"/>
>     </keywords>
> </result>
> ```

@NicolauLutz 
TB 1825 und 1851 bereinigt. .Neue Liste:
        <missing-register-data ref="1598"/>
        <missing-register-data ref="gfa-keywords-1784"/>
        <missing-register-data ref="gfa-keywords-1785"/>
        <missing-register-data ref="gfa-keywords-1786"/>
        <missing-register-data ref="gfa-keywords-1880"/>
        <missing-register-data ref="gfa-keywords-1758"/>
        <missing-register-data ref="gfa-places-"/>
        <missing-register-data ref="gfa-places1265"/>
        <missing-register-data ref="gfa-keywords-462"/>
        <missing-register-data ref="gfa-keywords-1815"/>
        <missing-register-data ref="gfa-keywords-1816"/>
        <missing-register-data ref="gfa-palces-142"/>
        <missing-register-data ref="gfa-places-xxxx"/>
        <missing-register-data ref="gfa-places2085"/>
        <missing-register-data ref="1760"/>

        <missing-register-data ref="gfa-acttors-7492"/>
        <missing-register-data ref="gfa-actors-7563"/>
        <missing-register-data ref="gfa-actors-7571"/>
        <missing-register-data ref="gfa-actors-7686"/>
        <missing-register-data ref="gfa-actors-7566"/>
        <missing-register-data ref="gfa-actors-7687"/>
        <missing-register-data ref="gfa-actors-7688"/>
        <missing-register-data ref="gfa-actors-7699"/>
        <missing-register-data ref="gfa-actors-7546"/>
        <missing-register-data ref="gfa-keywords-7723"/>
        <missing-register-data ref="gfa-actors-"/>
        <missing-register-data ref="gfa-actors-7712"/>
        <missing-register-data ref="gfa-actors-7729"/>
        <missing-register-data ref="gfa-actors-7608"/>
        <missing-register-data ref="gfa-keywords-7535"/>
        <missing-register-data ref="gfa-keywords-7517"/>
        <missing-register-data ref="gfa-actors-7706"/>
        <missing-register-data ref="gfa-actors-7707"/>
        <missing-register-data ref="gfa-actors-7708"/>

        <missing-register-data ref="gfa-actors-8090"/>
        <missing-register-data ref="gfa-keywords-"/>
        <missing-register-data ref="gfa-kewyords-8482"/>
        <missing-register-data ref="gfa-keywords-1773"/>
        <missing-register-data ref="gfa-keywords-8630-2757"/>
        <missing-register-data ref="gfa-actors-7446"/>
        <missing-register-data ref="gfa-actors-7728"/>
        <missing-register-data ref="gfa-keywords"/>

**Comment by vrukavina** [comment]
@ottosmops  Wie gehen wir mit Familien um? z.B. ID 8090 (Familie Gott).
Sollte da personGrp verwendet werden?

**Comment by vrukavina** [comment]
@NicolauLutz Familien werden wie Akteure behandelt. Siehe auch Info-Issue #260. Bitte im Wiki entsprechend festhalten.
