### ISSUE TITLE
Keywords Gussstahl bereinigen

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#213]
Keeywords ID 8482 (Gussstahl) und ID 8523 (Schweissbarer Gussstahl) in einer ID zusammenfassen.

**Comment by NicolauLutz** [comment]
ID 8523 bezieht sich auf den von Fischer um 1808 entwickelten Gussstahl, der sich in Herstellungsweise und Eigenschaften vom englischen (Huntsmannschen) Tiegelgussstahl unterschied. Fischer beherrschte um diese Zeit beide Arten der Gussstahlproduktion, aber beim Pariser Preisausschreiben von 1809 (Schib & Gnade) sowie auf seiner Reise von 1814 betonte er, dass es sich beim gewöhnlichen Gussstahl und bei seinem schweissbaren Gussstahl um zwei verschiedene Produkte handelte. Insofern gleicht der schweissbare Gussstahl dem Meteorstahl als eine "Markenlegierung".

Ich wäre desshalb dafür, beide IDs zu behalten (habe bei ID 8523 die Beschreibung Ergänzt).
