### ISSUE TITLE
TB 1794 - fehlende Tags für Keywords

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#217]
Folgende Keywords waren bisher noch nicht dem 1794 TB zugeordnet. Bitte Tags ergänzen:

- ID 9747 - Segelschiff - TB S. 36 ("Schiffe von drei Masten)
- ID 8628 - Feilenhaumaschine - TB S. 42 ("Feilhauer-Maschinen")
- ID 9328 - Münzpresse - TB S. 48
- ID 9061 - Gasapparat - TB S. 49 ("zur Verfertigung von Gasarten dienliche Instrumente")
- ID 8718 - Zwölfpfünder - TB S. 50

**Comment by NicolauLutz** [comment]
Keywords getaggd
