### ISSUE TITLE
Keywords Brennstahlöfen/Brennstahlfabrik

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#219]
Keywords zu einem zusammenfassen:
- Brennstahlöfen (ID 8904)
- Brennstahlfabrik (ID 9509)

**Comment by vrukavina** [comment]
Ich würde vorschlagen die Brennstahlfabrik (ID 9509) zu behalten und Brennstahlöfen zu löschen. @NicolauLutz Willst du ein Veto einlegen?
