### ISSUE TITLE
Website-Bug: TB 1794 bei Stockholm: Text nicht vollständig angezeigt

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#221]
Die Ansicht auf der Website und die Situation im xml (Zeile 224):

Scheinmbar hängt es mit den tags zusammen. 

![Screen Shot 2023-01-24 at 14 00 27](https://user-images.githubusercontent.com/92101460/214356030-7082d64f-2df0-4984-9ecf-8dde8086ae29.png)
![Screen Shot 2023-01-24 at 13 33 48](https://user-images.githubusercontent.com/92101460/214356062-3f0df262-fc55-46bb-9a7f-acfdc8adb7ba.png)

**Comment by wolfgangmm** [comment]
Hier wird der placeName offenbar übersprungen. Wir müssen @subtype="no_location" mit einer eigenen Regel behandeln.

**Comment by feggimann** [comment]
@subtype="no_location" wird eliminiert und entweder in Anton aufgenommen oder gelöscht. kann bei der Programmierung ignoriert werden, kommt am Ende bei Itinerar nicht mehr vor.

**Comment by wolfgangmm** [comment]
`@subtype="no_location"` wird vorläufig ausgegeben, aber nicht als Ort markiert.
