### ISSUE TITLE
Website: Überlappende Fenster bei Worten mit mehreren Keywords

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#222]
Beispiele aus dem TB 1794:

![Screen Shot 2023-01-24 at 13 13 40](https://user-images.githubusercontent.com/92101460/214356588-c7fb3784-d853-4081-af84-075856e22182.png)
![Screen Shot 2023-01-24 at 13 14 57](https://user-images.githubusercontent.com/92101460/214356616-eb16c44d-7f13-45ce-8558-3df3ad7485dd.png)

**Comment by wolfgangmm** [comment]
Verschachtelte Popups werden nun zusammengefasst

![image](https://user-images.githubusercontent.com/607433/219438942-ff65a6a1-732b-4d62-a81b-820da3ace7fa.png)
