### ISSUE TITLE
GFD für Thüringen und Hessen

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#225]
Die Bilder für die Länder Thüringen (GFD 2/7) und Hessen (GFD 2/6) zeigen die Städte Altenburg und Wiesbaden. Es sind sehr schöne alte Postkarten, aber ich finde sie für Regionen nicht ganz passend. Ich würde sie durch eine Landschaftsaufnahme oder Landkarte ersetzen.

**Comment by vrukavina** [comment]
Wurden ausgewechselt.
