### ISSUE TITLE
Ägyptologe Belzoni (7777) - TB "1815"

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#227]
Im Kommentarfeld in Anton steht das Jahr 1815. Kommt dieser Akteur in deinem TB 1814 vor Nicolau? Falls nein, ist es wohl ein Tippfehler (1825).

**Comment by NicolauLutz** [comment]
Er kommt nicht vor, habe das 1815 gelöscht.
