### ISSUE TITLE
Anton: Wikimediabild bei Schlagworten einblenden

### ISSUE THREAD

**Issue by ottosmops** [GF-Corporate-Archives/gf-johann-conrad-fischer#23]

**Comment by ottosmops** [comment]
Bitte mal anschauen. 

https://archives.georgfischer.com/keywords/8395

Das ist nicht optimal, da die Bilder ziemlich gross sind. Ausserdem ist die Implementierung wackelig. 

Die «Provider ID» sollte mit "File:" beginnen und dann den Dateinamen enthalten

`File:Amor_and_Psyche,_1787_CE,_by_Johan_Tobias_Sergel,_Nationalmuseum,_Sweden.jpg`

**Comment by ottosmops** [comment]
Wenn das ok ist, kann ich es auch für Orte und Akteure einbauen.

**Comment by feggimann** [comment]
Wow, das schaut doch schon super aus. Wegen Wackeligkeit kann ich nicht beurteilen. Beim ersten Aufruf hat man schon gesehen, wie das Bild von oben nach unten geladen wird, ging aber schnell.

Betr. Provider ID: Betrifft das uns beim Eingeben der Metadaten? Oder ist das nur eine Erklärung wie es funktioniert? Ich habe im Bearbeitungsmodus kein zusätzliches Feld gesehen, ich nehme an, die Anzeige erfolgt automatisch wenn es mit Wikimedia verknüpft ist?

Platzierung: Je nach dem wieviele Metadaten (und wie gross der Bildschirm) verschwindet das Foto unten aus dem Bildschirm. Wäre ev. eine Platzierung in der rechten Spalte unter den externen Links denkbar? Allerdings - wenn es dort viele Links gibt, dann rutscht es auch nach unten... Was meinst du? Wenn wir es auch für Orte und Akteure verwenden, dann stellt sich insb. bei den Orten die Frage nach der Platzierung. Google Maps geht nur über die linke Spalte, von daher wäre da rechts nicht so schlecht. Oder wie siehst du das?

**Comment by ottosmops** [comment]
Provider ID muss eingegeben werden wenn man Resourcen manuell verknüpft. Anton erwartet nun genau diese Form bei Wikimediaeinträgen.

**Comment by ottosmops** [comment]
Platzierung muss man ausprobieren. Wenn Ihr mal ein paar Wikimedias drin habt, mache ich das mal für Akteure und Orte und mache einen Vorschlag.

**Comment by ottosmops** [comment]
OK die Platzierung ist geändert und die Funktion ist für Akteure und Orte ebenfalls drin. Ausserdem greift er jetzt auf ein kleineres Bild zu. Das ist möglicherweise auch nicht schneller, weil dieses wohl erst hergestellt werden muss (bei wikimedia).
