### ISSUE TITLE
Vorkommen TB: ID 133 Schweden

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#230]
Im Kommentarfeld stehen unrealistische Angaben: Reisetagebücher JCF, Tagebuch 1794, 1814, 1825, 1827, 1856, 1864.

**Comment by vrukavina** [comment]
Bei ID 1843 handelt es sich auch um einen nicht ganz für uns typischen Fehler. Auffällig ist, dass beide Einträge zuletzt und um dieselbe Zeit von anton bearbeitet wurden.

**Comment by feggimann** [comment]
Das ist nichts besorgniserregends, würde ich sagen, sondern zwei realistische Tippfehler. Anton erscheint häufiger als Bearbeiter, z.B. wenn IDs gelöscht werden und die hinteren Datensätze in der DB-Struktur "nachrücken". 

Ich habe beide Einträg korrigiert (Schweden laut Vorkommen in Schib)
