### ISSUE TITLE
Places Thomas Turton/Sheaf Works

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#234]
Kann man die Place IDs 1721 (Thomas Turton and Sons) und 1679 (Sheaf Works) zusammenfassen?

Daneben gibt es auch Actor Thomas Turton (ID 7542)

**Comment by vrukavina** [comment]
Ich habe die Einträge zusammengefasst unter der ID 1721 für die Firma Thomas Turton and Sons.
ID 1679 wurde gelöscht. Der Akteur wurde korrigiert und verlinkt.
