### ISSUE TITLE
Doppelte ID, Schlagwörter: Drahtzug 8973 / Drahtzieherei 9741

### ISSUE THREAD

**Issue by HelenaBarteld** [GF-Corporate-Archives/gf-johann-conrad-fischer#236]

**Comment by vrukavina** [comment]
@NicolauLutz Ich würde sie zusammenlegen. In Wikipedia wurde der Begriff Drahtzug als Lemma genommen. Wollen wir das so übernehmen und Drahtzieherei dann als Alternative Namensform in der Beschreibung erwähnen?
