### ISSUE TITLE
Orte ID 104 (Niederlande) und 1140 (Holland)

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#237]
Im TB 1794 habe ich Holland mit der ID 104 getaggd. Gibt es einen Grund, wieso die ID 1140 angelegt wurde? Bezieht sie sich auf die Provinz Holland?

**Comment by vrukavina** [comment]
Ich würde deine Frage bejahen. Wie genau das damalas JCF in seinen Tagebüchern mit der Bezeichnung nahm, ist tatsächlich nicht ganz eindeutig, würde ich meinen.

**Comment by NicolauLutz** [comment]
Also sollen wir die ID 104 für den Staat Niederlande verwenden?

**Comment by feggimann** [comment]
Ich würde die beiden IDs zusammenfassen und andere Namensform benutzen. Ich glaube nicht, dass JCF bewusst zw Provinz und Staat unterschieden hat, sondern einfach die geografische Region gemeint hat.

**Comment by NicolauLutz** [comment]
In diesem Fall würde ich ID 104 behalten.

**Comment by vrukavina** [comment]
TB 1825 und 1851 wurden neu getaggt (ID 105).
