### ISSUE TITLE
ID 56 (Temperguss); ID 9007 (Hämmerbares Gusseisen); ID 8990 (Weiches Eisen)

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#238]
Vorschlag: 

- Tagebücher mit ID 9007 taggen (Schib & Gnade S. 66-72 konsultieren, wo Fischer über das Hämmerbare Gusseisen spricht, da nicht alle Stellen die Bezeichnung "Hämmerbares Gusseisen" verwenden) 
- ID 56 und ID 9007 gegenseitig verlinken
- Evtl. beim ersten Tag von ID 9007 mit Fussnote auf ID 56 und Temperguss verweisen (betrifft v.A. TBs 1814 und 1825) 
- ID 8990 löschen

**Comment by feggimann** [comment]
Nur Temperguss (ID 56) behalten und hämmerbares Gusseisen und weiches Eisen darin in die Beschreibung nehmen.

**Comment by vrukavina** [comment]
Alle drei IDs wurden zusammengelegt in ID 56 (Temperguss und in den Tagebüchern entsprechend neu getaggt. Keine Fussnoten gesetzt.
