### ISSUE TITLE
Grundsatz zu Alternativnamen bei Sachschlagworten

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#239]
Ich würde andere Namensformen nur auflisten, wenn sie sich grundlegend unterscheiden. Betrifft vor allem die Alternativen bei den Schib-Schlagworten (z.B. bei Eisenerz "auch Erz genannt").

Also falls Ihr solche seht, gerne löschen.

**Comment by HelenaBarteld** [comment]
Können wir damit noch warten? Sonst gehen beim taggen Seiten verloren.
