### ISSUE TITLE
Tagging: Tags haben sich verschoben auf Z. 69 bis 71 (S. XIII)

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#24]
<img width="586" alt="Screen Shot 2022-01-28 at 16 01 32" src="https://user-images.githubusercontent.com/92101460/151580130-c1d86a3c-02f0-4951-89c8-4a6e16f95512.png">

**Comment by ottosmops** [comment]
Mist melde ich weiter an Wolfgang

**Comment by ottosmops** [comment]
@NicolauLutz bitte von Hand korrigieren

**Comment by ottosmops** [comment]
Bitte neues issue eröffnen, wenn klar ist wie wir den Fehler reproduzieren können
