### ISSUE TITLE
TB 1851: Heureka - korrekte griechische Schreibweise

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#240]
TB 1851, Seite 56: Erzählung von Archimedes und dem Ausruf "Heureka". Aktuell steht im Text eine Schreibweise, die weder die Originalschreibweise bei JCF noch die korrekte Schreibweise ist. 

Bitte in Text Schreibweise aus JCF-Edition und dazu Fussnote mit korrekter griechischer Schreibweise.

**Comment by vrukavina** [comment]
Lösungsvorschlag von NL:  im Tagebuch: <emph rend="italic>ἐνρηκα!</emph> mit Note: <note>Korrekte Schreibweise: ηὕρηκα. </note>
Habe ich so korrigiert.
