### ISSUE TITLE
Doppelt? ID 9052 Freihandel und ID 9167 Handelsfreiheit

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#246]
Die beiden Begriffe kommen im TB 1851 vor. Schib hat sie einzeln aufgenommen. Brauchen wir wirklich beide?

**Comment by feggimann** [comment]
Er benutzt beide an allen vier Stellen im Sinn des rechtlich vereinbarten Freihandels. Gerne zusammennehmen. Ich würde Freihandel behalten, da Handelsfreiheit schnell mit Handlungsfreiheit verwechselt wird...

**Comment by vrukavina** [comment]
Zusammengelegt. ID 9167 gelöscht.
