### ISSUE TITLE
Actor ID 7546 (Familie Fenn)

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#247]
In der Beschreibung steht:

" Im Tagebuch 1851 erklärt Johann Conrad Fischer, dass er «Herrn Fenn Ironmonger» bereits 1794 kennengelernt hatte. Fischer besucht das Familienunternehmen auch 1814 und 1851."

weiter unten:

"Fischer begegnete allen drei Generationen der Fenns:
    1794: Daniel und Samuel Fenn
    1814: Samuel Fenn
    1851: Joseph Fenn"

Es gibt neben der ID 7546 (Familie Fenn) nur noch einen Eintrag zu Samuel Fenn (ID 7464). Dieser gehört laut Vermerk zum TB 1851. 

Im Beschreibungstext ist zudem vom "Familienunternehmen" die Rede. Besser Eintrag Körperschaft statt Familie?

Bitte überprüfen und bereinigen.

**Comment by NicolauLutz** [comment]
Eintrag als Körperschaft gemacht. Für Samuel Fenn müsste Valerija nachschauen, aber nach den Einträgen im Post-Directory zu urteilen muss es im TB 1851 Joseph Fenn gewesen sein.

**Comment by vrukavina** [comment]
Im TB kommt ein Herr Fenn nur einmal vor:
"Da es kaum 1 Uhr war, und erst nach 4 Uhr gespeisst wird, ging ich nach Newgatestreet, um Herrn Fenn Ironmonger, mit dem ich schon im Jahr 1794, als ich damals bei Mr. Rhé, Mechaniker in London, arbeitete, bekannt wurde, zu besuchen, traf ihn aber nicht auf dem Comptoir an, [...]" (S. 12)
Laut dieser Aussage meint Fischer hier aber bestimmt nicht Joseph, sondern Samuel oder Daniel. Klar kann man das nicht sagen. Im Eintrag zu JCF im Grace's Guide (https://www.gracesguide.co.uk/J._C._Fischer) hat jemand Herr Fenn als Samuel identifiziert. Deshalb hatte ich Samuel aufgenommen. Korrekterweise, wenn man nur dem Text und unserer Recherche folgt, dann kann Samuel nicht eindeutig identifiziert werden. Beide Brüder hatten ihr "Comptoir" ja an der Newgate Street..

Wollen wir hier nur das Unternehmen behalten/taggen? Und dann, zumindest bei mir im TB 1851, in einer Fussnote darauf verweisen, dass nicht eruiert werden konnte, ob Fischer Samuel oder Daniel Fenn meint.

**Comment by feggimann** [comment]
Ich finde das eine gute Lösung, nur die Körperschaft zu taggen und die Personeneinträge zu löschen. Dort stehen alle Namen der Familienmitglieder in den relevanten Jahren. Fenn kommt neben 1814 und 1851 auch im TB 1846 mehrmals vor, zudem offenbar als späterer Verweis auf das TB 1794. Es scheint ein wichtiger Kontakt für JCF gewesen zu sein, auch wenn er immer nur von "Mr Fenn" spricht.
