### ISSUE TITLE
Neues Keyword: Britannia Brücke

### ISSUE THREAD

**Issue by ChristopherZoller-Blundell** [GF-Corporate-Archives/gf-johann-conrad-fischer#249]
TB 1851, Seite 73 "und den Weg für die Eisenbahn zwischen dem festen Land und der Insel Anglesia bilden, um selbige auf ihre thurmgleichen an die 109 Fuss hohen gemauerten Lager, hinaufzuheben." 

Hier muss ein neues Keyword getaggt werden. Fischer bezieht sich hier auf eine [berühmte Brücke](https://en.wikipedia.org/wiki/Britannia_Bridge) von Robert Stephenson. Diese Brücke wurde ein Jahr vor der Great Exhibition fertiggestellt und war ein technisches Wunderwerk ihrer Zeit. 

Es gibt ein Bild auf Wikimedia Commons: https://commons.wikimedia.org/wiki/File:Britannia_Bridge_-_circa_1852.jpg

**Comment by vrukavina** [comment]
Wow, vielen Dank für den Hinweis und die Recherche! Ich lege gleich die nötigen Einträge im Anton an.
