### ISSUE TITLE
webseite: Farben für Links

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#252]
Ist es in der Entwurfsphase möglich, etwas grellere Farben für die Links der getaggten Keywords/Places/Actors zu verwenden? Die aktuellen Farben sind perfekt nach CD-Vorgabe und für das finale Layout sehr schön, aber v.a. die Keywords im Dunkelblau sind für die Überprüfung und Bearbeitung schlecht sichtbar.

**Comment by wolfgangmm** [comment]
Kontrastreichere Farben gewählt.
