### ISSUE TITLE
webseite: Inhaltsverzeichnis und Navigation/Blättern

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#253]
Wir wären froh, für die Navigation ein Inhaltsverzeichnis zu haben. Muss noch nicht die finale Darstellung sein, aber es erleichtert das Arbeiten.

Zudem Navigation nicht nur mit einfachem Pfeil vor-/rückwärts sondern auch mit Doppelpfeil auf erste/letzte Seite eines Tagebuchs.

**Comment by wolfgangmm** [comment]
Inhaltsverzeichnis nun vorhanden
