### ISSUE TITLE
webseite: Anzeige von Inhalten der Keywords/Places/Actors

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#255]
Die Anzeige von Texten der Keywords etc. in den weissen Popup-Fenstern stimmt nicht mehr: Inhaltstexte der Keywords etc. erscheinen als Fussnoten und im Fenster erscheinen nur Lebensdaten, Koordinaten u.ä.

<img width="1250" alt="Bildschirmfoto 2023-02-03 um 17 47 07" src="https://user-images.githubusercontent.com/92036071/216660984-804217bc-9e49-473a-9b9a-75c8f29f6dc8.png">
<img width="1309" alt="Bildschirmfoto 2023-02-03 um 17 51 49" src="https://user-images.githubusercontent.com/92036071/216661008-bcca5069-2a86-4ad9-88ff-74a7b9a28de0.png">
<img width="1815" alt="Bildschirmfoto 2023-02-03 um 17 46 33" src="https://user-images.githubusercontent.com/92036071/216661029-bf345795-9885-4578-a0fa-23850936db46.png">

**Comment by wolfgangmm** [comment]
Sollte behoben sein.,
