### ISSUE TITLE
webseite: Nummerierung von Seiten

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#257]
Eine Seitennummerierung wäre sinnvoll. Lässt sich das machen? z.B. Durchnummerierung der Titel (heads)

**Comment by windauer** [comment]
Ich habe jetzt vor jeden H1 Titel eine "Seitennummer"  generiert, echte Seitennummern haben wir ja m.W. nicht. Passt das so wie im Screenshot gezeigt? In [reisetagebuch-1.xml](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/blob/master/src/reisetagebuch-1.xml#L50) Zeile 50, gibt es bei der Aufzählung einen Fehler, da wäre es sehr hilfreich, wenn das leere `<div>` entfernt werden könnte, oder gibt es einen speziellen Anlass, warum das dort steht @feggimann , @wolfgangmm ?

**Comment by feggimann** [comment]
@NicolauLutz : Kannst du helfen betr div in TB 1794, Zeile 50?

**Comment by NicolauLutz** [comment]
Die <div> auf Z 50 hat eigentlich den Titel "Jugend und Ausbildung". Wurde wahrscheinlich nicht angezeigt, weil da ein <pb> dazwischen stand. Ich habe den <pb> verschoben, sollte nun besser kommen. 

Ansonsten müsste man diese <div> auch mit passendem <@type> ausstatten. @windauer

**Comment by windauer** [comment]
@NicolauLutz ja, der type auf dem div fehlt irgendwie, wobei ich mir nicht klar bin, ob das auch einfach ein "day" ist.

**Comment by NicolauLutz** [comment]
Ich habe ihm mal type="day" zugewiesen, können es Morgen aber genauer besprechen. @ottosmops @feggimann

**Comment by feggimann** [comment]
> Ich habe jetzt vor jeden H1 Titel eine "Seitennummer" generiert, echte Seitennummern haben wir ja m.W. nicht.

@windauer Die Nummerierung ist tatsächlich etwas verwirrend neben dem Titel. Ich würde sie doch wieder weglassen. Dafür die Titel (heads) im Inhaltsverzeichnis durchnummerieren.

**Comment by windauer** [comment]
done
