### ISSUE TITLE
webseite: grosse Bildanzeige ohne Detailtext

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#258]
In der grossen Bildanzeige nicht den ganzen Beschreibungstext anzeigen. Nur erste Zeile bis zur Leerzeile sowie die Bildlegende (Titel des Bildes). Dann Link zum Registereintrag des entsprechenden Keywords/Actors/Places mit den Detailangaben und dem ganzen Fliesstext.

<img width="1815" alt="Bildschirmfoto 2023-02-03 um 18 09 12" src="https://user-images.githubusercontent.com/92036071/216665277-bae8ab5f-4d01-4cbf-a395-77ffd912f00b.png">

**Comment by wolfgangmm** [comment]
![image](https://user-images.githubusercontent.com/607433/220139805-9af259b8-4ba9-4d5a-b09d-edbc44a95555.png)
