### ISSUE TITLE
TEI Publisher: Tagging mit TEI-Publischer ergibt "gf-" statt "gfa-" in ref="" 

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#26]

**Comment by ottosmops** [comment]
@vrukavina Das sollte gefixt sein? Wenn ja Ticket bitte schliessen, wenn nein bitte nochnal kommentieren

**Comment by NicolauLutz** [comment]
@ottosmops Habe gerade getestet, auf dem neuen Server ergibt das Tagging "gf-" statt "gfa-"

**Comment by wolfgangmm** [comment]
@NicolauLutz offenbar war die Version auf dem Server doch nicht ganz up to date. Habe die Anwendung nochmal neu installiert. Jetzt sollte das richtige Prefix kommen.

**Comment by ottosmops** [comment]
schliessen?
