### ISSUE TITLE
Familien (info)

### ISSUE THREAD

**Issue by ottosmops** [GF-Corporate-Archives/gf-johann-conrad-fischer#260]
Infor für @windauer und @wolfgangmm 

Familien werden in der Edition wie Personen verwendet/behandelt. 

Im Text werden sie mit persName getaggt. Im actors.xml sind sie als personGrp mit `role="family"` getaggt. 

Ab dem nächsten TEI Export sollte das so drin sein.

**Comment by windauer** [comment]
done
