### ISSUE TITLE
Listen (actors, keywords, places)

### ISSUE THREAD

**Issue by ottosmops** [GF-Corporate-Archives/gf-johann-conrad-fischer#261]
info für @windauer und @wolfgangmm 

- bibl vom type image enthalten nun einen Titel  
- Darstellung ist noch zu besprechen (als Legende? Link in den Anton (type="anton-image") , wo die weiteren Infos zum Bild zu finden sind)

**Comment by windauer** [comment]
Umsetzung habe ich so gemacht, wie in #284 bzw #285 beschrieben. Zudem habe ich Keywords analog zu Places und Actors umgesetzt
