### ISSUE TITLE
Links in acors, keywords and places

### ISSUE THREAD

**Issue by ottosmops** [GF-Corporate-Archives/gf-johann-conrad-fischer#262]
@windauer 

Ist es beim Abgleich der Daten mit den Texten (Löschen nicht vorkommender Personen, Keywords usw.) einfach möglich folgende Transformation einzubauen:

//p/ref/@target deren Inhalt mit https://archives.georgfischer.com/places oder https://archives.georgfischer.com/actors oder https://archives.georgfischer.com/actors beginnen sollen:

- wenn die Entität in der Edition vorkommt auf die Edition umgeschrieben werden 
- wenn nicht so belassen werden (auf Anton zeigen)

**Comment by windauer** [comment]
ich habe das Skript auf alle Registerdaten angewandt und die Daten hochgeladen. Bite gerne einmal kontrollieren, ob das so passt @ottosmops

**Comment by feggimann** [comment]
erledigt
