### ISSUE TITLE
Place ID 1707 Laboratoire des essais Quellenlink

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#264]
Der Quellenlink bei Place ID 1707 (Laboratoire des essais) funktioniert nicht, auf diversen Browsern ausprobiert.

Bitte überprüfen

**Comment by vrukavina** [comment]
Bei mir funktioniert er. Ich habe ihn aber nochmals ausgewechselt. Funktioniert es jetzt auch bei dir?

**Comment by vrukavina** [comment]
Funktioniert nun.
