### ISSUE TITLE
Was für eine Lizenz?

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#265]
Ich konnte endlich das Unternehmen "E. Rhodes & Co." identifizieren und ein passendes Bild für unser GFD finden: eine Anzeige aus dem Jahre 1828 (https://hawleysheffieldknives.com/n-fulldetails.php?val=r&kel=1046).
Das Bild scheint, wie auch der Text, von einer Publikation entnommen zu sein, die 2013 veröffentlicht wurde- Tweedale's Directory of Sheffield Cutlery Manufacturers 1740-2013.
Dürfen wir dieses digitale Bild verwenden? Unter welcher Lizenz?

**Comment by feggimann** [comment]
Es gibt kein Impressum auf der Homepage und keine Kontaktangabe. Das Buch (wie vermutlich auch die Webseite) hat Geoffrey Tweedale im Eigenverlag herausgegeben. Ich würde das Portrait vom Museum Sheffield nicht verwenden, aber die Werbung von 1828 schon. Als Lizenz "© Geoffrey Tweedale - Tweedale's Directory of Sheffield Cutlery Manufacturers 1740-2013 [2nd edition]"
