### ISSUE TITLE
Keywords Stöchiometrie (ID 9544)

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#266]
Stöchiometrie kommt genau einmal vor - TB 1851. Ich schlage vor es zu löschen und stattdessen mit Chemie (ID 604) zu taggen.

**Comment by vrukavina** [comment]
ID 9544 gelöscht. Stöchiometrie in der Beschreibung bei ID 604 (Chemie) kurz erwähnt.
