### ISSUE TITLE
Keywords Beschreibung ergänzen: Mutterstempel, Stahlmuster, Fischers Stahl

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#267]
Bitte für diese Keywords eine kurze Beschreibung und wenn möglich externe Links hinzufügen, damit wir TB 1851 abschliessen können:
- Mutterstempel (ID 9333)
- Stahlmuster (ID 9499)
- Fischers Stahl (ID 9474)

**Comment by vrukavina** [comment]
Mutterstempel wurde zusammengelegt mit Matrize (ID 8342). ID 9333 wurde gelöscht.
Bei der ID 9499 geht aus den Texten meiner Meinung nach klar hervor, dass es sich um Stahlmuster im Sinne von Stahlproben, -beispielen handelt. Seht ihr das auch so? Sollen wir das Schlagwort löschen?
Bei der ID 9474 verstehe ich nicht, was Schib als Fischers Stahl bezeichnet - den Meteorstahl? Diesen hat er aber auch separat aufgenommen..

**Comment by NicolauLutz** [comment]
Zu ID 9474 (Fischers Stahl): 
Schib hat damit alle Stellen gekennzeichnet, die Stahl aus Fischers Produktion zum Thema haben. Es handelt sich also nicht um eine bestimmte, sondert bezeichnet je nach Kontext verschiedene Stahlsorten: im TB 1814 sein Tiegelstahl, TB 1825 den Meteorstahl, etc. 

Das KW ist noch Sinvoll, da diese Stellen per Volltextsuche nicht alle gefunden werden können. Ich würde das KW behalten und in der Beschreibung das so erläutern.

**Comment by vrukavina** [comment]
Wie soll das im Text getaggt werden, wenn wir die spezifischen Stahlsorten schon getaggt haben? Ich glaube wir können dasselbe Wort nicht zweimal mit dem gleichen Tag (hier: term/keyword) versehen.

**Comment by feggimann** [comment]
Müssen wir mit Andreas klären ob das geht. Ich würde das Keyword mal behalten und in diesem Sinn beschreiben. Betr. Tagging können wir morgen kurz besprechen.
@ottosmops: Kann ein Wort mit zwei verschiedenen Keywords getaggt werden? Müsste eigentlich gehen, oder? Wie wenn man ein Wort mit Actor und Place gleichzeitig taggt.

**Comment by NicolauLutz** [comment]
> Wie soll das im Text getaggt werden, wenn wir die spezifischen Stahlsorten schon getaggt haben? Ich glaube wir können dasselbe Wort nicht zweimal mit dem gleichen Tag (hier: term/keyword) versehen.

Hier würde ich (Bzw. Helena) nach Schib gehen. In den meisten Fällen steht etwas wie "Mein Stahl". Beim TB 1851 S. 87. könnte man evtl. "von mir erfundenen Meteorstahl" mit ID 9474, und nur "Meteorstahl" mit ID 8453 taggen.

**Comment by vrukavina** [comment]
> Mutterstempel wurde zusammengelegt mit Matrize (ID 8342). ID 9333 wurde gelöscht.
> Bei der ID 9499 geht aus den Texten meiner Meinung nach klar hervor, dass es sich um Stahlmuster im Sinne von Stahlproben, -beispielen handelt. Seht ihr das auch so? Sollen wir das Schlagwort löschen?
> Bei der ID 9474 verstehe ich nicht, was Schib als Fischers Stahl bezeichnet - den Meteorstahl? Diesen hat er aber auch separat aufgenommen..

Ist jemand gegen das Eliminieren der ID 9499 (Stahlmuster)? Falls nein, lösche ich sie.

**Comment by NicolauLutz** [comment]
ID 9499 (Stahlmuster) kann man von mir aus löschen.

**Comment by feggimann** [comment]
Wenn ich richtig liege, kommen die Stahlmuster immer dort vor, wo Fischer seinen Stahl anpreist und die Muster als Verkaufsmuster zeigt. Stimmt das?

Dann können die Stahlmuster-Nennungen mit der ID Fischers Stahl getaggt werden und ID 9499 kann gelöscht werden.

**Comment by NicolauLutz** [comment]
ID 9499 (Stahlmuster) gelöscht.
