### ISSUE TITLE
3 Actors zu Naturforschende Gesellschaft: bereinigen

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#268]
Es hat aktuell drei Actors zu Naturforschende Gesellschaft:
- ID 8103: Akademie der Naturwissenschaften, früher Schweizerische Naturforschende Gesellschaft
- ID 8102: Naturforschende Gesellschaft SH
- ID 7482: Naturforschende Gesellschaft SO

Bei der NGSO ist im Text die Schweizerische Naturforschende Ges. gemeint, die ihre Jahresversammlung in Solothurn hatte. Bitte korrigieren und dann ID 7482 löschen. Andere beiden behalten, da beide vorkommen.

**Comment by vrukavina** [comment]
Wurde entsprechend bereinigt.
