### ISSUE TITLE
Keywords Meteorstahl/Meteoreisen bereinigen

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#269]
Es gibt momentan drei Keywords zu Meteor...:
- ID 8453: Meteorstahl
- ID 9010: Fischers Meteoreisen
- ID 9525: Fischers Meteorstahl

Ich würde ID 8453 und 9525 zusammenfassen. Die verbleibenden beiden Keywords entweder beide mit oder beide ohne "Fischers..." schreiben. Es ist ja eigentlich klar, dass es seine Erfindung ist, und es wird im Text auch beschrieben. Deshalb könnten sie auch einfach "Meteorstahl" und "Meteoreisen" ohne "Fischers..." heissen. Fände ich übersichtlicher.

**Comment by vrukavina** [comment]
Wurde wie vorgeschlagen bereinigt. Neu gibt es nur die ID 8453 Meteorstahl und ID 9010 Meteoreisen.

**Comment by vrukavina** [comment]
@NicolauLutz Falls du das im TB 1825-1827 auch schon korrigiert hast, können wir hier schliessen.

**Comment by NicolauLutz** [comment]
Ist für das TB 1825-1827 so eingetragen.
