### ISSUE TITLE
TB 1851 gelöschte und zusammengelegt IDs

### ISSUE THREAD

**Issue by HelenaBarteld** [GF-Corporate-Archives/gf-johann-conrad-fischer#272]
Blasen | [8834] | gelöscht |  
Complicat | [8923] | geöscht |  
Reverberierfeuer | [9404] | zusammengelegt mit Reverberieröfen | 8480
Banknoten | [8818] | zusammengelegt mit Notendruck | 9091
Dampfschifffabrik | [8947] | zusammengelegt mit Werft | 8969
Dampfschiffkurse | [8949] | zusammengelegt mit Dampfschiff | 8801
Eisen altes | [8984] | zusammengelegt mit Eisen | 8672
Eisen magnetisches | [8968] | zusammengelegt mit Eisen | 8672
Eisen russisches | [8988] | gelöscht, mit Russland getaggt |  
Weicheisengiesserei | [9016] | zusammengelegt mit Giesserei | 55
Eisenbahngesellschaft | [9017] | zusammengelegt mit Eisenbahn | 169
Eisenbahnreisende | [9020] | zusammengelegt mit Eisenbahn |  
Eisenbahnwagen | [9021] | zusammengelegt mit Eisenbahn |  
Eisenbahnkurse | [9018] | zusammengelegt mit Eisenbahn |  
Eisenbahnnetz | [9019] | zusammengelegt mit Eisenbahn |  
Sumpferz phosphorhaltiges | [9029] | zusammengelegt mit Sumpferz | 8483
Genius der Enländer | [9068] | gelöscht |  
hämmerbares Glockenmetall | [9134] | gelöscht |  
Grundbestanteile | [9154] | gelöscht |  
Urstoffe | [9596] | gelöscht |  
Grundrechte | [9157] | gelöscht |  
Federmesserstahl | [9511] | zusammengelegt mit Federmesser | 8660
ägyptische Industrieprodukte | [9192] | gelöscht |  
Kapital | [9203] | gelöscht |  
Liberalität | [9272] | gelöscht |  
Naturkräfte | [9339] | gelöscht |  
Papierfabrik | [9349] | gelöscht |  
Parteigeist | [9352 | gelöscht |  
Postdampfschiff | [9376] | zusammengelegt mit Dampfschiff | 8801
Radikale | [9394] | gelöscht |  
Schiffsballast | [9431] | gelöscht |  
Schiffsausrüstung | [9430] | gelöscht |  
Schleife | [9432] | zusammengelegt mit Schleifen | 8879
Schmelzhäuser | [9435] | zusammengelegt mit Schmelzerei | 88
Schmelzmeiser | [9437] | zusammengelegt mit Schmelzen | 8696
Schmelzprozess | ? | zusammengelegt mit Schmelzen |  
Baumwollspinnerei | [8823] | zusammengelegt mit Spinnerei | 9466
Seidenstoffe | 9452 | umbenennen zu Seide | 9452
Seidenwaren | [9453] | zusammenlegen mit Seide, jetzt gelöscht | 9452
Flachsspinnerei | [9050] | zusammengelegt mit Spinnerei | 9466
Rasiermesserfabrikant | [9396] | zusammengelegt mit Rasiermesserfabrik | 9395
Gussstahlfabrikant | [9520] | zusammengelegt mit Gussstahlfabrik | 9519
Seebäder | 9449 | sg |  
Hammerwerke |   | sg |  
Fischers Giesserei |   | gelöscht |  
Fischers Stahwerk |   | gelöscht |  
Sonntag |   | gelöscht |  
Lokomotivfederfabrik |   | gelöscht |  
Strohgeflecht |   | gelöscht |  
Vaterland |   | gelöscht |  
Volksversammlung |   | gelöscht |  
Zinkerz |   | zusammengelegt mit Zink |  
Seigerungsprozess |   | zusammengelegt mit Seigerung |  
Federnstahl |   | zusammengelegt mit Federstahl |  
Tonarbeiter |   | zusammengelegt mit Ton |  
Tiegelmaterial |   | zusammengelegt mit Tiegel |  
Waschgold |   | zusammnengelegt mit Gold |  
Ziegelstienmanufaktur |   | zusammengelegt mit Ziegelei |  
Englisches Zinn |   | zusammengelegt mit Zinn |  
Zink regulinisches |   | zusammengelegt mit Zink |  
Ziegelstein |   | zu Ziegel umbenannt |  
Chymistenladen |   | Bar, Getränkestube (Beschreibung hinzufügen) |

**Comment by vrukavina** [comment]
@HelenaBarteld Wurden die IDs entsprechend auch im Annotations gelöscht und korrekt wieder getaggt?

**Comment by HelenaBarteld** [comment]
Ja
