### ISSUE TITLE
Website: Itinerar TB 1794 falsch angezeigt

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#275]
Auf der neuesten Website-Version kommt im Itinerar zwischen Potsdam und Hamburg Bern vor. Bern kommt im TB 1794 aber gar nicht vor. Im XML ist das Itinerar folgendermassen:

- Potsdam: n=16
- Berlin: n=17
- Hamburg: n=18

**Comment by wolfgangmm** [comment]
`<placeName ref="gfa-places-17" type="itinerar" when="1793" n="17">Berlin</placeName>`  ist falsch. Die ID sollte wohl gfa-places-16 sein?

**Comment by wolfgangmm** [comment]
> Weitere Itinerar-Fehler:
> 
> Auf Karte: Møn -- Schweden -- Helsingborg
> 
> XML: Møn: n=20 Kopenhagen ("diese Königsstadt"): n=21 Schweden: n=22

Konnte ich in der aktuellen Version nicht mehr nachvollziehen.

**Comment by NicolauLutz** [comment]
> `<placeName ref="gfa-places-17" type="itinerar" when="1793" n="17">Berlin</placeName>` ist falsch. Die ID sollte wohl gfa-places-16 sein?

Habe die ID korrigiert.
