### ISSUE TITLE
TB 1814: Neues Jerusalem

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#277]
TB 1814, S. 175: "dass nämlich eine eben herausgekommene Vorstellung des jüngsten Gerichts, so wie sie ein Pater Abraham a Sancta Clara oder irgend ein exaltirter Dominikanermönch mag geträumt haben, den grossen Haufen vorzüglich und anhaltend anzog; auch spielten die Teufel mit ihren Geräthschaften und derselben Anwendung eine weit interessantere Rolle, als die etwas übelgerathenen Engel, welche den Weg nach dem **neuen Jerusalem** zeigten, der aber so schmal war, dass nicht einmal Mann und Frau neben einander hineingehen konnten."

Im Moment ist dort mit der ID 1768 (Jerusalem) getaggd. Macht das Sinn? Mit dem "neuen Jerusalem" ist ja genau nicht die Stadt Jerusalem auf Erden gemeint.

**Comment by ChristopherZoller-Blundell** [comment]
Ich würde vorschlagen, entweder kein Tag oder wenn dann mit einem neuen Keyword Tag wie "Utopie".

**Comment by NicolauLutz** [comment]
Im TB 1814 nicht mehr getaggd.
