### ISSUE TITLE
TB 1851: Tippfehler korrigieren

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#283]
Auf Seite 87 sollte "Länder" statt "Lander" stehen:
![grafik](https://user-images.githubusercontent.com/92036071/220035582-cc429a43-24a8-4113-ac2d-abbda8b6faf9.png)

**Comment by vrukavina** [comment]
Wurde im xml und der Word-clean-Version korrigiert.
