### ISSUE TITLE
webseite: Actors - angezeigte Informationen

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#284]
### Actors: angezeigte Informationen an Beispiel Christoph Jetzler (`<person xml:id="gfa-actors-7372">`)

**Detailansicht Register**

1. Graue Kopfleiste: 
- [ x] so wie es jetzt schon dasteht (`<persName type="full">Jetzler, Christoph (1734-1791)</persName>`)
2. Hauptseite, Spalte links: 
- [x]  Bild (`<bibl type="image">`)
- [x]  darunter Bildlegende (`<bibl type="image"><title>Christoph Jetzler (Portrait von Michael Wachsmuth), 1775</title>`)
- [x]  darunter "Bildinformationen" (Link zu `<ptr type="anton-image" target="https://archives.georgfischer.com/objects/124045"/>`)
3. Hauptseite, Spalte Mitte:
- [x]  "Person: [Name]" (`<persName>Jetzler, Christoph</persName>`) (als Überschrift, ohne Lebensdaten)
- [x]  "20. Dezember 1734 – 5. September 1791" (Lebensdaten falls vorhanden, Monate ausgeschrieben)
- [x]  "weitere Namensformen: […; …]" (`<persName type="alternative">Christoph Jezler</persName><persName type="alternative">Christof Jezler</persName>`) (falls vorhanden, abgetrennt mit ;)
- [x] "[Beschreibung/Biografie]" (`<note type="bio" xml:lang="de">`) (falls vorhanden, ohne Titel "Biografie" o.ä., nur den Text)
- [x] "Quellen: [Auflistung der Quellen]" (`<note type="sources">`) (falls vorhanden)
- [x] "weiterführende Informationen" etc. (so wie es jetzt schon aufgelistet ist, Schreibweisen wie in Anton, alphabetisch)
4. Hauptseite, Spalte rechts:
- [ x] "Erwähnungen" etc. (so wie es jetzt schon aufgelistet wird)

**Weisses Popup in Text**

- [x] So wie es jetzt schon aussieht mit Name, Daten, Bio, Bild, aber von Biografie nur die erste Zeile, danach "(…)" als Link zu Registereintrag. 
- [x] Falls in Biografie Wörter verlinkt, bitte nicht anzeigen.

**Schwarzes Popup mit grossem Bild**

- [x] So wie es jetzt schon aussieht – super!!! Ich würde nur Lebensdaten anders abtrennen, nicht mit Gedankenstrich, sondern in Klammern. 
- [x] Falls in Biografie Wörter verlinkt, bitte nicht anzeigen.

**Linkliste (mittlere Spalte)**

- [x] Nicht ausführliche Lebensdaten, sondern nur Jahre von-bis in Klammern

**Comment by feggimann** [comment]
Ich hatte die TEI-Befehle reinkopiert, aber die zeigt es nicht an :-) ich hoffe, es ist trotzdem klar wo was hinkommt.

**Comment by windauer** [comment]
alles issues umgesetzt, die neue Version muss noch ausgerollt werden für den review.
