### ISSUE TITLE
webseite: Places - angezeigte Informationen

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#285]
### Places: angezeigte Informationen an Beispiel Soho Foundry (place xml:id="gfa-places-1694")

**Detailansicht Register**
* [x] 1. Graue Kopfleiste:  "Ort: Birmingham, Soho Foundry" (settlement, placeName) (falls settlement und placeName gleicher Wert nur einmal schreiben, z.B. "London" etc. // z.T. kein settlement vorhanden)
2. Hauptseite, Spalte links: 
- [x] Bild (bibl type="image")
- [x] darunter Bildlegende (<title>Soho Foundry (Zeichnung von John Phillp), 1799</title>)
- [x]  darunter "Bildinformationen" (Link zu ptr type="anton-image" target="https://archives.georgfischer.com/objects/127163"/)
3. Hauptseite, Spalte mitte:
- [x]  "Ort: Soho Foundry" (placeName) (als Überschrift)
- [x]  "Birmingham, Vereinigtes Königreich" (settlement, country) (bitte keine ß verwenden, sondern ss)
- [x]  "weitere Namensformen: […; …]" (placeName type="alternative") (falls vorhanden, abgetrennt mit ;)
- [x]  "[Beschreibung]" (note type="description" xml:lang="de") (falls vorhanden, ohne Titel "Beschreibung" o.ä., nur den Text)
- [x]  "Quellen: [Auflistung der Quellen]" (note type="sources") (falls vorhanden)
- [x]  "weiterführende Informationen" etc. (so wie es jetzt schon aufgelistet ist, Schreibweisen wie in Anton, alphabetisch)
4. Hauptseite, Spalte rechts:
- [x] "Erwähnungen" etc. (so wie es jetzt schon aufgelistet wird)

**Weisses Popup in Text**

- [x]  So wie es jetzt schon aussieht mit Name, Ort, Beschreibung, Bild. Trennung nicht mit / sondern Komma und Land weglassen (Soho Foundry, Birmingham). Von Beschreibung nur die erste Zeile, danach "(…)" als Link zu Registereintrag.
- [x]  Falls in Beschreibung Wörter verlinkt, bitte nicht anzeigen.

**Schwarzes Popup mit grossem Bild**

- [x]  So wie es jetzt schon aussieht – super!!! Bitte nach Name noch Ort (Soho Foundry, Birmingham). 
- [x]  Falls in Beschreibung Wörter verlinkt, bitte nicht anzeigen.

**Linkliste (mittlere Spalte)**
- [x]  Schreibweise "Ort, Name" (ohne Land), z.B. "Birmingham, Soho Foundry"

**Comment by wolfgangmm** [comment]
`(...)` für den Link zum Registereintrag ist ungünstig, da die Beschreibung bereits als Paragraph formattiert ist und der Link daher immer in der nächsten Zeile darunter erscheint. Den Link nach oben zu schieben (müsste vor den schliessenden Punkt) wird aufwendig. Ich lasse einstweilen den Link as `Weitere Informationen`.

**Comment by windauer** [comment]
Ticket ist fertig,  Änderungen müssen noch für review live geschaltet werden
