### ISSUE TITLE
TB 1794: place ID Berlin korrigieren

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#286]
Berlin hat place ID 16, nicht 17 (das ist Bern). Bitte korrigieren
![grafik](https://user-images.githubusercontent.com/92036071/220081889-a16f5493-bb72-4fc4-984c-e4fcdd2f6a99.png)

**Comment by NicolauLutz** [comment]
Korrigiert.
