### ISSUE TITLE
Anton: ID 9616 (Maschinenwebstühle) und ID 9617 (Mechanischer Webstuhl) zusammengelegt

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#287]
ID 9617 wird gelöscht. Betrifft TB 1794, 1825, 1825-1827

**Comment by NicolauLutz** [comment]
Evtl. auch mit ID 3009 (Webmaschine) zusammentun?

**Comment by ChristopherZoller-Blundell** [comment]
Wenn eine Unterscheidung mit separaten Keywords überhaupt nötig wäre, dann wäre das für Power Looms gewesen (als sehr intensiv mechanische und schliesslich automatisierte Webstühle, die die Textilindustrie massiv veränderte). Aber Power Looms sind Maschinenwebstühle (9616) oder Webmaschinen (3009) - die Synonyme sind. Alle diese Geräte sind mechanisierte Webstühle (9617), also von mir aus können alle zusammengelegt werden. Als übergreifendes Keyword halte ich Webmaschinen (3009) für den geeignetsten.

**Comment by NicolauLutz** [comment]
Die mit ID 9616 und 9617 gekennzeichneten terms in den entsprechenden Tagebüchern neu mit ID 3009 kennzeichnen.

**Comment by vrukavina** [comment]
im TB 1825 korrigiert.
