### ISSUE TITLE
Website: 2 Worte mit demselben Tag taggen? 

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#289]
Kann man dasselbe Wort mit zwei verschiedenen Actors, oder zwei verschiedenen Places taggen? Oder ist es nur möglich, einen Actor oder Ort mit einem Keyword zu kombinieren?

**Comment by feggimann** [comment]
Auch zwei verschiedene Keywords für das gleiche Wort wären sinnvoll.

**Comment by feggimann** [comment]
Ist das möglich?

**Comment by wolfgangmm** [comment]
In TEI würden mehrere referenzierte Orte meist mit `<placeName ref="#ort1 #ort2">` kodiert. Da wir in der Website aber sehr viele Lookups auf die `ref` Attribute haben, würde diese Lösung die entsprechenden Zugriffe sehr verkomplizieren bzw. die Seite verlangsamen.

Ich möchte daher davon abraten und stattdessen vorschlagen, einfach mehrfach verschachtelte `persName` oder `placeName` zu verwenden:

```xml
<placeName ref="#ort1"><placeName ref="#ort2">XXX</placeName></placeName>
```
