### ISSUE TITLE
Anton: ID 9506 (Stahlstreckhammer) gelöscht

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#292]
Betroffene Stellen mit ID 9099 (Streckhammer) taggen. Betrifft TB 1825, 1825-1827

**Comment by NicolauLutz** [comment]
Ebenso ID 9505 (Stahlstrecke). Stelle mit ID 9098 (Verstrecken) taggen. Betrifft TB 1825.

**Comment by NicolauLutz** [comment]
Möglicherweise auch ID 9015 (Streckeisen). Musst du beurteilen @vrukavina

**Comment by vrukavina** [comment]
9506 kam im TB 1825 nicht vor. Stahlstrecke (ID 9505) hätte ich jetzt eigentlich so gelassen, da bei mir die Werkstatt damit gemeint ist und nicht das Verfahren.

ID 9015 würde ich behalten. Es kommt in einer Aufzählung mit anderen Stahl- und Blechsorten vor, die auch getaggt sind.
