### ISSUE TITLE
Anton: Keywords "Gewehrfabrik"; "Büchsenmacherei"; "Büchsenmacher"; "Gewehrfabrikant"

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#295]
Stellen in den TBs: 

Büchsenmacher: 
- TB 1814: 2 Stellen (als Beruf)
- TB 1825-1827: 1 Stelle (Büchsenmacher-Werkstelle)

Büchsenmacherei: 
- TB 1825: 2 Stellen (Büchsenmacherei als Verfahren/Handwerk)

Gewehrfabrik:
- TB 1825: 1 Stelle (als Standort)

Gewehrfabrikant:
- TB 1825: 1 Stelle (als Beruf)

Vorschlag: 

1 KW für das Verfahren/Handwerk (Büchsenmacherei)
1 KW für den Beruf (Büchsenmacher/Gewehrfabrikant)

Die Stelle im TB 1825 mit dem Betrieb mit KW für Handwerk taggen.

**Comment by feggimann** [comment]
Es gibt schon das KW 9112 Gewehrfabrik. 9113 hiess Gewehrfabrikant, nicht Büchsenmacher, das wurde gelöscht. 

1 neues KW für Büchsenmacherei ist ok. Das andere lassen wir. Verteilt bitte die vorkommenden Stellen auf Gewehrfabrik und Büchsenmacherei.

**Comment by NicolauLutz** [comment]
Gut, dann KW 9112 für Gewehrfabrik und neues KW für Büchsenmacherei.

**Comment by NicolauLutz** [comment]
@HelenaBarteld: Bitte "Büchsenmacher-Werkstelle" auf S. 29 mit ID 9793 (Büchsenmacherei) taggen.

**Comment by vrukavina** [comment]
wurde im TB 1825 korrigiert

**Comment by HelenaBarteld** [comment]
erledigt

**Comment by NicolauLutz** [comment]
Super! Ich schliesse damit das Issue.
