### ISSUE TITLE
Recherche: Dampfboot und Kapitän Joner

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#296]
Im TB 1825 auf S. 21 steht: "Diese Erscheinung brachte die Abreise des in der Themse liegenden Dampfbootes für Ostindien zur Sprache. Schon im März sollte sie Statt haben, und die Kohlen, welche selbiges neuerdings vom Vorgebirg der guten Hoffnung einzunehmen hat, gingen als Ballast schon im Anfang des Jahres mit mehrern Schiffen ab; aber noch konnte man wegen eines Komplotts der Schiffszimmerleute, die einen höhern Lohn (Wages) verlangen, und nun ihn zu erzwecken, gar nicht arbeiten, sondern aus ihrem Fond und gegenseitiger Unterstützung leben, selbiges bis jetzt nicht gar fertig machen. Es hat zwei Dampfmaschinen, jede zu 80 Pferdestärken, von den Herren Boulton und Watt gebaut, als bewegende Kraft, und den berühmten Joner, der ein höchst erfahrner und kühner Seemann ist, als Befehlshaber."

Das Schiff hatte ich vor einigen Wochen mit der Enterprise ([https://de.wikipedia.org/wiki/Enterprise_(1825)](https://de.wikipedia.org/wiki/Enterprise_(1825))) identifiziert. Der Kapitän des Schiffs war dann aber nicht George A. Jones, wie bei Schib vermerkt, sondern James Henry Johnston.

Was meinst du @ChristopherZoller-Blundell?

**Comment by ChristopherZoller-Blundell** [comment]
@vrukavina 

Die Informationen, wie ich sie sehe, widersprechen sich nicht. Auf der Wikipedia-Seite wird James Henry Johnston als Eigentümer zusammen mit einem Syndikat aufgeführt, nicht als Kapitän. Ich habe noch keine Informationen über George A. Jones finden können, aber es könnte gut sein, dass er als Kapitän des Schiffes eingesetzt wurde. Ich würde mich hier an die Informationen von Schib halten.

Dass James Henry Johnston einen Rang hatte und als Leutnant auf der Wiki-Seite aufgeführt ist, ist hier vielleicht etwas irreführend. Wäre Johnston der Kapitän des Schiffes gewesen, hätte er seinen Titel als Kapitän und nicht als Leutnant angegeben. Alle Schiffskommandanten, unabhängig von ihrem Rang, werden technisch als Kapitän bezeichnet, wenn sie ein Schiff kommandieren. Die Tatsache, dass er als Eigentümer den Titel eines Leutnants verwendet hat, sagt einiges über Johnston aus. Ich halte es für sehr wahrscheinlich, dass er in der Royal Navy diente und den Rang eines Leutnants erreichte. Das war eine grosse Sache, da dies der Rang war, ab dem man als "Master and Commander" (technischer Kapitän) eines Schiffes eingesetzt werden konnte. Wenn man experimentelle Projekte mit Schiffen durchführte, dann war dieser Rang etwas, was man bekannt machte, denn es war eine Qualifikation, ein Zeichen für Qualität, für Erfahrung – dass man mit Verantwortung umgehen konnte. Das würde natürlich die Investoren in solche spekulativen neuen Technologien beruhigen.

**Comment by vrukavina** [comment]
DANKE!
