### ISSUE TITLE
Website: Tagebücher laden nicht auf Firefox

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#298]
Der Text und die Inhaltsangabe der Tagebücher laden im Firefox-Browser nicht. Vor etwa 2 Wochen war das Problem noch nicht da. 

Browser-Version: Firefox 78.15.0esr (64-bit)

<img width="888" alt="Screen Shot 2023-02-28 at 12 18 09" src="https://user-images.githubusercontent.com/92101460/221839442-2aeb239d-5f16-462f-88e9-93ddab5cef97.png">

**Comment by windauer** [comment]
@NicolauLutz auf der aktuellen Entwicklungsversion bei mir lokal kann ich das Problem nicht nachvollziehen, allerdings habe ich einen Mac und Firefox 110.0 (64-bit). Wir werden demnächst nochmal eine aktuelle Version ausspielen, in der Hoffnung dass der Fehler sich dann in Wohlgefallen auflöst, ansonsten werden wir dem nachgehen. 

Haben wir denn schon definiert, welche Browser und bis zu welcher Versionsnummer runter voll unterstützt werden müssen? [Firefox 78.15.0 ESR](https://www.mozilla.org/en-US/firefox/78.15.0/releasenotes/) z.B. ist von Oktober 2021 und es gibt inzwischen schon [Firefox 102.8.0 ESR](https://www.mozilla.org/en-US/firefox/102.8.0/releasenotes/) vom 14.02.23.

**Comment by windauer** [comment]
@NicolauLutz , @feggimann ich habe eben gerade die Webseite auf den letzten Entwicklungsstand aktualisiert // cc @wolfgangmm 

@NicolauLutz biste teste noch einmal, ob der Firefox Fehler noch auftritt und falls ja, teilt uns bitte mit, bis zu wie alte Firefox Versionen wir unterstützen sollen. 

Generell ist es gut möglich, dass ihr "Shift Reload" in Eurem Browser machen müsst, damit die Änderungen sichtbar werden.

**Comment by windauer** [comment]
server ist jetzt auf dem aktuellsten Stand, inkl aktueller Registerdaten von @ottosmops

**Comment by NicolauLutz** [comment]
Die Webseite lädt bei mir auf Firefox immer noch nicht. @windauer

**Comment by windauer** [comment]
@NicolauLutz ok, ich habe mir jetzt mal Firefox 78.15 installiert und kann bestätigen, dass die Seite dann folgenden Fehler wirft: 

```
Uncaught (in promise) TypeError: Illegal constructor.
    x https://gf.tei-publisher.com/itinerary/resources/scripts/pb-message-fbc1b645.js:174
```
@NicolauLutz für uns wäre es jetzt wirklich wichtig zu wissen, bis zurück zu welche Firefox Version die Seite funktionieren muss. Müssen noch ältere Versionen als 78.15 unterstützt werden? Je nach dem wie weit runter, wir die Browser unterstützen müssen, kann das durchaus umfangreich arbeiten nach sich ziehen. Auf einen aktuellen Firefox upzudaten ist keine Option @NicolauLutz?  // cc @wolfgangmm

**Comment by windauer** [comment]
I just noticed, that when I install Firefox 78.15 it will update in the background to Version 102.8.0esr (64-bit) and then everything works fine again. It is possible that this is only a problem with you Firefox not updating to the lastest ESR version @NicolauLutz or is it not possible for you to update it?

**Comment by NicolauLutz** [comment]
@windauer Ich kann die Website auf Chrome aufrufen, also Firefox 78.15 muss nicht zwingend unterstützt werden, wenn das schwierige Arbeiten nach sich zieht.

**Comment by feggimann** [comment]
@windauer GF hat als Standardbrowser Microsoft Edge, aktuell Version 110.0.1587.69 (Offizielles Build) (64-Bit). Dieser muss zwingend unterstützt werden.  

Abgesehen davon bei anderen Browsern Unterstützung der gängigen Versionen. Bei älteren Versionen sollte dafür eine Hinweismeldung kommen, dass der Browser nur bis Version xy korrekt unterstützt.

**Comment by windauer** [comment]
wir konzentrieren uns für die Vernissage auf aktuelle Desktop / Mobile Browser (Microsoft Edge, Firefox, Chrome, Safari). Ein extra handling für ältere Browser kann sehr kompliziert werden und werden wir bis zur Vernissage nicht schaffen, von daher habe ich das Ticket jetzt in "Milestone 2" geschoben. ich hoffe das passt so @feggimann

**Comment by feggimann** [comment]
wir lassen das so stehen. auf allen aktuellen Browsern funktioniert es einwandfrei.
