### ISSUE TITLE
Aetheratmosphäre (Rundgang in Apothecaries Hall, 11. Juni 1825) S. 65

### ISSUE THREAD

**Issue by HelenaBarteld** [GF-Corporate-Archives/gf-johann-conrad-fischer#299]
Ist damit auch, wie einige Sätze zuvor erwähnt, Diethylether ID 9646 gemeint oder Äther ID 8464? Schib hat diese Stelle und eine Stelle im TB 1851 unter Aether ins Sachregister aufgenommen. Im TB 1851 wurde Äther ID 8464 getaggt.

**Comment by vrukavina** [comment]
Ich würde es so machen wie Schib, also mit der ITD 8464 taggen.

**Comment by vrukavina** [comment]
@HelenaBarteld Wurde das entsprechend bearbeitet und kann geschlossen werden?
