### ISSUE TITLE
Recherche 1825, 1814: Schenk

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#300]
Im TB 1824 kommt ein Herr Schenk vor. Nicolau hat einen Schenk, A. im Anton aufgenommen. Helena einen Schenk, David.
Der David ist im TB 1814 jedoch nicht getaggt. (nur zur Info)

Im TB 1825 verbringt JCF einen gemütlichen Abend mit einem Herrn S. «dessen lange und erprobte Freundschaft, obschon er seit 28 Jahren von unserer gemeinschaftlichen Vaterstadt entfernt, und im Getümmel der hiesigen Geschäfte lebt, ich schon oft erfahren [...]» (S. 246)

Meine Fragen wären:
1. Welcher Schenk ist es nun? David oder A.?
2. Kann es sein, dass JCF im TB 1825 mit Herrn S. diesen Herrn Schenk meint? Dann müsste er Schaffhauser sein.

**Comment by NicolauLutz** [comment]
Im TB 1814 kommt auch ein "Herr S." vor (ID 7691). Möglicherweise handelt es sich um Schenk, Fischer ist erratisch mit den Abkürzungen. Dass es sich im TB 1814 um A. Schenk handelt, ist ziemlich sicher (Brief in Henderson 1966). Ich weiss nicht, wie Schib auf D. Schenk kommt.

**Comment by vrukavina** [comment]
Es kann nicht eruiert werden, ob mit Herrn S. Fischer den Herrn A. Schenk meint.
