### ISSUE TITLE
Recherche: Museum der Künste in London

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#301]
Im TB 1825 schreibt JCF: "Diesem fügte er noch zwei für mich sehr verbindlich geschriebene Empfehlungen an Herrn Aikin, Direktor des Museums der Künste [...]".
Kann es sein, dass Fischer hier die National Gallery meint?
Die Angaben des Direktors, die ich finden konnte, gehen nur bis 1855 zurück, aber ansonsten wäre diese Information ein gutes Hilfsmittel.

**Comment by NicolauLutz** [comment]
Ich habe mir die Stelle angesehen und in der Oxford Dictionary of National Biography nach Aikin gesucht. Eigentlich käme nur Arthur Aikin (1773-1854) in Frage. Da es in der Textstelle um Geologie geht, würde das auch Sinn machen. Wenn Arthur Aikin gemeint ist, dann wäre das Museum der Künste die "London Institution". Künste hier zu verstehen als "Arts and Sciences".

**Comment by vrukavina** [comment]
Beim Museum würde ich dann aber doch lieber die Royal Society of Arts als Organisation aufnehmen und taggen. Da er 1825 dort, zwar nicht DIrektor, aber Schriftführer war.
VIELEN DANK! :)
