### ISSUE TITLE
Doppeltes Schlagwort: ID 1614 Alien Office (TB 1814, 1815) und ID 2046 Fremdenamt (TB 1845)

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#302]
Können die IDs zusammengelegt werden?

**Comment by HelenaBarteld** [comment]
Nein ich denke nicht, das eine ist in Places ID 1614 ist in Dover und Places  ID 2046 ist in London.

**Comment by vrukavina** [comment]
Stimmt. Habe ich übersehen. Danke!
