### ISSUE TITLE
Places: Café Véry (2054), École des Mines (1934), Laboratoire des essais (1707)

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#304]
Café Véry: welches TB betrifft dieser Ort?

École des mines und Laboratoire des essais: ist das das gleiche?

**Comment by vrukavina** [comment]
Das Café kommt imt TB 1825 vor. Ich habe die fehlende Angabe ergänzt.
Es ist nicht ganz das gleiche. Das Labor war allerdings Teil der Ecole des mines. Die Ecole hat als Uni fortbestanden, aber das Labor wurde bereits um 1840 geschlossen. JCF erwähnt im TB 1851 allerdings nur das Herr Bréant Inspecteur des Essais war. Da das Labor zu dieser Zeit geschlossen war, könnte man eventuell nur die Ecole beibehalten.
Dann würde ich im Beschrieb der Ecole des mines das Versuchslabor und Herr Bréant erwähnen, und das Laboratoire als Ortseintrag löschen. Wäre das okay so?

**Comment by vrukavina** [comment]
Wurde so gemacht.
