### ISSUE TITLE
Recherche TB 1825: The Red Boy?

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#306]
S. 159: "erhielt, gingen sein Sohn und ich nach der northern Exhibition, wo eine sehr schöne Gemäldesammlung englischer Künstler nur von den zwei letzten Jahren aufgestellt war.
Unter allen fiel mir sogleich auf, und gefiel mir zum allermeisten, ein Portrait in Lebensgrösse, wie ich glaube von Lord Howder, durch den Präsidenten der königl. Akademie Herrn Lawrence gemalt. — Man behauptet, und ich glaube es, er sei der erste der nun lebenden Portraitmaler. Dieses Stück kostete über sechshundert Pfund Sterling. "

Könnte es sein, dass JCF hier den Red Boy (https://www.artwarefineart.com/gallery/portrait-master-charles-william-lambton-red-boy-1818-1831) sieht? Dieser wurde als Auftrag vom Vater Lord Durham (nicht Howder) an Thomas Lawrence gegeben und 1825 fertiggestellt.
Sogar die Kosten würden stimmen. (https://en.wikipedia.org/wiki/The_Red_Boy)
Mich stört allerdings, dass ich diese Northern Exhibition in Leeds nicht identifizieren kann..

Vorsichtshalber würde ich den Red Boy als Sachschlagwort erwähnen, aber nicht direkt im Text taggen, sondern in der Fussnote mit einer Interpretationserläuterung. Wäre das zu gewagt?

**Comment by vrukavina** [comment]
Die Northern Exhibition habe ich mit dem Ort Leeds Museums and Galleries (ID 2055), das 1821 errichtet wurde, getaggt.

**Comment by ChristopherZoller-Blundell** [comment]
1825 gab es eine Ausstellung der Royal Academy (ihre 57. Ausstellung). Die Ausstellung fand ursprünglich in London statt, und es scheint, dass einige oder vielleicht alle Bilder als Wanderausstellung nach Leeds gebracht wurden.

Das Gemälde von Lawrence ist auf Seite 18 (Nummer 288) als "Porträt des Sohnes von J.G. Lambton, Esq." aufgeführt (Katalog hier: https://www.royalacademy.org.uk/art-artists/exhibition-catalogue/ra-sec-vol57-1825). Also, ich denke, du hast Recht, dass das Gemälde "The Red Boy" gemeint ist. Ein Lord Howder ist nirgendwo zu finden.

**Comment by vrukavina** [comment]
Sehr schön! :)

**Comment by vrukavina** [comment]
Aber leider kann doch nicht ganz eindeutig gesagt werden, dass es dieses Gemälde war. Zwei weitere Gemälde von Thomas Lawrence waren auch Teil der Ausstellung: eins von [George Canning](https://en.wikipedia.org/wiki/George_Canning_(disambiguation)) und eins von Henry Peter Brougham ([Lord High Chancellor](https://en.wikipedia.org/wiki/Lord_Chancellor)). Es könnte sein das JCF den letzteren gesehen, aber mit diesem Lord Howder verwechselt hat.

Man müsste irgendwie herausfinden welche Gemälde damals genau nach Leeds gebracht wurden. Die Frage würde mehr Recherche benötigen.

**Comment by ChristopherZoller-Blundell** [comment]
Ja, das ist richtig. Mir ist gerade ein weiteres Detail aufgefallen, nämlich dass das Gemälde "Red Boy" nicht lebensgross ist (137x112cm), wie Fischer das Bild beschreibt, das ihm gefiel. Von den anderen Werken von Lawrence in der Ausstellung - wenn es tatsächlich diese Ausstellung war - gibt es nur zwei weitere plausible Kandidaten: das Porträt von John Wilson Croker esq. oder des Lordkanzlers, der damals John Scott, Baron Eldon war (die anderen sind entweder Radierungen, zu klein oder von Frauen). Ich denke, dass der Lordkanzler wahrscheinlicher ist. Glaubst du, dass das "Howden" ein falsch verstandenes "Eldon" ist? Das Problem, das ich jetzt habe, ist, ein Gemälde von Eldon aus den Jahren 1823-25 zu finden. Es gibt eines von Lawrence aus dem Jahr 1826, aber das ist natürlich zu spät und die Gemälde ist nicht lebensgross.

**Comment by vrukavina** [comment]
Das stimmt auch wieder.
Ich würde sagen, wir belassen es bei dem, dass das Gemälde nicht eindeutig identifiziert werden kann. Ich nehme also keines der Bilder im Anton auf. Man könnte hier mit einer Fussnote arbeiten, aber auch das würde ich eher nicht tun, da diese eventuell nur noch mehr Verwirrung stiften könnte.
Vielen Dank für deine Hilfe und aufwändige Recherche!
