### ISSUE TITLE
Dokumentation: Querverweise

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#307]
Verweise auf eine andere Tagebuchseite desselben Tagebuchs haben wir bis jetzt so geregelt: 

`<ref type="cross" target="x"></ref>` wobei das `target` mit einer `xml:id` fongenden Formats gekennzeichnet wird:  

`"p_[Seitennummer]"` 

z.B. `xml:id="p_20"`

Für Verweise auf eine Seite in einem anderen Tagebuch haben wir folgendes Format für die `xml:id` festgelegt: 

`"[Tagebuchtitel.xml]#p_[Seitennummer]"`

z.B. `xml:id="Reisetagebuch-2.xml#p_20"`

Ist das von der technischen Seite so abgesegnet @wolfgangmm @windauer ?

**Comment by windauer** [comment]
@NicolauLutz von der Handhabung aus technischer Sicht, wäre es deutlich leichter, wenn die xml:id einfach über alle Dokumente eindeutig ist und dann müssten Verweise innerhalb eines Tagebuches auch nicht anders gehandelt werden als Verweise auf einen anderen Band. Wäre das noch möglich? Als z.B. `xml:id="tb2_p_20"`. 

Also eigentlich wie Dein Beispiel mit `xml:id="Reisetagebuch-2.xml#p_20"` wobei ich glaube, dort meintest Du eigentlich ein <ref type="cross" target="Reisetagebuch-2.xml#p_20"></ref>` als Verweis auf ein anderes Tagebuch und die xml:id in Reisetagebuch-2.xml wäre dann doch "nur" `xml:id="p_20"` oder? Das hätte dann den Nachtei, dass wir `target="Reisetagebuch-2.xml#p_20"` jedes mal parsen müssen, das richtige Tagebuch raussuchen und dort dann die richtige xml:id finden. Techisch ist das auf jeden Fall machbar, aber eben etwas aufwendiger als ein einfacher ID lookup und auch im processing teurer, weswegen ich Euch eindeutige xml:ids über alle Tagebücher empfehlen würde.

**Comment by NicolauLutz** [comment]
> Also eigentlich wie Dein Beispiel mit `xml:id="Reisetagebuch-2.xml#p_20"` wobei ich glaube, dort meintest Du eigentlich ein `<ref type="cross" target="Reisetagebuch-2.xml#p_20"></ref>` als Verweis auf ein anderes Tagebuch und die xml:id in Reisetagebuch-2.xml wäre dann doch "nur" `xml:id="p_20"` oder? 

Ja ich meinte das so.

Dein Lösungsvorschlag (`xml:id="tb2_p20"`) finde ich gut. Wir müssten dann die bestehenden Tags umbenennen, aber es sind nicht viele. 

Es gäbe noch einen weiteren Fall, und zwar ein Verweis auf ein Kapitel/Reisetag (eine `<div>`): 

Bis jetzt gibt es dazu eine Instanz, bei der der Tag so aussah: 

`xml:id="d_29_8"` (also d_[Tag]_[Monat]). 

Solche fälle würde ich dann mit `xml:id="tb2_d_29_8"` taggen?

**Comment by windauer** [comment]
@NicolauLutz klingt gut für mich, ggf. könnten auch die xml:ids für Kapitel/Reisetag wieder die Seite beinhalten, also `xml:id="tb2_p20_d_29_8"` allerdings ist uns das nicht wichtig, toll wäre nur wenn alle `xml:id` über alle Tagebücher eindeutig sind.

**Comment by NicolauLutz** [comment]
Im [Wiki](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/wiki/OXYGEN:-Textcodierung-(TEI-Tags)) festgehalten.

@vrukavina: Stellen im TB 1851 und 1825 entsprechend updaten.

**Comment by vrukavina** [comment]
Bei Verweisen auf ein anderes Tagebuch als Ganzes kann aber weiterhin ref cross target="reisetagebuch-[Zahl].xml" verwendet werden? Den Namen der Datei sollten wir, glaube ich, nicht ändern.
