### ISSUE TITLE
Website: Itinerar Anzeige

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#308]
Ich habe festgestellt, dass das Itinerar auf der Karte abgekürzt wiedergegeben wird bzw. nicht alle nummerierten Ortspunkte berücksichtigt werden.

Beispiel TB 1814, Paris 15. August (https://gf.tei-publisher.com/itinerary/reisetagebuch-2.xml?root=1.5.4.8) 

<img width="297" alt="Screen Shot 2023-03-08 at 15 50 02" src="https://user-images.githubusercontent.com/92101460/223983236-0a49350b-9893-464e-8af1-be44147a0be0.png">

Der Punkt "Palais Royal" ist verbunden mit dem Punkt "Tuileriengarten". Das stimmt für das vorgehende Kapitel, aber in diesem Kapitel würde im Itinerar auf den Punkt "Palais Royal" (n=20) der Punkt "Louvre Museum" (n=21) folgen. Den Punkt "Louvre Museum" verbindet die Karte mit dem Punkt "Waffengeschäft Lepage", obwohl in diesem Kapitel und im nummerierten Itinerar der Punkt "Palais Royal" (n=22) folgen müsste (im xml Zeilen 66 und 67).

**Comment by vrukavina** [comment]
Weitere falsche Anzeige vom Itinerar im Tagebuch 1794:
Von der Shoe Lane in London (n=101) geht Fischer nach Hause nach Schaffhausen (n=102), und nicht nach Kopenhagen wie auf der Karte angezeigt:
![Bildschirmfoto 2023-03-24 um 12 31 38](https://user-images.githubusercontent.com/102786242/227510417-7c62c89b-10c2-4012-9d65-82c7120a00a8.png)

https://gf.tei-publisher.com/itinerary/reisetagebuch-1.xml?root=1.5.4.4.11

**Comment by windauer** [comment]
done

**Comment by windauer** [comment]
siehe https://gf.tei-publisher.com/itinerary/reisetagebuch-2.xml?view=div&odd=gf-tagebuecher&root=1.5.4.6 (ggf. ist ein "shift + reload" im Browser nötig, damit die Daten richtig angezeigt werden)
