### ISSUE TITLE
Itinerar Tagebuch 1851

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#309]
Das Itinerar des Tagebuchs 1851 wird weder auf der Übersichtsseite der Reisen/TB noch in den Tagebuchseiten selber angezeigt. Es ist aber schon länger vollständig vorhanden im xml-file.
<img width="271" alt="Bildschirmfoto 2023-03-10 um 14 20 03" src="https://user-images.githubusercontent.com/92036071/224326361-5a32f6b9-e8f7-42f2-8b1b-d69a39203ca5.png">

**Comment by windauer** [comment]
@feggimann der Grund dafür ist, dass in `reisetagebuch-7.xml` die meisten placeName folgendermaßen aussehen: 

`<placeName type="itinerar_London51" `

Wenn ich mit Suchen / Ersetzen den type zu `itinerar` anstatt `itinerar_London51` ändere, funktioniert auch die Geodaten Generierung und dann wird die Reise auch sauber angezeigt. 

Beim der Fehlersuche ist mir aufgefallen, dass es noch weitere, "falsche" itinerar attribute gibt, z.B. in `reisetagebuch-1.xml`  gibt es 2 x `itinerar_Stockholm` und in `reisetagebuch-7.xml` gibt es 2 x `itinerar_London1851` als type.  Wenn ihr eine Volltextsuche nach `itinerar_` über alle Reisetagebücher macht, solltet ihr die sehr leicht finden und fixen können. Alternativ kann ich das auch tun wenn ihr mögt. 

<img width="949" alt="Screenshot 2023-03-14 at 14 16 36" src="https://user-images.githubusercontent.com/514615/225012830-efb34bc2-ebbe-45ca-b030-8b08febf7fd6.png">

**Comment by windauer** [comment]
@vrukavina ich kann Deinen Änderungen auf https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/commits/master noch nicht sehen. Sobald sie im Git vorhanden sind, kann ich das TB 1851 nochmal prozessieren und Euch eine neue Version auf https://gf.tei-publisher.com/ bereitstellen.

**Comment by windauer** [comment]
Tagebuch 1851 ist jetzt auf der Übersichtsseite und den Detailseiten sichtbar: https://gf.tei-publisher.com/start.html
