### ISSUE TITLE
Anton: Wikimedia Bild wird nicht angezeigt

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#31]
https://archives.georgfischer.com/actors/7381

**Comment by ottosmops** [comment]
Ich glaube, dass wir das anders lösen müssen. Wir müssen die Bilder wohl doch herunterladen. Ausserdem würde ich dann den Fotografen und die Lizenz speichern und anzeigen wollen.

**Comment by ottosmops** [comment]
Ich denke wir müssen die Bilder herunterladen und in Anton hochladen. Dann sollten wir aber Fotograf und Lizenz dazu abspeichern. Das müssen wir noch diskutieren, bevor ich es umsetze.

**Comment by feggimann** [comment]
ID 7381 ist erledigt und funktioniert.

**Comment by vrukavina** [comment]
ID 7404 wurde ausgewechselt und ID 7438 neu verknüpft. Beide werden nun angezeigt.

**Comment by ottosmops** [comment]
Idee: Wir legen eine Sammlung mit Bildern in Anton an. Dort verzeichnen wir auch Fotograf und Rechte, sowie Herkunft (genaueres müssten wir noch festlegen). Anschliessend programmiere ich die Möglichkeit Bilder aus Anton bei den Akteuren, Orten und Schlagworten einzubinden.

**Comment by ottosmops** [comment]
Lösungsvorschlag:

## Vorschlag

### Bestand für externe Bilder

Einzelstücke:
- pro Datensatz ein Bild
- Titel 
- Erstellung: Fotograf, Datum
- Reproduktionsbestimmungen: Lizenz/Public Domain 

Zu beachten: alle Datensätze müssen nicht gesperrt und ohne Schutzfrist sein  
Optimierung: neues Selectfeld für Lizenzen

### Verlinkung in Akteur/Ort/Schlagwort:
```
Provider: "anton image"
Provider ID: Object-ID
URL: /objects/Object-ID
```

**Comment by ottosmops** [comment]
Bsp: https://archives.georgfischer.com/actors/5432

**Comment by ottosmops** [comment]
- Titel => Bildlegende
- Reproduktionsbestimmungen => Lizenz
- Form und Inhalt => Künstler
- Kopien/Reproduktionen => Fotograf

Nur den Deskriptor (akteur usw) verlinken, zu dem das Bild gehören soll.
