### ISSUE TITLE
Umbenennungen

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#313]
Bitte an allen Stellen "Schlagworte" in "Begriffe" umbenennen.
Bitte in Detailansicht Registereinträge für externe Quellen "Weiterführende Informationen" umbenennen in "Externe Links"
Bitte in Detailansicht Keywords "Kategorie: [...]" weglassen

**Comment by windauer** [comment]
@feggimann Detailansicht Keywords "Kategorie: [...]" weglassen meint nicht nur die Überschrift "Kategorie" sondern auch den Wert (also den Inhalt aus `tei:objectType`), richtig?

**Comment by feggimann** [comment]
@windauer genau, ganzen Kategoroie-Eintrag mit Wert weglassen

**Comment by windauer** [comment]
done
