### ISSUE TITLE
Datumsangaben highlighten

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#314]
Datumsangaben im Text farblich highlighten.
Bsp. Reisetagebuch 1 (1794) https://gf.tei-publisher.com/itinerary/reisetagebuch-1.xml?root=1.5.4.4.7
"Im kommenden Frühjahr" farblich highlighten.
<img width="559" alt="Bildschirmfoto 2023-03-10 um 15 21 50" src="https://user-images.githubusercontent.com/92036071/224339938-5c568f55-4d82-487e-af42-85b604c1a825.png">
<img width="784" alt="Bildschirmfoto 2023-03-10 um 15 23 29" src="https://user-images.githubusercontent.com/92036071/224340360-27ee53d3-f368-4d05-a501-b398f3d442ca.png">

**Comment by windauer** [comment]
done
