### ISSUE TITLE
Register Keywords - Quellen

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#315]
Listen in Quellen werden bei Keywords nicht korrekt angezeigt (bei Actors und Places hingegen korrekte Darstellung).

Bsp. "Gummi" mit zwei Quellen als Liste:
https://gf.tei-publisher.com/keywords/gfa-keywords-3522?category=G&search=gummi

<img width="839" alt="Bildschirmfoto 2023-03-10 um 15 30 23" src="https://user-images.githubusercontent.com/92036071/224341922-b6fcfac5-b3eb-4e55-8b3b-9d6a9ce6ce33.png">

**Comment by windauer** [comment]
Wir jetzt als Liste angezeigt: https://gf.tei-publisher.com/keywords/gfa-keywords-3522?category=G&search=gummi - allerdings nur als ein und nicht zwei Einträge, da es im source code nur ein `bibl` Element ist und nicht zwei. Damit zwei Einträge gerändert werden, muss `archives-keywords-tei.xml` entsprechend geändert werden. Momentan sieht es folgendermaßen aus: 

```
<note type="sources">
  <listBibl>
    <bibl>Gummi. In: Krünitz, J.G.: Oekonomische Encyklopädie, Band 20, 1780 (<ref target="https://www.kruenitz1.uni-trier.de/">Krünitz Online</ref>, Stand 22.2.2023). - Fischer, Johann Conrad: Tagebücher. Bearbeitet von Karl Schib. Schaffhausen 1951.</bibl>
  </listBibl>
</note>
```

**Comment by ottosmops** [comment]
Sollte nun im Export korrekt sein.
