### ISSUE TITLE
Anton: Doppel: Gig und Kabriolett (ID 9122 und 8909)

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#316]
Ich habe schon Chaise und Kabriolett zusammengelegt. Im Grunde handelt es sich auch bei der Gig um dasselbe wie beim Kabriolett (leichte, zweirädrige Kutsche).

Desshalb würde ich vorschlagen, nur Kabriolett zu behalten, und Gig zu löschen.

**Comment by vrukavina** [comment]
Wenn es wirklich Synonyme sind, dann stimmte ich zu.
Beim Beschrieb von Kabriolett muss dann aber noch die Bezeichnung Gig ergänzt werden. Die ID befindet sich aber schon im Lektorat.. Ist es diesen Aufwand wert?
