### ISSUE TITLE
Head "Titelseite"

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#317]
Könnt ihr bitte in den xml-Files im Abschnitt "titlepage" jeweils einen head "Titelseite" einfügen, als Titel und für das Inhaltsverzeichnis.

**Comment by NicolauLutz** [comment]
Wir können keinen `head` einfügen ohne eine `div`, und in den Abschnitt `titlepage` können wir keine `div`einfügen.

Ich habe nun nach dem Abschnitt `titelpage`eine neue `div`mit dem `head` "Titelseite" gesetzt. Das sollte funktionieren.

**Comment by windauer** [comment]
@feggimann wie soll die Titelseite denn genau aussehen? Soll dort wie jetzt groß "Titelseite" stehen und da drunter dann der eigentliche Titel, oder "Titelseite: <HIER DER TITEL>" oder soll "Titelseite" durch den eigentlichen Titel ersetzt werden?

**Comment by feggimann** [comment]
"Titelseite" ist die Überschrift oder der Seitentitel und wird gleich wie die anderen Seitentitel im Rest des Tagebuchs dargestellt. So wie es jetzt steht ist gut. Der Inhalt ist alles was zw. "titlePage" und "/titlePage" steht, also der Text des Titelblatts in der gedruckten Ausgabe.

Hier Bsp. TB 1794 (reisetagebuch-1): Zeilen 17 bis 27.

<img width="953" alt="Bildschirmfoto 2023-04-02 um 23 28 38" src="https://user-images.githubusercontent.com/92036071/229379901-43ab37bf-fec7-4051-9e0a-2919a771a4ce.png">

**Comment by windauer** [comment]
Ist implementiert, siehe z.B. hier: https://gf.tei-publisher.com/itinerary/reisetagebuch-1.xml

Reisetagebuch-2.xml hat allerdings zwei titlePage Elemente, ist das Absicht? https://gf.tei-publisher.com/itinerary/reisetagebuch-2.xml

**Comment by feggimann** [comment]
@windauer zwei titlePage Elemente bei Reisetagebuch-2.xml: das ist im Original so, ein vollständiges Titelblatt und eine weitere Seite mit Kurztitel. Unter "Titelseite" sollte nur das erste titlePage Element angezeigt werden. Können wir das zweite im xml lassen oder müssen wir es löschen?

**Comment by feggimann** [comment]
@windauer Text der titlePage Elemente ist jetzt da, aber der Titel "Titelseite" (wie im Inhaltsverzeichnis) ist weg. Bitte "Titelseite" wieder als Seitentitel hin und darunter das titlePage Element.

**Comment by feggimann** [comment]
ist ok
