### ISSUE TITLE
Edition: Bilder werden nicht angezeigt

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#318]
Die Bilder, die sich im Anhang im TB 1851 befinden, werden nicht angezeigt. 
[https://gf.tei-publisher.com/itinerary/reisetagebuch-7.xml?root=1.4.4.70](https://gf.tei-publisher.com/itinerary/reisetagebuch-7.xml?root=1.4.4.70)
![Bildschirmfoto 2023-03-14 um 17 06 02](https://user-images.githubusercontent.com/102786242/225066811-e3558b6f-d812-41db-ad53-1f5c2f03c011.png)
![Bildschirmfoto 2023-03-14 um 17 07 53](https://user-images.githubusercontent.com/102786242/225067217-508af2f3-8398-410d-be64-11b6c591f7fb.png)

**Comment by windauer** [comment]
@vrukavina  wir gehen davon aus, dass diese Bilder direkt im Text und nicht in der extra Spalte als Thumbnail angezeigt werden sollen, richtig? Das sähe dann so aus, wie im Screenshot. 

Damit das möglich ist, fügt bitte der url jeweils noch ein ".." hinzu, sowie in diesem Bsp: `<graphic url="../images/JCF1851_3_Stadtplan1.jpg"/>`

Und mir ist aufgefallen, dass es das Bild `JCF1851_3_Palastskizze.jpg` nicht gibt, dafür aber `JCF1851_2_Palastskizze.jpg` und anstatt `JCF1851_4_Stadtplan2.jpg` müsste es wohl `JCF1851_4_Stadtplan2.png` heißen, zumindest gibt es kein `JCF1851_4_Stadtplan2.jpg`. Bitte bestätigt kurz, ob ich das richtig verstanden habe und stellt sicher, dass die Verlinkung stimmt und die Bilder da sind, dann baue ich das gerne ein. 


<img width="1899" alt="Screenshot 2023-03-14 at 18 02 09" src="https://user-images.githubusercontent.com/514615/225090932-578562c0-f4c9-4e7e-8122-1ba43acc8c8e.png">

**Comment by vrukavina** [comment]
Genau, es handelt sich um Skizzen/Bilder, die im Text vorkommen. Es sollten schon überall die "..." stehen, und die Dateien habe ich nun auch alle als jpeg gespeichert.

Vielen Dank!

**Comment by windauer** [comment]
@vrukavina wunderbar, das funktioniert jetzt auch. Allerdings gibt es noch ein Problem mit dem Bild `JCF1794_2_Säule.jpg`, eXist-db weigert sich, wegen dem Umlaut das Bild in der Datenbank zu speichern. Wäre es möglich, dass Bild in `JCF1794_2_Saeule.jpg` umzubennen und die Referenz in Reisetagebuch-1.xml entsprechend anzupassen?  

Und wenn ich nach `<graphic url="images` suche, finde ich immer noch 13 Vorkommnisse wo die bitte in  `<graphic url="../images` geändert werden müssen.

**Comment by vrukavina** [comment]
> @vrukavina wunderbar, das funktioniert jetzt auch. Allerdings gibt es noch ein Problem mit dem Bild `JCF1794_2_Säule.jpg`, eXist-db weigert sich, wegen dem Umlaut das Bild in der Datenbank zu speichern. Wäre es möglich, dass Bild in `JCF1794_2_Saeule.jpg` umzubennen und die Referenz in Reisetagebuch-1.xml entsprechend anzupassen?
> 
> Und wenn ich nach `<graphic url="images` suche, finde ich immer noch 13 Vorkommnisse wo die bitte in `<graphic url="../images` geändert werden müssen.

Das sieht super aus im TB 1851. Vielen Dank! :)
Ja, das geht. Ich habe den Dateinamen wie vorgeschlagen angepasst.

**Comment by vrukavina** [comment]
> das ganze ist jetzt auch auf https://gf.tei-publisher.com/itinerary/reisetagebuch-7.xml?root=1.4.4.70 sichtbar. Wichtig wäre noch die Umbenennung von Dateinamen und Referenz von 'Säule' zu "Saeule" und das Anpassen der Pfade zu den Bildern in den Daten (fehlende "..")

Ich verstehe nicht ganz was fehlt. Wenn wir eine url zum Bild setzen, dann kommt automatisch die Struktur: graphic url= "images/JCF1794_2_Saeule.jpg"/>. Diese soll nun umgeschrieben werden damit sie immer so aussieht: graphic url="JCF1794_2_Saeule.jpg/images" ?

**Comment by vrukavina** [comment]
@windauer Im TB 1794 wird ein Bild im Fliesstext ebenfalls nicht angezeigt. Zeile 213 im xml. Sieht so aus: figure xml:id="fig1"><graphic url="images/JCF1794_1_Bohrkopf.jpg"/> /figure

**Comment by feggimann** [comment]
...hier noch die Formeln für TB 1

Bild 1:
`von dieser Figur <figure xml:id="fig1"><graphic url="images/JCF1794_1_Bohrkopf.jpg"/></figure> versehen`

Bild 2:
`<figure xml:id="fig2">
                        <graphic url="JCF1794_2_Saeule.jpg/images"/>
                        <figDesc>Säule unter dem <term ref="gfa-keywords-9057">Frontispiece</term> von der <placeName ref="gfa-places-1524">Münze</placeName> in <placeName ref="gfa-places-142">Stokholm</placeName>, nach Art derer zu <placeName ref="gfa-places-1522">Pestum</placeName> vorgefundenen.</figDesc>
                    </figure>`

**Comment by feggimann** [comment]
Bilder TB 7 (1851):
![grafik](https://user-images.githubusercontent.com/92036071/234887068-07119196-6a4f-42a3-bbd8-e1f8f6e226c3.png)

Bild 1:
https://gf.tei-publisher.com/itinerary/reisetagebuch-7.xml?view=div&odd=gf-tagebuecher&root=1.4.4.50

`<figure xml:id="fig1">
                    <graphic url="images/JCF1851_1_Muenze.jpg"/>
                </figure>`

![grafik](https://user-images.githubusercontent.com/92036071/234887519-245b6812-9fd0-4690-8b2f-eba4eeb69391.png)

Bilder 2-4:
https://gf.tei-publisher.com/itinerary/reisetagebuch-7.xml?view=div&odd=gf-tagebuecher#TB7_p_107

`<figure xml:id="fig2">
                    <graphic url="images/JCF1851_2_Palastskizze.jpg"/>
                </figure>
                <pb n="108" facs="https://www.e-rara.ch/ebs/content/zoom/16618596"/><lb/>
                <figure xml:id="fig3">
                    <graphic url="images/JCF1851_3_Stadtplan1.jpg"/>
                </figure>
                <pb n="109" facs="https://www.e-rara.ch/ebs/content/zoom/16618597"/><lb/>
                <figure xml:id="fig4">
                    <graphic url="images/JCF1851_4_Stadtplan2.jpg"/>
                </figure>`

![grafik](https://user-images.githubusercontent.com/92036071/234887833-55e16cc3-b631-406a-b77d-824735dbaba5.png)
