### ISSUE TITLE
TB 1851 12. Juni

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#319]
Freiburg ist mit Karlsruhe verlinkt - falsche ID beim Tagging?
<img width="693" alt="Bildschirmfoto 2023-03-14 um 17 40 23" src="https://user-images.githubusercontent.com/92036071/225075838-ca41ac56-7319-49a4-8bbd-0d2ec26dcf09.png">
TB 1851

**Comment by vrukavina** [comment]
Falscher Tag wurde korrigiert.
