### ISSUE TITLE
Fischers Stahlwerke im Mühlental

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#320]
Bitte die ID 1216 (Stahlgiesserei/Werk I) nicht in der Edition verwenden. Für Fischers Werke zu seinen Lebzeiten sind folgende zwei IDs möglich:
- ID 84 (Kräutermühle): bis ca. 1835
- ID 1967 (Fischers Stahlwerke): ab ca. 1835

Hier müsste der Tag noch korrigiert werden:
![grafik](https://user-images.githubusercontent.com/92036071/225284033-8ab6a04b-ff47-4503-a0bb-a617f9ea97c5.png)

**Comment by vrukavina** [comment]
Wurde im TB 1851 korrigiert.
