### ISSUE TITLE
TB 1825-1827: Itinerar Änderung mit <anchor>

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#323]
Zur Information/Rückmeldung @windauer @wolfgangmm:

Wir haben das Itinerar des TB 1825-1827 angepasst. Es wurden drei neue "Geister" Itinerarpunkte eingeführt (mit `<anchor>` im Text markiert), um die jeweilige Rückkehr nach Schaffhausen zwischen den Reisen von 1825, 1826, und 1827 zu Illustrieren. Ich habe jetzt auch Nummern mit Dezimalstellen in die Nummerierung des Itinerars eingeführt. 

Zeile 31: Neuer Itinerarpunkt für Schaffhausen: 

`<placeName ref="gfa-places-131" type="itinerar" when="1825" notBefore="1825-07-26" notAfter="1825-10-19" n="1"><anchor/></placeName>`

Zeile 41: Itinerar Nummer geändert auf `n="1.1"`

Zeile 88: Neuer Itinerarpunkt für Schaffhausen:

`<placeName ref="gfa-places-131" type="itinerar" notBefore="1825-10-23" notAfter="1826-11-30" n="18.1"><anchor/></placeName>`

Zeile 113: Neuer Itinerarpunkt für Schaffhausen:

`<placeName ref="gfa-places-131" type="itinerar" notBefore="1826-12-05" notAfter="1827-09-20" n="28.1"><anchor/></placeName>`

**Comment by feggimann** [comment]
erledigt
