### ISSUE TITLE
Anzeige von Datumsangaben 

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#325]
Bei Datumsangaben, die dem Muster date when="JJJJ-MM-DD" folgen, ist die Anzeige richtig: farblich hinterlegt + Popup.
Bei solchen, die so aussehen: date from="JJJJ-MM-DD" to="JJJJ-MM-DD" ist die Angabe in der Edition fabrlich hinterlegt, aber es erscheint kein Popup/keine Info. Könnt ihr das bitte auch noch implementieren?

Screenshot (https://gf.tei-publisher.com/itinerary/reisetagebuch-1.xml?root=1.5.4.4#1.5.4.4.3)
![Bildschirmfoto 2023-03-22 um 16 54 14](https://user-images.githubusercontent.com/102786242/226963629-ae169804-30cb-4618-b332-147e64a9f418.png)
Beispiel: TB 1794, Zeile 59 im xml
![Bildschirmfoto 2023-03-22 um 16 56 50](https://user-images.githubusercontent.com/102786242/226964225-8f797eda-2088-49fe-ab5b-055d9f23c680.png)

**Comment by NicolauLutz** [comment]
Es gibt auch noch den Fall mit `<notBefore>`und `<notAfter>`.

**Comment by NicolauLutz** [comment]
Soweit ich weiss kommen sie nicht alleine vor.

**Comment by vrukavina** [comment]
Sie kommen nicht alleine vor

> Soweit ich weiss kommen sie nicht alleine vor.

@windauer Genau. Sie kommen nicht alleine vor.

**Comment by vrukavina** [comment]
Es gibt das date auch in Kombination mit Zeitangaben, und manchmal gibt es keine Tages- und/oder Monatsangabe, also z.B. date when="1794", oder "1794-05".
