### ISSUE TITLE
Anzeige: Fussnoten

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#326]
Im TB 1794 ist auf einer Seite die Anzeige der Fussnoten fehlerhaft. Sonst aber immer korrekt.

https://gf.tei-publisher.com/itinerary/reisetagebuch-1.xml?root=1.5.4.4.11
![Bildschirmfoto 2023-03-24 um 08 39 04](https://user-images.githubusercontent.com/102786242/227455990-7b2cb420-5998-4f66-9cba-7cef3d578670.png)

**Comment by windauer** [comment]
done

**Comment by vrukavina** [comment]
Zwei neue Fälle im TB 1851:
![Bildschirmfoto 2023-04-05 um 11 33 50](https://user-images.githubusercontent.com/102786242/230102696-98d2cf37-0ad2-45fc-8f62-7a47892313d3.png)
(22 Juni)
und
![Bildschirmfoto 2023-04-05 um 15 55 54](https://user-images.githubusercontent.com/102786242/230103034-34f1f484-47d4-4961-8c5c-2f24a75204c7.png)
(2. Juli)

**Comment by windauer** [comment]
@vrukavina es wäre toll, wenn Du bitte bei solchen Funden neben dem Screenshot auch immer einen Link zu der jeweiligen Seite hinzufügst, Danke! Das gilt übrigens eigentlich immer, dass das für uns sehr hilfreich ist, weswegen ich hier auch @feggimann und @NicolauLutz erwähne. Keine Kritik, so können wir einfach ein ganz bissl schneller sein, was dem Projekt Zeit aka Geld spart ;)
