### ISSUE TITLE
Anzeige: Popups bei mehrfachem Tagging

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#327]
Könnten bitte auch noch im Falle des Observatoriums (Doppeltag: place und keyword) die Popups "vereint" werden?
Jetzt sieht es so aus: https://gf.tei-publisher.com/itinerary/reisetagebuch-1.xml?root=1.5.4.20
![Bildschirmfoto 2023-03-24 um 08 54 37](https://user-images.githubusercontent.com/102786242/227459383-f77b28c7-1a96-4e4c-9acf-b8c1bcf372f9.png)

Schön wäre es, wenn es so aussehen könnte wie bei der Kaiserkrönung: https://gf.tei-publisher.com/itinerary/reisetagebuch-1.xml?root=1.5.4.4.5
![Bildschirmfoto 2023-03-24 um 08 58 08](https://user-images.githubusercontent.com/102786242/227459622-fb3903d5-6e7f-4551-b65a-145a740d11df.png)

**Comment by vrukavina** [comment]
Wird anders kodiert werden.

**Comment by windauer** [comment]
sollte jetzt überall gefixt sein. Ansonsten bitte nochmal ein neues Bsp mit URL und screenshot, danke.
