### ISSUE TITLE
Edition: TB 1814 Seitenumbrüche

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#329]
Auf der Editionsseite fehlen beim TB 1814 die Zeichen (Striche), welche einen Seitenumbruch markieren. Könnt ihr das bitte in diesem TB auch so programmieren, dass sie angezeigt werden? Danke!

**Comment by vrukavina** [comment]
Das Problem betrifft alle Tagebücher ausser TB 1794.

**Comment by windauer** [comment]
fixed, see: https://gf.tei-publisher.com/itinerary/reisetagebuch-2.xml?root=1.5.4.6&view=div&odd=gf-tagebuecher
