### ISSUE TITLE
Edition: Schriftart und -grösse von Brüchen und Formeln

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#330]
Könnten die Brüche und Formeln auch in der gleichen Schriftart und -grösse angezeigt werden, wie der restliche Text der Tagebücher? Dies ist im Moment nicht der Fall.
Hier ein Beispiel aus dem TB 1814: 
![Bildschirmfoto 2023-04-03 um 12 21 07](https://user-images.githubusercontent.com/102786242/229483023-85a7a2c9-67fd-4c9f-ba7b-ab04179ed474.png)
(Die $-Zeichen habe ich jetzt gelöscht. Wird es dann immer noch richtig angezeigt?)

Kodiert haben wir das ganze nach folgendem Muster im xml (Zeile 254): 
![Bildschirmfoto 2023-04-03 um 12 27 23](https://user-images.githubusercontent.com/102786242/229484262-ccb5609c-280b-461a-a891-96e1c50b34f5.png)

**Comment by vrukavina** [comment]
Dasselbe gilt für TB 1851, Kapitel "Über den englischen Absatzmarkt, 27. Juni 1851". Hier scheinen die Ziffern noch grösser zu sein.
![Uploading Bildschirmfoto 2023-04-05 um 15.02.10.png…]()

**Comment by windauer** [comment]
Das ist leider nicht möglich, MathML unterstützt im Moment nur die eigene Schriftart, siehe: https://docs.mathjax.org/en/latest/output/fonts.html#mathjax-font-support - Auch ein Anpassen der Größe ergibt keinen Sinn, da genau das eine der Stärken von MathML ist, eine Formel so zu rendern, dass sie mathematisch richtig dargestellt wird ohne die Zeilenhöhe kaputt zu machen und dadurch zu komischen Whitespace und anderen Problemen zu führen. Ich fürchte, dass Anpassen der Schriftart und -größe für Formeln die via MathML gerendert werden, ist deswegen nicht möglich und auch nicht sinnvoll.
