### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by windauer** [GF-Corporate-Archives/gf-johann-conrad-fischer#332]
Dies ist ein Issue um Design Fragen zu sammeln,  zu klären und zu verlinken. Bitte antwortet gerne in den Kommentaren oder lasst uns, da wo es sinnvoll ist einzelne Tickets zum Thema Design erstellen und hier verlinken.   

### Webseite Farben
Wir nutzen momentan noch das "Entwicklungsfarbschema" um gewisse Kontraste besser sehen zu können. Dieses Schema ist aktuell auch auf https://gf.tei-publisher.com/ zu sehen. Dazu folgende Fragen: 

* Dürfen wir die Farben vom Entwicklungsfarbschema auf das finale Farbschema wechseln? 
* Gibt es Wünsche von Georg Fischer Seite, welche Farben für was genau genutzt werden sollen, ob ggf. noch weitere Farben dazukommen sollen? 

* Entwicklungsfarbschema:  <img width="1268" alt="GF-Dev-Color-Scheme" src="https://user-images.githubusercontent.com/514615/230329787-f93b4439-49a3-489d-9787-73f673dd9e1e.png">
* Finale Farbschema: <img width="1284" alt="GF-Final-Color-Scheme" src="https://user-images.githubusercontent.com/514615/230329793-c61ede73-584f-4ae9-b3fc-6e51cbbda951.png">

### Generell Design Fragen /  Wünsche
* im ersten Schritt werden wir uns Design mäßig darauf konzentrieren, dass das Design auf verschiedenen Displays (Großer Bildschirm, Laptop, Tablett, Mobile) gut aussieht und technisch alles wie erwartet funktioniert. Teilt uns gerne generelle Wünsche zu Schriftarten, Proportionen, Anordnungen usw. mit.

**Comment by feggimann** [comment]
@windauer Bitte die Farben bis Ende April noch lassen. Dann melden wir uns auch noch genauer zu Design. Danke!
