### ISSUE TITLE
Darstellung mehrfach getaggter Einheiten

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#334]
Wir haben die mehrfach getaggten Einheiten nun so "verschachtelt", dass der Tag, der am nächsten am Originaltext steht, als am bedeutendsten gilt.
Wäre es möglich die Popups dann quasi in dieser Reihenfolge (von Innen nach Aussen) anzuordnen? Die Farbe, mit welcher das mehrfach getaggte Wort eingeblendet wird, sollte dann die Farbe der Kategorie des ersten Tags erhalten.

Beispiel: placeName term persName XXXXXXXX /persName /term /placeName
Popups verbunden + in der Reihenfolge: Akeurseintrag, Schlagworteintrag, Ortseintrag
Farbe des Textes (hier: XXXXXXX) = Farbe der Kategorie "Akteure"

**Comment by windauer** [comment]
Textfarben sind entsprechend implementiert, popups sind wir noch dran

**Comment by vrukavina** [comment]
Beim Anzeigen der Popus scheint etwas noch nicht ganz zu stimmen. Hier z.B. wird das Popup zum keyword Gussstahlfabrik einmal korrekt mit dem Popup zum Ort verbunden und einmal erscheint es separat.

https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/blob/master/src/reisetagebuch-3.xml
![Bildschirmfoto 2023-05-03 um 10 21 54](https://user-images.githubusercontent.com/102786242/235867140-feef9803-bf67-4471-a809-adbff32965ec.png)

https://gf.tei-publisher.com/itinerary/reisetagebuch-3.xml?view=div&odd=gf-tagebuecher&root=1.5.4.4
![Bildschirmfoto 2023-05-03 um 10 30 49](https://user-images.githubusercontent.com/102786242/235867356-d356c09b-7afe-488b-8a93-96e4c2b851a2.png)

**Comment by vrukavina** [comment]
Hier werden die Popups hingegen, wie damals zu Beginn, nicht verbunden:

https://gf.tei-publisher.com/itinerary/reisetagebuch-3.xml?view=div&odd=gf-tagebuecher&root=1.5.4.6
![Bildschirmfoto 2023-05-03 um 10 35 34](https://user-images.githubusercontent.com/102786242/235868545-02e246ad-ded2-49bc-b2d0-64cbd836a160.png)

https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/blob/master/src/reisetagebuch-3.xml
![Bildschirmfoto 2023-05-03 um 10 35 51](https://user-images.githubusercontent.com/102786242/235868607-aedbc85b-d480-4708-85aa-46d11e2e0a65.png)
