### ISSUE TITLE
Kopfzeile Beschriftung

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#335]
Das EB-Logo wird noch ersetzt durch rundes Home-Signet (folgt in ein paar Tagen). Bitte Wort "Home" rechts daneben löschen. Bitte "Bildergalerie" mit einem L statt "Bildergallerie"

<img width="764" alt="Bildschirmfoto 2023-04-12 um 22 04 25" src="https://user-images.githubusercontent.com/92036071/231572477-1de06180-0449-48e8-a95b-9bf03de3db7f.png">

**Comment by windauer** [comment]
done. Das Logo wechseln wir aus, wenn es vorhanden ist und wir ans finale Design gehen.
