### ISSUE TITLE
Inhaltsverzeichnis Nummerierung

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#336]
Die Nummerierung der Titel/Seiten im Inhaltsverzeichnis ist verschwunden. Bitte wieder einfügen.
<img width="678" alt="Bildschirmfoto 2023-04-12 um 22 08 42" src="https://user-images.githubusercontent.com/92036071/231573007-0d2f054f-17f7-478a-a2bd-7908aa3027c7.png">

**Comment by windauer** [comment]
das ist leider wg Update auf TEI Publisher 8 weggeflogen.. Funktioniert jetzt aber wieder.
