### ISSUE TITLE
Karte in Seitenansicht: weisses Datumsfeld

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#337]
Beim Aufrufen einer Inhaltsseite erscheint das Datumsfeld des ersten Itinerarpunkts. Bitte weglassen, da übersichtlicher.

Bsp. https://gf.tei-publisher.com/itinerary/reisetagebuch-2.xml?view=div&odd=gf-tagebuecher&root=1.5.4.6

Feld "Paris" mit vier Datumsangaben sollte nicht schon beim Aufrufen automatisch da sein, sondern erst wenn man mit der Maus über den Punkt fährt, wie bei den anderen Punkten.

<img width="909" alt="Bildschirmfoto 2023-04-12 um 22 11 38" src="https://user-images.githubusercontent.com/92036071/231574010-f9ae0bf3-3225-45e6-a236-197c4a6dccd6.png">

**Comment by windauer** [comment]
done, siehe https://gf.tei-publisher.com/itinerary/reisetagebuch-3.xml?lang=de&view=div&odd=gf-tagebuecher&root=1.6.4.146

**Comment by feggimann** [comment]
ok
