### ISSUE TITLE
Inhaltsseite Personenliste: Anzeige Lebensdaten

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#338]
In den Inhaltsseiten in der Spalte der Listen mit den Registereinträgen bitte Lebensaten von Personen von–bis (mit langem Bindestrich) statt */✝

Falls nur Geburts- oder Todesjahr vorhanden, dann mit */✝

Bsp. https://gf.tei-publisher.com/itinerary/reisetagebuch-2.xml?view=div&odd=gf-tagebuecher&root=1.5.4.8

Bonaparte, Napoleon (1769–1821)
<img width="535" alt="Bildschirmfoto 2023-04-12 um 22 17 17" src="https://user-images.githubusercontent.com/92036071/231575669-b6f67342-51e9-4ecd-93a1-3a87426f9e03.png">

**Comment by windauer** [comment]
Ich habe mich jetzt für den "Gedankenstrich" entschieden, der längste Strich, der Geviertstrich sah im Text merkwürdig aus. 
 
‐ | Bindestrich (auch Divis) | `&#x2010;`
‑ | Geschützter Bindestrich | `&#x2011;`
– | Gedankenstrich | `&#x2013;`
— | Geviertstrich | `&#x2014;`

**Comment by feggimann** [comment]
Genau, Gedankenstrich ist richtg. Bitte keine Leerschläge vor/nach Gedankenstrich, also (1745–1812) statt (1745 – 1812)

**Comment by windauer** [comment]
ist mit dem nächsten update gefixt

**Comment by feggimann** [comment]
ok
