### ISSUE TITLE
grosses Popup mit Bildern: Darstellung

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#340]
Bitte bei grossen Bilderpopups immer zuoberst Bild, darunter Name: Beschreibung

Bsp. https://gf.tei-publisher.com/itinerary/reisetagebuch-2.xml?view=div&odd=gf-tagebuecher&root=1.5.4.8

**Actors**: Name (von–bis): Beschreibung
[Bild]
Denon, Vivant (1747–1825): Französischer Künstler und Diplomat.
[Weitere Informationen](https://gf.tei-publisher.com/names/gfa-actors-7626)

<img width="1479" alt="Bildschirmfoto 2023-04-12 um 22 29 35" src="https://user-images.githubusercontent.com/92036071/231577965-9d3d5cfb-6090-4b2a-9c71-67dd955357bd.png">

**Places**: Name, Stadt/Ort: Beschreibung
[Bild]
Théâtre des Variétés, Paris: Bühne für Musiktheater in Paris, gegründet um 1807 durch Marguerite Brunet.
[Weitere Informationen](https://gf.tei-publisher.com/places/gfa-places-1598)

<img width="1479" alt="Bildschirmfoto 2023-04-12 um 22 36 52" src="https://user-images.githubusercontent.com/92036071/231578902-8be205a0-2784-43f4-a302-36cd20eee496.png">

Keywords: Name: Beschreibung
[Bild]
Colonne Vendôme: Steinerne, zwischen 1806 und 1810 errichtete Siegessäule mit Bronzeverkleidung auf dem Place Vendôme in Paris.
[Weitere Informationen](https://gf.tei-publisher.com/keywords/gfa-keywords-8432)

<img width="1479" alt="Bildschirmfoto 2023-04-12 um 22 39 26" src="https://user-images.githubusercontent.com/92036071/231579530-fcb3a7a4-921f-42c3-b4d9-b09c3c9e2b7a.png">

**Comment by windauer** [comment]
@feggimann soll das wirklich unterschiedlich sein bei kleinen und großen Bildern? Ich denke, es ergibt mehr Sinn, das immer gleich zu machen, also z.B. immer den Text unter das Bild. Alternativ können wir sicherlich auch eine maximale Größe für Bilder festlegen und den Text so lassen wie er ist, aber eben sicherstellen, dass das Bild höchsten in der max Größe angezeigt wird.

**Comment by feggimann** [comment]
@windauer Ich meine grosse (schwarze) Popups im Gegensatz zu kleinen (weissen) Popups im Fliesstext. Dieses Issue bezieht sich nur auf die grossen schwarzen Popups, egal ob grosse oder kleine Bilder. Innerhalb dieser Popups Anordnung bei allen Bildern gleich, wie oben beschrieben.

**Comment by windauer** [comment]
wurde entsprechend geändert, siehe hier: https://gf.tei-publisher.com/itinerary/reisetagebuch-1.xml?lang=de&view=div&odd=gf-tagebuecher&root=1.6.4.2 - beim generellen CSS Feinschliff kommen da noch Abstände usw. dazu.
