### ISSUE TITLE
Inhaltsseiten: lange Listen der Keywords/Places/Actors

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#343]
In den Inhaltsseiten sind die Listen in der Registerspalte teilweise sehr lang. Ist es möglich, pro Typ nur die ersten 5 als Standard anzuzeigen und den Rest mit einer Akkordeon-/Ausklappfunktion?

Bsp. https://gf.tei-publisher.com/itinerary/reisetagebuch-2.xml?view=div&odd=gf-tagebuecher#d_29_8

ca. 30 Orte und 50 Keywords! (ist das der Rekord? :-))

**Comment by windauer** [comment]
aktuelle Beispiele mit langen listen: 

* https://gf.tei-publisher.com/itinerary/reisetagebuch-2.xml?view=div&odd=gf-tagebuecher&root=1.5.4.20#d_29_8
* https://gf.tei-publisher.com/itinerary/reisetagebuch-2.xml?view=div&odd=gf-tagebuecher&root=1.5.4.32#d_29_8

**Comment by feggimann** [comment]
Hat sich mit angepasstem Design erübrigt
