### ISSUE TITLE
Detailansicht Register: Bild vergrössern in Popup

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#349]
Bei Detailansicht Registerdaten Bild vergrösserbar in Popup (wie bei Bildergalerie oder Bilderspalte). Popup nur mit Bild und darunter Bildlegende (anton image title). Für alle drei Registerarten.

Bsp. https://gf.tei-publisher.com/keywords/gfa-keywords-8521?category=T&search=tragbar&view=div

Bild in Popup vergrösserbar. Darstellung Popup: Bild, darunter "Tragbare Dampfmaschine von Matthew Murray (Zeichnung von C. Livesey), 1805"

<img width="1683" alt="Bildschirmfoto 2023-04-16 um 16 58 23" src="https://user-images.githubusercontent.com/92036071/232323818-078813b7-798e-47f5-9b0a-675719b6ea7a.png">

**Comment by windauer** [comment]
@feggimann passt das jetzt so mit der Größe: https://gf.tei-publisher.com/keywords/gfa-keywords-8521?category=T&search=tragbar&view=div ?

**Comment by feggimann** [comment]
erledigt
