### ISSUE TITLE
Anton: Neuer 'Typ' bei den Keywords: "Schriftstück, Publikation"

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#35]
Ein Typ um Schriftstücke, Druckwerke, Manuskripte, etc. zusammenzufassen, wie die keywords 8421-8428

**Comment by feggimann** [comment]
@ottosmops bitte Typenliste in den Keywords ergänzen mit "Buch, Manuskript, Publikation"
