### ISSUE TITLE
Detailansicht Personen

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#351]
Bei Detailansicht Personen bitte ändern (s. Bsp. unten):

**mittlere Textspalte**
- Bei Überschrift "Person:" weglassen, Bsp. "Russell, John Scott" statt " Person: Russell, John Scott"
- Unter Überschrift drei Zeilen mit Typ, Lebensdaten, andere Namensformen, Bsp. 
Person
9. Mai 1808 – 8. Juni 1882
Weitere Namensformen: John Scott Rüssel
- Lebensdaten: Monat ausschreiben und für von-bis Gedankenstrich statt kurzer Bindestrich, Bsp. "9. Mai 1808 – 8. Juni 1882" statt "9. May 1808 - 8. Jun 1882"
- Lebensdaten: falls nur Geburts- oder Todesdatum bekannt, dann angeben mit "geboren 9. Mai 1808" bzw. "gestorben 8. Juni 1882"

Bsp. siehe hier: https://gf.tei-publisher.com/names/gfa-actors-7479?view=div

<img width="1683" alt="Bildschirmfoto 2023-04-16 um 17 15 27" src="https://user-images.githubusercontent.com/92036071/232325168-3e591136-9631-494b-9729-b6629321736b.png">

**Comment by windauer** [comment]
@ottosmops ich sehe keinen "Typ" in den Daten, oder übersehe ich da etwas? Gilt neben `person` auch für `org` und `personGrp`

**Comment by ottosmops** [comment]
Ich denke hier ist "Person" der Typ. Und eben "Personengruppe" und "Körperschaft" (für Organisation) 

@feggimann Bitte bestätigen und die Begriffe aud Deutsch und Englisch liefern

**Comment by ottosmops** [comment]
@windauer Im Frontend komms Du auf die meisten Datsätze ohne Anmeldung darauf: https://archives.georgfischer.com/actors/7479

**Comment by feggimann** [comment]
Mit Typ meinte ich (de / en):
- Person / Person
- Organisation / Organization
- Familie / Family

**Comment by feggimann** [comment]
schaut gut aus
