### ISSUE TITLE
TEI-Export Actors

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#352]
Bitte TEI-Export anpassen:

**persName type="full"**
- Lebensjahre mit Gedankenstrich statt kurzem Bindestrich verbinden
- Bsp. Actor ID 7479: Russell, John Scott (1808–1882) >> statt (1808-1882)

**Bildlegende (image / title):** 
- Datierung vor/nach Gedankenstrich kein Leerschlag
- Falls Datierung in Anton Image mit ca.: "um" vor Datierung (nur 1x vorne, nicht bei beiden Zahlen)
- Bsp. Actor ID 7479, Anton Image ID 127117 
- Bildlegende aktuell: John Scott Russell (Gemälde von Henry Wyndham Phillips), 1840 – 1850
- Bildlegende neu: John Scott Russell (Gemälde von Henry Wyndham Phillips), um 1840–1850

**Comment by ottosmops** [comment]
Die Bildlegende ist so m.E. teilweise irreführend, Beispiel https://archives.georgfischer.com/objects/124049

Wird im Moment zur Legende: "König Friedrich V. (Portrait von Andreas Møller), 1736–1741" Die Jahresangabe müsste in die Klammer?

@feggimann kannst Du mir hierfür angeben, wie die Bildlegende aussehen sollte. 

- NB: Zweimal "ca." durch einmal zu ersetzen führt zu Mehrdeutigkeiten.

**Comment by feggimann** [comment]
Bildlegende wird neu nicht zusammengesetzt, sondern Legende = Titel. Daten/Laufzeiten werden manuell in den Titel geschrieben.

**Comment by ottosmops** [comment]
aus meiner Sicht erledigt
