### ISSUE TITLE
TEI-Export Actors: Biografiefeld bei Familien / Detaileintrag Register für Familien

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#353]
@ottosmops Bei Familien (personGrp role="family") fehlt das Biografiefeld (Geschichte) im TEI-Export. Bitte ergänzen.

@windauer Bitte Familien (personGrp role="family") gleich darstellen wie Personen in Detailansicht Register: 
- Überschirft = Name
- darunter Typ = "Familie"
- darunter Beschreibung/Geschichte
- Quellen
- Externe Links

**Comment by ottosmops** [comment]
Bitte überprüfen

**Comment by windauer** [comment]
Wird mit dem nächsten ausrollen hier https://gf.tei-publisher.com/names/gfa-actors-1237?lang=de gefixt sein.

**Comment by feggimann** [comment]
schaut gut aus
