### ISSUE TITLE
TEI-Export Actors: bei Körperschaften Laufzeit/Datum ergänzen

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#354]
Bei TEI-Export fehlen:

**Laufzeit/Datum**
- Bitte bei Körperschaften die Laufzeit bzw. das Datum ergänzen analog zu Lebensdaten bei Personen. 

**orgName type="full"** 
- analog zu Personen hinten in Klammer Daten ergänzen wo vorhanden
- Bsp. Actor ID 7375 (Lateinische Schule)
- orgName type="full" aktuell = Lateinische Schule (Schaffhausen)
- orgName type="full" neu = Lateinische Schule (Schaffhausen) (1525–1850)

**Comment by ottosmops** [comment]
@windauer @wolfgangmm in `<org>` gibt es kein Datumelement wie `<birth>`. 

Ich habe es jetzt mal so eingebaut:

```xml
<event type="start" when="1525"/>
<event type="end" when="1850"/>
```
Wenn Ihr es anders braucht, bitte melden.

**Comment by feggimann** [comment]
ok
