### ISSUE TITLE
Detailansicht Körperschaften

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#355]
Bei Detailansicht Organisationen bitte ändern (s. Bsp. unten) - TEI der Registerdaten wird von Andreas noch angepasst:

**mittlere Textspalte**
- [x] Bei Überschrift "Organisation:" weglassen, Bsp. "Royal Institution of Great Britain " statt "Organisation: Royal Institution of Great Britain "
- Unter Überschrift drei Zeilen mit Typ, Daten, andere Namensformen, Bsp.
    - [x] Organisation
    - [x] 1799–1814
   -  [x] Weitere Namensformen: xxx

- [x] Daten/Laufzeit: für von-bis Gedankenstrich statt kurzer Bindestrich, Bsp. "1808–1882"
- [x] Lebensdaten: falls nur Gründungsdatum bekannt, dann angeben mit "gegründet 1808"

S. Beispiel https://gf.tei-publisher.com/names/gfa-actors-7575?category=R&search=royal&view=div

<img width="1683" alt="Bildschirmfoto 2023-04-16 um 17 16 46" src="https://user-images.githubusercontent.com/92036071/232335455-70dfc641-b1ac-4d02-a9e1-e8e3c51ecf9c.png">

**Comment by windauer** [comment]
done, wird mit dem nächsten Update ausgerollt.

**Comment by feggimann** [comment]
ok
