### ISSUE TITLE
TEI-Export Places: Felder ergänzen Typ und andere Namensformen

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#356]
Bei TEI-Export von Places bitte folgende Felder ergänzen/ändern:
- Typ (Gewässer / Strasse / Gebäude / Stadt, Dorf / Berg etc.)
- Andere Namensformen

**Comment by ottosmops** [comment]
@windauer Da es hier kein Element "Typ" gibt, habe ich es in das Attribute `@type` geschrieben.

**Comment by feggimann** [comment]
@ottosmops Kannst du im TEI Export schon die ß eliminieren und in ss umwandeln (oder sogar für den Anton allgemein - fände ich auch nicht schlecht) - dann muss das nachher in der Edition nicht mehr angepasst werden @windauer . Ich glaube, das sind nur zwei bei den places:
- Großbritannien > Grossbritannien
- Typ Straße, Eisenbahnlinie

<img width="524" alt="Bildschirmfoto 2023-05-11 um 22 33 53" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/64291982-bc15-407f-aad4-1c725f226e61">

<img width="524" alt="Bildschirmfoto 2023-05-11 um 22 33 36" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/85dc088d-f04d-410d-840a-9c600b5696ae">

**Comment by feggimann** [comment]
@ottosmops wir haben die englischen Bildlegenden für anton image in die Titelfelder eingepflegt. Können die dann beim TEI Export für die englsichen TB exportiert werden, damit wir sie nicht ein zweites Mal einpflegen müssen?

Ich habe gestern versucht, in der englischen Oberfläche einen TEI Export zu machen, da kam ein fatal error.

**Comment by feggimann** [comment]
@ottosmops TEI Export für englische TB: können Länder englisch exportiert werden?

**Comment by windauer** [comment]
wird sauber angezeigt: https://gf.tei-publisher.com/places/gfa-places-89?lang=de&category=L&search=London

**Comment by feggimann** [comment]
schaut gut aus
