### ISSUE TITLE
Detailansicht Orte anpassen

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#357]
Bei Detailansicht Places bitte ändern (s. Bsp. unten) - TEI der Registerdaten wird von Andreas noch angepasst:

**mittlere Textspalte**
- [x] Bei Überschrift "Ort:" weglassen, Bsp. "Shoe Lane" statt "Ort: Shoe Lane"
- [x] Unter Überschrift drei Zeilen mit Typ, Settlement/Country, andere Namensformen, Bsp.
    Strasse, Eisenbahnlinie [bitte kein ß verwenden >> ss]
    London, Vereinigtes Königreich [Country bitte ausschreiben, nicht Kürzel]
    Weitere Namensformen: xxx
- Rest wie bisher (Beschreibung, Quellen, Externe Links)

Bsp. https://gf.tei-publisher.com/places/gfa-places-1493?view=div

<img width="1683" alt="Bildschirmfoto 2023-04-16 um 17 21 18" src="https://user-images.githubusercontent.com/92036071/232336496-2bfb3f42-9e85-4b59-b64e-6803a23ee3d6.png">

**Comment by windauer** [comment]
wir benötigen eine Liste aller Länder mit ihrem Key und dem deutschen und englischen Namen.

**Comment by windauer** [comment]
siehe https://gf.tei-publisher.com/places/gfa-places-1493?view=div

**Comment by feggimann** [comment]
schaut gut aus
