### ISSUE TITLE
Oxygen: Fehlermeldung beim Gebrauch des "&"

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#36]
Reisetagebuch von 1851, Zeilen 23 und 198
![Bildschirmfoto 2022-05-10 um 14 24 27](https://user-images.githubusercontent.com/102786242/167628480-d4cb2998-40e0-466e-aa46-d66ea7f2111c.png)

**Comment by ottosmops** [comment]
Schreib statt '&' '&amp;'

**Comment by ottosmops** [comment]
:-) `&amp;`
