### ISSUE TITLE
Anton Keywords: Typ "Objekt" / Typen in TEI-Export

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#361]
Typ "Objekt" bei Keywords bitte umbenennen in "Objekt, Maschine, Gerät, Werkzeug, technisches Instrument" (englisch: Object, machine, apparatus, tool, technical instrument"

Und dann das Feld Typ auch in den TEI-Export aufnehmen.

**Comment by ottosmops** [comment]
@windauer Der Objekttyp ist im TEI vermutlich zeigt ihr ihn noch nicht an? `<objectType>`

@feggimann Umbenennung sollte durch sein.

**Comment by ottosmops** [comment]
https://archives.georgfischer.com/tei/archives-keywords-tei.xml

**Comment by feggimann** [comment]
@ottosmops Danke! Hatte ich gar nicht überprüft im TEI. Danke auch für Umbenennung, alles bestens.

**Comment by windauer** [comment]
wird in der nächsten Version mit ausgerollt

**Comment by feggimann** [comment]
schaut gut aus
