### ISSUE TITLE
Reisetagebuch-1 (1794): Inhalt wird nicht richtig angezeigt, Fehler beim Blättern, S. 3 kann nicht angewählt werden

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#362]
Zahlreiche Seiten von reisetagebuch-1 (1794) werden nicht richtig angezeigt. 

Bsp. Titelblatt, Seite 1 (Widmung) und Seiten 6 bis 9 werden korrekt angezeigt:
https://gf.tei-publisher.com/itinerary/reisetagebuch-1.xml?view=div&odd=gf-tagebuecher&root=1.5.4.2&hash=1.5.4.4.3
<img width="1683" alt="Bildschirmfoto 2023-04-17 um 20 54 27" src="https://user-images.githubusercontent.com/92036071/232584949-435f13ef-3aeb-4991-ae04-2ca64810ce12.png">

Seiten 2 bis 5 und wieder ab Seite 10 werden nicht richtig angezeigt: "the server did not return any content"
https://gf.tei-publisher.com/itinerary/reisetagebuch-1.xml?view=div&odd=gf-tagebuecher&root=1.5.4.2&hash=1.5.4.4
<img width="1683" alt="Bildschirmfoto 2023-04-17 um 20 54 47" src="https://user-images.githubusercontent.com/92036071/232585718-40e5a53f-4cbd-443c-834d-8ece5eaf80fc.png">

Blättern funktioniert auch nicht richtig, plötzlich erscheint Titelblatt neben Registerlisten einer Seite:
https://gf.tei-publisher.com/itinerary/reisetagebuch-1.xml?view=div&odd=gf-tagebuecher&root=1.5.4.4&hash=1.5.4.4.3
<img width="1683" alt="Bildschirmfoto 2023-04-17 um 21 05 03" src="https://user-images.githubusercontent.com/92036071/232586146-0f2fd40f-4faf-4c62-abbb-6eacb1f60a9a.png">

Seite 3 (Jugend und Ausbildung) kann im Inhaltsverzeichnis nicht angewählt werden (reagiert nicht bei Mausklick), die anderen Seiten aber schon.

**Comment by windauer** [comment]
fixed, sollte alles wie gewohnt funktionieren, inklusive Auswahl von "Seite 3 (Jugend und Ausbildung) " im Inhaltsverzeichnis
