### ISSUE TITLE
Reisetagebuch-1: Orte auf Karte führen nicht auf Tagebuchseite

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#363]
Wenn ich auf der Startseite der Edition auf einen Itinerarort des TB 1794 klicke, kommt folgende Fehlermeldung: 

<img width="1280" alt="Screen Shot 2023-04-16 at 16 54 44" src="https://user-images.githubusercontent.com/92101460/232711259-31afc1d8-6668-4259-b54d-91fa3a4ed4f8.png">

Website: https://gf.tei-publisher.com/start.html?view=div
Browser: Chrome Version 103.0.5060.134

**Comment by windauer** [comment]
ich habe den Fehler gefunden und behoben. Allerdings macht github.com gerade Ärger, weswegen ich die neue Version noch nicht ausrollen kann. Ich schreibe hier, sobald das wieder funktioniert.

**Comment by windauer** [comment]
neuste Version ist ausgerollt und das rendering der Tagebuchseiten funktioniert wieder.

**Comment by NicolauLutz** [comment]
Stockholm ist ein anderes Beispiel.

**Comment by windauer** [comment]
danke! Ich kann den Fehler reproduzieren. Mein Bugfix war offensichtlich kein Bugfix sondern hat einen neuen Fehler erzeugt. Schaue ich mir an

**Comment by windauer** [comment]
dieser Fehler sollte nun endlich behoben sein.

**Comment by NicolauLutz** [comment]
Funktioniert soweit ich sehen kann, Danke!
