### ISSUE TITLE
Suche

### ISSUE THREAD

**Issue by windauer** [GF-Corporate-Archives/gf-johann-conrad-fischer#364]
* [x] Suggestions / Autocomple (über alles Registerdaten) 
  * [x]  über "Label" / Design kenntlich machen, was Tagebuch und was Registerdaten sind
* [x] Suche mit drücken von "Return"
* [x] Trefferliste: KWIC wie bei Karl Barth 
* [x] bisherige filter entfernen, dafür (an Karl Barth orientiert): 
   * [x] Tagebücher (besonders hervorheben, sind nur 7) 
   * [x] Namen 
   * [x] Begriffe
   * [x] Orte 
* [x] Suche auslösen bei klick auf Lupe

Bekannt Einschränkung der Suche: Auswahl mehrerer Personen / Begriffe / Orte innerhalb eines Suchfeldes ist eine "oder" und keine "und" Verknüpfung. 

Suche soll angelehnt sein an [Karl Barth Suche](https://kbga.karl-barth.ch/texts/?query=Karl&dates=&sort=last-modified) und [Spiegel.de Suche](https://www.spiegel.de/suche/?suchbegriff=Scholz) (bei Spiegel insb. das "Lupe" + Input)

**Comment by feggimann** [comment]
Bitte Reihenfolge der Suchfelder:
Tagebücher
Namen
Orte
Begriffe
(Registerdaten immer in dieser Reihenfolge)

**Comment by windauer** [comment]
done

**Comment by ottosmops** [comment]
Gibt es keine direkte Möglichkeit auf die Suche zu kommen?

**Comment by windauer** [comment]
done

**Comment by feggimann** [comment]
passt
