### ISSUE TITLE
Karte - Zoom passend zur Reise der jeweiligen Seite 

### ISSUE THREAD

**Issue by windauer** [GF-Corporate-Archives/gf-johann-conrad-fischer#365]
Die Karte soll so gezoomed werden, dass alle Orte die auf der jeweiligen Seite bereist wurden, auf der Karte sichtbar sind. 

Information zum Zoom sollte aus Daten generiert werden, falls nicht möglich "händisch" ein Zoom Level verwenden. Falls letzteres muss @feggimann asap Bescheid wissen um entsprechende Ressourcen einzuplanen.

**Comment by feggimann** [comment]
schaut super aus
