### ISSUE TITLE
Karte - Farbe der Marker passend zur Reise der jeweiligen

### ISSUE THREAD

**Issue by windauer** [GF-Corporate-Archives/gf-johann-conrad-fischer#366]
* [x] must: Farbe der Kartenpunkte und Verbindungslinien anpassen:
   * [x] Itinerarpunkte und -linien grün
   * [x] nicht-Itinerar-Orte dunkelblau
* [x] should:  Die Marker der an diesem Tag bereisten Route andersfarbig darstellen. 
   * @windauer: ist primär ein technisches Problem, ggf. erst nach Vernissage. 

###### @feggimann  (24.05.23)
Frage betr. verschiedene Farben für Punkte in und ausserhalb der Karte ist noch offen (aktuellen Itinerarpunkte im Hauptgrün, die weiteren Itinerarpunkte in einem helleren Grün; die aktuellen nicht-Itinerar-Orte in einem dunklen Blau und die nicht aktuellen nicht-Itinerar-Orte in einem helleren Blau). Wenn unklar, schauen wir es nach Vernissage an.

###### @windauer  (20.04.23)
* Farbe könnte ein grelleres Orange als das jetzige sein, um die Verbindung deutlich zu machen. Ortsmarker für Reisedaten die nicht an dem Tag bereist wurden, aber sichtbar sind oder durch rauszoomen sichtbar werden, sollen Orange bleiben. 
Noch unklar was die technische Machbarkeit angeht aufgrund der verwendeten Kartenanwendung. 

###### @feggimann  (24.05.23)
Frage betr. verschiedene Farben für Punkte in und ausserhalb der Karte ist noch offen (aktuellen Itinerarpunkte im Hauptgrün, die weiteren Itinerarpunkte in einem helleren Grün; die aktuellen nicht-Itinerar-Orte in einem dunklen Blau und die nicht aktuellen nicht-Itinerar-Orte in einem helleren Blau). Wenn unklar, schauen wir es nach Vernissage an.

**Comment by feggimann** [comment]
Das gilt auch für die Punkte, die nicht auf dem Itinerar sind, sondern erwähnt werden (aktuell blaue Punke). D.h. es bräuchte 4 Farben:
- aktuelles Itinerar des Tages, weitere Itinerarpunkte beim Rauszoomen (z. B. starkes und blasses Orange)
- am Tag erwähnte Orte, weitere Orte des Tagebuchs, die beim Rauszoomen sichtbar werden (z.B. starkes und blasses Blau)

**Comment by feggimann** [comment]
@windauer @wolfgangmm Frage betr. verschiedene Farben für Punkte in und ausserhalb der Karte ist noch offen (aktuellen Itinerarpunkte im Hauptgrün, die weiteren Itinerarpunkte in einem helleren Grün; die aktuellen nicht-Itinerar-Orte in einem dunklen Blau und die nicht aktuellen nicht-Itinerar-Orte in einem helleren Blau)

Wenn unklar, schauen wir es nach Vernissage an. 

Bitte aber unbedingt Farbe der Kartenpunkte und Verbindungslinien anpassen:
- Itinerarpunkte und -linien grün
- nicht-Itinerar-Orte dunkelblau

**Comment by windauer** [comment]
done

**Comment by feggimann** [comment]
@windauer @wolfgangmm sehr schön, vielen Dank!

Nur ein Detail: in der englischen Version stimmt bei https://gf.tei-publisher.com/en/travels die Farbe von 1851 in der Liste links und in der Karte rechts nicht überein (zudem noch deutscher Titel "Reisetagebücher"):

<img width="1259" alt="Bildschirmfoto 2023-05-30 um 01 07 33" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/7f56a9f0-8f04-42eb-a8fb-76095fcf9333">

**Comment by feggimann** [comment]
@windauer @wolfgangmm ist es möglich, unterhalb der Karte eine Legende zu den Farben hinzuschreiben?

[dunkelgrüner Punkt] Itinerar des aktuellen Kapitels
[hellgründer Punkt] Itinerar der aktuellen Reise
[dunkelblauer Punkt] Ort erwähnt im aktuellen Kapitel
hellblauer Punkt] Ort erwähnt im aktuellen Tagebuch

Müsste sehr kleine Schrift sein, damit es nicht stört, etwa wie die REgisterlisten über der KArte.

Falls die Legende geht, übersetze ich sie noch auf Englisch.

**Comment by feggimann** [comment]
Erledigt. Letzter Punkt zur Karte wird in neuem Issue #417 weitergeführt.
