### ISSUE TITLE
Github Issues Organisation

### ISSUE THREAD

**Issue by windauer** [GF-Corporate-Archives/gf-johann-conrad-fischer#368]
Dies ist eine Metaticket, um organisatorische Dinge festzuhalten und Fragen zu klären: 

* @windauer:  hat [Milestones für Abgabetermine](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/milestones) angelegt. Würde sich freuen, wenn wir die verwenden. 
  * genauen Angabe auf den Milestones (z.B. Datum) sind ausm Bauch raus gewürfelt, gerne anpassen! 
  *  im Moment sind nur issues, welche an @windauer assigned sind, in Milestones einsortiert. Gerne auch für alle anderen issues nutzen.
* neue [Label](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/labels): 
  * "highest priority" - to be worked on asap
  * "high priority" - important to work on, but not as important as "highest priority"

**Comment by feggimann** [comment]
ok wird so angewendet
