### ISSUE TITLE
Bug: TB 1794: Itinerar falsche Verbindung

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#369]
Im Itinerar des TB 1794 wird eine Verbindung zwischen Kopenhagen und Schaffhausen angezeigt, die so nicht existieren dürfte.

Version: https://gf.tei-publisher.com/itinerary/reisetagebuch-1.xml?view=div&odd=gf-tagebuecher

<img width="281" alt="Screen Shot 2023-04-21 at 16 22 57" src="https://user-images.githubusercontent.com/92101460/233674797-bdcd0c7e-0cf7-4f6b-9c77-e5cd6c850685.png">

**Comment by feggimann** [comment]
Kopenhagen-Schaffhausen nicht mehr verbunden. Ok.
