### ISSUE TITLE
Karte - Pfeile für die Reiserichtung

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#370]
Wäre es möglich, den Itinerar-Verbindungen Pfeilen dazuzugeben, um die Reiserichtung darzustellen?

Sollte gemäss xml gehen: der Pfeil zeigt immer in Richtung der nächsthöheren `n=""`

**Comment by feggimann** [comment]
Das muss nochmals besprochen werden, hat momentan keine Priorität. Wenn, dann müsste definiert werden, ab welchem Zommlevel, da es sonst zu übersichtlich wird.

**Comment by windauer** [comment]
@feggimann wollen wir dieses Ticket in Milestone 2 verschieben und  nach der Vernissage diskutieren, wie wir damit verfahren?

**Comment by feggimann** [comment]
Wir lassen das, wäre zu aufwändig und unübersichtlich mit den verschiedenen Kartenzooms.
