### ISSUE TITLE
Karte - Ortsnamen ausserhalb eines Landes ohne Klammern im Namen anzeigen 

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#371]
Beispiel: Karte für TB 1794: Nordsee

![Screen Shot 2023-04-21 at 16 29 02](https://user-images.githubusercontent.com/92101460/233676085-8f9af641-eb34-43c7-835b-803003355bc7.png)

<img width="1280" alt="Screen Shot 2023-04-21 at 16 28 50 (2)" src="https://user-images.githubusercontent.com/92101460/233676150-ca39ea6f-eb13-48b5-87c7-675a4e8c40f9.png">

**Comment by windauer** [comment]
gefixt, siehe auch Ostesee auf https://gf.tei-publisher.com/itinerary/reisetagebuch-1.xml?lang=de&view=div&odd=gf-tagebuecher&root=1.6.4.2 

<img width="607" alt="Screenshot 2023-05-23 at 11 24 54" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/514615/e62fa016-2da5-401b-bcf8-3c36d4cbf7d4">
