### ISSUE TITLE
Kopfzeile Edition

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#373]
Die Kopfzeile bitte wie folgt aufbauen:

1. linke Seite
- Signet [Link zu home, Signet folgt]
- Reisen [Link zu start]
- Register [drop-down menu: Namen, Orte, Begriffe > Links zu names, places, keywords]
- Bildergalerie [Link zu gallery]
- Lupe [Link zu Suchseite]

2. reche Seite
- über die Edition [drop-down menu: über das Projekt, Editionsrichtlinien, Bibliografie, Impressum/Lizenz, Dank]
- DE / EN [Wahl Sprachversion]
- Anmeldefunktion löschen

**Comment by JoernT** [comment]
Ist soweit umgesetzt inkl. mobilem Menu
