### ISSUE TITLE
Fussnoten Unterschied zwischen Original und neuen FN

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#374]
Es gibt wenige FN, die schon im Originaltext drin waren, die sind mit * gekennzeichnet und sollten nicht in der Nummerierung unserer FN eingereiht werden.

Ursprüngliche FN sind gekennzeichnet: **note n="*" type="original"** und sollten mit * dargestellt werden und nicht mitgezählt bei neuen FN, die von uns kommen.

Bsp. FN 11 in TB 1794 sollte mit * sein und nicht mitgezählt, FN 12 wird dann zu FN 11 https://gf.tei-publisher.com/itinerary/reisetagebuch-1.xml?view=div&odd=gf-tagebuecher&root=1.5.4.4.29

![grafik](https://user-images.githubusercontent.com/92036071/234223408-c4510a2e-a4cc-46be-a43d-d6e3884b128e.png)
![grafik](https://user-images.githubusercontent.com/92036071/234223540-57068c90-a48b-4829-802b-9e82ae6033d0.png)

**Comment by windauer** [comment]
done, wird in den nächsten 1-2 Tagen ausgerollt.

**Comment by feggimann** [comment]
schaut gut aus
