### ISSUE TITLE
Problem Annotations: Tags wieder verschoben + Textelement verloren gegangen

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#375]
Ich bin dabei im Annotations zu taggen und habe beim zurückklicken auf die zuvor bereits bearbeitete Seite gesehen, dass sich die Tags verschoben haben (s. Pferdekräfte, Pfund Sterling, Kutsche, Schillings, Dampfschiff). Ausserdem ging auch ein Teil vom Text verloren, und zwar hiess das Dampfschiff Lord Melville und nicht nur "Lord".

https://georg-fischer.tei-publisher.com/reisetagebuch-3.xml?tab=0&root=1.5.4.10
![Bildschirmfoto 2023-04-25 um 10 57 41](https://user-images.githubusercontent.com/102786242/234227360-849c2933-a682-4969-b4dc-40af71d2ba96.png)

Im TEI betrifft das die Zeilen 198 bis 207. (https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/blob/master/src/reisetagebuch-3.xml)
![Bildschirmfoto 2023-04-25 um 11 02 50](https://user-images.githubusercontent.com/102786242/234228625-65a291a0-268b-4121-bd14-9c437a8868ee.png)

Wieso kommt es immer wieder dazu, dass dies passiert? Könnt ihr das beheben, damit das nicht mehr passiert oder mir Hinweise geben, auf was ich achten soll? Vielen Dank!

**Comment by wolfgangmm** [comment]
Ich habe versucht, das Problem bei mir zu reproduzieren und kann bestätigen, dass nach dem Speichern der Seite Tags verschoben sind. Es muss also im XML vor der entsprechenden Textsequenz (beginnend mit "von 36 Pferdekräften") irgendeine Besonderheit geben, die den Algorithmus stört. Welche genau, ist nicht ohne weiteres zu sagen. Das muss ich noch eruieren.

**Comment by wolfgangmm** [comment]
Es lag an der mathematischen Formel im selben Absatz. Diese müssen wir in den Annotationen unformatiert ausgeben, sonst kommt es zu besagten Verschiebungen. Das Problem sollte nun behoben sein.

Zur Korrektur der bereits verschobenen Tags empfiehlt es sich allerdings, wie folgt vorzugehen, da es ansonsten wieder zu Fehlern kommen kann:

1. falsches Tag löschen
2. Speichern
3. korrektes Tag neu eingeben

**Comment by vrukavina** [comment]
Die Korrektur funktionierte einwandfrei.
Vielen Dank fürs Identifizieren und Beheben des Problems!
