### ISSUE TITLE
<date> issues (@when, @notBefore, @notAfter)

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#376]
#### Date issues

* [ ] verifizieren, was mit Dates die Zeitangabe haben passiert (@NicolauLutz , @windauer )

##### alt 
Im TB 1794 Abschnitt 5 (Sachsen...) wird der Datumstag `<date when="1793-03">lm kommenden Frühjahr</date>` in der Edition als "Datum: 1793" angezeigt, aber der Datumstag `<date when="1793-10">im Oktober des gleichen Jahrs</date>` wid als "Datum: Oktober 1793" angezeigt.

**Comment by NicolauLutz** [comment]
Auch bemerkt:
TB 1825-1827 Abschnit 11 (Brunel zeigt...):

Kodierung: `<date when="1826" notBefore="1826-11-01" notAfter="1826-12-31">Ende des Jahres 1826</date>`
Anzeige: "Datum: 1826"

**Comment by vrukavina** [comment]
@windauer  Im TB 1825-1827 sieht es so aus:

![Bildschirmfoto 2023-05-24 um 10 11 48](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/12d2876b-1f03-4877-b172-8abe0fd1e0af)
https://gf.tei-publisher.com/itinerary/reisetagebuch-4.xml?lang=de&view=div&odd=gf-tagebuecher&root=1.6.4.20

im xml so:
![Bildschirmfoto 2023-05-24 um 10 10 49](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/31fb1f36-0957-4a94-b082-0a52037042fb)

Müssten man da vielleicht when= weglassen und nur mit notBefore und notAfter arbeiten?

**Comment by vrukavina** [comment]
Es gibt auch Fälle, wo es nur ein notAfter gibt. Ist das ein Problem?
Ausserdem haben einige Daten auch eine Zeitangabe. Das sieht dann jetzt so aus im xml:
![Bildschirmfoto 2023-05-24 um 11 14 39](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/c48c343a-b276-4fb8-856e-137d3e2ff177)

**Comment by windauer** [comment]
@vrukavina nur "notAfter" oder nur "notBefore" ist kein Problem. Wichtig für uns ist

* Wenn `@when` dann kein @notBefore oder @notAfter
* `@notBefore` und `@notAfter` dürfen zusammen oder einzeln vorkommen

Funktioniert das mit dem Rendering der Zeitangabe denn, wie ihr es erwartet und falls nicht, was ist Eure Erwartung?

**Comment by vrukavina** [comment]
Jetzt ist alles klar. Die Zeitangaben werden korrekt gerendert. Sieht jetzt alles super aus. Vielen Dank!
