### ISSUE TITLE
Anzeige doppelter und dreifacher Tag nicht korrekt

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#377]
TB 7 (1851), zwei verschiedene Personen getaggt, in der Anzeige erscheint nur eine.

https://gf.tei-publisher.com/itinerary/reisetagebuch-7.xml?view=div&odd=gf-tagebuecher&root=1.4.4.8

![grafik](https://user-images.githubusercontent.com/92036071/234297798-3f0d4b73-ebd2-42d2-8a2e-424376475a7b.png)

![grafik](https://user-images.githubusercontent.com/92036071/234297867-c9f79c6b-a589-44b0-9d50-fc10cd248015.png)

**Comment by feggimann** [comment]
Das scheint ein genereller Bug zu sein. Im gleichen Tagebuch bei einem Tag mit zwei anderen Actors erscheint auch nur der eine:

https://gf.tei-publisher.com/itinerary/reisetagebuch-7.xml?view=div&odd=gf-tagebuecher&root=1.4.4.24

![grafik](https://user-images.githubusercontent.com/92036071/234588467-821c08b9-8b31-413e-8322-86a4d4106f23.png)

![grafik](https://user-images.githubusercontent.com/92036071/234589005-20eef56b-d83e-4c81-a9a2-bd7185507b8a.png)

**Comment by NicolauLutz** [comment]
Weiteres Beispiel für einen dreifach-Tag im TB 7 (1851):

https://gf.tei-publisher.com/itinerary/reisetagebuch-7.xml?view=div&odd=gf-tagebuecher&root=1.4.4.8

Z. 61:
`Abends um 7 Uhr waren <persName ref="gfa-actors-35"><persName ref="gfa-actors-7449"><persName ref="gfa-actors-7450">wir</persName></persName></persName> in`

![Screen Shot 2023-05-03 at 10 23 45](https://user-images.githubusercontent.com/92101460/235879165-20ac00ea-4a58-4b14-989a-a426c39639e1.png)

**Comment by wolfgangmm** [comment]
Der Algorithums für die Auflösung mehrfach verschachtelter Popups wurde in XQuery neu implementiert. Damit sollte das Problem grundsätzlich behoben sein.
