### ISSUE TITLE
Pagebreak innerhalb eines getaggten Worts

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#378]
Ist es möglich, den Pagebreak innerhalb eines getaggten Begriffs separat anzuzeigen (d.h. Farbe wie Pagebreak und nicht im gleichen Popup wie Begriff)

Bsp. guss-(pb)-eisernen auf Seite https://gf.tei-publisher.com/itinerary/reisetagebuch-7.xml?view=div&odd=gf-tagebuecher&root=1.4.4.14

![grafik](https://user-images.githubusercontent.com/92036071/234305333-72b527f5-b598-418d-9747-5c9570f27080.png)

![grafik](https://user-images.githubusercontent.com/92036071/234305738-24b4daed-032e-4096-aedc-7c8f7eda1526.png)

**Comment by windauer** [comment]
@feggimann im Moment sieht das so aus: 

* URL: gf.tei-publisher.com/itinerary/reisetagebuch-7.xml?lang=de&view=div&odd=gf-tagebuecher&root=1.6.4.16

#### Text ohne Popover
<img width="139" alt="Screenshot 2023-05-23 at 13 46 33" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/514615/d614f1f3-1fb9-4958-8940-64ec892f7e83">

#### Popover "guss" und "eisernen" 
<img width="1237" alt="Screenshot 2023-05-23 at 13 46 19" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/514615/3d76cb77-fb3f-450d-b081-95f1e63bbaa4">

#### Popover "|" 
<img width="689" alt="Screenshot 2023-05-23 at 13 46 26" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/514615/24c173a4-bd73-4c1c-9d08-4ef1d43683d7">


Wenn Dir das so recht ist, würden wir das so lassen.

**Comment by feggimann** [comment]
super, danke
