### ISSUE TITLE
Anzeige Fussnoten-Popup fehlerhaft

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#379]
Im TB 7 (1851) wird das Popup einer Fussnote nicht korrekt dargestellt. (FN 12) Die nächste FN 13 wird wieder korrekt angezeigt. Liegt das an den Tags in der Fussnote oder woran?

Zeile 140:
ältern Brüder<note>Gemeint sind hier <persName ref="gfa-actors-7384">Wilhelm Fischer (1803—1882)</persName> und <persName ref="gfa-actors-148">Georg Fischer (1804—1888)</persName>.</note>

https://gf.tei-publisher.com/itinerary/reisetagebuch-7.xml?view=div&odd=gf-tagebuecher&root=1.4.4.26

![grafik](https://user-images.githubusercontent.com/92036071/234592295-5b0182e0-c72e-493b-be64-548c4c56c3cb.png)

**Comment by windauer** [comment]
@feggimann in der jetzigen Version wird Fußnote 12 (https://gf.tei-publisher.com/itinerary/reisetagebuch-7.xml?lang=de&view=div&odd=gf-tagebuecher&root=1.6.4.14) und 13 (http://localhost:8080/exist/apps/gf-tagebuecher/itinerary/reisetagebuch-7.xml?lang=de&view=div&odd=gf-tagebuecher&root=1.6.4.16) und 14, 15 (http://localhost:8080/exist/apps/gf-tagebuecher/itinerary/reisetagebuch-7.xml?lang=de&view=div&odd=gf-tagebuecher&root=1.6.4.26) richtig angezeigt. Das Problem sollte behoben sein.

**Comment by feggimann** [comment]
@windauer Das Popup zu Fussnote 14 ist immer noch übermässig gross (https://gf.tei-publisher.com/de/1851/16), aber wenn kompliziert zu fixen können wir es auch stehenlassen.

**Comment by feggimann** [comment]
@windauer Das Popup zu Fussnote 14 ist immer noch übermässig gross (https://gf.tei-publisher.com/de/1851/14). Kann man das ändern? Sonst lassen wir es dann so stehen.

**Comment by windauer** [comment]
@feggimann die ist so groß, weil da ganz rechts die beiden Bilder von den Personen zu sehen sind.. eigentlich müsste die also breiter sein, damit die Bilder zu sehen sind und nicht kleiner. Wir schauen mal, warum die Bilder die abgeschnitten werden und auf einmal gescrollt werden muss im Popup, das sollte nicht sein.

**Comment by windauer** [comment]
fixed

**Comment by feggimann** [comment]
super, passt
