### ISSUE TITLE
Formeln werden nicht korrekt angezeigt

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#380]
Tagebuch 7 (1851): Formel für Brüche wird nicht korrekt angezeigt.

https://gf.tei-publisher.com/itinerary/reisetagebuch-7.xml?view=div&odd=gf-tagebuecher&root=1.4.4.50

Formel 3/16: 1<formula rend="inline" notation="tex">\frac{3}{16}</formula>

![grafik](https://user-images.githubusercontent.com/92036071/234882698-661660c1-681d-42c3-be57-a2f7f4b22ba2.png)

**Comment by windauer** [comment]
gefixt, siehe: https://gf.tei-publisher.com/itinerary/reisetagebuch-7.xml?view=div&odd=gf-tagebuecher&root=1.4.4.52
