### ISSUE TITLE
Popup Place in Text wird nicht beim Wort selber angezeigt

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#381]
Popup ist verschoben und zentriert, steht nicht beim getaggten Wort.

TB 7 (1851): "eigenen Hause"=Charles Sandersons Zuhause

https://gf.tei-publisher.com/itinerary/reisetagebuch-7.xml?view=div&odd=gf-tagebuecher&root=1.4.4.56#TB7_p_107

`<placeName ref="gfa-places-2158" cert="0" type="itinerar" when="1851-07-07" n="102">eigenen Hause</placeName>`

![grafik](https://user-images.githubusercontent.com/92036071/234900446-0d5eb35f-676b-48f3-b38f-722dada4b91f.png)

**Comment by windauer** [comment]
sollte mit dem ausrollen des neuen Design behoben sein, siehe hier: http://localhost:8080/exist/apps/gf-tagebuecher/itinerary/reisetagebuch-7.xml?lang=de&view=div&odd=gf-tagebuecher&root=1.6.4.56

**Comment by feggimann** [comment]
@windauer ist bei Orten gefixt. Aber bei Keywords ist es immer noch eingemittet wenn Keyword über die Zeile geht. Ist aber auch nicht tragisch, von mir aus kein Milestone. Lassen wir so.
