### ISSUE TITLE
Dateinamen englische xml-Files

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#383]
Innerhalb der Files wird die Sprachversion in der ersten Zeile ausgewiesen:
`<TEI xmlns="http://www.tei-c.org/ns/1.0" xml:lang="de">`

Ist das korrekt?
Wie sollen wir die englischen xml-files benennen?
Speichern wir sie auch im Sourcesordner /src/ neben den deutschen files oder separat in einem neuen Ordner?

Vorschläge:
de: reisetagebuch-1.xml
en: traveljournal-1.xml
en: reisetagebuch-1-en.xml

**Comment by windauer** [comment]
@feggimann Sprachversion: ja, genau richtig! 

Am einfachsten wäre es für uns, wenn es in src einen "de" und "en" Ordner gebe, und wir die Dokumente in getrennten Ordnern haben. Schlussendlich könnt ihr das aber machen, wie es Euch am liebsten ist, da es ja nicht viele Tagebücher sind.

**Comment by NicolauLutz** [comment]
Ich habe einen neuen Ordner mit Namen "en" angelegt. Der Ordner enthält die datei der englischen Version des TB1 mit dem Dateinamen "traveljournal-1.xml".
