### ISSUE TITLE
Koordinaten: Walnut Cottage und Fabrik Wililam Fairbairn and Sons

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#386]
Es wäre gut, wenn diese zwei Orte nicht die gleichen Koordinaten aufweisen würden.

Walnut Cottage (https://archives.georgfischer.com/places/1951) ist das Landhaus von Lee. Dieses hat nicht viel mit der Fabrik von Fairbairn (https://archives.georgfischer.com/places/1718) zu tun.

**Comment by vrukavina** [comment]
Auch hier sind die genau gleichen Koordinaten: https://archives.georgfischer.com/places/1943

**Comment by vrukavina** [comment]
Hier ebenfalls: https://archives.georgfischer.com/places/1944 (The Dales)

**Comment by NicolauLutz** [comment]
Dazu müsste man die Koordinaten dieser Orte herausfinden, bzw. approximative Koordinaten definieren.

**Comment by vrukavina** [comment]
Genau. Hättest du Zeit dafür, weil du dich da schon auskennst?

**Comment by vrukavina** [comment]
Weiteres Beispiel: Sheffield auf der Karte als Rodgers and Sons
https://gf.tei-publisher.com/itinerary/reisetagebuch-7.xml?view=div&odd=gf-tagebuecher&root=1.4.4.38

**Comment by vrukavina** [comment]
Southwark als Phoenix Giesserei angezeigt
https://gf.tei-publisher.com/itinerary/reisetagebuch-7.xml?view=div&odd=gf-tagebuecher&root=1.4.4.38

**Comment by vrukavina** [comment]
Nun wieder aus dem TB 1825: Northern Exhibition als Ölgasanstalt angezeigt
https://gf.tei-publisher.com/itinerary/reisetagebuch-3.xml?view=div&odd=gf-tagebuecher&root=1.5.4.78

**Comment by vrukavina** [comment]
Leeds als Ölgastanstalt angezeigt: https://gf.tei-publisher.com/itinerary/reisetagebuch-3.xml?view=div&odd=gf-tagebuecher&root=1.5.4.78

**Comment by vrukavina** [comment]
Sheffield als Fischers Untekunft angezeigt: https://gf.tei-publisher.com/itinerary/reisetagebuch-3.xml?view=div&odd=gf-tagebuecher&root=1.5.4.92

**Comment by vrukavina** [comment]
Messerschmiede auch als Gussstahlfabrik angezeigt: https://gf.tei-publisher.com/itinerary/reisetagebuch-3.xml?view=div&odd=gf-tagebuecher&root=1.5.4.96

**Comment by vrukavina** [comment]
Gussstahldrahtzug auch als Fischers Unterkunft angezeigt: https://gf.tei-publisher.com/itinerary/reisetagebuch-3.xml?view=div&odd=gf-tagebuecher&root=1.5.4.98

**Comment by vrukavina** [comment]
T. Mill auch als Fischers Unterkunft angezeigt: https://georg-fischer.tei-publisher.com/reisetagebuch-3.xml?tab=0&root=1.5.4.104

**Comment by vrukavina** [comment]
Albion Hotel als Malleable Iron Factory angezeigt: https://gf.tei-publisher.com/itinerary/reisetagebuch-3.xml?view=div&odd=gf-tagebuecher&root=1.5.4.114

**Comment by vrukavina** [comment]
London wird als Etablissement für tragbares Ölgas angezeigt: https://gf.tei-publisher.com/itinerary/reisetagebuch-3.xml?view=div&odd=gf-tagebuecher&root=1.5.4.118

**Comment by feggimann** [comment]
@vrukavina hat sich das erledigt? dann bitte schliessen

**Comment by vrukavina** [comment]
Sieht gut aus.
