### ISSUE TITLE
Anton/keywords: ID 9179 umbenennen

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#387]
Kann die ID 9179 Doppelhobeleisen in Hobeleisen umbenannt werden? Dann würdees auch im TB 1825 vorkommen.

**Comment by NicolauLutz** [comment]
Kann man von mir aus tun. Die Beschreibung bezieht sich eigentlich auf ein
Hobeleisen.



Am Fr., 5. Mai 2023 um 11:17 Uhr schrieb vrukavina ***@***.***

**Comment by vrukavina** [comment]
Erledigt.
