### ISSUE TITLE
Edition: Querverweis funktioniert nicht

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#388]
Beim Anklicken auf den Querverweis auf der Seite https://gf.tei-publisher.com/itinerary/reisetagebuch-3.xml?view=div&odd=gf-tagebuecher&root=1.5.4.90 erscheint folgende Fehlermeldung:
![Bildschirmfoto 2023-05-09 um 09 48 44](https://user-images.githubusercontent.com/102786242/237030371-9236edb7-7641-43bd-874c-c213828307ff.png)

Im xml (https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/blob/master/src/reisetagebuch-3.xml) sieht es so aus: 
![Bildschirmfoto 2023-05-09 um 09 51 48](https://user-images.githubusercontent.com/102786242/237030927-ef81dd1c-b2e2-4c8b-8fb8-e3f11d54586b.png)

**Comment by windauer** [comment]
Was genau soll den passieren wenn `<ref type="cross" target="TB3_p_179">` als Link gerendert wird. Soll der auf die Seite `<head>Besuch der Flachsspinnerei Marshall Mills, 28. Juni 1825</head>` wechseln, wo dann das pb mit der richtigen ID als Kind steht (`<pb n="179" facs="https://www.e-rara.ch/ebs/content/zoom/16557920" break="no" xml:id="TB3_p_179"/>`) oder was genau soll passieren?

**Comment by vrukavina** [comment]
Ja, genau.
Dort sieht es im pb so aus: 
![Bildschirmfoto 2023-05-10 um 07 54 57](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/53882b06-9c6d-492c-9eb5-e0de2a92eadc)

**Comment by windauer** [comment]
done, siehe auf https://gf.tei-publisher.com/de/1825/46, dort wird aus `<ref type="cross" target="TB3_p_179">Rezept zur menschlichen Glückseligkeit</ref>` der link `<a href="TB3_p_179" class="tei-ref4 ref" target="">Rezept zur menschlichen Glückseligkeit</a>` der dann zu http://localhost:8080/exist/apps/gf-tagebuecher/de/1825/TB3_p_179 auflöst.

**Comment by vrukavina** [comment]
Super! Vielen Dank.
