### ISSUE TITLE
Fragen zum Design

### ISSUE THREAD

**Issue by line-o** [GF-Corporate-Archives/gf-johann-conrad-fischer#389]
Bei der Durchsicht und Umsetzung des neuen Designs sind uns folgende Punkte aufgefallen:

Fehlende Assets (nicht in den bereitgestellten Downloads enthalten):

- [x] GF  Kopf Logo fehlt (im Bestfall als SVG)
   <img width="86" alt="Screenshot 2023-05-05 at 15 19 52" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/657222/7de422df-0ad4-4e70-8b08-ba8e7d4aa0c4">
- [x]  Bibliothekslogo in Weiss fehlt (wir haben nur eine schwarz-blaue Version)
   <img width="243" alt="Screenshot 2023-05-05 at 15 34 51" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/657222/2f8af21b-452e-47bc-94e5-1dccef7955d5">
- [x]  Hintergrundbilder für die Register-Boxen auf der Homepage fehlen
- [x]  die Bilder für die Highlights haben unterschiedliche Seitenverhältnisse und sind teilweise sehr hochauflösend bekommen wir zugeschnittene Bilder die in das gelieferte Design passen?
- [x] Hintergrundbild für die Hauptüberschrift auf der Homepage fehlt

Unklares Layout:

- Allgemein:
   - [x] Dropdown Menu Einträge. Es ist aus dem Mockup nicht ersichtlich ob das Menü on hover oder on click erscheinen oder sogar immer angezeigt werden soll. Ein dropdown wäre einfach müsste aber einen hintergrund definieren.
   - [x] Im Design Mockup ragt das Menü in den Text hinein und hat einen grossen Abstand zum Überpunkt. Wie ist das gedacht. Zumindest müsste man den Overlap vermeiden. Siehe 
![Screenshot 2023-05-09 at 11 01 13](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/484059/e08d4612-ecff-44dd-a7f5-f73de7605751)
   - [x] Ein Beispiel für statische Inhaltsseiten wie Zitiervorschlag, Datenschutz und Impressum sind nicht in der Designvorlage enthalten
   - [x] Die Aufteilung des Footers ist unklar, wie zum Beispiel der Abstand des Lizenzhinweises vom rechten Bildrand
   - [x] Auf der Homepage ist das Namenregister mit "Personen" betitelt und die Reihenfolge der Boxen entspricht nicht der im Register-Dropdown. Soll der Titel und die Reihenfolge der Registerboxen denen des Dropdowns entsprechen?
- Reisetagebuch Detailseiten
   - [x] Auf Seite [3](https://xd.adobe.com/view/7c51f0b5-b6cf-48cc-89d6-69d56a08ae11-2902/screen/ba30d817-7839-4237-b07b-23fc3da7cc1a) und [4](https://xd.adobe.com/view/7c51f0b5-b6cf-48cc-89d6-69d56a08ae11-2902/screen/f5f2cef9-ce29-4bcd-b3af-aee1dc74e9a7) ist das Deckblatt neben der Akkordion Überschrift
   - [x] Auf Seite [5](https://xd.adobe.com/view/7c51f0b5-b6cf-48cc-89d6-69d56a08ae11-2902/screen/c0e2603b-f809-44d0-bd14-b4bede53bb4b) füllt das Akkordion die gesamte linke Spalte des Layouts.
   - [x] Die Akkordeonbreite sollte sich nicht ändern bei Ein- und Ausklappen.
- Ort-Detailansicht [Seite 10](https://xd.adobe.com/view/7c51f0b5-b6cf-48cc-89d6-69d56a08ae11-2902/screen/4498b0f6-6e2e-4849-bbc3-b83dc07aed8f):
   - [x] Sind die Spaltenbreiten mit der großen Lücke beabsichtigt oder können wir hier dieselben Spalten wie auf der Reisetagebuch Detailseite annehmen?
   - [x] Ortsregister [Seite 13](https://xd.adobe.com/view/7c51f0b5-b6cf-48cc-89d6-69d56a08ae11-2902/screen/965f49f7-4b67-4a87-ba58-f5d25c3342a4)
   - [x] Wir nehmen an das die drei Spalten mit Ortsbezeichnungen die gesamte Seitenbreite ausfüllen sollen. Ist das korrekt?
- Suche
   - [x] Design fehlt
- "Über die Edition"
   - [x] Design fehlt   
- Fehlerseite(n) 
   - [ ] Design fehlt    
   - [ ] im ersten Schritt eine generelle Fehlerseite mit "Die Seite existiert nicht. Bitte gehen sie hierhin....". Im zweiten Schritt, falls noch Luft, könnten wir für Tagebücher auch etwas bauen wie, "dieses Tagebuch gibt es in ihrer Sprache nicht".

**Comment by windauer** [comment]
* Iconbibliothek: wir nutzen die TEI-Publisher Icon Bibliothek bis auf weiteres
* Hintergrundbild für Startseite
* Tagebücher Milestone 1: 
  * Deutsch: alle außer 5 und 6
  * Englisch: 1 und 7
* de/en im URL Pfad funktioniert erstmal nicht, deswegen jetzt erstmal mit lang=en und lang=de.

**Comment by feggimann** [comment]
Fragen im Issue zu Registerspalten, die wir gestern nicht angesprochen haben:
- Bei Ortsregister ist rechts die Karte. Deshalb bitte Ortsregister nur einspaltig (S. [10](https://xd.adobe.com/view/7c51f0b5-b6cf-48cc-89d6-69d56a08ae11-2902/screen/4498b0f6-6e2e-4849-bbc3-b83dc07aed8f/))
- - S. [13](https://xd.adobe.com/view/7c51f0b5-b6cf-48cc-89d6-69d56a08ae11-2902/screen/965f49f7-4b67-4a87-ba58-f5d25c3342a4/) zeigt eine Variante für Register von Namen und Begriffen. Von mir aus kann es drei- oder auch einspaltig sein wie bei Orten. Wenn dreispaltig bitte wie von euch vorgeschlagen über die Seite verteilt, damit genügend Abstand zwischen den Spalten

**Comment by windauer** [comment]
Danke @feggimann, wegen Deinen Fragen meldet sich @line-o nochmal bei Dir zurück, aber ich denke mal, das passt alles so. 

Ich habe eben gerade eine neues [Ticket](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/issues/392) angelegt, in dem es darum geht, dass wir jetzt die Inhalte für die statischen Seite asap benötigen. Und dazu habe ich Dir [html templates für alle Seiten](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/tree/master/src/html-pages) in diesem Repo angelegt.

**Comment by feggimann** [comment]
Fehlerseiten kommen momentan nicht vor. Von mir aus ist das issue erledigt.
