### ISSUE TITLE
zu übersetzende Texte

### ISSUE THREAD

**Issue by windauer** [GF-Corporate-Archives/gf-johann-conrad-fischer#390]
Im Zip findet sich eine `de.json` und eine `en.json` Datei mit denen alle Label / Text gesteuert werden, die nicht aus dem TEI selbst kommen. In der `en.json` Datei fehlen viele Übersetzungen und in `de.json` gerne Verwendung von Begriffen prüfen. Bitte niemals den sog. Key ändern, sondern immer nur den Text rechts vom `:`. Also bei `"all": "Alle",` bitte nur den Inhalt von `"Alle"` ändern. 

* [lang-files-2023-05-09T1434.zip](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/files/11431145/lang-files-2023-05-09T1434.zip)

**Comment by feggimann** [comment]
Hier schon mal das deutsche File, das englische folgt morgen. Ich war mir nicht überall sicher, wo die Labels eingesetzt werden. Z.B. "Actors" wo kommt das vor? Wenn etwas noch nicht stimmt, sehe ich es ja dann im Entwurf der Edition.

Ab Zeile 48 habe ich nichts angepasst. Diese Labels werden nicht mehr verwendet, sondern direkt aus dem TEI genommen, wenn ich mich richtg erinnere? 

[de.json.zip](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/files/11472423/de.json.zip)

**Comment by feggimann** [comment]
Hier nun auch das englische File.
[en.zip](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/files/11476724/en.zip)

**Comment by windauer** [comment]
@feggimann ich habe die files jetzt hier ins Repository eingefügt:  https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/tree/master/src/i18n

Es sind noch ein paar Labels / Keys hinzugekommen und die Labels waren nicht in der richtigen alphabetischen Reihenfolge und unterschiedlich eingerückt, was einen Vergleich von en.json mit de.json erschwert hat. Dies wurde nun korrigiert. 

Was alles ab `"BELOW THIS ONLY GENERATED TYPES":"BELOW THIS ONLY GENERATED TYPES",` (vormals Zeile 48) angeht, diese Keys wurden aus dem TEI generiert, werden aber noch benutzt. Sonst stünde auf den Detailseiten anstatt "Encyclopaedia Britannica Online" immer "encyclopaedia-britannica-online", was nicht wirklich schön aussieht. Oder übersehe ich hier gerade etwas? // cc @ottosmops

**Comment by feggimann** [comment]
@windauer de.json und en.json sind jetzt up to date. Ich hoffe, wir haben alle Labels richtig interpretiert.

**Comment by windauer** [comment]
@feggimann super, danke! Ich probiere das mal aus. Ich würde sagen, wir lassen das Ticket erstmal noch offen, weil ja von unserer Seite ggf. auch wieder neu Dinge hinzukommen.

**Comment by feggimann** [comment]
@windauer bei den i18n-Dateien braucht es noch eine zusätzliche Zeile für die Bezeichnung der externen Links "wikipedia-(de)". Am besten eingefügt zw Zeile 114 und 115. Ich möchte nicht selber dreinpfuschen, oder soll ich die Zeile einfügen?
Bezeichnung in TEI-File "wikipedia-(de)" sollte als "wikipedia (de)" ausgegeben werden.

**Comment by windauer** [comment]
@feggimann füg Du die Zeile gerne ein! Ich habe in das gleiche Verzeichnis eben gerade auch highlights.de.xml und highlights.en.xml geladen, dort stehen alle Informationen drin, die aus Deinem Wordfile kamen, welches für das Karussell auf der Startseite verwendet werden. Somit kannst Du auch da nochmal Dinge ändern.

**Comment by feggimann** [comment]
@windauer bei den Highlights-Zitaten sollte unter dem Zitat noch Ort/Datum stehen und "weiterlesen..." damit die Leser auch draufklicken. Ist das korrekt, wenn ich die highlights-xmls so ergänze (Bsp. erstes Highlight):

``<text><p>«Bei dieser flüchtigen Musterung fielen nur die Menge Leute in Picadilly auf, die Sodawasser, Ingwer-Bier und Bärenschmalz zu verkaufen anbieten.»</p><p>London, 10. Juni 1825</p><p>weiterlesen...</p></text>``

Wenn das so passt, dann ergänze ich es bei den übrigen auch noch.

**Comment by feggimann** [comment]
erledigt
