### ISSUE TITLE
Fehlende statische Texte in HTML

### ISSUE THREAD

**Issue by windauer** [GF-Corporate-Archives/gf-johann-conrad-fischer#392]
Bitte alle Inhalte auf Deutsch und Englisch in HTML für folgende statische HTML Seiten bereitstellen. Die HTML Templates zum Einpflegen der Daten, liegen im Ordner [src/html-pages](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/tree/master/src/html-pages) in diesem [Github Repository](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer).

1. [x] about-de.html  
8. [x] about-en.html  
2. [x] bibliography-de.html  
9. [x] bibliography-en.html  
3. [x] citation-de.html  
10. [x] citation-en.html  
4. [x] editorial-guidelines-de.html  
11. [x] editorial-guidelines-en.html  
5. [x] gdpr-de.html  
12. [x] gdpr-en.html  
6. [x] impressum-de.html  
13. [x] impressum-en.html  
7. [x] thank-you-de.html
14. [x] thank-you-en.html

**Comment by windauer** [comment]
@feggimann ich habe gerade noch einmal das Template für das HTML angepasst, ich hoffe das ist kein Problem. 

Alle Informationen von Euch, bite immer innerhalb von <main> </main>. 

Ihr könnt auch HTML headings, tables, listen und ggf. sogar Bilder nutzen, aber bitte möglichst immer consistent und schränkt Euch gerne ein in der Verwendung der HTML Elemente. 

Laded die Texte gerne so früh wie möglich ins Github, damit wir schon mal testen können, dass der Prozess funktioniert und sicherstellen, dass die ordentlich gerendert werden. Der Prozess wird so sein, dass ihr die Daten immer wieder ändern könnt.

**Comment by feggimann** [comment]
@windauer Ich habe bibliography-de.html jetzt mal befüllt. Schaust du bitte, ob das so passt? 

Die anderen folgen dann in den nächsten Tagen.

**Comment by windauer** [comment]
@feggimann das passt so! Lediglich eine Kleinigkeit, in HTML muss ein `&` folgendermaßen geschrieben werden `&amp;` aka es muss escaped werden. Der Enduser sieht dann ein `&`. Ich habe das in `bibliography-de.html ` gefixt und meine Änderung ins repo gepusht.

**Comment by feggimann** [comment]
@windauer alle Texte sind jetzt da, ausser Datenschutz, der folgt noch. 

- Bitte bei Zitiervorschlag ``citation-de.html`` und ``citation-en.html``überprüfen ob urls so stimmen.
- Bitte im Impressum kontrollieren, ob eure Nennung so ok.
- Bitte im Impressum kontrollieren, ob Satz zu Open Source unter Lizenzen so ok (Link zu Github kann später ergänzt werden).
- Bitte in ``about-de.html`` und ``about-en.html`` kontrollieren, ob Formulierung unter 4. Technisches so ok.

**Comment by windauer** [comment]
* @feggimann die URLs sehen gut aus
* im Impressum uns bitte nicht persönlich nennen sondern die JinnTec GmbH und gerne mit Link auf https://jinntec.de/. Ich persönlich finde ja, dass die JinnTec GmbH auch unter "Gestaltung" mit erwähnt werden sollte, da wir große Teile des Design selbst gemacht haben, das betrifft das ganze Mobile Design als auch Suche, Galerie und anderes.. liegt natürlich bei Euch ob ihr das wollt oder nicht. 
* Open Source / Lizenzen: solltet ihr dann nicht auch Euer Github Repo (also dieses) dort verlinken, ansonsten wissen die User zwar es ist Open Source aber nicht wo sie es finden. Den Satz `Die technische Grundlage der Edition wird als Open Source veröffentlicht.` würde ich im Moment einfach noch weglassen, bis wir die Anwendung so sauber geputzt haben, dass sie veröffentlicht werden kann. Das kann aber durchaus noch ne Weile dauern. 
* about: passt

**Comment by windauer** [comment]
@feggimann ach so, und ganz wichtig, bitte achtet drauf, dass das HTML nicht nur valides HTML ist (war es nicht wegen Verwendung von `&` sondern dass es auch valides XML ist ( z.B. kein `<br>` sondern immer `<br/> nutzen. Für dieses mal habe ich das gefixt, aber bitte sorgt da in Zukunft selbst für.

**Comment by feggimann** [comment]
@windauer DAnke für die Inputs, habe das jetzt alles in den Impressumsfiles angepasst.

**Comment by feggimann** [comment]
erledigt
