### ISSUE TITLE
Orte mit gleichen Koordinaten

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#394]
Es gibt in mehreren Fällen Orte mit gleichen Koordinaten, v.a. wenn die Lokalisierung nur annähernd genau ist. Wir haben bemerkt, dass das für die Darstellung auf der Karte schwierig ist, und werden die Koordinaten ändern, so dass jeder Ort in der Edition einmalige Koordinaten hat.

@wolfgangmm @windauer Wie genau sind die Koordinaten in die Karte übernommen? D.h. wie viele Stellen nach dem Komma sind berücksichtigt? 

Damit wir beim Anpassen der Koordinaten nicht zu weit hinter dem Komma ändern und sie in der Karte dann doch identisch sind.

**Comment by windauer** [comment]
@feggimann wir nutzen für die Darstellung OpenStreetMap und bei denen finde [hier](https://wiki.openstreetmap.org/wiki/DE:Genauigkeit_von_Koordinaten#:~:text=8%20Siehe%20auch-,OSM%2DDatenformat,11%20mm%20f%C3%BCr%20den%20L%C3%A4ngenwert.) ich folgendes:  `In der OSM-Datenbank werden die Koordinaten der [Punkte](https://wiki.openstreetmap.org/wiki/DE:Node) als Dezimalzahlen mit sieben Nachkommastellen im BCD-Format gespeichert. Dies ergibt eine Auflösung von 100 Nanograd. Diese Granularität entspricht einer Genauigkeit von 11 mm für den Breitenwert und von mindestens 11 mm für den Längenwert.`. 

Sprich wenn ihr in Anton Koordinaten mit bis zu 7 Nachkommatellen vermerkt, sollte die Karte die entsprechend anzeigen. Aktuell habt ihr "nur" 5 Nachkommastellen verwendet. 

Disclaimer: ich habe das nicht getestet, aber ich gehe davon aus, dass wir die Geokoordinaten 1:1 an OpenStreetMap weiterreichen und das deswegen wie beschrieben funktionieren müsste // cc @wolfgangmm, @ottosmops

**Comment by feggimann** [comment]
Die Koordinaten wurden inzwischen geändert und  individualisiert.
