### ISSUE TITLE
Entscheidung Kartendesign

### ISSUE THREAD

**Issue by windauer** [GF-Corporate-Archives/gf-johann-conrad-fischer#395]
Für das Rendering der Geokoordinaten auf der Karte verwenden wir [Leaflet JS](https://leafletjs.com/) welches seinerseits auf [OpenStreetMap](https://www.openstreetmap.de/) basiert. 

LeafletJS bietet folgende Designs für seine Karten an: https://leaflet-extras.github.io/leaflet-providers/preview/

Es ist wohl auch möglich, weitere Kartendesign einzubinden bzw. sogar käuflich zu erwerben. Diese können wir gerne auch einbinden, allerdings wäre da sicherzustellen, dass das Design auch wirklich kompatibel mit LeafletJS ist. 

Ihr könnt auch gerne mehrere Kartendesigns wählen, in dem Fall wird LeafletJS eine Möglichkeit zum Umschalten der Designs für Enduser anzeigen.

**Comment by feggimann** [comment]
Spannend!

Erste Zwischenauswahl: 
- https://leaflet-extras.github.io/leaflet-providers/preview/#filter=CartoDB.Positron
- https://leaflet-extras.github.io/leaflet-providers/preview/#filter=Stadia.AlidadeSmooth
- https://leaflet-extras.github.io/leaflet-providers/preview/#filter=Jawg.Light

Und ev. zum Umschalten:
- https://leaflet-extras.github.io/leaflet-providers/preview/#filter=Esri.WorldImagery
- https://leaflet-extras.github.io/leaflet-providers/preview/#filter=CartoDB.Voyager

Schaue es morgen am grossen Bildschirm nochmals an und entscheide definitiv.

**Comment by feggimann** [comment]
@windauer Wir haben uns für dieses Kartendesign entschieden. Es zeigt zwar auf einer Mittelebene die Nationalstrassennummern an, aber passt sonst am besten:
- https://leaflet-extras.github.io/leaflet-providers/preview/#filter=Stadia.AlidadeSmooth

Zudem wenn es möglich ist, gerne diese beiden Karten zum Umschalten:
-     https://leaflet-extras.github.io/leaflet-providers/preview/#filter=Esri.WorldImagery
-     https://leaflet-extras.github.io/leaflet-providers/preview/#filter=CartoDB.Voyager
