### ISSUE TITLE
TEI Export Actors

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#397]
@ottosmops im TEI Export kommt Biografiefeld doppelt vor:
``<note type="description">``in Markdown
``<note type="bio" xml:lang="de">``in xml
Ich nehme an, das ist extra so?

**Comment by feggimann** [comment]
@ottosmops wir haben die englischen Bildlegenden in der englischen Oberfläche im Titelfeld eingepflegt. Können die beim TEI Export für die englischen TB auch exportiert werden? Dann müssen wir sie nicht doppelt einpflegen.

**Comment by ottosmops** [comment]
@windauer : zur doppelten note: welche verwendet ihr `<note type="description">` oder `<note type="bio" xml:lang="de">`

**Comment by ottosmops** [comment]
@feggimann hast Du mal einen Export auf der englischen Oberfläche ausprobiert? Eigentlich müsste das schon gehen.

**Comment by feggimann** [comment]
@ottosmops ich habe einen Export auf der englischen Oberfläche ausprobiert. Es kam fatal error.

**Comment by windauer** [comment]
@ottosmops wie damals im Ticket spezifiziert, benutzen wir beide, also: 

*  `tei:note[@type="description"][@xml:lang=$lang]/tei:*` und 
*  `tei:note[@type="bio"][@xml:lang=$lang]/tei:*`

**Comment by feggimann** [comment]
@ottosmops englischer Export hat jetzt geklappt

**Comment by feggimann** [comment]
@windauer @ottosmops d.h. wir müsen beide Biografieerwähnungen jeweils auf Englisch übersetzen. Ist ziemlich fehleranfällig. Weshalb braucht es denn beide?

**Comment by windauer** [comment]
@feggimann aus meiner Sicht braucht es überhaupt nicht beide, wir zeigen dort an was Du / Ihr uns sagt und wir können auch nur notes vom type "bio" oder "description" anzeigen. Sagt und einfach welche note wir anzeigen bzw. ausblenden sollen.

**Comment by feggimann** [comment]
@windauer Wir befüllen morgen das TEI-File für die Actors mit den englischen Übersetzungen. Ich habe soeben einen aktuellen Export der Actors von der englischen Anton-Oberfläche gemacht. Ist es möglich, dass du aus diesem TEI-File alle Actor IDs herausfilterst, die in den deutschen xml-Files der Reisetagebücher 1 und 7 vorkommen? D.h. im File nur die IDs der TB 1 und 7 stehen lassen, alle anderen löschen. Geht das?

Ich schlage vor, dass wir das File mit den korrekten IDs im englischen Sourcesordner auf Github ablegen:
https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/tree/master/src/en

Passt der Dateinmae so mit dem -en am Ende? Sonst bitte angeben wie das File heissen soll.

[archives-actors-tei-en.xml.zip](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/files/11472663/archives-actors-tei-en.xml.zip)

**Comment by feggimann** [comment]
Wegen notes type "bio" oder "description" schaue ich in dem Fall mit meinen Mitarbeitern, was besser/einfacher ist zum Befüllen. Danke!

**Comment by windauer** [comment]
@feggimann das geht schon, allerdings müssen die Daten am Schluss auch wirklich in Anton verfügbar sein, stellt ihr das dann sicher? In der Anwendung hilft uns das File mit den englischen Übersetzungen nicht, da ziehen wir uns diese Daten ausschließlich von Anton. Wenn es aber jetzt bei den Übersetzungen hilft, kann ich solch ein File gerne bereitstellen.

**Comment by feggimann** [comment]
@windauer @ottosmops Das scheint ein Misverständnis zu sein. Wir können diese Daten nicht in Anton eintragen, da es keine Felder dafür gibt bei Actors und Places. Wir hatten mit Andreas abgemacht, dass wir die englischen Übersetzungen direkt in die TEI Files übertragen. Wir sollten dringend wissen, wie wir die englischen Actors und Places speichern, wenn nicht in einem TEI file.

**Comment by windauer** [comment]
@feggimann, @ottosmops  das hatte ich gerade nicht auf dem Zeiger. Wir können auf das archives-actors-tei.xml und archives-places-tei.xml wechseln. Aber das ist dann ein wirklicher Wechsel und wir werden ausschließlich diese Dateien nutzen und es wird keine Updates in diesen Registerdaten mehr via Anton geben, sprich ich würde den Mechanismus, dass wir uns beim bauen einen Anton Dump erzeugen und dann alle Registerdaten mit denen von Anton ersetzen, für Actors und Places ausschalten und in Zukunft nur noch das TEI aus diesem Repository hier nehmen, korrekt? // cc @wolfgangmm

**Comment by feggimann** [comment]
@windauer @ottosmops können wir das kurz besprechen? Andreas ist grad unterwegs, aber könnte um 17 Uhr an einem Teams teilnehmen. Lars, würde dir das auch passen? Dann schicke ich schnell einen Termin.

**Comment by windauer** [comment]
closing this ticket, discussion continues at https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/issues/398
