### ISSUE TITLE
Update Prozess Anton - eXist-db inkl Übersetzungen

### ISSUE THREAD

**Issue by windauer** [GF-Corporate-Archives/gf-johann-conrad-fischer#398]
## Prozessvorschlag

* [x] Übersetzungen für Register in Excel (@feggimann , @ottosmops )
* [x] Bildlegenden auf Englisch @ottosmops  
* [x] es gibt in Zukunft pro Sprache eine Registerdatei (z.B. archives-actors-tei-de.xml und archives-actors-tei-en.xml)
   * [x] Anwendung entsprechend umstellen @windauer  
* [x] Anwendung fragt alle Registerdaten via update batch von Anton ab
   * [x] nach Anton Update müssen alle Namen, Orte und Begriff die nicht in den Tagebüchern verlinkt sind, aus Registerdaten entfernt werden (jeweils pro Sprachen!) 
   * [x] Links müssen nach intern / extern angepasst werden. (@ottosmops dokumentiert wie links sein müssen, @windauer implementiert). Siehe auch [Issue 262](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/issues/262)

**Comment by windauer** [comment]
@feggimann auch wenn wir das jetzt über Excel lösen sollten, habe ich Dir mal in https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/tree/master/src/register die aktuellen Registerdaten eingespielt, wie sie uns als XML Vorliegen. Ich habe vorher das Skript laufen lassen, welche alle Namen, Orte und Begriffe entfernt, die nicht in den Editionen verwendet werden, entfernt. Die Daten sind also bereinigt. 


Und hier noch ein ZIP file welches alle IDs von Namen, Orten und Begriffen enthält, welche in Tagebuch-1 oder 7 referenziert sind: [ids-tagebuch-1-und-7.xml.zip](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/files/11481188/ids-tagebuch-1-und-7.xml.zip)

**Comment by ottosmops** [comment]
1. @feggimann Aus meiner Sicht funktioniert die Schummelei mit Excel recht gut. Ihr könnt also beginnen die Excel mit den Übersetzungen abzufüllen. 
  1.1. Bitte Spalte "Alternative Names" (dann ist es mit den Antonbezeichnungen konsistent)
  1.2. Excel können als Metadaten beim normalen Import hochgeladen werden (die sind da natürlich nicht übermässig gesichert, aber so brauchen wir keinerlei neue Logik)
  1.3. Bildlegenden sollten nun übersetzt sein, bitte checken
3. @windauer Achtung die `xml:lang` sind dann auf englisch gesetzt. Da kannst Du mir aber sagen, was ich noch wie anpassen kann und soll.
4. Beim Englischen File exportieren wir nur die übersetzten Akteure und Places, ok?
5. Ich implementiere nun noch places und keywords (ohne Excel) usw. und melde mich dann, wenn es auch online geht

[archives-actors-tei-en.xml.zip](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/files/11484641/archives-actors-tei-en.xml.zip)

**Comment by ottosmops** [comment]
Sieht für mich erstmal plausibel aus.

- [ ] @Lars Die files aus Anton nun mit dem Dateinamen mit der locale abholen (z.B. archives-actors-tei-de.xml)

Erzeugt werden kann es zurzeit nur über den Browser. Das mache ich dann noch.

![Bildschirmfoto 2023-05-16 um 10 16 21](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/4144389/afacc19b-b36b-4356-9dc1-15c335332bc2)

**Comment by feggimann** [comment]
> 
@windauer Danke für die IDs von Namen, Orten und Begriffen. Das ist sehr hilfreich. Wir haben bemerkt, dass nur die IDs des TB 1 dabei sind, die von TB 7 fehlen. Zudem sind bei den Actors nur Personen und Familien, aber keine Körperschaften. Könntest du bitte die Körperschaften noch ergänzen und die IDs des TB 7 filtern?

**Comment by windauer** [comment]
@feggimann da war noch ein Fehler im Skript, jetzt alle IDs aus TB1 und 7 inkl. Körperschaften. Passt das so? 

* [ids-tagebuch-1-und-7.xml.zip](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/files/11488710/ids-tagebuch-1-und-7.xml.zip)

**Comment by feggimann** [comment]
@windauer Danke, jetzt sind beide Tagebücher drin, aber die Körperschaften fehlen noch. Könntest du die bitte noch ergänzen?

**Comment by windauer** [comment]
@feggimann entschuldige bitte, da war noch ein Fehler im Skript, weswegen `<org>` nicht berücksichtig wurden, obwohl ich dachte, ich hätte sie eingebaut. Hier nun die hoffentlich vollständige Variante:  [ids-tagebuch-1-und-7-v3.xml.zip](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/files/11500058/ids-tagebuch-1-und-7-v3.xml.zip)

**Comment by ottosmops** [comment]
Jetzt sind auch die places angepasst und alles ist auf dem Server.

**Comment by feggimann** [comment]
@ottosmops @windauer die englischen Actors sind jetzt vollständig im Excel, mit Lars' Liste der IDs abgeglichen und in den Antonimport hochgeladen.

Ich habe neue TEI-Dateien generiert, dabei ist mir bei den Actors aufgefallen:
- note type="description" ist jetzt in beiden Sprachen doppelt vorhanden.
- note type="description": ich sehe keine Zeilentrennungen. Sind die drin? Wichtig für ersten Satz für Kurzbeschrieb.
- englische Bildlegende fehlt

Places und Keywords habe ich noch nicht kontrolliert, das folgt.

**Comment by feggimann** [comment]
@ottosmops @windauer die englischen Places sind jetzt azch im Excel, mit LArs' Liste der IDs abgeglichen und in den Antonimport hochgeladen.

Im TEI-File der Places werden die Zeilentrennungen in (note type="description") sauber dargestellt.

Nur die englischen Bildlegendn fehlen auch noch.

**Comment by ottosmops** [comment]
@feggimann sollte nun alles erledigt sein

**Comment by windauer** [comment]
von unserer Seite sollte auch alles erledigt sein. Die geänderten Links werden mit dem nächsten Update sichtbar werden (heute oder spätestens Morgen)

**Comment by feggimann** [comment]
alles gut. danke.
