### ISSUE TITLE
TEI Header in Registerdaten anpassen

### ISSUE THREAD

**Issue by windauer** [GF-Corporate-Archives/gf-johann-conrad-fischer#399]

**Comment by feggimann** [comment]
@ottosmops hier der neue header:

``<fileDesc>
<titleStmt>
<title>Digitale Edition der Reisetagebücher von Johann Conrad Fischer</title>
</titleStmt>
<editionStmt>
<edition>Digitale Edition der Reisetagebücher von Johann Conrad Fischer</edition>
<sponsor>Georg Fischer AG</sponsor>
</editionStmt>
<publicationStmt>
<publisher>Franziska Eggimann, Eisenbibliothek</publisher>
<pubPlace>Schlatt</pubPlace>
<date when="2023">2023</date>
<availability>
<licence target="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons BY-SA 4.0</licence>
</availability>
</publicationStmt>
<sourceDesc>
<p>
Datenbankexport vom 2023-05-23 19:43:25 aus Konzernarchiv der Georg Fischer AG
</p>
</sourceDesc>
</fileDesc>``

**Comment by feggimann** [comment]
@ottosmops hat nicht geklappt, hier zweiter Versuch:
- title: Digitale Edition der Reisetagebücher von Johann Conrad Fischer
- edition: Digitale Edition der Reisetagebücher von Johann Conrad Fischer
- sponsor: Georg Fischer AG
- publisher: Franziska Eggimann, Eisenbibliothek
- pubPlace: Schlatt
- ``<licence target="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons BY-SA 4.0</licence>``

**Comment by feggimann** [comment]
erledigt
