### ISSUE TITLE
Recherche, Anton: Arkwrights Schwager?

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#40]
TB 1851, S. 82 im Word.
Gebaut wurden die Modelle laut Wikipedia & Co. von John Kay, einem Uhrmacher; doch JCF schreibt es habe sie Arkwrights Schwager gebaut. Dieser ist aber Tischler gewesen.
Kann es sein, dass sich JCF geirrt hat oder ist John Kay doch der Schwager?

**Comment by NicolauLutz** [comment]
Vielleicht kann man diese Geschichte beim Keyword "Arkwright's Waterframe" erwaehnen, statt einen Personeneintrag zu machen, da wir nicht einmal den Namen kennen? Unwahrscheinlich, dass John Kay sein Schwager war, als das keine Quelle so erwaehnt. Auch unwahrscheinlich, dass JCF Kay mit dem Schwager verwechselt hat, da Kay ja Uhrmacher war, und nicht Tischler. Es kann sein, dass sich Fischer hier auf eine ganz andere Tradition beruft, die er irgendwoher uebernommen hat. 

Evtl. mehr Info in Bio wie Fitton, The Arkwrights, 1989

**Comment by vrukavina** [comment]
Sehe ich auch so. Vielen Dank!
Kommt "Arkwrights Waterframe" in deinem TB von 1814 vor?
