### ISSUE TITLE
Website im neuen Design

### ISSUE THREAD

**Issue by windauer** [GF-Corporate-Archives/gf-johann-conrad-fischer#400]
Wir haben so eben das neue Design auf der bekannten URL https://gf.tei-publisher.com/index.html
Wir haben das Umsetzen des Designs noch nicht abgeschlossen und haben auch noch mit der Unterstützung mehrsprachiger Registerdateien einiges zu tun. 

Von daher gebt uns bitte noch bis Ende nächster Woche Zeit existierende Tickets zu adressieren und weiter Design und Sprachunterstützung zu implementieren, bevor ihr neue Tickets zur Webseite anlegt. 

**Wichtig**:  Ein bekanntes Problem ist, dass in gewissen Situation noch der URL Parameter `lang=en` bzw. `lang=de` abgeschnitten wird und es in der Folge zu Fehlern kommen kann.

**Comment by line-o** [comment]
Das Ticket kann geschlossen werden, richtig?

**Comment by feggimann** [comment]
ok
