### ISSUE TITLE
GIF  wandernder JCF während Seiten laden

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#401]
@windauer Hier das GIF des wandernden Johann Conrad Fischer in zwei kleineren bzw. leichteren Versionen.

[75_JCF-Signet.zip](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/files/11531648/75_JCF-Signet.zip)

**Comment by windauer** [comment]
ist eingebunden

**Comment by feggimann** [comment]
schaut super aus
