### ISSUE TITLE
Editionsseite: Tagebuch wird nicht aufgerufen

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#402]
Wenn ich auf unserer Editionsseite bin und oben links auf "Reisen" drücke, um ein anderes TB auswählen zu können, kommt folgende Meldung:

![Bildschirmfoto 2023-05-23 um 08 59 56](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/14cb86e6-94db-4aa4-a2e9-3240c305da79)
https://gf.tei-publisher.com/start.html?lang=

**Comment by windauer** [comment]
In der URL fehlt hinter lang die Sprache de oder en. Wie ich am Freitag schrieb, kann das unter gewissen Umständen noch passieren. Sollte es dazu kommen, einfach lang=en oder lang=de setzen und es sollte tun. Das Issue werden wir asap beheben.

Für Tagebuch 4 funktioniert z.B. https://gf.tei-publisher.com/itinerary/reisetagebuch-4.xml?lang=de

Wir arbeiten mit Hochdruck an stabileren und schöneren URLs.
