### ISSUE TITLE
Fehlerhafte Textdarstellung und Bilderwiederholungen

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#403]
Im Text gibt es nun Zeilenumbrüche, die dort nicht sein sollten.
Beispiel hier aus dem TB 1825-1827:

![Bildschirmfoto 2023-05-24 um 10 40 07](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/0a32de48-d5b8-4294-93d3-e1b2fc22d503)
https://gf.tei-publisher.com/itinerary/reisetagebuch-4.xml?lang=de&view=div&odd=gf-tagebuecher&root=1.6.4.22

Im xml steht an diesen Stellen kein neuer <p>:
![Bildschirmfoto 2023-05-24 um 10 37 47](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/7f78ba06-8991-471d-abc0-ea716520ac6d)
https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/blob/master/src/de/reisetagebuch-4.xml

Ausserdem sieht man bei diesem Beispiel, dass nun wieder die Bilder bei jedem Tag eingeblendet zu sein scheinen (siehe Kanone). Die Bilder sollten aber nur beim ersten Erwähnen (Tag) im Text eingeblendet werden, und dann später nicht mehr auf dieser Seite.

**Comment by windauer** [comment]
Das Rendering funktioniert jetzt wieder: https://gf.tei-publisher.com/itinerary/reisetagebuch-4.xml?lang=de&view=div&odd=gf-tagebuecher&root=1.6.4.22

@vrukavina erstellst Du bitte für das doppelte Rendering der Bilder auf der Textseite ein Ticket und weist es mir zu, danke!  Da ist jetzt offensichtlich beim Fixen von Anderen Dingen, etwas kaputt gegangen. Aber wir sollten bitte keine Tickets mischen, sonst übersehe ich zu leicht Dinge :)

**Comment by vrukavina** [comment]
Sieht jetzt gut aus.

Alles klar. Habe ich erstellt. Danke!
