### ISSUE TITLE
Doppeltes Rendering der Bilder auf Textseite

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#404]
Beispiel:
https://gf.tei-publisher.com/itinerary/reisetagebuch-4.xml?lang=de&view=div&odd=gf-tagebuecher&root=1.6.4.22
![Bildschirmfoto 2023-05-24 um 10 40 07](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/d6435ad7-7f0c-4b04-9f28-b37c14d099cf)

**Comment by windauer** [comment]
done

**Comment by vrukavina** [comment]
sieht gut aus
