### ISSUE TITLE
Inhaltsverzeichnis klappt nicht automatisch ein

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#407]
Das Inhaltsverzeichnis klappt nach dem Anwählen des Kapitels nicht automatisch ein. Damit der Text sichtbar wird, muss man erneut oben auf "Inhalt" klicken. Bitte so machen, dass Inhaltsverzeichnis verschwindet, wenn man ein Kapitel angeklickt hat.

Zudem Aufzählungspunkte weglassen in Liste - die Gliederung ist die Kapitelnummerierung, es braucht nicht beides:

<img width="783" alt="Bildschirmfoto 2023-05-30 um 02 17 06" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/a86a881d-2b81-4394-895a-e7a36905dcd0">

**Comment by line-o** [comment]
Ist inzwischen gefixt.

**Comment by feggimann** [comment]
passt. danke.
