### ISSUE TITLE
TB 4: Doppelte Skizze - lieber Querverweis?

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#408]
Soll die Skizze wirklich hier mitten im Text erscheinen?
![Bildschirmfoto 2023-05-30 um 09 08 58](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/6e41d30e-fc4e-4f1e-8453-aaecc5064772)
https://gf.tei-publisher.com/de/1825-1827/9

... und dann auf der folgenden Seite nochmals?
![Bildschirmfoto 2023-05-30 um 09 12 30](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/301a49a1-7e10-4110-9511-1d995e4eecdd)
https://gf.tei-publisher.com/de/1825-1827/10

Wäre es nicht schöner, wenn auf der ersten Seite (https://gf.tei-publisher.com/de/1825-1827/9) ein Querverweis stehen würden auf die nächste Seite? Dann wäre nur dort das Bild.

**Comment by NicolauLutz** [comment]
Ja, einverstanden. Am besten im Text "Diese Maschine" mit `<ref type="cross">` taggen und Querverweis auf die nächste Seite.
