### ISSUE TITLE
Verweis auf anderes Tagebuch innerhalb eines anderen funktioniert nicht

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#409]
Wenn ich auf den Link/Verweis "Tagebuch der frühern Reise..." hier klicke,
![Bildschirmfoto 2023-05-30 um 09 21 20](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/61e1ec11-0f1a-49dd-9d30-2831af80c3f4)
https://gf.tei-publisher.com/de/1825/2

...dann kommt anstelle des TB 2 (der Titelseite davon), folgende Meldung:
![Bildschirmfoto 2023-05-30 um 09 21 06](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/4e34d54d-1ceb-4696-aee0-43175cfb1dcf)
https://gf.tei-publisher.com/de/1825/reisetagebuch-2.xml

**Comment by vrukavina** [comment]
Gleiches Problem mit gleicher Fehlmeldung nochmals hier:
![Bildschirmfoto 2023-05-30 um 09 28 59](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/dcd08edb-1c18-4814-b2f6-d3fc6a899d90)
https://gf.tei-publisher.com/de/1825/6

**Comment by windauer** [comment]
@vrukavina das Problem ist, dass die Links jetzt auf Grund des neuen URL schemas nicht mehr passen und alle angepasst werden müssen. 

Für `<ref type="cross" target="reisetagebuch-2.xml">` muss  URL im Target Attribut jetzt <ref type="cross" target="../1814">` lauten. Analog für alle anderen links zu Reisetagebüchern. Das sollte mit Suchen / ersetzen hoffentlich sehr gut und einfach anzupassen sein.

**Comment by feggimann** [comment]
@windauer @vrukavina @lutz wir kümmern uns darum. Verweise nur auf ganze Tagebücher oder Kapitel, keine kleineren Einheiten.

**Comment by feggimann** [comment]
@vrukavina @NicolauLutz bitte baldmöglichst mit mir anschauen, damit es bereinigt werden kann:
- Querverweise korrigieren nach Lars' Muster oben
- Bei en TB kontrollieren, dass keine Querverweise ins Leere, sonst entfernen

**Comment by feggimann** [comment]
@NicolauLutz Bitte Querverweise in englischem TB 1851 zu noch nicht publizierten TBs löschen.

**Comment by feggimann** [comment]
erledigt
