### ISSUE TITLE
Zu grosse Darstellung der Skizzen im Text

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#410]
Grafiken, die im Text eingebettet sind, werden zu gross dargestellt.
Beispiel hier aus dem ersten Tagebuch von 1794 (https://gf.tei-publisher.com/de/1794/20):
![Bildschirmfoto 2023-05-31 um 10 39 47](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/62f79666-5f46-4a87-b4b2-bc1cbc5f5f96)
https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/blob/master/src/de/reisetagebuch-1.xml

Wäre es möglich zwischen solchen zu unterscheiden, die alleine auf einer Seite stehen (meistens im Anhang, s. Anhang TB7: https://gf.tei-publisher.com/de/1851/TB7_p_107) und jenen, die umgeben sind von Text wie das Beispiel hier aus TB 1?

**Comment by feggimann** [comment]
@windauer @line-o besprechen wir morgen.

**Comment by feggimann** [comment]
@windauer auf Textseiten ist jetzt alles ok, aber Titelblatt wird noch nicht angezeigt. Wir haben es im Moment so gelöst, dass es direkt unter dem "head" steht, da die Reihenfolge der Anzeige sein sollte:
- Titel (head)
- Einschub mit Tag zum Keyword des Titelblatts
- ausgeschriebener Titel (alles in "titlePage")

Passt das so oder wo sollten wir den Tag zum Keyword einbauen?

Hier Bsp. TB 1 (1794):

<img width="919" alt="Bildschirmfoto 2023-06-04 um 16 17 34" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/d0be8138-3dee-4bfd-aed1-76fd4797229f">

**Comment by windauer** [comment]
@feggimann passt das so? https://gf.tei-publisher.com/de/1794/1

**Comment by feggimann** [comment]
@windauer Keyword und Bild passt super, danke. Kannst du bitte "titlePage" nicht einmitten, sondern linksbündig? Wenn es geht.

**Comment by windauer** [comment]
done, wird mit der nächsten Version ausgerollt.

**Comment by feggimann** [comment]
erledigt, schaut gut aus
