### ISSUE TITLE
Skizze/Grafik im Text wird nicht angezeigt

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#411]
Im Anhang vom 1. Tagebuch von 1794 sollte im Anhang eine Grafik erscheinen, und nicht nur die Bildlegende dazu.
https://gf.tei-publisher.com/de/1794/26

![Bildschirmfoto 2023-05-31 um 10 57](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/0f8cb1c4-a031-4f44-b7ba-1a7f79c94650)

Gibt es da vielleicht Interferenzen wegen der Legende? Nur in diesem TB wurde nämlich eine gesetzt, so viel ich weiss.
![Bildschirmfoto 2023-05-31 um 10 59 30](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/d71b7b05-6cb3-494e-809f-481e5cb058f8)
https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/blob/master/src/de/reisetagebuch-1.xml

**Comment by feggimann** [comment]
@NicolauLutz bitte baldmöglichst beheben

**Comment by NicolauLutz** [comment]
4 `<pb n="` Elemente, die auf leere Seiten in der Ursprungsedition verwiesen haben, sind nun gelöscht.
