### ISSUE TITLE
Startseite en: Highlights-Bilder werden nicht angezeigt

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#412]
Auf der Startseite der englischen Version werden die Bilder bei den Highlights nicht angezeigt.

![Bildschirmfoto 2023-05-31 um 14 18 26](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/58866c8b-c0b6-44ce-8ab8-0c73c32038c0)
https://gf.tei-publisher.com/en/

**Comment by windauer** [comment]
das ist, weil wir nie die Bilder dazu bekommen hätten. Und wir brauchen Sie bitte in dem richtigen Format von `862 × 315` Pixeln bei 72 Pixel/Inch Auflösung als `.jpg` Bilder. Für Deutsch haben wir das Beispielhaft gemacht, aber es hat uns vie Zeit gekostet und die haben wir leider gerade nicht mehr. Zudem müssen für das Englische Highlights files noch die Links angepasst werden, die stimmen alle so noch nicht. 

Das File zum Anpassen der Highlights findet sich in diesem Repository unter [src/i18n/highlights.en.xml](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/blob/master/src/i18n/highlights.en.xml) - in highlights.de.xml könnt ihr sehen, wie Links aussehen müssen und wie wir das für die existierenden Bilder mit dem Einbinden macht. Z.B: `<img>01_gfd_2_69-0001_start_4_3</img>` um das Bild `01_gfd_2_69-0001_start_4_3.jpg` zu laden.

**Comment by vrukavina** [comment]
@feggimann @NicolauLutz Hier gibt es noch eine grössere Baustelle wie es aussieht.
