### ISSUE TITLE
Englische Version: Inhaltsverzeichnis auf Deutsch anstatt Englisch

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#413]
Bei der englischen Version sind im Inhaltsverzeichnis noch die deutschen Titel. 

![Bildschirmfoto 2023-05-31 um 14 25 00](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/ecc204cf-823e-495a-9952-cea918ed6a13)
https://gf.tei-publisher.com/en/1794/3

Bitte auch hier die englischen setzen.

**Comment by feggimann** [comment]
passt, danke
