### ISSUE TITLE
Suchfunktion: Fehler mit der Englischen Suchfunktion

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#414]
1. Wenn man auf der englischen Website (https://gf.tei-publisher.com/en/) nach einem Wort sucht, das nur in einem deutschen Text vorkommt (Beispiel: "Grotius"), und dann auf die vorgeschlagene Textstelle klickt, kommt folgende Fehlermeldung: 

<img width="1278" alt="Screen Shot 2023-05-31 at 14 54 00" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92101460/40d0f4b7-2872-4833-80b4-59f40114d771">

2. Suche nach "Ostend" bringt nur Resultate aus dem Register, und keine Textstelle. Wenn man nach "Ostende" sucht, kommt folgende Textstelle: https://gf.tei-publisher.com/en/1851/32?action=search. Diese Stelle müsste bei der Suche nach "Ostend" auch aufgeführt werden. Ähnlicher Fehler bei Suche nach Begriffen, die keinen Registereintrag haben. Beispiel: "industry" (https://gf.tei-publisher.com/en/search?query=industry) und "industrie" (https://gf.tei-publisher.com/en/search?query=industrie&start=1)

3. Titel und Vorschau der Textstelle sind bei der englischen Suche auf Deutsch, obwohl der Link auf die englische Seite geht. Beispiel "hurter" (https://gf.tei-publisher.com/en/search?query=hurter&start=1)

**Comment by windauer** [comment]
done

**Comment by feggimann** [comment]
@windauer stimmt noch nicht ganz: Suche nach "hurter" ergibt nun zwei Errormeldungen:

<img width="1320" alt="Bildschirmfoto 2023-06-01 um 23 22 52" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/f9714bc9-3335-4829-9de5-60dfd19baccf">

**Comment by windauer** [comment]
wow.. das müssen wir uns näher anschauen! 

Wenn wir auf Deutsch die Suche ausführen (https://gf.tei-publisher.com/de/search?query=hurter) sehen wir, dass die Treffer in 1794 (reisetagebuch-1.xml) sind, welches ja im Englischen auch vorhanden ist. So gesehen ist es richtig, dass die Suche die beiden Ergebnisse findet, nur ist unklar warum der Fehler und warum Text auf Deutsch, müssen wir uns genau anschauen.

**Comment by windauer** [comment]
done

**Comment by feggimann** [comment]
@windauer englische Suche funktioniert noch nicht immer. Suche ohne Treffer ist jetzt ok. Aber dafür ist mir aufgefallen:

- Mehrfachnennung von gleichem Registereintrag in der Trefferliste, Bsp. Suche nach "Basel":

<img width="1363" alt="Bildschirmfoto 2023-06-04 um 17 31 21" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/73204765-062c-4f2b-984f-305d382b020a">

- Suche Wortteil/Wort finktioniert manchmal, manchmal aber nicht. Bsp. Suche nach "chemist" bringt auch Treffer "chemistry". Suche nach "ginger" bringt aber nicht Treffer "gingerbeer":

<img width="1363" alt="Bildschirmfoto 2023-06-04 um 17 33 07" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/29147721-c515-4777-9454-12ada0d514c2">

<img width="1363" alt="Bildschirmfoto 2023-06-04 um 17 31 37" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/d82b0650-bde9-4e07-9d5d-30ba685e003d">

<img width="1363" alt="Bildschirmfoto 2023-06-04 um 17 31 48" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/77efb108-b7ff-4479-a99a-9a2faef781d6">

**Comment by windauer** [comment]
@feggimann sollte behoben sein: 

* 'Basel' de: https://johannconradfischer.sources-online.org/de/search?query=Basel 
* 'Basel' en: https://johannconradfischer.sources-online.org/en/search?query=Basel
* 'ginger' de: https://johannconradfischer.sources-online.org/de/search?query=ginger
* 'ginger' en: https://johannconradfischer.sources-online.org/en/search?query=ginger

**Comment by feggimann** [comment]
schaut gut aus
