### ISSUE TITLE
Register: Namen fehlen bei englischer Seite

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#415]
Gewisse Personen haben im englischen Register keinen Namen. 

Beispiel: 

George IV: Englisch: https://gf.tei-publisher.com/en/names/gfa-actors-7839?action=search&#1.3.4.2.2.532.3) ; Deutsch: https://gf.tei-publisher.com/de/names/gfa-actors-7839

**Comment by windauer** [comment]
@NicolauLutz ja tut es, im Register werden jeweils alle Namen, Orte / Begriffe angezeigt und zwar direkt aus dem Register. Jetzt immer abzufragen, kommt der Eintrag auch wirklich im Tagebuch vor kostet Rechenzeit und ist so nicht implementiert worden. Für den Moment wäre es wahrscheinlich am einfachsten, wenn für alle Namen und Orte mind. ein `<persName xml:lang="en">` bzw. <placeName xml:lang="en">` mit einer Kopie des deutschen Namens vorkommt, wenn ihr das nicht übersetzt bekommt. Wäre das einfach via Anton machbar @ottosmops?

**Comment by windauer** [comment]
ich habe mal @line-o,  @feggimann  und @ottosmops mit auf das Ticket genommen, hier müssen wir asap ein für alle Seiten tragbare Lösung finden.

**Comment by feggimann** [comment]
@windauer @line-o @ottosmops Wir gingen davon aus, dass in der englischen Version nur die Actors/Places/Keywords angezeigt werden, die in den zwei publizierten englischen Tagebüchern getaggt sind. Die anderen sind noch nicht übersetzt. Müssen wir morgen besprechen.

**Comment by ottosmops** [comment]
Ok, ich dachte, dass wir besprochen hatten, dass die Anton Daten vorher nach diesen Kriterien gefiltert werden. Ich habe in `.bin/`ein neues Skript erstellt, das in Anton nur noch die Entitäten abfragt, die in der jeweiligen Sprachversion vorkommen und die passenden Registerdateien erstellt. 

Skript bitte ausführbar machen: 

```bash
sudo bin/get-anton-data.sh
```

anschliessend mit dem Anton API-TOKEN als Parameter aufrufen:

```bash
./bin/get-anton-data.sh {API_TOKEN}
```

Bitte testen und Ergebnisse überprüfen.

**Comment by ottosmops** [comment]
Das Registerverzeichnis kann anschliessend entsprechend bereinigt werden.

**Comment by windauer** [comment]
wir haben das jetzt auf unserer Seite gelöst, sollte mit dem nächsten Update sauber für Namen, Orte und Begriffe funktionieren.

**Comment by ottosmops** [comment]
Trotzdem sollte das Script für die Aktualisierung hier im Datenrepo verwendet werden. Dann sind die Editionsdaten konsistent.

**Comment by feggimann** [comment]
Schaut jetzt gut aus.
