### ISSUE TITLE
Register: Links zu anderen Registerarten funktioniert nicht

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#416]
Links zwischen den drei Registerarten Namen/Orte/Begriffe funktionieren nicht.

Bsp. Londoner Weltausstellung: https://gf.tei-publisher.com/de/keywords/gfa-keywords-8436

Im Beschreibungstext hat es diverse verlinkte Actors (Georg und Berthold Fischer), Places (Hyde Park) und Keywords (Meteorstahl, Kautschuk, etc.)
- Links zu anderen Keywords funktionieren
- Links zu Actors: bleibt in den Keywords und zeigt weisse Seite (https://gf.tei-publisher.com/de/keywords/gfa-actors-148)
- Link zu Place: wechselt zu Place in Anton (https://archives.georgfischer.com/places/1698) statt zu Place in Edition (https://gf.tei-publisher.com/de/places/gfa-places-1698)

**Comment by windauer** [comment]
gefixt, siehe: https://gf.tei-publisher.com/de/keywords/gfa-keywords-8436

**Comment by feggimann** [comment]
@windauer ich habe diverse getestet, alle haben korrekt funktioniert, ausser ein Link:

Keyword "Ausstellungskatalog von Bullock" (https://gf.tei-publisher.com/de/keywords/gfa-keywords-9804): hier springt der Link bei Actor William Bullock zum Eintrag in Anton (https://archives.georgfischer.com/actors/7909)

**Comment by windauer** [comment]
gefixt, wird gleich live gestellt.

**Comment by feggimann** [comment]
passt
