### ISSUE TITLE
Legende unter Karte auf Textseiten

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#417]
Bitte unter die Karte auf den Textseiten eine Legende zu den verschiedenfarbigen Punkten setzen. Legendenschrift nicht zu gross, etwa wie Schriftgrösse der Registerlisten über der Karte.

Bsp. https://gf.tei-publisher.com/de/1814/4

DE:
[dunkelgrüner Punkt] Itinerar des aktuellen Kapitels
[hellgründer Punkt] Itinerar der aktuellen Reise
[dunkelblauer Punkt] Ort erwähnt im aktuellen Kapitel
[hellblauer Punkt] Ort erwähnt im aktuellen Tagebuch

EN
[dunkelgrüner Punkt] itinerary of the current chapter
[hellgründer Punkt] itinerary of the current journey
[dunkelblauer Punkt] place mentioned in the current chapter
[hellblauer Punkt] place mentioned in the current journal

**Comment by windauer** [comment]
done

**Comment by feggimann** [comment]
@windauer farbige Punkte sind da, aber Text fehlt:

<img width="608" alt="Bildschirmfoto 2023-06-01 um 22 22 39" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/ec5ec6a8-b4fa-435a-8de4-37da877c2ccd">

**Comment by windauer** [comment]
verdammt, ich hatte mir die i18n keys selbst wieder gelöscht und es nicht gemerkt, kommt mit dem nächsten Update.

**Comment by feggimann** [comment]
passt
