### ISSUE TITLE
rechte Spalte mit Registerlisten und Karte an sichtbaren Seitenausschnitt anheften

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#418]
Kann bei Textseiten die rechte Spalte mit Registerlisten und Karte angeheftet/fixiert werden, damit beil Scrollen nur die linke Text/Bildspalte scrollt und die Karte sichtbar bleibt? Schade wenn bei langen Seiten die Karte verschwindet.

**Comment by windauer** [comment]
done

**Comment by feggimann** [comment]
unglaublich, schaut super aus!
