### ISSUE TITLE
Highlights mit Ort und Datum

### ISSUE THREAD

**Issue by windauer** [GF-Corporate-Archives/gf-johann-conrad-fischer#419]
Highlights unterstützen jetzt auch mehrere Textelemente

```
    <highlight>
        <text>«Bei dieser flüchtigen Musterung fielen nur die Menge Leute in Picadilly auf, die Sodawasser, Ingwer-Bier und Bärenschmalz zu verkaufen anbieten.»</text>
        <text>Piccadilly Circus, London</text>
        <text>10. Juni 1825</text>
        <link>1825/13</link>       
        <img>01_gfd_2_69-0001_start_4_3</img>
    </highlight>
````

Es sind allerdings keine Links oder andere HTML innerhalb von `<text>` möglich, nur reiner Text (da der ganze Text ein Link ist)

**Comment by feggimann** [comment]
@windauer ok, ich habe bei allen Einträgen eine Textzeile ergänzt mit [Ort, Datum]. Hoffe, das stimmt so.

**Comment by windauer** [comment]
done, siehe https://gf.tei-publisher.com/en/

**Comment by feggimann** [comment]
@windauer deutsche Highlights sehen super aus. Bei englischen ist es noch nicht implementiert:

<img width="1363" alt="Bildschirmfoto 2023-06-04 um 17 26 05" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/c357629f-8eef-4a27-b642-cf54f4172d01">

**Comment by windauer** [comment]
@feggimann bitte probier mal ein "Shift + reload" mit Deinem Browser oder ein privates Browser Fenster .. das scheint ein cashing issue zu sein, bei mir funktioniert es lokal und auf https://gf.tei-publisher.com/en/ - 

<img width="1429" alt="Screenshot 2023-06-05 at 13 15 51" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/514615/879413f1-be12-45ec-8af2-a2ae4a1359ed">

**Comment by feggimann** [comment]
funktioniert alles
