### ISSUE TITLE
Recherche, Anton: Herr Johnson

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#42]
TB. 1851, S. 88.
Es kann nicht eruiert werden, ob hier Thomas Manby Johnson oder Henry S. Johnson gemeint ist.

**Comment by NicolauLutz** [comment]
Ich wuerde den Satz folgendermassen Taggen: 
"Von Ihnen weg besuchte ich die Gussstahlfabrike von <persName>den Herrn Johnson, Cammel, & Comp.</persName>, in welcher... "

Und dann Eintrag fuer:
<persName>den Herrn Johnson, Cammel, & Comp.</persName>

als "Johnson, Cammel, & Comp." als Koerperschaft.

Und dann individuelle Eintraege fuer Thomas Johnson, Henry Johnson, und Charles Cammel.

**Comment by vrukavina** [comment]
Genau, das habe ich auch so gemacht.
Deiner Meinung nach ist also mit Herr Johnson Henry gemeint und nicht Thomas?

**Comment by NicolauLutz** [comment]
Kann glaube ich nicht mehr eruiert werden, wer von den beiden gemeint ist.
