### ISSUE TITLE
Seite Zitiervorschlag in Dropdownliste "über die Edition"

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#421]
Bitte die Seite "Zitiervorschlag" auch in "über die Edition" in die Dropdownliste aufnehmen. Zwischen "Impressum/Lizenzen" und "Dank".
<img width="383" alt="Bildschirmfoto 2023-06-01 um 22 34 50" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/7f42f60d-2bd9-4158-87a7-72035ca50a08">

**Comment by windauer** [comment]
done, kommt mit der nächsten Veröffentlichung

**Comment by feggimann** [comment]
perfekt
