### ISSUE TITLE
Liste Ortsregister: englische und deutsche Namen gemischt

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#422]
Bei manchen Ortseinträgen erschein bei Städten oder Regionen in der dt Version der en Name:

Einige Beispiele:
Munich/München
Saxony/Sachsen
Geneva/Genf

<img width="383" alt="Bildschirmfoto 2023-06-01 um 22 40 54" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/a64b2728-649a-4651-acb7-be55d1d5b0f7">
<img width="383" alt="Bildschirmfoto 2023-06-01 um 22 41 47" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/836142e6-aa93-455f-b67b-2d5cdc9686ab">
<img width="383" alt="Bildschirmfoto 2023-06-01 um 22 42 24" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/944e2bc5-3387-4f18-8a58-06343d120491">

Sehr verwirrend sind die Beispiele zu Kopenhagen:
Kopenhagen
Kopenhagen/Schloss Rosenborg
aber:
Copenhagen/Christianshavn
Copenhagen/Schloss Christiansborg

Schloss Rosenborg kommt in der englischen Version noch nicht vor, die anderen drei zu Kopenhagen schon.

<img width="383" alt="Bildschirmfoto 2023-06-01 um 22 43 22" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/f5a8561a-59fc-4ed5-b323-4e927c39c3ce">
<img width="383" alt="Bildschirmfoto 2023-06-01 um 22 43 59" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/cde63f42-df6f-46a7-9d19-55b043f07a3f">

Es zieht sich bis in die Detailansicht, auch hier z.T. englischer Ort:

<img width="667" alt="Bildschirmfoto 2023-06-01 um 22 49 50" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/f832c309-90a8-4d7e-a588-15386f25d2e6">

In der englischen Version der Edition stimmt es, z.B. Geneva, Ghent:

<img width="330" alt="Bildschirmfoto 2023-06-01 um 22 52 17" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/bc0d930a-58a0-45dd-ba7a-5cf79865770d">

**Comment by windauer** [comment]
@feggimann , @ottosmops das liegt daran, dass die Daten die wir aus Anton bekommen, hier falsch sind. Siehe z.B. 
`<settlement xml:lang="de">Munich</settlement>` [hier](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/blob/ff95aefab86c0c64b0e4cef6d14dca13264f6fb9/src/register/archives-anton-places-de.xml#L1992). 

Ich kann Euch gerne noch einmal eine archives-places-tei.xml wie von der ab verwendet ins repository laden wenn gewünscht. Dann würde ich aber all die andere Registerdaten dort löschen, weil das m.E. mehr verwirrt wenn da so viele Versionen in https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/tree/master/src/register rumfliegen.

**Comment by ottosmops** [comment]
@feggimann Habe das nochmal grundsätzlich ein bisschen anders (besser?) aufgegleist. Da möglicherweise auch die Akteure von dem Problem betroffen sein könnten. Deshalb bitte places und actors nochmals überprüfen.

**Comment by feggimann** [comment]
@ottosmops danke für Hinweis. Zeilenumbruch ist raus und excel neu hochgeladen.

**Comment by feggimann** [comment]
schaut jetzt gut aus
