### ISSUE TITLE
grosse Bilder-Popups: Legenden bei Personen

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#424]
Die Lebensdaten werden nicht richtig angezeigt. Zudem fehlt der erste Satz der Beschreibung/Biografie:

<img width="611" alt="Bildschirmfoto 2023-06-01 um 22 58 27" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/900f2f66-b5ce-4d9e-a05c-24b796243dec">

**Comment by windauer** [comment]
done

**Comment by feggimann** [comment]
passt
