### ISSUE TITLE
Falscher Link zu Facsimile

### ISSUE THREAD

**Issue by windauer** [GF-Corporate-Archives/gf-johann-conrad-fischer#428]
In Reisetagebuch-3.xml scheint folgende URL im facs Attribut falsch zu sein: `<pb n="250" facs="https://www.e-rara.ch/ebs/content/zoom/165579891"/>`.  Ich denke der richtige Link muss: https://www.e-rara.ch/ebs/content/zoom/16557981 lauten.

**Comment by feggimann** [comment]
@windauer danke für den Hinweis.
@NicolauLutz In TB 1825 stimmen die urls ab Seite 250 bis Schluss nicht. Bitte korrigieren. Vorher bis Seite 249 korrekt.

**Comment by NicolauLutz** [comment]
Links von Seite 250 bis Schluss wurden korrigiert.
