### ISSUE TITLE
grüne Popups mit Bild: Link zu grosser Bilderansicht funktioniert nicht

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#430]
@windauer Bei grünen Popups im Fliesstext, die ein Bild enthalten, erscheint die "Klickhand" wenn man mit der Maus übers Bild fährt. Aber wenn man drauf klickt, öffnet sich die grosse Bilderansicht nicht (hat früher einmal funktioniert).

**Comment by windauer** [comment]
good find :) ist gefixt mit der nächsten Version!

**Comment by feggimann** [comment]
@windauer funktioniert jetzt für Personen, Körperschaften und Keywords. Aber bei Orten funktioniert es nicht.

**Comment by windauer** [comment]
ist mit der nächsten Version gefixt.

**Comment by feggimann** [comment]
funktioniert
