### ISSUE TITLE
Registerdaten: weitere Namensformen werden doppelt angezeigt

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#431]
@windauer In Detailansicht Registerdaten werden "weitere Namensformen" doppelt angezeigt. Betrifft sowohl in de und en:
- Personen
- Körperschaften
- Orte

Hier Beispiele:
<img width="753" alt="Bildschirmfoto 2023-06-04 um 17 46 14" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/ab1f5739-416d-4f6e-89d1-3bceb4ac4d2f">
<img width="753" alt="Bildschirmfoto 2023-06-04 um 17 46 40" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/727548f1-27da-427a-86e4-285845e721ba">
<img width="753" alt="Bildschirmfoto 2023-06-04 um 17 47 47" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/ad81712a-ebfb-4424-a70f-94100e279c67">
<img width="753" alt="Bildschirmfoto 2023-06-04 um 17 47 11" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/e5d0a11b-ff5b-4937-95e3-24b57a7e9304">
<img width="753" alt="Bildschirmfoto 2023-06-04 um 17 47 47" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/48c46b49-9f20-43df-8c8e-ad0290652603">

**Comment by windauer** [comment]
ist gefixt

**Comment by feggimann** [comment]
sieht gut aus
