### ISSUE TITLE
Startseite: neues Kartenbild

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#433]
@windauer Hier der neue Kartenausschnitt bei "zu dfen Reisen". Ich hoffe, die Dimensionen passen.
[karte_2_gfd_2_231-0001-1240.zip](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/files/11649663/karte_2_gfd_2_231-0001-1240.zip)

**Comment by windauer** [comment]
danke, ist eingebaut, geht mit der nächsten Version live.

**Comment by feggimann** [comment]
super, ist da
