### ISSUE TITLE
Legende grosse Bilderansicht Weltausstellung

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#435]
@windauer Beim Keyword "Londoner Weltausstellung" stimmt die Anzeige der Legende bei der grossen Bilderansicht nicht. Die Beschreibung ist verzerrt. Sonst ist mir das bei keinem Bild aufgefallen.

![grafik](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/b5ea3027-c629-4d46-be47-a8ec76e4421a)

**Comment by windauer** [comment]
@feggimann bitte immer einen Link dazu posten, damit wir das schnell nachvollziehen können. Danke

**Comment by windauer** [comment]
done

**Comment by feggimann** [comment]
stimmt wieder
