### ISSUE TITLE
Unterseite "travels" in en Version de Titel

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#438]
@windauer In der en Version hat die Unterseite "travels" den deutschen Titel "Reisetagebücher" statt englisch "Travel Journals". Bitte in "Travel Journals" ändern:
https://johannconradfischer.sources-online.org/en/travels

<img width="800" alt="Bildschirmfoto 2023-06-05 um 23 05 04" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/5a067b2c-0456-47f3-8ff1-fa48c29839e5">

**Comment by windauer** [comment]
done

**Comment by feggimann** [comment]
erledigt
