### ISSUE TITLE
Fusszeile: Links

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#439]
@windauer Die Links zu Zitiervorschlag, Datenschutz, Lizenz öffnen alle in neuem Tab. Ist m.E. nicht nötig. Bitte in gleichem Tab öffnen.

Ist es möglich, bei Logo Eisenbibliothek den Link zu Webseite zu hinterlegen?
de: https://www.eisenbibliothek.ch/de.html
en: https://www.eisenbibliothek.ch/en.html

<img width="1314" alt="Bildschirmfoto 2023-06-05 um 23 21 16" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/84a1a2fa-8a22-46c1-8973-18f4b2a2850c">

**Comment by windauer** [comment]
done

**Comment by feggimann** [comment]
passt
