### ISSUE TITLE
Mobileversion: grosse Bildansicht

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#440]
@windauer In der Mobileversion lässt sich die grosse Bildansicht nicht navigieren. Man kann einzig die Bilder hin- und herwischen. Aber weder die Pfeile links und rechts noch das "weitere Informationen" noch Schliessen bei ins Leere tippen funktioniert. Man ist auf der Bildansicht blockiert.

Lässt sich das beheben?

**Comment by windauer** [comment]
Popups und Image Gallerie auf Mobiles sind gerade unsere größten Sorgenkinder und wir probieren das heute noch in den Griff zu bekommen.

**Comment by windauer** [comment]
done, die Galerie sollte jetzt ordentlich funktionieren. Für eine kleine mobile Ansicht, haben wir uns dafür entschieden,  die Bilder nicht rechts neben dem Text zu rendern, da sie dort zu viel Platz wegnehmen. Die Bilder sind aber über die Popups ja noch erreichbar. Dort gibt es gerade noch ein Problem mit dem Links im Popup auf Mobile Devices, aber wir gehen davon aus, das heute noch fixen zu können.

**Comment by windauer** [comment]
zu dem Problem mit den Links von Thumbails auf image-gallery auf mobiles gibt es jetzt hier ein Ticket: https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/issues/442

**Comment by feggimann** [comment]
grosse Bildansicht ok auf iPhone 11 Pro
