### ISSUE TITLE
Mobileversion: grüne Popups bleiben nicht stehen

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#441]
@windauer Die grünen Popups im Fliesstext bleiben in der Mobileversion nicht offen wenn man auf das verlinkte Wort tippt. Wenn ich auf ein verlinktes Wort tippe, erscheint das Popup und verschwindet grad wieder. Wenn ich mit dem Finger länger drauf bleibe, um das Wort zu markieren, dann bleibt das Popup stehen. Ist nicht tragisch, aber auch nicht intuitiv. Wenn es schwierig zu ändern ist, dann ist es sicher ein Fall für Milestone 2.

**Comment by windauer** [comment]
sind wir dran

**Comment by windauer** [comment]
done

**Comment by feggimann** [comment]
funktioniert
