### ISSUE TITLE
Mobilversion: Links von Thumbnails in Popups auf die image-gallery funktionieren nicht.

### ISSUE THREAD

**Issue by windauer** [GF-Corporate-Archives/gf-johann-conrad-fischer#442]
z.B. https://johannconradfischer.sources-online.org/de/1794/2 > klick auf Basel öffnet Popup > click auf Thumbnail im Popup sollte image-gallery öffnen, das funktioniert aber auf Apple iPhone 12 mini gerade nicht.

**Comment by windauer** [comment]
done

**Comment by feggimann** [comment]
passt
