### ISSUE TITLE
Darstellung Datumsangabe

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#443]
from-to Daten werden ohne Leerschläge dargestellt.

Bsp. reisetagebuch-2 // https://johannconradfischer.com/de/1814/19

``<date from="1814-01-01" to="1814-01-31">Januar 1814</date>``

<img width="734" alt="Bildschirmfoto 2023-07-28 um 16 18 06" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/50bd6eb7-5265-4f75-a507-40bc3a2634c3">

**Comment by windauer** [comment]
done

**Comment by feggimann** [comment]
danke

**Comment by feggimann** [comment]
siehe dazu Issue #470
