### ISSUE TITLE
Farbe Itinerar 1851

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#444]
Die Farbe des Itinerars in der Karte stimmt bei der Reise 1851 nicht mit der Legendenfarbe in der linken Spalte überein (weder de noch en):
https://johannconradfischer.com/de/travels
https://johannconradfischer.com/en/travels

<img width="1323" alt="Bildschirmfoto 2023-07-28 um 16 22 35" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/a29b106e-9995-4d30-bcd6-a5ff6c53dda6">
<img width="1323" alt="Bildschirmfoto 2023-07-28 um 16 22 51" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/d529d1b3-a0b6-4cb2-a1dc-2c5ef29b3548">

**Comment by windauer** [comment]
Ich konnte das Issue nachstellen, es hängt mit der Art und Weise zusammen, wie die Farben berechnet werden und ist etwas tricky.

**Comment by windauer** [comment]
done

**Comment by feggimann** [comment]
passt
