### ISSUE TITLE
Sortierung Orte in Ortsregister

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#445]
Bei Orten in Städten sollte in der Liste zuoberst die Stadt selber, danach die Strassen/Gebäude/Orte in der Stadt erscheinen. In den Ortslisten bei den Tagebuchtexten ist es richtig, aber im Ortsregister stimmt es nicht.

Hier Bsp Leeds im TB 1814: https://johannconradfischer.com/de/1814/27

<img width="1501" alt="Bildschirmfoto 2023-07-28 um 16 28 02" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/fbba7735-1346-429b-aa14-eb94735bfef2">
<img width="1501" alt="Bildschirmfoto 2023-07-28 um 16 27 41" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/f1ae052b-b5a0-4d0a-9e60-211db34e3192">

**Comment by windauer** [comment]
Die Sortierung der Orte auf der Registerseite ist jetzt die gleiche, wie für die Ortslisten für die Textseiten. 

<img width="1348" alt="Screenshot 2023-09-20 at 15 45 37" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/514615/34925222-5b6d-4592-9015-c4d2fbec550f">

Wird mit dem nächsten update auf gf.tei-publisher.com eingespielt.

**Comment by feggimann** [comment]
super, danke
