### ISSUE TITLE
urls de/en abstimmen

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#446]
Die urls der de/en Versionen sollten aufeinander abgestimmt werden. Beim Wechseln der Sprache sollte man nicht auf die Startseite kommen, sondern auf der gleichen Seite in der anderen Sprache bleiben.

Also z.B. 
https://johannconradfischer.com/de/1794/1
de>en
https://johannconradfischer.com/en/1794/1

oder
https://johannconradfischer.com/en/places/gfa-places-131
en>de
https://johannconradfischer.com/de/places/gfa-places-131

**Comment by windauer** [comment]
done

**Comment by feggimann** [comment]
Super! Vielen Dnak!
