### ISSUE TITLE
Registersuche: Filtern der Treffer funktioniert nicht immer

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#447]
Bei der Registersuche verschwinden teilweise die richtigen Treffen mit fortschreitendem Eintippen des Worts - ein Muster haben wir leider nicht erkannt. Einige Beispiele:

**Namen**
"Anubis": funktioniert
"Athene": bis "athen" sichtbar, bei "athene" weg

**Orte**
"Helsingör": bis "helsing" sichtbar, bei "helsingö" weg

**Begriffe**
"Alabaster": bis "alabast" sichtbar, bei "alabaste" weg
"Wasserkraft" funktioniert

<img width="878" alt="Bildschirmfoto 2023-07-28 um 17 26 19" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/7fe8e8d4-1a97-4046-b071-63fb1bc4d5f8">
<img width="878" alt="Bildschirmfoto 2023-07-28 um 17 26 42" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/e3527e3e-5da0-46e1-b63b-35985ce4f6a4">
<img width="878" alt="Bildschirmfoto 2023-07-28 um 17 26 51" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/1a3e3cbb-30c5-49b7-a797-37340789bcd5">
<img width="878" alt="Bildschirmfoto 2023-07-28 um 17 27 38" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/d91eb700-d5db-421e-9c5f-764d4e0cb1cb">
<img width="878" alt="Bildschirmfoto 2023-07-28 um 17 27 47" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/23c00c23-f928-4a9b-8788-56af19c3c99c">
<img width="878" alt="Bildschirmfoto 2023-07-28 um 17 28 11" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/883a179b-eefe-4519-9bb6-ed03564530bc">
<img width="878" alt="Bildschirmfoto 2023-07-28 um 17 28 17" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/230b65e7-adb1-4d50-8434-2a1940e32861">
<img width="878" alt="Bildschirmfoto 2023-07-28 um 17 28 53" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/d40cee6c-dac8-4e5b-9182-2c988425cc63">

**Comment by windauer** [comment]
Dieses issue ist sehr tricky, für alle Fälle bis auf Orte und den Fall `Helsingö` geht es jetzt. `Helsing` und `Helsingör` sowie `Helsingo` findet etwas, aber leider `Helsingö` nicht. Das noch übrige Problem scheint tief unten in Lucene zu sein, und erfordert weitere Nachforschungen. Mit dem nächsten Update, sollte die Suche auf den Registerdaten aber schon deutlich besser sein.

**Comment by windauer** [comment]
done

**Comment by feggimann** [comment]
alle Beispiele funktionieren jetzt
