### ISSUE TITLE
Suche: Treffer in Fussnote - falsche Nummerierung

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#448]
- Suche nach "Nawab" > Treffer ist in Fussnote 21, Kapitel 62 von Tagebuch 3 (1825)
- Aufrufen des Treffers > Fussnote wird als Fussnote 1 nummeriert
- auch nach Hin- und Herklicken in ein anderes Kapitel und zurück zu Kapitel 62 wird immer noch Fussnote 1 angezeigt und Nawab ist nach wie vor gelb markiert

<img width="1484" alt="Bildschirmfoto 2023-07-28 um 17 47 11" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/aacdb8c0-7784-4482-a047-6e418d04de3d">
<img width="1484" alt="Bildschirmfoto 2023-07-28 um 17 47 29" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/a394d910-5d48-4e08-a37f-1f936d39be33">
<img width="1484" alt="Bildschirmfoto 2023-07-28 um 17 48 36" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/7e4f149b-687d-4b44-9701-e7d16d24e192">
<img width="1484" alt="Bildschirmfoto 2023-07-28 um 17 48 11" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/df1d7a64-68e9-43ab-acb9-8b200659032b">

**Comment by HelenaSabel** [comment]
Footnote number fixed when coming from a search result. Tested with the “Nawab” example
![image](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/8516387/d98061f2-fc3c-477f-8453-88408c93e00f)

See live version at: https://gf.tei-publisher.com

**Comment by feggimann** [comment]
Still a but with search results in footnotes: search "Wegstunden" > one result is footnote 6 in journal 6 (1846) > when you click on the result, all three footnotes in this chapters have number 43:

![grafik](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/62fa13e0-bd14-4b15-89e2-6880a7c45a95)

![grafik](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/29538d42-57a3-412a-8c90-45df400b5c29)

![grafik](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/b9812a5e-2978-46a4-a745-b6dbddf20a42)

**Comment by feggimann** [comment]
looks fine now, thank you. Yes, this is correct that the number of footnotes differ between German and English.
