### ISSUE TITLE
Karte: Verlinkung der Itinerarorte nicht korrekt

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#449]
Verlinkungen der Itinerarorte von Titelseite eines Tagebuchs führen entweder auf das jeweils folgende Kapitel des eigentlich richtigen, oder es kommt "Anfrage schlug fehl":

**Tagebuch 1814** https://johannconradfischer.com/de/1814/1
Auf Startseite Klicken auf **Epernay (12. August)** > **Kapitel 5** zum 14. August wird geöffnet (statt **Kapitel 4**, das richtig wäre)
Auch bei anderen Beispielen in TB 1794 oder 1851 wird jeweils das Kapitel danach angezeigt.

<img width="1728" alt="Bildschirmfoto 2023-07-28 um 17 58 07" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/8ec2dfe4-9b9c-46db-b7ea-bfc7b35f3e04">

<img width="1728" alt="Bildschirmfoto 2023-07-28 um 17 59 20" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/88867085-7ddb-4037-83ee-12d3eabf0c8b">

**Tagebuch 1825-1827** https://johannconradfischer.com/de/1825-1827/1
Auf Startseite Klicken auf **Amiens** > Seite wird geöffnet mit "**Anfrage schlug fehl**"

<img width="1728" alt="Bildschirmfoto 2023-07-28 um 18 03 38" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/083ecbff-85be-4441-be72-9fc37534b7e4">

<img width="1728" alt="Bildschirmfoto 2023-07-28 um 18 03 58" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/53f3e8e6-4a07-43d4-9ddf-758bcf919d26">

**Tagebuch 1825** https://johannconradfischer.com/de/1825/1
Auf Startseite Klicken auf **Chalons-en-Champagne** > "**Anfrage schlug fehl**"
!**Aber**! auf Startseite Klicken auf **Aston Hall, Birmingham** > wieder das **Kapitel danach**

<img width="1728" alt="Bildschirmfoto 2023-07-28 um 18 11 17" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/b01f2c15-2993-45ea-b5d9-95d20a33bf8c">

<img width="1728" alt="Bildschirmfoto 2023-07-28 um 18 11 27" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/4624a627-70ab-4e21-b619-3eddc71490fb">

<img width="1728" alt="Bildschirmfoto 2023-07-28 um 18 12 22" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/1961838f-329f-4637-a5cb-92e439ca468d">

<img width="1728" alt="Bildschirmfoto 2023-07-28 um 18 12 37" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/ebb578b2-80e0-48a5-a8f6-cb3a294fed42">

**Comment by feggimann** [comment]
Das gleiche nicht nur auf der Titelseite, sondern auch innerhalb eines Tagebuchs: Klicken auf einen hellgrünen Itinerarpunkt führt jeweils zum Kapitel, das auf das richtige Kapitel folgt. Also Kapitel 15 statt 14 oder Kapitel 4 statt 3.

**Comment by windauer** [comment]
ich kann das fehlerhafte Verhalten reproduzieren.

**Comment by windauer** [comment]
done

**Comment by feggimann** [comment]
super
