### ISSUE TITLE
Recherche, Anton: Howard und Kreeft

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#45]
TB 1851.
Es ist nicht ganz klar, ob das eine Person oder zwei Personen sind. Howard wird nur 1 Mal erwähnt (S. 16); Kreeft mehrmals (S. 16, 31, 32, 37, 74, 88, 94). Handelt es sich um S. C. Kreeft? (damaliger Generalkonsul) oder um Henry Louis Kreeft?

**Comment by NicolauLutz** [comment]
Bei Kreeft handelt es sich wohl um Siegrich Christopher Kreeft, Mecklenburgischer Konsul. Seine Addresse bei Billiter Squre (S. 39) wird bestätigt durch das *Post Office London Directory* von 1852, S. 335, 647 (= 839, 1634) [Link](http://specialcollections.le.ac.uk/digital/collection/p16445coll4/id/181327). Dort geht auch hervor, dass Kreeft neben seinen konsularischen Tätigkeiten auch als Geschäftsmann auftrat (es war typisch für das neunzehnte Jahrhundert, dass Geschäftsleute im Ausland "Ehrenamtlich" noch konsularische Pflichten für ihr Heimatland erfüllten).

**Comment by NicolauLutz** [comment]
Interessant ist auch der Eintrag im *Post Office London Directory* von 1840, der belegt, dass Kreeft als "Foreign Agent" für [Butterley Co.](https://en.wikipedia.org/wiki/Butterley_Company), einer Londoner Giesserei, tätig war ([Link](http://specialcollections.le.ac.uk/digital/collection/p16445coll4/id/26763), S. 335 (=363). Gemäss Graces Guide wurde Kreeft 

Zu Howard habe ich leider nichts gefunden, aber wahrscheinlich war er ein Geschäftspartner von Kreeft. "Howard und Kreeft" im TB S. 16 bezeichnet möglicherweise ihre Geschäftsfirma. 

 Im Fazit, es würde wohl Sinn machen, den Eintrag für Howard und Kreeft zu behalten für die Geschäftsfirma, und einen neuen Eintrag anzulegen für Siegrich Christopher Kreeft, insbesondere da Fischer mit Kreeft ja einiges zu tun hatte.
