### ISSUE TITLE
Registereinträge: Sortierung der Listen bei "Erwähnungen in den Tagebüchern"

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#450]
Bitte die Listen der relevanten Kapitel unter "Erwähnung in den Tagebüchern" chronologisch, d.h. nach Nummerierung der Kapitel, ordnen. Im Moment sind sie wild durcheinander:

Bsp  Place "Piccadilly": https://johannconradfischer.com/de/places/gfa-places-1630?&category=L&search=picca

<img width="1728" alt="Bildschirmfoto 2023-07-28 um 18 28 23" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/b3db728a-9ca2-4869-a87e-0176cd4786c6">

**Comment by windauer** [comment]
done

**Comment by feggimann** [comment]
perfekt
