### ISSUE TITLE
kleine grüne Popups bei Tagebuchtexten: Link "weitere Informationen"

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#452]
Bitte bei kleinen grünen Popups in Tagebuchtexten den Link "weitere Informationen" unterstreichen. Dann ist es klarer, dass das ein Link ist. 

(Bei den Texten auf weissen Hintergrund zeigt die grüne Schrift, dass es ein Link ist, aber hier sind sowohl normaler Text wie Links in Schriftfarbe weiss auf grünem Hintergrund. Somit merkt man nicht wann ein Link hinterlegt ist)

Betrifft Popups zu Namen (Personen, Familien, Organisationen), Orten, Begriffen, Datumsangaben und in Fussnoten

Bispiel von Seite https://johannconradfischer.com/de/1851/5
<img width="1545" alt="Bildschirmfoto 2023-07-31 um 18 15 11" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/dedde2c9-0d37-4388-99ff-158d783de628">

**Comment by windauer** [comment]
done

<img width="902" alt="Screenshot 2023-09-19 at 16 54 58" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/514615/e036de40-be30-480f-b0dd-2944e11adec5">

**Comment by feggimann** [comment]
danke
