### ISSUE TITLE
kleine grüne Popups in Tagebuchtexten: Schriftgrösse

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#453]
Die Schriftgrösse in den grünen Popups ist grenzwertig klein. Ev. etwas grösser darstellen, z.B. gleich gross wie die Einträge in den Registerlisten in rechter Spalte oberhalb der Karte oder die Ortspopups in der Karte?

Gut wäre, nicht noch eine weitere neue Schriftgrösse, sonst wird es zu uneinheitlich. Wenn ich es richtig sehe, gibt es im Moment folgende Schriftgrössen:
- **gross**: Kapitelüberschrift
- "**normal**": Haupttext, Navigation in Kpofzeile
- **klein**: Inhaltsverzeichnis, Registerlisten in rechter Spalte, Kartenlegende, Kapitelnavigation (vorheriges/nächstes Kapitel)
- **ganz klein**: grüne Popups, Fussnoten

Stimmt das? D.h. ev. grüne Popups auch "klein", und nur Fussnoten "ganz klein"?

Bsp. von Seite https://johannconradfischer.com/de/1851/5
<img width="1545" alt="Bildschirmfoto 2023-07-31 um 18 26 53" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/ec723a8d-bd8e-4b91-9ccd-7c8842a4dce2">

**Comment by windauer** [comment]
@feggimann mit den Schriftgrößen hast Du recht, das sieht bei uns folgendermaßen aus: 

```
    /* font-sizes */
    --gf-font-size-base: 1.125rem; /* 18px */
    --gf-font-size-slightly-smaller: 0.9375rem; /* 15px */
    --gf-font-size-small: 0.875rem; /* 14px */
    --gf-font-size-smallest: .75em; /* 13px */
```

Heutzutage werden Schriftgrößen im Web nicht mehr mit Pixeln angegeben, sondern mit `rem`, dahinter haben wir jeweils vermerkt, um wieviel Pixel sich es sich grob handelt. Ich habe jetzt die Schriftgröße in Popups von `smallest` auf `small` gesetzt. 

#### Vorher
<img width="603" alt="Screenshot 2023-09-19 at 16 30 32" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/514615/b3ba7af3-fde3-4efa-9dcc-e7ca00e09c06">

#### Nachher

<img width="597" alt="Screenshot 2023-09-19 at 16 30 11" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/514615/af213925-bd57-40c4-9b30-9edf9da456cf">


Die Änderung wird mit dem nächsten Update ausgerollt

**Comment by feggimann** [comment]
viel besser, danke!
