### ISSUE TITLE
Zitiervorschlag auf jeder Seite anzeigen

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#454]
Es wäre super, wenn jede Seite den richtigen Zitiervorschlag für diese Seite anzeigt, z.B. in der Fusszeile?

D.h. Zitiervorschläge für:
- Tagebuchseiten entsprechendes Tagebuch und Kapitel
- Register entsprechender Name/Ort/Begriff
- Bildergalerie entsprechendes Tagebuch
- Übersicht Itinerare
- alle anderen Seiten Zitat wie für Gesamtedition

Z.B.
**Tagebuch 1851, Kapitel 2 (in [] Angaben, die wechseln):**
Johann Conrad Fischer: Reisetagebuch [**1851**], [**Gedanken zur Weltausstellung in London 1851**]. In: Reiseberichte eines Pioniers. Digitale Edition der Reisetagebücher von Johann Conrad Fischer 1794–1851. Herausgegeben von Franziska Eggimann. Bearbeitet von Franziska Eggimann, Nicolau Lutz, Valerija Rukavina und Christopher Zoller-Blundell. Schlatt 2023, Version 1.0, [**https://johannconradfischer.com/de/1851/2**], Stand [**8. Juni 2023**].

**Ort: Crystal Palace (in [] Angaben, die wechseln):**
[**The Crystal Palace**]. In: Reiseberichte eines Pioniers. Digitale Edition der Reisetagebücher von Johann Conrad Fischer 1794–1851. Herausgegeben von Franziska Eggimann. Bearbeitet von Franziska Eggimann, Nicolau Lutz, Valerija Rukavina und Christopher Zoller-Blundell. Schlatt 2023, Version 1.0, [**https://johannconradfischer.com/de/places/gfa-places-1701**], Stand [**8. Juni 2023**].

**Bildergalerie 1794 (in [] Angaben, die wechseln):**
Johann Conrad Fischer: Reisetagebuch [**1794**], Bildergalerie. In: Reiseberichte eines Pioniers. Digitale Edition der Reisetagebücher von Johann Conrad Fischer 1794–1851. Herausgegeben von Franziska Eggimann. Bearbeitet von Franziska Eggimann, Nicolau Lutz, Valerija Rukavina und Christopher Zoller-Blundell. Schlatt 2023, Version 1.0, [**https://johannconradfischer.com/de/gallery/1794**], Stand [**8. Juni 2023**].

etc.

Vorschläge für englische Seiten analog.

Ist das möglich?

**Comment by HelenaSabel** [comment]
Done! See live version at https://gf.tei-publisher.com

**Comment by feggimann** [comment]
Citation in chapters have the correct link, but in register data and gallery they have a longer link with "exist/apps/gf-tagebuecher" in between. Please use always correct link.

**Comment by HelenaSabel** [comment]
@feggimann I think we have addressed all the different issues you mention.

**Comment by feggimann** [comment]
@HelenaSabel @windauer just two points regarding citation still open - rest looks fine:
- please use for citation in chapters of journals the same font size as in register data and gallery
- please add citation for keywords. actors and places are fine.

**Comment by HelenaSabel** [comment]
@feggimann: the last modifications are now deployed

**Comment by feggimann** [comment]
looks good now, thank you
