### ISSUE TITLE
grosses Bilderpopup: Schliessen mit X o.ä.

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#456]
Einige User haben schon gemeldet, dass es nicht klar ist, wie sie aus der grossen Bilderansicht wieder herauskommen.

Kann man oben rechts ein X einbauen zum Schliessen? Oder im grünen Legendenkästchen neben "weitere Informationen" auch "schliessen"? Oder was gäbe es sonst für eine Möglichkeit?

**Comment by windauer** [comment]
done

**Comment by feggimann** [comment]
super
