### ISSUE TITLE
Register Detailansicht: oberste Zeilen mit Kategorien/Definitionen kleiner darstellen

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#458]
Bei der Detailansicht der Registereinträge sollten die "Kopfdaten" mit der Kategorie etc. besser vom Beschreibungstext abgegrenzt werden. Z.B. mit kleinerer Schrift? Ev. auch Feldname vornedran?

Das betrifft folgende Informationen:

Bei Begriffen:
- oberste Zeile mit Typ
- Bsp. "Stubenofen" (https://johannconradfischer.com/de/keywords/gfa-keywords-9781)

Bei Orten:
- oberste drei Zeilen mit Typ, Ort/Land, weiteren Namensformen
- Bsp. "Philosophical Hall" (https://johannconradfischer.com/de/places/gfa-places-1973)

Bei Namen:
- oberste drei Zeilen mit Typ, Lebensdaten und weiteren Namensformen
- Bsp. "Abraham a Sancta Clara" (https://johannconradfischer.com/de/names/gfa-actors-7724)

**Comment by windauer** [comment]
ich habe jetzt mal "eine Schriftgröße kleiner + italic" gewählt, muss dann ggf. noch angepasst werden. Wir mit nächsten Update ausgeliefert.

**Comment by feggimann** [comment]
Schaut viel besser aus! Aber bitte nur kleiner, nicht italic, sonst haben wir schon wieder eine Stilvariante mehr.

Wäre es möglich, bei Actors und Places den Abstand zwischen diesen Zeilen kleiner zu machen, damit es nicht so gesperrt ausschaut? Also in untenstehenden Beispielen zw. Typ, Lebensdaten, weiteren Namensformen bzw. zw. Typ, Ort, weiteren Namensformen (wobei Lebensdaten, weitere Namensformen und Ort nicht immer vorhanden)?

<img width="723" alt="Bildschirmfoto 2023-10-06 um 15 11 12" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/0ba3ad8d-cd23-4256-96e7-f876a1a4a1f9">
<img width="723" alt="Bildschirmfoto 2023-10-06 um 15 12 36" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/edee4fab-59a9-484e-a0bf-a8a568150ac7">

**Comment by windauer** [comment]
@feggimann so? 

<img width="728" alt="Screenshot 2023-10-10 at 16 20 38" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/514615/79cb36d9-4baa-415d-a3f7-3c5d57cf5d4b">

<img width="748" alt="Screenshot 2023-10-10 at 16 21 06" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/514615/a75cca67-79e1-4e22-af94-3d69c2ba5bca">

**Comment by feggimann** [comment]
@windauer Ja, super, vielen Dank. So finde ich es perfekt.
