### ISSUE TITLE
Fussnote in getaggtem Wort: Sollte nicht eingefärbt sein

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#459]
Normalerweise sind die Fussnoten am Ende des Kapitels und ihre zugehörige Zahl im Text in schwarzer Farbe. Beim folgenden Beispiel handelt es sich um einen Fall, bei welchem die Fussnote innerhalb einer getaggten Einheit steht. Die Tags können nicht anders gesetzt werden. Ist es trotzdem möglich den Text in der Fussnote sowie ihre Zahl im Fliesstext wie üblich in schwarzer Farbe darzustellen?

Bsp. https://johannconradfischer.sources-online.org/de/1814/13
![Bildschirmfoto 2023-08-02 um 17 11 38](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/28c530c1-68ef-45c1-8321-0eaf4bd32e05)

![Bildschirmfoto 2023-08-02 um 16 55 51](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/cf5d7321-04fb-4692-837b-75331d15e0f4)

**Comment by windauer** [comment]
@vrukavina das ist ein wirklich komplizierter Fall, den wir so noch nicht hatten und durchaus komplex ist. Der jetzige Ausdruck `<term ref="gfa-keywords-8528">One<note>Erratum aus <ref target="https://www.e-rara.ch/ebs/content/zoom/16557726">Erstdruck</ref>.</note> hundred merry tales of Shakespeare</term>` führt dazu, dass alles innerhalb vom tei:term ein Popup wird, somit führ auch der Link der `8` im Text nicht zur Fußnote, sondern öffnet den Popup zum Term. Und selbst, wenn wir es hinbekommen, dass "One" und "hundred merry tales of Shakespeare" das Popup öffnen und die `8` dann zur Fußnote springt, für Enduser ist das m.E. verwirrend, da es wie ein Link aussieht:  <img width="445" alt="Screenshot 2023-09-19 at 14 44 40" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/514615/7d964da2-5fe0-4e9a-b79d-c6b734bb94f0">

Du hast zwar geschrieben, die note muss genau hinter "One" kommen, aber ich habe mir erlaubt den Ausdruck testweise mal wie folgt umzustellen: 

`<term ref="gfa-keywords-8528">One hundred merry tales of Shakespeare</term><note>Erratum aus <ref target="https://www.e-rara.ch/ebs/content/zoom/16557726">Erstdruck</ref>.</note>`

Dadurch ist die Fußnote jetzt natürlich am Ende des term und nicht mehr hinter one, allerdings ist es so möglich, das Popup zu öffnen und zur Fußnote zu springen und auch die Fußnote selbst, wird sauber gerendert: 

<img width="720" alt="Screenshot 2023-09-19 at 14 38 32" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/514615/05c29f26-ecc3-4f5c-8f75-57c2d27801b2">

Wenn wir probieren sollen, eine technische Lösung für tei:note in term (aber auch placeName, persName usw.) zu implementieren, können wir das gerne angehen, das kann aber durchaus umfangreicher werden, da es überhaupt erstmal ein Konzept braucht, wie wir das im Text rendern wollen und selbiges implementieren können. Einfach nur den Text in der Fußnote in Schwarz darstellen, funktioniert nicht, da dann alle Links in Fußnoten schwarz wären und Besucher nicht mehr wüßten, was ein Link ist und was nicht. Zudem ist ja nicht nur die Farbe, sondern das ganze Verhalten momentan falsch, da die Anwendung mit diesem Fall bislang nicht umgehen kann.

**Comment by vrukavina** [comment]
Vielen Dank für die ausführliche Erklärung. Ich würde sagen, dass es sich nicht lohnt diesen riesigen Aufwand für eine Fussnote zu betreiben. Ich werde die Fussnote, wie hier dargestellt, nach hinten verschieben, und dann ist das Problem bereits gelöst.
