### ISSUE TITLE
Kapitelnummer und Text stimmen nicht überein

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#460]
Ich habe mich durch das TB 1825 geklickt. Dabei ist mir plötzlich aufgefallen, dass ich vom Titel und Text her auf dem Kapitel 30 war, die url aber 29 angezeigt hat. Dann habe ich im Inhaltsverzeichnis das Kap. 29 angewählt und nun zeigt es mit der gleichen url das richtige Kapitel an, s. screenshots:

<img width="1728" alt="Bildschirmfoto 2023-08-07 um 21 44 17" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/4408955b-5f48-4106-be04-a177be4898cc">

<img width="1728" alt="Bildschirmfoto 2023-08-07 um 21 44 36" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/3de805e4-bfde-4362-bdbc-0a801a0ad556">

<img width="1728" alt="Bildschirmfoto 2023-08-07 um 21 48 39" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/ad8d1897-e6f3-413b-92fb-36ae0f2a966c">

**Comment by feggimann** [comment]
Schon wieder passiert, diemal ist die url sogar zwei Kapitel daneben, TB 1825, Kapitel 41/43. Kann es sein, dass das passiert, wenn man zu schnell durch die Kapitel klickt mit vorheriges/nächstes Kapitel, bevor die Seite ganz geladen hat?

**Comment by windauer** [comment]
@feggimann ich kann den Fehler reproduzieren und Dein Eindruck ist richtig, das passiert, wenn man sehr schnell durch die Kapitel klickt (vorwärts wie rückwärts). Lokal auf meinem Rechner, kann ich das nicht reproduzieren, aber auf https://www.johannconradfischer.com/ schon. Hierzu muss ich mal intern diskutieren, was wir da tun können. Eine Möglichkeit wäre ggf. dass "nächstes" und "vorherige" Kapitel nur geklickt werden können, wenn die aktuelle Seite geladen ist, was für Benutzer:innen aber auch nicht wirklich schön ist, wenn man sich schnell zu einem Kapitel vor oder zurück klicken möchte.

**Comment by HelenaSabel** [comment]
@feggimann To fix this out-of-sync issue, the navigation buttons are now hidden until the page loads. As @windauer pointed out above, it might not be the nicest solution for the users who want to browse the chapters quickly. However, the TOC can easily get you from one chapter to the other, so the functionality to quickly get to a different chapter is not lost.

You can see this solution deployed at: https://gf.tei-publisher.com

**Comment by feggimann** [comment]
ok for me, thank you
