### ISSUE TITLE
Pop-up-Anzeige von Familien (actors) fehlerhaft

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#462]
Bei den Akteuren des Typs "Familie" wird der Name (sonst in fetter Schrift) nicht im grünen Pop-up angezeigt.

Beispiel hier: Huntsman
http://gf.tei-publisher.com/de/1845/12
![Bildschirmfoto 2023-08-14 um 11 54 10](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/ffe58427-7170-4c80-ae76-a91d35ef1c94)

**Comment by windauer** [comment]
dies war noch ein Fehler im ODD, ist behoben und wird mit dem nächsten update ausgerollt
