### ISSUE TITLE
Anzeige von Tag in Fussnote fehlerhaft + neue unerwünschte Fussnote

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#463]
In der Fussnote Nr. 14 scheint die Familie Gott als Tag Probleme zu machen. Wenn man auf das getaggt Wort klickt, erscheint kein grünes Pop-up, dafür gibt es aber plötzlich eine eigene, falsche Fussnote (hier im Beispiel Nr. 525).

Tagebuch 1845, Kapitel Low Moor Ironworks, 28. Juli 1845:
http://gf.tei-publisher.com/de/1845/17
![Bildschirmfoto 2023-08-14 um 12 27 47](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/c2ce69c7-12cf-4bc5-b2a8-9323b6fb9496)

xml ist sauber:
![Bildschirmfoto 2023-08-14 um 12 28](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/5d1b010a-9d4f-4b92-b635-e9f75ae4015c)

**Comment by windauer** [comment]
Die Fehler sind beide in reisetagebuch-5.xml und vom gleichen Typ: 

1. in Zeile 149 steht `<orgName ref="gfa-actors-8090">Familie Gott</orgName>`, richtig ist: `<persName ref="gfa-actors-8090">Familie Gott</persName>`, da Familie Gott eine tei:persGroup ist und keine tei:org. 
2. in Zeile 187 steht `<orgName ref="gfa-actors-7729">Huntsmans</orgName>`, genau das gleiche Problem, richtig ist: <persName ref="gfa-actors-7729">Huntsmans</persName>. 

Anschließend werden beide Seiten auch wieder richtig gerendert. 

### Issue 1 
<img width="689" alt="Screenshot 2023-09-19 at 11 26 55" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/514615/644e13af-2ff0-4246-b92f-836d58f59897">

### Issue 2 
<img width="537" alt="Screenshot 2023-09-19 at 11 36 07" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/514615/17d35bbf-1861-4bc2-9281-4ade1732ffbc"> 

<img width="733" alt="Screenshot 2023-09-19 at 11 35 52" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/514615/3ca496ca-8373-400e-8970-31daa305a6c7">

**Comment by vrukavina** [comment]
Alles klar. Ich habe es jetzt richtig getaggt. Danke für den Hinweis!
@NicolauLutz Bitte in der englischen Version korrigieren und dann Issue schliessen. Danke.

**Comment by NicolauLutz** [comment]
TB 5 Englische Version die erste Stelle (<orgName ref="gfa-actors-8090">Familie Gott</orgName>) korrigiert. Die zweite Stelle war schon korrigiert.
