### ISSUE TITLE
Edition: engl. Übersetzung unvollständig

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#464]
Wenn man bei der englischen Version bei "About the edition" auf "Thanks" klickt, dann steht dort der deutsche Titel ("Dank"). Der restliche Text steht aber korrekt auf englisch.
Könnte der Titel bitte auch englisch sein? Also in "Thanks" umgeändert werden? Danke! :)

**Comment by vrukavina** [comment]
![Bildschirmfoto 2023-09-20 um 13 26 37](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/7bae3a45-8f55-4fdc-bb5a-8225fb46cf29)
https://gf.tei-publisher.com/en/content/thank-you

**Comment by windauer** [comment]
@vrukavina die Datei nehmen wir aus diesem Repository: https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/blob/master/src/html-pages/thank-you-en.html und ihr könnt sie selbst, nach eigenen belieben ändern. Wichtig ist nur, dass `<main>` außen drum steht und ihr valides HTML benutzt. In der Datei steht im Moment noch `Dank` und nicht `Thanks` drin.

**Comment by vrukavina** [comment]
Danke für den Hinweis!
@feggimann weisst du wie das geht und könntest das korrigieren? Oder hat das Chris gemacht?

**Comment by windauer** [comment]
@vrukavina wenn Du bei Github angemeldet, solltest Du das gleich im Browser hier: https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/edit/master/src/html-pages/thank-you-en.html ändern können.  Einfach auf den Stift (siehe Screenshot) klicken und Du kannst das direkt im Browser editieren. 

<img width="357" alt="Screenshot 2023-09-20 at 13 57 00" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/514615/5ea8992c-f61e-4a4d-a42e-b78e8b1935a8">

**Comment by vrukavina** [comment]
Und ich dachte, dass wäre eine Zauberei. :) Vielen Dank! Zum Glück lernt man nie aus.
