### ISSUE TITLE
Sortierung der Registerdaten - Sonderbuchstaben

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#465]
Zur Zeit ist es ein wenig verwirrend, wenn man bei der Suche nach der École des Mines in Paris, diese zuunterst findet:
https://johannconradfischer.sources-online.org/de/places/?category=P&search=
![Bildschirmfoto 2023-09-20 um 13 43 23](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/5141575f-cd2d-4a17-8d15-298238bc75c8)
Wäre es möglich Buchstaben mit Diakritika beim 'zugehörigen' Buchstaben einzuordnen? Hier konkret also "é" nach "e" aber vor "f".

**Comment by windauer** [comment]
ich habe dich missverstanden @vrukavina, ich dachte Du hast eine Suche auf der Seite ausgeführt, aber Dir geht es um die Reihenfolge der Sortierung. Ja, Sonderzeichen sind hier im Moment noch ein größeres Problem, da in den verschiedenen Stadtnamen oftmals auch Sonderzeichen vorkommen, die es so im Deutschen / Englischen nicht gibt. Die Sortierung sollte inzwischen deutlich besser sein, aber die Sonderzeichen, sind noch ein Problem.

**Comment by windauer** [comment]
Eigentlich gibt es für so etwas innerhalb einer Sprach eine "Collation" die genau das tut, allerdings haben wir es hier mit Sonderzeichen aus mehreren Sprachen zu tun, z.B. beim `É` und da gibt es dann nur die "Unicode Collation" und deren Reihenfolge ist genau so, wie hier dargestellt (erst A-Z, dann a-z, dann alle Sonderzeichen). Es gibt jetzt 2 Möglichkeiten das zu lösen:

1. Wir (JinnTec) führen ein extra Indexfield für die Sortierung ein und ersetzen alle Sonderzeichen, nach Rücksprache mit Euch in nicht Sonderzeichen (z.B. `Ä` wird `Ae` aber was ist mit `É` vs `È`?) und zum sortieren der Registerdaten benutzen wir dann dieses Field. 
2. Ihr (Eisenbibliothek ggf. zusammen mit @ottosmops ) führt für betroffenen Registerdaten ein weiteres Element mit dem Attribut `type="sort"` ein, also z.B. `<placeName type="sort" xml:lang="de">Eepernay</placeName>` und dort könnt ihr dann bestimmen, wie intern sortiert werden soll, z.B. könnte "É" auch zu "EEE" oder "EAE" ersetzt werden.. die Besucher:innen der Website würden das natürlich niemals sehen.

**Comment by feggimann** [comment]
Ich habe durchgeschaut, was überhaupt an Umlauten/Sonderzeichen/Akzenten vorkommt, und hoffentlich alles erwischt. Wenn ihr folgende Regeln anwendet, dann sollte alles abgedeckt sein:

- ä, ö, Ø, ü behandeln wie ae, oe, ue
- é, è behandeln wie e
- à behandeln wie a
- kein Unterschied ob Klein- oder Grossbuchstabe

@windauer könnt ihr das so umsetzen?

Vieles wird sowieso schon so umgesetzt, z.B. Actor Bréant, Cäsar, DÍaz; oder Gross-/Kleinschreibung bei engl. Keywords
<img width="509" alt="Bildschirmfoto 2023-10-06 um 15 02 16" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/353e30c5-1548-4c6a-9dcf-8fcba007eb07">
<img width="509" alt="Bildschirmfoto 2023-10-06 um 15 02 46" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/41501a3d-3665-4118-810e-d8533ad93d69">
<img width="509" alt="Bildschirmfoto 2023-10-06 um 15 03 18" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/69906c9c-fb6b-4ed5-8ade-58e6909e532a">
<img width="509" alt="Bildschirmfoto 2023-10-06 um 15 05 00" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/336484fb-a764-47f4-89dd-2cb55bd5c6dc">



Bitte dann auch die Umlaute nicht mehr gesondert aufführen im Auswahlaphabet ganz oben unter der Suche - die sind ja in den A, O und U versorgt:
<img width="629" alt="Bildschirmfoto 2023-10-06 um 14 56 40" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/eba3da43-46fb-4be5-99e7-8d011b4fe030">

**Comment by windauer** [comment]
done

**Comment by feggimann** [comment]
Super, vielen Dank!
