### ISSUE TITLE
n attribute missing

### ISSUE THREAD

**Issue by windauer** [GF-Corporate-Archives/gf-johann-conrad-fischer#467]
Auf dem TEI root Element von reisetagebuch-6.xml fehlt noch ein `n="6"` Attribut. Da die Tagebuecher in `src/wip/` im Moment  auf https://gf.tei-publisher.com/de/travels veröffentlicht werden, wäre es gut wenn das fehlende Attribut hinzugefügt wird. Oder sollen die gar nicht mit veröffentlicht werden auf dem Testserver? 

siehe: https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/blob/1dc920b8f8e65bd584f77271b57b447274350c47/src/wip/reisetagebuch-6.xml#L1C52-L1C52

**Comment by feggimann** [comment]
@windauer nein, die TB im wip-Ordner werden nicht veröffentlicht. Für nächstes Update bitte nur die TB in den Ordnern [de](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/tree/master/src/de) und [en](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/tree/master/src/en) berücksichtigen. D.h. TB 1, 2, 3, 4 und 7 in beiden Sprachen. TB 4 in Englisch fehlt noch, sonst sind alle da.

**Comment by feggimann** [comment]
@vrukavina und @NicolauLutz schaut ihr euch bitte das fehlende Attribut in TB 6 an. Danke

**Comment by vrukavina** [comment]
@feggimann Habe das Attribut ergänzt.
