### ISSUE TITLE
grosse Bilderpopups - Legendentext neu

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#468]
Bitte das Textfeld bei den grossen Bilderpopups vereinheitlichen. Immer gleich aufgebaut, egal ob Popup aus Bildergalerie, Bilderspalte in Tagebüchern oder kleinen grünen Popups:

- **Personen**: 1. Zeile: Name / 2. Zeile: Bildlegende (bibl type="image", title...) / 3. Zeile: "weitere Informationen" (Link)
- **Organisationen**: 1. Zeile: Name / 2. Zeile: Bildlegende (bibl type="image", title...) / 3. Zeile: "weitere Informationen" (Link)
- **Familien**: 1. Zeile: Name / 2. Zeile: Bildlegende (bibl type="image", title...) / 3. Zeile: "weitere Informationen" (Link)
- **Orte**: 1. Zeile: Name / 2. Zeile: Bildlegende (bibl type="image", title...) / 3. Zeile: "weitere Informationen" (Link)
- **Begriffe**: 1. Zeile: Label / 2. Zeile: Bildlegende (bibl type="image", title...) / 3. Zeile: "weitere Informationen" (Link)

**Comment by feggimann** [comment]
Link jeweils zu Registereintrag

**Comment by windauer** [comment]
@feggimann meinst Du nur die Vollbildansicht der Bilder oder soll das auch für die kleinen grünen Popups im Text (siehe screenshot) angepasst werden? Gerade bei Popups im Text brechen wir das "weitere Informationen" z.B. nicht um, wenn genug Platz ist, damit die Popups nicht so groß waren. Und wir betreiben da auch Aufwand, um sicherzustellen, dass die immer gut aussehen, z.B. schneiden wir Text ab wenn es mehr als "160" Zeichen sind und fügen ein `[...]` ans Ende. Wenn die Inhalte für Popups und Vollbildansicht genau gleich sein sollen, würde ich das so auch für die Vollbildansicht implementieren. 

 
Popup im Text: <img width="332" alt="Screenshot 2023-10-04 at 10 57 01" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/514615/5826714f-d01e-4853-b541-c800a065ae03">

**Comment by feggimann** [comment]
@windauer nein, ich meine nicht die grünen Popups! Die sind bestens! Sondern die Bildervergrösserungen, die den ganzen Bildschirm füllen. Dort sollte der Text in den grünen Kästchen unten rechts neu und einheitlich sein. D.h. überall folgender Text:
- 1. Zeile: Name (bzw. Label bei Keywords)
- 2. Zeile: Bildlegende (bibl type="image", title...)
- 3. Zeile: "weitere Informationen" (Link zu Registereintrag (aus Galerie und aus Textseite) bzw. zu Anton (aus Registereintrag))

**Bsp. Royal Academy of Arts (Actor ID 8288)**

- Aktuell Text bei Vergrösserung in [Galerie](https://gf.tei-publisher.com/de/gallery/1825): Name (Laufzeit) / erste Zeile Beschreibung / weitere Informationen
- Aktuell Text bei Vergrösserung in Bilderspalte auf [Textseite](https://gf.tei-publisher.com/de/1825/40): Name / weitere Information
- Aktuell Text bei Vergrösserung in [Registereintrag](https://gf.tei-publisher.com/de/names/gfa-actors-8288): Bildlegende / weitere Informationen

Neu: **Royal Academy of Arts** / Ausstellungsraum der Royal Academy of Arts (Stich von Augustus Pugin nach Thomas Rowlandson koloriert von Hill, um 1808–1810) / weitere Informationen
(und bitte Schriftgrösse bei Name/Label nicht ganz so gross wie aktuell)
 
<img width="1840" alt="Bildschirmfoto 2023-10-06 um 13 47 23" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/a89a5388-8220-48d9-a5bc-d7a9346db700">

<img width="1840" alt="Bildschirmfoto 2023-10-06 um 13 44 53" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/bc1402ca-0e2a-47a1-a30b-9ed441167cea">

<img width="1840" alt="Bildschirmfoto 2023-10-06 um 13 57 43" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/fc3288f1-2469-4532-a22e-068876b3c3c6">

**Comment by windauer** [comment]
done

**Comment by feggimann** [comment]
DAnke!
