### ISSUE TITLE
Register - bei allen drei Registerarten Liste einspaltig

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#469]
Bei den Orten erscheint die Registerliste einspaltig, da rechts die Karte platziert ist. Die Namen und Begriffe haben dreispaltige Listen. Wir haben uns bis jetzt nicht wirklich an diese drei Spalten und den horizontalen Verlauf gewöhnt.

Bitte alle drei Register einspaltig darstellen, auch Namen und Begriffe. Es wird zwar z.T. eine lange Liste, aber das ist uns lieber.

Wenn du findest, dass es zu leer ausschaut, dann können wir rechts, wo bei den Orten die Karte steht, bei Namen und Begriffen ein Bild platzieren, z.B. das Bild von den Registerlinks auf der Startseite. Aber muss nicht sein.

**Comment by windauer** [comment]
done

**Comment by feggimann** [comment]
Danke. Kannst du bitte noch die Schrift von "Namen" und "Begriffe" im Bild anpassen? Die hat es nicht übernommen.

<img width="1120" alt="Bildschirmfoto 2023-10-06 um 13 33 00" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/de6f46c7-81d7-475d-8698-1e771db49eaf">
<img width="1120" alt="Bildschirmfoto 2023-10-06 um 13 33 13" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/aed75fee-2d4b-42fb-b84a-352817e26a5b">

vgl. mit Startseite:
<img width="1120" alt="Bildschirmfoto 2023-10-06 um 13 33 35" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/886d05d9-e17c-46ea-9818-5eaeddec934a">

**Comment by windauer** [comment]
done

**Comment by feggimann** [comment]
Danke!
