### ISSUE TITLE
Bilder: Copyright Check Scottish National Galleries

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#47]
Terms of Service: 

"Image licensing terms and conditions

Out of Copyright, National Galleries of Scotland.

This image is available for download under a personal-use license agreement.

You may copy, print, display, and store this image for your personal, non-commercial use.

This includes:

    use in free educational lectures and classes
    use on an individual or group's website discussing the artwork in question (except on websites where the individual is promoting themselves or a group, commercially)
    use on websites that are primarily information led, research orientated and non-commercial, for example Wikipedia
    use on personal social media accounts

    The image must be attributed with the artist, title of the artwork, copyright holder, and 'National Galleries of Scotland'. The image must also be linked back to this artwork page on the National Galleries of Scotland website.

    If the above license does not cover your personal use requirements or if you require a commercial license [please fill in an online application](https://www.nationalgalleries.org/picture-library)."

**Comment by feggimann** [comment]
Copyright ist hier geregelt: https://www.nationalgalleries.org/copyright-image-licensing

Sofern Copyright expired, sind sie unter CC-BY-NC 3.0 verwendbar. Es ist sehr deutlich unter dem Bild ausgewiesen. Ich habe vier GFD 1-Einträge gesehen, dort ist alles ok.

<img width="814" alt="Bildschirmfoto 2023-03-10 um 16 03 11" src="https://user-images.githubusercontent.com/92036071/224349858-4a27ee02-5f8f-4b88-89d7-53c98c91f18e.png">
