### ISSUE TITLE
Fehlerhafte Darstellung in englischer Version: Akteure

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#471]
In der en Version des TB von 1825 werden Pop-ups von gewissen Akteuren fehlerhaft angezeigt und rechts in der Spalte unter "Namen" nicht aufgewiesen.
![Bildschirmfoto 2023-09-25 um 16 58 27](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/e2e8dc80-7045-45de-90f6-1c8e1346a681)

Der Tag (hier Bsp. von Beckh-Widmanstätten, Alois (1754–1849)) scheint mir aber korrekt zu sein.
![Bildschirmfoto 2023-09-25 um 17 00 33](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/e7a81e66-80f3-4e97-ac4c-0f2698e48322)

**Comment by vrukavina** [comment]
Das gleiche Problem scheint auch diverse Orte zu betreffen. Hier Bsp. Trieste:
![Bildschirmfoto 2023-09-25 um 17 08 56](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/cd5ad86b-b7e6-46be-ba3c-4987991408db)

**Comment by windauer** [comment]
für [`gfa-actors-7966`](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/blob/master/src/register/archives-actors-tei.xml#L16231) und [`gfa-places-1819`](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/blob/master/src/register/archives-places-tei.xml#L20524) fehlen jeweils die Übersetzungen (`xml:lang="en"`), deswegen wird dort nichts angezeigt.
