### ISSUE TITLE
Tagebücher für nächste Veröffentlichung

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#473]
Die TB im wip-Ordner werden nicht veröffentlicht. 

Für nächstes Update des Liveservers bitte nur die TB in den Ordnern [de](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/tree/master/src/de) und [en](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/tree/master/src/en) berücksichtigen. D.h. TB 1, 2, 3, 4 und 7 in beiden Sprachen.

Die TB 5 und 6 werden in beiden Sprachen erst später beim allerletzten Update im Liveserver veröffentlicht.

Bitte auch auf dem Testserver so darstellen.

**Comment by windauer** [comment]
done, wird bis heute EOB live gestellt.

**Comment by feggimann** [comment]
super, danke
