### ISSUE TITLE
Detailansicht Register Places: Karte fehlt

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#474]
In der Detailansicht der Places wird die Karte nicht mehr dargestellt

<img width="425" alt="Bildschirmfoto 2023-10-06 um 15 35 47" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/6508e62a-fab8-47fb-b026-01e6967247cb">
<img width="1325" alt="Bildschirmfoto 2023-10-06 um 15 36 02" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/8c036fb3-322d-41f3-a759-cc43840523c9">
<img width="1325" alt="Bildschirmfoto 2023-10-06 um 15 36 12" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/a215374f-971e-4b16-a822-7d00300fe425">

**Comment by windauer** [comment]
done

**Comment by feggimann** [comment]
Danke
