### ISSUE TITLE
Registerliste: Darstellung mehrzeilige Einträge

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#475]
Zwei Fragen zur Darstellung der mehrzeiligen Listeneinträge im Register:
- ist es möglich, einen grössren Abstand zwischen den Zeilen zu machen? bei mehrzeiligen Einträgen ist jetzt nicht klar was zu was gehört:
<img width="664" alt="Bildschirmfoto 2023-10-06 um 15 38 10" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/23013064-3bb1-47af-93bf-ce5d0d5c5c95">

- bei mehrzeiligen Ortseinträgen steht das Kartensymbol in der zweiten Zeile. Das verwirrt beim Lesen. sollte m.E. am Anfang des Listeneintrags sein:
<img width="664" alt="Bildschirmfoto 2023-10-06 um 15 37 51" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/f15c6b3d-ff79-43f2-a633-7f6ad4453d95">

**Comment by windauer** [comment]
@feggimann ich habe das jetzt so lösen können, dass alles immer einzeilig ist, was m.E. deutlich schön aussieht. Falls nicht genug Platz ist (wenn Du das Fenster klein schiebst), dann muss halt nach rechts gescrollt werden.. finde ich persönlich aber schöner. Bei den Orten war es etwas schwieriger, da musste ich zum Schluss das "map" icon von hinten ans Ende des Texts nehmen, dann ging es auch dort mit einspaltig: 

* [Begriff](https://gf.tei-publisher.com/de/keywords/?category=%5BA-Z%5D&search=)
* [Orte](https://gf.tei-publisher.com/de/places/?category=%5BA-Z%5D&search=)

Ist Dir das so recht?

**Comment by feggimann** [comment]
Finde ich super, vielen Dank!
