### ISSUE TITLE
nächstes Liveupdate: Kontrolle Registereinträge und url-Abstimmung de/en

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#476]
Wir sind so weit für das nächste Liveupdate mit den kompletten englischen und deutschen TB 1, 2, 3, 4, 7.

Ich will nur zuvor gerne durchchecken, ob wirklich alle darin vorhandenen IDs erfasst und übersetzt sind, oder ob uns etwas durch die Latten ist. 

@windauer Kannst du mir bitte alle Registerdaten herausfiltern, die aktuell in diesen fünf xml-Dateien de und en vorkommen? So wie es am einfachsten für dich geht, entweder einfach eine Liste der IDs oder grad die ganzen Einträge. Und auch egal ob de/en zusammen oder getrennt.

Fast alle offenen Issues können wir auch nachher fertig lösen bis zum finalen Liveupdate. Ausser die de/en url-Abstimmung: Da wir jetzt die gleichen en und de TB veröffentlichen, sollte die Umschaltung de-en auf den einzelnen Seiten funktionieren. Könnt ihr das Issue #446  vorziehen?

**Comment by windauer** [comment]
@feggimann die gewünschten Registerdaten kannst Du hier im Git Repository sehen: https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/tree/master/src/register - die entsprechen genau Deinen Kriterien. 

Wir können gerne #446  vorziehen, gleichzeitig ist dies aber auch das komplexeste Ticket und ich kann Dir noch nicht sagen, wie lange es dauern wird, selbiges zu implementieren. // cc @wolfgangmm

**Comment by windauer** [comment]
@feggimann dieses Ticket kann dann ja zu und ich priorisiere #446 hoch, ok?

**Comment by feggimann** [comment]
ja, danke, alles bestens
