### ISSUE TITLE
Querverlinkungen zu anderen Tagebüchern

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#477]
Links zu anderen Tagebüchern im Text sind auch einfach grün und nicht zu unterscheiden von getaggten Registerdaten oder Datumsangaben. Wenn man drauf klickt, kommt man aber logischerweise auf ein anderes Tagebuch, was etwas verwirren kann.

Wäre es möglich, das mit einem Popup zu lösen wie etwa bei den vertikalen Seitenstrichen, die extern zu e-rara führen? z.B. mit der Angabe "Tagebuch xy, Kapitel xy" und dies dann aber unterstrichen, damit Link sichtbar und nicht das Symbol für externer Link, da ja innerhalb der Edition.

Bsp. TB 1825, Kap. 2, letzter Abschnitt:
"Tagebuch meiner frühern Reise nach England" > Popup mit Link "Tagebuch 1814"/"Journal 1814"

<img width="931" alt="Bildschirmfoto 2023-10-06 um 16 05 26" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/e9338e69-9cf8-44a9-8a7e-eba27df977bf">

<img width="799" alt="Bildschirmfoto 2023-10-06 um 16 02 50" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/32b2670d-f65a-4e25-9804-f153d2584419">

Bsp. TB 1851, Kap. 17, Fussnote:
"Vergleiche Tagebuch 1825-1827, S. 32..." > Popup mit Link "Tagebuch 1825-1827, Kapitel 7"/"Journal 1825-1827, Chapter 7"

<img width="931" alt="Bildschirmfoto 2023-10-06 um 16 08 26" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/f78c2f22-3df9-41fe-abba-ce61b388908e">

<img width="1277" alt="Bildschirmfoto 2023-10-06 um 16 09 24" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/6f8ebd02-6a83-43ad-80bb-5beb19832b09">

**Comment by windauer** [comment]
done

**Comment by feggimann** [comment]
Super, danke
