### ISSUE TITLE
Externe Links: Symbol Grösse

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#478]
Das Symbol für externe Links ist jetzt unterschiedlich gross dargestellt:
- In Detailansicht Register bei Bildinformation unter Bild
- In Popup in Text mit Link zu e-rara

Bitte das Symbol bei e-rara kleiner darstellen wie bei den Bildinformationen:

<img width="616" alt="Bildschirmfoto 2023-10-06 um 16 13 36" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/0f7f0803-990f-4442-b5ce-f4d7eef7ac4e">
<img width="616" alt="Bildschirmfoto 2023-10-06 um 16 14 06" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/713b068e-2d1c-4e30-b8ea-e6e81d37b180">

**Comment by windauer** [comment]
done

**Comment by feggimann** [comment]
danke
