### ISSUE TITLE
Metatexte

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#479]
Aktualisierung Metatexte vor nächstem Update

**Comment by feggimann** [comment]
@windauer Ich habe heute noch die html-Files in [html-pages](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/tree/master/src/html-pages) und ein xml-File in [i18n](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/tree/master/src/i18n) aktualisiert.

Jetzt ist alles bereit fürs Liveupdate. Keine weiteren Änderungen. Ist das immer noch ok am Freitag?

**Comment by windauer** [comment]
@feggimann wegen mir können wir gerne Morgen live gehen. Ich habe Vormittags und am Nachmittag jeweils einen Termin, würde das dann also so gegen Mittag herum auf johannconradfischer.com veröffentlichen, ist Dir das recht? Soll ich dann einfach veröffentlichen wenn ich soweit bin, oder noch auf ein Go oder ähnliches von Dir warten? 

Ich werde heute noch an Tickets arbeiten, aber ich tendiere dazu, diese Änderungen dann nicht mehr mit einfließen zu lassen in das update Morgen, weil die Gefahr zu groß ist, einen Fehler zu machen, den zwischen heute Abend und Morgen livegang niemand mehr mitbekommt. Wenn das auch ok für Dich ist, würde ich heute den Livegang schon vorbereiten, damit ich ihn dann Morgen schneller durchführen kann. Ich werde trotzdem noch weiter an Tickets arbeiten, aber die gehen dann eben nicht mehr ins Release für Morgen.

**Comment by windauer** [comment]
ach so, ich habe so eben einen Livegang auf gf.tei-publisher.com gemacht, alle Änderungen sind dort jetzt also live und die Registerdaten in diesem Gitrepo wurden auch aktualisiert, diese ticket is somit aus meiner Sicht `done`.

**Comment by feggimann** [comment]
Danke, ich schaue noch genauer drüber. Auf den ersten Blick alles gut.
