### ISSUE TITLE
Recherche, Fenn in JCF 1851

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#48]
Ist Fischer in 1851 Samuel Fenn oder Josef Fenn begegnet?

Siehe auch [Fenn (Familie)](https://archives.georgfischer.com/actors/7546)

**Comment by vrukavina** [comment]
Ich dachte es sein Samuel gewesen, aber du hast Recht, es kann auch ein anderer Fenn gewesen sein - Daniel?
Im TB steht nämlich: 

> _Da es kaum 1 Uhr war, und erst nach 4 Uhr gespeisst wird, ging ich nach Newgatestreet, um Herrn Fenn Ironmonger, mit dem ich schon im Jahr 1794, als ich damals bei Mr. Rhé, Mechaniker in London, arbeitete, bekannt wurde, zu besuchen, traf ihn aber nicht auf dem Comptoir an, und kaufte noch zerschiedenes für meine Garderobe ein, was ich nicht von zu Hause mitschleppen wollte._

**Comment by NicolauLutz** [comment]
Ja, entweder Daniel oder Samuel, wobei Daniel Fenn um 1851 entweder sehr alt, oder schon verschieden war. Samuel muss wohl Fischer's Alter gehabt haben. Aber so wie es aussieht, ist nicht ganz klar, wen er genau mit "Herrn Fenn" meint...

Vieleicht kann man hier mit einer <note> arbeiten?

**Comment by NicolauLutz** [comment]
* "<note>"

**Comment by NicolauLutz** [comment]
* < note >

**Comment by vrukavina** [comment]
Sehe ich auch so. Wir können ja den Eintrag zu Samuel erstellen, und zusätzlich mit einer Notiz arbeiten.
