### ISSUE TITLE
TB 1825-1827, FN 2: Tippfehler

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#480]
Tippfehler "Buchhanldung" in FN 2, TB 1825-1827 de und en.
Bitte beheben.

![grafik](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/753805bc-b03f-41f6-98b7-5e8fd6bf41d7)

**Comment by vrukavina** [comment]
Danke! Habe ich in beiden Versionen korrigiert.
