### ISSUE TITLE
Bereinigung unterschiedliche Anführungs- und Schlusszeichen

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#483]
Das en TB 2 hat als einziges TB eine andere Art von Anführungs- und Schlusszeichen (leicht geschwungen). In der Edition fällt es kaum auf, aber im xml sieht man den Unterschied deutlich.
Beispiel:
![Bildschirmfoto 2023-10-10 um 11 11 34](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/a56d77cf-6020-4eff-855f-121dcddfee2e)
![Bildschirmfoto 2023-10-10 um 11 12](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/78f59d2e-b1f4-4cdb-83cd-e4f0f0333cec)

In den anderen sind die Zeichen 'gerade':
Bsp. TB 4:
![Bildschirmfoto 2023-10-10 um 11 15 27](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/67802683-57a9-477a-8a6c-796acb4070b6)
![Bildschirmfoto 2023-10-10 um 11 16 54](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/282ba08c-0730-409f-aa16-447d3f8ba9ea)

Haben wir die Auswahl irgendwo einmal festgehalten?

**Comment by feggimann** [comment]
Es ist nicht so einfach wie dargestellt. Es kommen diverse Anführungszeichen in den verschiedenen TB vor. Ich versuche grad mit Hilfe von Flavia eine Übersicht zu erhalten. Welche englischen Anführungszeichen wir verwenden sollten bespreche ich morgen mit Christopher. Ich melde mich danach wieder.

**Comment by feggimann** [comment]
Folgende Anführungszeichen können in den **deutschen** Versionen schon bereinigt werden:

TB 1814, Z. 294 - Schlusszeichen falsch:
«wenn Ihr Sack in der Kutsche war, so müssen Sie ihn heute Abend oder morgen früh bekommen,”

TB 1825, Z. 1862 - Schlusszeichen falsch:
«Die Schweizer Kantone sind sehr zu tadeln, dass sie gänzlich vernachlässigen, den Schnee wegzukehren, sondern ihn liegen lassen, bis die Sonne oder der Regen ihn schmilzt."

TB 1825-1827, Z. 293 – Anführungszeichen verkehrt:
»It turn’d about bis brains»

TB 1851, Z. 202 – Schlusszeichen fehlt:
«da möchte ich wohnen! in London bleibe ich nicht!

**Comment by feggimann** [comment]
Zudem bitte in den **deutschen** Versionen die Apostrophzeichen bereinigen. 
Es sollte das geschwungene Zeichen für Apostroph verwendet werden: ’
Teilweise ist aber das gerade Zeichen gesetzt: '

TB 1814 - Total 19 Apostrophzeichen, davon 17 korrekt ’ und 2 gerade ', die ersetzt werden sollten.
TB 1825 - Total 5 Apostrophzeichen, davon 4 korrekt ’ und 1 gerade ', das ersetzt werden sollte.
TB 1825-1827 - Total 18 Apostrophzeichen, davon 15 korrekt ’ und 3 gerade ', die ersetzt werden sollten.
TB 1851 - Total 12 Apostrophzeichen, davon 11 korrekt ’ und 1 gerade ', das ersetzt werden sollte.

**Comment by feggimann** [comment]
Wir verwenden falls möglich die “englischen geschwungenen” Anführungszeichen und nicht die "geraden". Ich schaue am Montag mit Andreas ob wir das automatisiert machen können.

**Comment by vrukavina** [comment]
> ’

Die **deutschen** Tagebücher 1814, 1825-1827, 1851 wurden bearbeitet.

**Comment by NicolauLutz** [comment]
TB EN 1794: «» ersetzt durch “”.

Aber es gibt es Instanzen, in denen möglicherweise einfache Anführungszeichen stehen sollten: 

Beispiel: 

TB 1794 EN p. XV: “Dresden Buckets”

TB 1794 EN p. XVI: “Royal Sow Garden”

TB 1794 EN p. 53: long ”spiral staircase”

**Comment by feggimann** [comment]
> TB EN 1794: «» ersetzt durch “”.
> 
> Aber es gibt es Instanzen, in denen möglicherweise einfache Anführungszeichen stehen sollten:
> 
> Beispiel:
> 
> TB 1794 EN p. XV: “Dresden Buckets”
> 
> TB 1794 EN p. XVI: “Royal Sow Garden”
> 
> TB 1794 EN p. 53: long “spiral staircase”

Die drei Beispiele machen für mich auch mehr Sinn mit einfachen Anführungszeichen. @NicolauLutz kannst du das ändern? Danke

**Comment by NicolauLutz** [comment]
Wurde angepasst.

**Comment by NicolauLutz** [comment]
Zur Frage der Prime-Zeichen: Ich habe alle deutschen TBs durchsucht nach folgenden ‘strings’ und es ist nichts herausgekommen:

- «′» : (Hochstrich)
- «″» : (Zweistrich)
- « " » : (Anführungszeichen gerade mit Leerschlägen)
- «>"<» : (Anführungszeichen gerade mit Vergleichszeichen)

**Comment by feggimann** [comment]
bitte weitere Stelle korrigieren:

TB 1794 en, Fussnote “only” in geschwungene Anführungszeichen setzen:
<note>The tower is actually 35 metres or 115 feet high. Either Fischer overestimated the height or this is a printing error, which would explain the word "only".</note>

**Comment by feggimann** [comment]
> bitte weitere Stelle korrigieren:
> 
> TB 1794 en, Fussnote “only” in geschwungene Anführungszeichen setzen: The tower is actually 35 metres or 115 feet high. Either Fischer overestimated the height or this is a printing error, which would explain the word "only".

Zudem ist diese FN am falschen Ort. Sie sollte am Ende des Satzes stehen.

**Comment by feggimann** [comment]
weitere Stelle:

TB 1825 en, Zitat mit richtigem Anführungszeichen, aber falschem Schlusszeichen:
To which I replied: “And i shuld be glad to have a few lines from You containing Your opinion about it".

**Comment by feggimann** [comment]
weitere Stelle:

TB 1851 en, richtige Anführungszeichen, aber falsche Schlusszeichen:
Their patented so-called “<term ref="gfa-keywords-8481">Patenttoughened</term>"

**Comment by NicolauLutz** [comment]
Alle Stellen (1794, 1825, 1851) korrigiert

**Comment by vrukavina** [comment]
> Wir verwenden falls möglich die “englischen geschwungenen” Anführungszeichen und nicht die "geraden". Ich schaue am Montag mit Andreas ob wir das automatisiert machen können.

@feggimann @NicolauLutz Wurde in allen en Tagebüchern (auch TB 5) so ersetzt. (Stand 17.10)

**Comment by feggimann** [comment]
Alle Anführungszeichen bereinigt. Somit kann das Issue geschlossen werden.
