### ISSUE TITLE
englische Tagebücher: Querverlinkungen

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#484]
Bitte die englischen Tagebücher überprüfen nach Querverlinkungen zu anderen Tagebüchern. Bei der ersten Liveschaltung waren nur Querlinks zwischen 1794 und 1851 aktiv, nun sind aber drei weitere TB dazugekommen.

Bsp. TB 1851, Kap. 17, Fussnote: Link zu TB 1825-1827 ist nur im deutschen TB getaggt, im englischen nicht:
<img width="616" alt="Bildschirmfoto 2023-10-10 um 20 52 05" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/6eacabe4-e11c-49e8-b621-cf01056556d7">
<img width="616" alt="Bildschirmfoto 2023-10-10 um 20 52 21" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/ebe31d9e-31b4-4e77-aab1-d948391f87e9">

Vermutlich müssen die deutschen TB nach dem entsprechenden Code abgesucht und dann mit den englischen verglichen werden.

**Comment by vrukavina** [comment]
Wurde erledigt. Nun sollten in den de und en Versionen alle Querverlinkungen zu den TB 1,2,3,4 und 7 kodiert sein.
