### ISSUE TITLE
Keyword 8636 (Tigel) in 8532 (Tiegel) verschieben

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#485]
Das Keyword 8636 (Tigel) ist einmal getaggt in 1825. Bitte umtaggen zu Keyword 8532 (Tiegel) und dann 8636 löschen.

**Comment by vrukavina** [comment]
WIrklich ein unschöner Fehler, der sich hier reingeschlichen hat. Danke fürs Finden! Habe das xml angepasst und die ID in Anton gelöscht.
