### ISSUE TITLE
TB 1814, Kap. 4 Keyword de und en falsch getaggt

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#487]
Im ersten Abschnitt ist das Wort "Pässe" mit "Reichsgeld" (ID 9722) statt "Reisepapiere" (ID 9772) getaggt. Bitte korrigieren.

![grafik](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/2825b2e8-a059-4c41-bcbd-28be461d6887)

**Comment by vrukavina** [comment]
Danke! Wurde umgetaggt.
