### ISSUE TITLE
Fehler in der Formel 

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#488]
Auf dem Testserver TB 1814 EN/DE Kapitel 27 wird die Formel nicht rightig angezeigt, es stimmt wahrscheinlich etwas in der Kodierung nicht aber ich weiss nicht was es ist: 

<img width="826" alt="Screen Shot 2023-10-13 at 12 01 56" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92101460/c58cba8a-3d4d-4c33-9481-02dfa995da2a">

<img width="1193" alt="Screen Shot 2023-10-13 at 11 57 25" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92101460/f5a6f12b-c313-4d06-bb47-641cf4b19697">

<img width="628" alt="Screen Shot 2023-10-13 at 11 57 02" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92101460/821ab016-1775-4660-83bc-44ec085656e9">

**Comment by NicolauLutz** [comment]
Gemeint ist das "1/4" im ersten Bruch, wiedergegeben als "14". Das 120 am Ende der Gleichung habe ich korrigiert.

**Comment by ottosmops** [comment]
#122 
<formula rend="inline" notation="tex">$\frac{1^2}{(1/4)^2 }\times \frac{15}{2}\times50=120\times50=6000$ 
</formula> Pfund oder 60 Zentner

```
<formula rend="inline" notation="tex">$\frac{1^2}{(1/4)^2 }\times \frac{15}{2}\times50=120\times50=6000$ 
</formula>
```

**Comment by ottosmops** [comment]
Ah jetzt: @windauer das muss demnach was im Publisher sein, denn hier wird die Formel korrekt dargestellt oder?

**Comment by NicolauLutz** [comment]
Könnte man einfach das "¼" Unicode zeichen benutzen? Wäre das eine Lösung?

**Comment by windauer** [comment]
@NicolauLutz , @ottosmops wo genau wird das denn falsch angezeigt? Ich habe gerade mit Firefox sowohl local, als auch auf der [neuen Version](https://gf.tei-publisher.com/en/1814/27) und der prod. [live version](https://www.johannconradfischer.com/de/1814/27) geschaut, und überall sieht das m.E. richtig aus: 

<img width="738" alt="Screenshot 2023-10-18 at 11 28 13" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/514615/c8d8d41f-a845-420a-b80b-d6c1e3847ae1">

Könnt ihr mir bitte eine URL zuschicken, wo ich das falsche Rendering sehen kann?

**Comment by windauer** [comment]
Firefox and Safari look both fine as well - I would have been rather surprised if not but wanted to be sure.

**Comment by feggimann** [comment]
Schaut auch bei mir in Firefox und Safari korrekt aus. Ich schliesse das Issue demnach.
