### ISSUE TITLE
Institutionen für Dankesliste in Edition finales Update

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#489]
Bitte hier wieder Institutionen aus den GFD sammeln bis zum finalen Update. Bitte nur Institutionen, die in der [Dankesliste](https://johannconradfischer.com/de/content/thank-you) noch nicht vorkommen.

**Comment by niklausmueller** [comment]
Mit den Sachschlagwort-Bildern, die ich hinzugefügt habe, und die Publikationen betreffen, kämen die untenstehenden Institutionen neu zur Dankesliste dazu. Die drei letzten haben einen etwas anderen Status und wir müssen allenfalls entscheiden, ob sie mit in die Dankesliste gehören.

Badische Landesbibliothek, Karlsruhe
British Newspaper Archive, London
Librairie Galignani, Paris
Penn Libraries, Philadelphia (PA)

Nur als digitalisierende Institution:

Google Books, Mountain View (CA)
Internet Archive, San Francisco

Nur als Aufbewahrungsort für die Digitalisate, d. h. weder als digitalisierende Institution noch als Aufbewahrungsort der physischen Originale:

Hathi Trust, Ann Arbor

**Comment by vrukavina** [comment]
The Finnish National Gallery, Helsinki

**Comment by feggimann** [comment]
Hier alle zusammen für das final Update:

- Badische Landesbibliothek, Karlsruhe
- British Newspaper Archive, London
- Eremitage, Sankt Petersburg
- Finnish National Gallery, Helsinki
- Gemäldegalerie der Staatlichen Museen zu Berlin
- Geographicus Rare Antique Maps, New York NY
- Hathi Trust, Ann Arbor MI
- Koninklijk Museum voor Schone Kunsten (KMSKA), Antwerpen
- Librairie Galignani, Paris
- Museo del Prado, Madrid
- Museu do Ipiranga, São Paulo
- National Library of Medicine, Bethesda MD
- Neue Pinakothek, München
- Penn Libraries, Philadelphia PA
- University of Exeter

**Comment by feggimann** [comment]
neu:
- Sheffield History Forum, Sheffield

**Comment by feggimann** [comment]
alles eingefügt
