### ISSUE TITLE
Go Live Milestone 3

### ISSUE THREAD

**Issue by windauer** [GF-Corporate-Archives/gf-johann-conrad-fischer#490]
Go live on Friday, October 20 around lunch time if not agreed differently between @feggimann and @windauer

**Comment by feggimann** [comment]
Perfekt. Das ist bestens für mich. Vielen Dank.

**Comment by windauer** [comment]
@feggimann ich beginne jetzt mit dem Go-Live und werde johannconradfischer.com demnächst offline nehmen. Ich sage hier Bescheid, wenn der go live von Milestone-3 fertig ist.

**Comment by windauer** [comment]
https://www.johannconradfischer.com/ ist down für das Update

**Comment by windauer** [comment]
Milestone 3 ist live auf https://www.johannconradfischer.com/ - bitte denkt dran, dass es ggf. einen "Shift Reload" Eures Browser braucht oder ihr den Browser einmal kurz schließen solltet, damit sichergestellt ist, dass er nicht JavaScript oder CSS cached (bei mir war das z.B. bei der Sprachumschaltung der Fall).

**Comment by windauer** [comment]
done :)

**Comment by feggimann** [comment]
Grossartig! Bei mir klappt's prima :-)
Vielen Dank!
Milestone 3 kann also auch geschlossen werden!
