### ISSUE TITLE
Fehlermeldung Dankesseite

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#491]
Wir haben uns noch durch die Edition geklickt. Es scheint alles zu funktionieren, ausser die Seite Über uns/Dank. Da kommt sowohl in der deutschen wie englischen Version eine Fehlermeldung:

http://gf.tei-publisher.com/de/content/thank-you
![grafik](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/13a51295-f8c2-4970-879f-920f3a5b78d8)

kannst du dir das bitte noch anschauen?

**Comment by windauer** [comment]
das liegt daran, dass in den HTML Seiten ein `&` verwendet wurde, welches nicht encodiert wurde. In HTML muss ein `&` immer als `&amp;` geschrieben werden. Ich habe das gefixt und werde später noch eine neue Version ausrollen.

**Comment by windauer** [comment]
Danke sagen tut wieder ;) https://gf.tei-publisher.com/de/content/thank-you

**Comment by feggimann** [comment]
Habe es gesehen, danke. Sorry, das war mein Fehler, habe nicht mehr an die Sonderzeichen gedacht.
