### ISSUE TITLE
X bei Bildansicht fehlt (wieder)

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#492]
Wenn man die Bilder auf der Textseite in der Bildspalte anklickt und es gross erscheint, muss man wieder irgendwo neben das Bild klicken, um zum Text zurückzugelangen. Vor ein paar Wochen wurde ein "X" zum Schliessen programmiert. Nun ist es aber wieder weg. Kann das bitte wieder eingeführt werden? Danke!
![Bildschirmfoto 2023-10-20 um 08 40 27](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/defd1f94-758e-4ce0-9c4e-2cd59fac17ef)

**Comment by vrukavina** [comment]
Siehe auch geschlossenens Issue #456

**Comment by feggimann** [comment]
@vrukavina vermutlich meintest du, dass die Liveversion schon heute morgen upgedated ist, das erfolgt aber erst heute Mittag. 

@windauer auf dem Testserver erscheinen bei mir überall die X für das Schliessen des Fensters. Es ist also alles ok und kann so live gehen.
