### ISSUE TITLE
TB 1814: John Dollond / Peter Dollond

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#493]
Diese Verlinkung in TB 1814 ist nicht korrekt, es sollte der Sohn Peter (ID 7545) sein. Damit John Dollond (ID 298) trotzdem in der Edition "drin" bleibt, müsste man eine Fussnote ergänzen.

![grafik](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/fd02eb4a-f54d-4557-982f-0db913d6ee19)

**Comment by NicolauLutz** [comment]
Vorschlag für Fussnote bei «... besuchte den berühmten Optiker Dollond…»: "Peter Dollond war der Sohn des bekannten Optikers John Dollond."

Ursprünglich wurde der Vater aufgenommen in der Annahme, dass Fischer ähnlich wie bei Wedgwood oder Watt den Sohn mit dem Vater verwechselte und das "berühmt" sich auf den Vater bezog. Aber da der Vater bereits um 1761 starb, kann wohl angenommen werden, dass Fischer den Sohn selber meinte. Aus diesem Grund könnte man auch darüber nachdenken, den Vater ganz aus der Edition zu lassen.

**Comment by vrukavina** [comment]
Ich habe "Dollond" von John auf den Sohn Peter umgetaggt und die Fussnote (bereits existierende) um den Vorschlag von Nicolau ergänzt und dort den Vater getaggt. Beide Dollonds bleiben somit bei uns verewigt, ganz wie die Watts und Boultons.
