### ISSUE TITLE
TB 1851: Leverian Museum Verweis auf TB 1794

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#494]
JCF beschreibt im TB 1851, was er vor 50 Jahren im Leverian Museum gesehen hat. Da das Museum 1806 geschlossen wurde, muss es auf der Reise 1794 gewesen sein:
- Querverlinkung von hier zum TB 1794?
- Erwähnung bei Eintrag zu Leverian Museum (Place ID 1662), dass JCF es auf der Reise 1794 besucht hat?

[https://johannconradfischer.com/de/1851/21](https://johannconradfischer.com/de/1851/21)
![grafik](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/0d791892-e982-4371-8634-5a1912f36016)

**Comment by NicolauLutz** [comment]
Das würde Sinn machen. 

Habe den Querverweis im TB 1851 en und de ergänzt.

**Comment by vrukavina** [comment]
Man könnte auch noch genauer auf den Tagebucheintrag mit dem Titel "Schweden und London, April und Mari 1794" verweisen, resp. die Querverlinkung auf 1794/7 setzen, da nur dieser Abschnitt von seinem Aufenthalt in London berichtet. Den Beschrieb habe ich in Anton mit dem Vorschlag von Nicolau ergänzt, und, zusammen mit einer englischen Übersetzung, auf meine Liste mit den geänderten Registereinträgen gesetzt.
