### ISSUE TITLE
Fehlendes Textelement in der deutschen Version des TB4

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#498]
Fehlendes Textelement (nur) in der deutschen Version von TB 4.
Zwischen Physik und Chemie fehlt ein «und».

https://johannconradfischer.com/de/1825-1827/13
![image](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/06e6db2b-9c16-4055-9d97-6a749eade4e1)

Im xml steht es aber:
![image](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/3bb7d405-8cfb-43b9-a873-d28818ba4141)

**Comment by HelenaSabel** [comment]
Done! See live version at: https://gf.tei-publisher.com/de/1825-1827/13

**Comment by vrukavina** [comment]
Great! Thank you.
