### ISSUE TITLE
"Vorwort" - Titel im Text löschen

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#500]
![Bildschirmfoto 2023-12-04 um 08 25 12](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/d60a70e2-1c0f-4bbe-a8f2-904918eb6fb8)
https://gf.tei-publisher.com/de/1846/2
Das 'zweite' "Vorwort" kann aus dem Fliesstext gelöscht werden, wenn es schon als Titel dort steht.

**Comment by NicolauLutz** [comment]
Gelöscht.
