### ISSUE TITLE
TB 1846: Fischers Fussnote entsprechend kodieren

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#501]
![Screenshot 2023-12-04 091703](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/afb17f98-b011-422e-8387-50b19e47bba6)
Im 3. Kapitel hat JCF eine Fussnote gesetzt (mit *). Diese wurde aber im Text in einer Klammer wiedergegeben, was falsch ist.

Die Fussnote muss mit note, typ= original, place = bottom kodiert werden. Im TB3 kommt ein solcher Fall schon vor (siehe: https://gf.tei-publisher.com/de/1825/41?action=search).

**Comment by NicolauLutz** [comment]
Verbessert.
