### ISSUE TITLE
TB 1846: "bis" bei Datumsangaben in Kapitelnamen 

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#502]
Im TB 1846 und 1845 wird das "bis" bei Datumsangaben in den Kapitelnamen ausgeschrieben. 

![Screenshot 2023-12-04 093202](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/f2c6d96b-44df-4394-9dfb-98ef9ae82ab8)

Bei den anderen TB haben wir dafür einen Bindestrich (–) verwendet. Bsp. TB 1814:

![Screenshot 2023-12-04 093535](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/c92e3544-9b3f-42df-a82c-4ff6297772d1)

@feggimann Wollen wir dies noch vereinheitlichen? Und immer den Bindestrich verwenden?

**Comment by feggimann** [comment]
@NicolauLutz Ja, bitte vereinheitlichen:
- bei zwei Tagen mit Schrägstrich, z.B. "9./10. Oktober"
- bei mehr Tagen langer Bindestrich, z.B. "9.–11. April"

**Comment by NicolauLutz** [comment]
Wurde verbessert.
