### ISSUE TITLE
TB 1846: Währungen/Einheiten

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#503]
Beispielsweise hier die 1 und 7 nicht mittaggen.
![Screenshot 2023-12-04 094501](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/b5a27e0a-d8eb-4539-a1f7-6afc078c8dff)

Zusätzlich hier noch: Sh. war JCFs Abkürzung für Schilling. Das muss noch getaggt werden.

**Comment by vrukavina** [comment]
Im Kapitel 8: 
![image](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/3397dfc4-818d-490b-b4b1-5dfddead137e)

Schilling umtaggen: Taggen mit Schilling, nicht Pfund Sterling.

**Comment by NicolauLutz** [comment]
Verbessert und Kontrolliert.
