### ISSUE TITLE
Search in Places not correct

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#505]
Search for "schaff" gives just 3 results:

![grafik](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/b886991f-3bda-4863-bd3c-6dabe0522636)

But there should be 7:

![grafik](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/f454969e-5e24-41c7-8d0e-9ebb65a91a8f)

Same for "London2 - only 10 results:

![grafik](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/468e5f6e-2c96-48fb-9b54-2c79ddc50526)

While the list under "L" ist far longer...

![grafik](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/513ea50f-ed74-4495-a68e-b6bf847945fd)

**Comment by HelenaSabel** [comment]
Done and deployed (see https://gf.tei-publisher.com/de/places/?category=A&search=schaff)

**Comment by feggimann** [comment]
now it looks fine, thank you
