### ISSUE TITLE
TB 1846: Taggen des Unternehmens Fenn bei Mr. Fenn fehlerhaft

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#506]
Im Kapitel 10 wurde Mr. Fenn mit dem Unternehmen Fenn getaggt aber als persName, was nicht geht. Deshalb ist die Anzeige fehlerhaft:
![Screenshot 2023-12-04 122530](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/4909ff7a-7524-4f87-bd21-f7556030e7fe)
Muss mit orgName getaggt werden.

+ weiterer Vorschlag: Entweder Tag an derselben Stelle lassen, oder weiter unten im Satz "das Geschäft" damit taggen. Eine Person "Fenn" haben wir in der Datenbank ja leider nicht.

**Comment by NicolauLutz** [comment]
Verbessert.
