### ISSUE TITLE
TB 1846: Falsche Schreibweise und Tag von Leadenhall-Street

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#507]
Im gleichen Abschnitt wurde die Leadenhall-Streel falsch geschrieben... 
=> Stree**t**
![Screenshot 2023-12-04 123147](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/3f27b5b3-80cb-4796-901f-a3b3852451da)
Bitte auch in der clear-Version des Textes (Worddokument auf J) korrigieren und neue Version hochladen.

... und die Strasse wurde falsch getaggt => fälschlicherweise keywords anstatt places
![Screenshot 2023-12-04 123132](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/bea40500-6e87-44a8-9a0c-8f46b8407a9b)

**Comment by NicolauLutz** [comment]
Xml und Word-File verbessert.
