### ISSUE TITLE
Bild, ID: 127146 stellt wahrscheinlich Matthew Boulton (Vater) dar (und nicht Matthew Robinson Boulton)

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#51]
Link: (https://archives.georgfischer.com/objects/127146)

**Comment by vrukavina** [comment]
Ich bin der Beschreibung auf Wikimedia gefolgt. Ob dies ein Abbild eines 33- oder 75-Jährigen ist, kann ich schlecht einschätzen.

**Comment by vrukavina** [comment]
Ist sehr wahrscheinlich der Vater (75-Jähriger).
