### ISSUE TITLE
TB 1846: Anführungszeichen ausserhalb des Tags setzen!

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#512]
Wir hatten abgemacht, dass Anführungszeichen ausserhalb des Tags stehen sollten. Dies muss noch im ganzen TB 1846 korrigiert werden.
Beispiel Kapitel 20:
![Screenshot 2023-12-04 154457](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/82434d6e-9035-4cf1-9740-b1851aef7931)

**Comment by NicolauLutz** [comment]
Korrigiert.
