### ISSUE TITLE
space between card and caption

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#514]
Please put same distance between card caption and card as picture caption and picture (i.e. for cards slightly more space as now)

![grafik](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/cbf4dce0-ce39-4840-b6a9-bf7fa9407962)

![grafik](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/c34805ed-df94-4579-881a-5c7622966b55)

**Comment by HelenaSabel** [comment]
Done and deployed: 

![image](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/8516387/10035bdc-dd37-4ed6-bf8b-41deac0bddc4)

**Comment by feggimann** [comment]
looks fine thank you
