### ISSUE TITLE
TB 1846: Anführungs- und Schlusszeichen setzen

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#515]
Im Kapitel 20 würde ich Polytechnical Institution, founded in the Year 1837 in Anführungs- und Schlusszeichen setzen, da JCF das Gelesene zitiert. In der englischen Übersetzung sind sie schon gesetzt.

**Comment by NicolauLutz** [comment]
Anführungs- und Schlusszeichen gesetzt.
