### ISSUE TITLE
TB 1846: Fremdsprachige Sätze/Reden kursiv setzen

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#516]
Im Kapitel 6 müsste man den französischen Satz kursiv setzen. 
![Screenshot 2023-12-04 162049](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/8f02f238-abca-4867-8104-0cc932597770)
In der englischen Version auch.

In den anderen TB wurden keine Anführungs- und Schlusszeichen verwendet, nur Kursivschreibung. Siehe Beispiel aus TB7:
(https://gf.tei-publisher.com/de/1814/21?action=search#1.6.4.40.11.2)
deutsch:
![Screenshot 2023-12-04 162517](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/7603986b-95fb-4432-8bac-c38e645a09e3)

englisch:
![Screenshot 2023-12-04 162916](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/9db4a06a-7003-4ad8-9e1a-7efa717bf3d3)

**Comment by vrukavina** [comment]
@feggimann  Wenn wir aber unserer Regel folgen, dass wir von JCF buchstäblich übernommene Begriffe im englischen unter Anführungs- und Schlusszeichen setzen (wie wir es für seine englischen Begriffe in der englischen Übersetzung gemacht haben), dann müssten wir das hier auch so handhaben, oder?

Falls ja, müssen wir das dann noch in allen Tagebüchern vereinheitlichen.

**Comment by feggimann** [comment]
ich finde, das würde zu weit gehen. Entweder kursiv oder Anführungszeichen. Hier ist ja Französisch und daher sowohl im Deutschen wie Englischen klar, dass es von JCF so geschrieben ist. Kursiv reicht völlig.

**Comment by NicolauLutz** [comment]
Kursiv gesetzt.
