### ISSUE TITLE
TB 1845: Kleine Verbesserung am englischen Text

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#517]
Zur Dokumentation:
S. 66: 

“the most likely reason for this stability is on the one hand the cheapness of the fuel, and on the other the fact that the actual smelting is done by the smelters, whereas the gentlemen or factory owners attend only to the profits;”

was changed (.xml and .docx) to: 

“the most likely reason for this stability is on the one hand the cheapness of the fuel, and on the other the fact that the actual smelting is done by the **workers (smelters)**, whereas the gentlemen or factory owners attend only to the profits;”

in accordance with the german version of the passage:

«...die Praxis nur in den Händen der Arbeiter (Schmelzer) zu liegen scheint...»

**Comment by feggimann** [comment]
super, finde ich gut!
