### ISSUE TITLE
Englische Übersetzungen zum Überprüfen

### ISSUE THREAD

**Issue by niklausmueller** [GF-Corporate-Archives/gf-johann-conrad-fischer#519]
Folgende IDs wurden inhaltlich angepasst; bitte englische Übersetzungen überprüfen:

NICOLAU HAT KONTROLLIERT Keyword ID 3945 «Waffe» ([https://archives.georgfischer.com/keywords/3945](https://archives.georgfischer.com/keywords/3945)) hat eine neue deutsche Beschreibung erhalten. Ich habe mich an einer englischen Übersetzung versucht, aber verbessert diese bitte nach Möglichkeit noch.

NICOLAU HAT KONTROLLIERT Keyword ID 8635 «Leuchtgas» (https://archives.georgfischer.com/keywords/8635) ist in der Version auf Anton, die ich vorgefunden habe, umfangreicher als in Valerijas Dokument, aber die Version auf Anton ist verbindlich, soweit ich erkennen kann.

NICOLAU HAT KONTROLLIERT Keyword ID 8921 «Cicerone» ([https://archives.georgfischer.com/keywords/8921](https://archives.georgfischer.com/keywords/8921)) wurde von Valerija neu hinzugefügt; hier gilt ebenfalls, das die Übersetzung noch kontrolliert werden sollte.

Keyword ID 3013 Maschinenhaus

Keyword ID 9740 Hebeisen:
"Tool made from [wrought iron](https://archives.georgfischer.com/keywords/9012) which is used for lifting heavy weights." statt
"Tool for lifting heavy weights used in [iron forging](https://archives.georgfischer.com/keywords/9012)."

Keyword ID 9745 Hammergang:
"Term denoting the regular movement of a mechanically operated (steam) hammer ([tilt hammer](https://archives.georgfischer.com/keywords/8540), [stretching hammer](https://archives.georgfischer.com/keywords/9099) etc.)." statt
"Term denoting the regular movement of a mechanically operated (steam) hammer ([Aufwerfhammer](https://archives.georgfischer.com/keywords/8540), [Streckhammer](https://archives.georgfischer.com/keywords/9099) etc.)."

Keyword ID 9810 Cyanotypie:
"This is how blueprints are produced." statt
"This is how blueprints were produced."

Keyword ID 9825 Knallgas:
"Also known as “knallgas”. This German term derives from the sound produced by exploding oxyhydrogen." statt
"Also known as *knallgas*."

Keyword ID 9578 Traubenzucker
[Ich habe Nicolaus Übersetzung etwas umgestellt; der deutsche und englische Sprachgebrauch sind hier asymmetrisch:]
EN Label: glucose
"Also called grape sugar.

The term “grape sugar” was coined by Jean Baptiste Dumas in 1838 and refers to the original extraction of grape sugar from [grapes](https://archives.georgfischer.com/keywords/9577)."

**Comment by NicolauLutz** [comment]
ID 8635 «Leuchtgas» würde ich etwas umstellen: 

"Gas used in the 19th century for lighting and obtained through [coal gasification](https://archives.georgfischer.com/keywords/8549), the main component being hydrogen."

ID 8921 «Cicerone» den zweiten Satz ändern auf: 

"The term was probably derived from the Roman politician and philosopher [Marcus Tullius Cicero](https://archives.georgfischer.com/actors/7576), who was famous for his eloquence."

Sonst sieht es gut aus.

**Comment by niklausmueller** [comment]
Vielen Dank, ich ändere 8635 «Leuchtgas» und 8921 «Cicerone» gleich; es kommen dann noch mehr Übersetzungen dazu, die ich im ursprünglichen Post per Editieren hinzufüge.

**Comment by vrukavina** [comment]
Bitte auch noch ID 3013 Maschinenhaus überprüfen.

**Comment by feggimann** [comment]
Ich habe bei Leuchtgas im Anton noch leicht angepasst und korrigiert. Rest ist von mir aus ok.

**Comment by niklausmueller** [comment]
Bitte die folgenden Übersetzungen von Keyword-Beschreibungen ebenfalls noch überprüfen; sie sind in Anton eingepflegt:

ID 8890 Braunkohle
ID 9044 Feilenschmiede
ID 9251 Konzession
ID 9363 Physiker
ID 9482 Rotbrüchiger Stahl
ID 9507 Stahlwaren
ID 9555 Taucher
ID 9621 Weltverbesserer

**Comment by vrukavina** [comment]
Engl. Übersetzung von ID 9724 Heuwender bitte auch überprüfen.

**Comment by niklausmueller** [comment]
Bitte englische Beschreibung von Keyword ID 9459 Silbernitrat auch noch überprüfen.

**Comment by niklausmueller** [comment]
Bitte englische Beschreibung von Keyword ID 9736 Orgel auch noch überprüfen.

**Comment by ChristopherZoller-Blundell** [comment]
> Bitte auch noch das englische Label von 9686 Stahlformguss kontrollieren: crucible steel production. Die ursprünglich vorgeschlagene Übersetzung war "cast steel"; sie überschneidet sich aber mit der Übersetzung von 8482 Gussstahl.

Suggest "crucible steel casting" as EN translation of Stahlformguss. It is different from Gussstahl / cast steel, as these refer to a class of finished or semi-finished object, whereas Stahlformguss refers to a process that produces them.

**Comment by ChristopherZoller-Blundell** [comment]
> Bitte englische Beschreibung von Keyword ID 9459 Silbernitrat auch noch überprüfen.

The translation and description are ok.

**Comment by ChristopherZoller-Blundell** [comment]
> Bitte englische Beschreibung von Keyword ID 9736 Orgel auch noch überprüfen.

The translation and description are ok here too.

**Comment by ChristopherZoller-Blundell** [comment]
> ID 8890 Braunkohle
> ID 9044 Feilenschmiede
> ID 9251 Konzession
> ID 9363 Physiker
> ID 9482 Rotbrüchiger Stahl
> ID 9507 Stahlwaren
> ID 9555 Taucher
> ID 9621 Weltverbesserer

All of these translations and descriptions are very good. I have no suggestions for changes.

**Comment by ChristopherZoller-Blundell** [comment]
> Bitte auch noch ID 3013 Maschinenhaus überprüfen.

I have undertaken a minor correction to this entry. Otherwise it is very good as it is.

**Comment by vrukavina** [comment]
Kann von mir aus geschlossen werden. Wie sieht es bei dir aus @niklausmueller ? Falls ebenfalls alles in Ordnung ist, bitte schliessen.

**Comment by niklausmueller** [comment]
Danke fürs Durchschauen, super!
