### ISSUE TITLE
Keywords ohne Beschreibung

### ISSUE THREAD

**Issue by niklausmueller** [GF-Corporate-Archives/gf-johann-conrad-fischer#520]
Folgende Keywords haben noch keinerlei Beschreibung und sind mir beim Bearbeiten aufgefallen:

Keyword ID 9251 Konzession
Keyword ID 9363 Physiker
Keyword ID 9482 Rotbrüchiger Stahl
Keyword ID 9507 Stahlwaren
Keyword ID 9555 Taucher
Keyword ID 9621 Weltverbesserer [+Englischer Übersetzungsvorschlag für Tag: allenfalls "do-gooder" statt "philanthropist"?]

**Comment by feggimann** [comment]
Danke für die Vorschläge. Hier meine Kommentare (gilt für deutsche Versionen):

- Keyword ID 9251 Konzession: im TB geht es um die Konzession zum Betreiben von Eisenbahnlinien. Die Beschreibung ist deshalb in diesem Zusammenhang nicht ganz passend.
- Keyword ID 9363 Physiker: von mir aus ok
- Keyword ID 9482 Rotbrüchiger Stahl: lieber diese Definition "Als rotbrüchig bezeichnet man einen Stahl, der sich bei Rotglut (700 bis 900 °C) nicht mehr warmverformen lässt.", s. Quelle [Stahl und Eisen](http://delibra.bg.polsl.pl/Content/19057/P-770_1933-2_30.pdf), S. 779. Bitte auch diese Quellenangabe.
- Keyword ID 9507 Stahlwaren: von mir aus ok
- Keyword ID 9555 Taucher: von mir aus ok
- Keyword ID 9621 Weltverbesserer: JCF verwendet den Begriff für Politiker. Das könnte noch in die Beschreibung. Ich finde "do-gooder" gut als Label, würde aber sowohl in der deutschen wie englischen Version "Philantrop" bzw. "philantropist" in Beschreibung einbauen.

@vrukavina und @niklausmueller könnt ihr das bitte zusammen anschauen? Danke

**Comment by niklausmueller** [comment]
Hier nochmals Vorschläge zur Diskussion mit @vrukavina :

Keyword ID 8890 Braunkohle:
Braune bis pechschwarze [Kohlenmasse](https://archives.georgfischer.com/keywords/2570) mit 30-70 Prozent [Kohlenstoffanteil](https://archives.georgfischer.com/keywords/9227), die während des Tertiär abgelagert wurde.
EN: Brown to pitch-black [coal](https://archives.georgfischer.com/keywords/2570) mass with 30-70 percent [carbon](https://archives.georgfischer.com/keywords/9227) content, which was deposited during the Tertiary period.

+ Quelle: Brockhaus' Kleines Konversations-Lexikon, fünfte Auflage, Band 1. Leipzig 1911., S. 259. ([Zeno.org](http://www.zeno.org/nid/20000979961).

Keyword ID 9044 Feilenschmiede:
Schmiede, in der Feilen hergestellt werden.
EN: Smithy where files are made.

Keyword ID 9251 Konzession
Tag EN: concession
Erlaubnis, ein Gewerbe zu betreiben oder Bauten zu erstellen, die von der lokal zuständigen Obrigkeit erteilt wird.

Der Begriff wird unter anderem verwendet für die Erlaubnis, eine Eisenbahninfrastruktur zu bauen und zu betreiben.
EN: Permission to operate a business or construct buildings granted by the local authorities.

The term is used, among other things, for permission to build and operate a railroad infrastructure.

Keyword ID 9482 Rotbrüchiger Stahl
Tag EN: brittle red steel

Als rotbrüchig bezeichnet man einen [Stahl](https://archives.georgfischer.com/keywords/613), der sich bei Rotglut (700 bis 900 °C) nicht mehr warmverformen lässt.
EN: A [steel](https://archives.georgfischer.com/keywords/613) that can no longer be worked at red heat (700 to 900 °C).

    Quelle: Rotbruch. In: Lueger, Otto: Lexikon der gesamten Technik und ihrer Hilfswissenschaften, Bd. 7. Stuttgart, Leipzig 1909., S. 513 ([Zeno.org](http://www.zeno.org/nid/20006115519), Stand 08.12.2023).

+ Nehl, Franz: Die Rotbrüchigkeit kupferhaltiger Stähle und ihre Vermeidung, in: Stahl und Eisen 53 (33), 1933, S. 779.

Keyword ID 9621 Weltverbesserer
Tag EN: do-gooder
Person, welche die Welt durch ihre Handlungen zu verbessern versucht; ein Philanthrop.

Wird oft mit abwertendem Unterton verwendet. Kann mit Bezug auf Politiker mit (vermeintlich) wohlmeinenden Absichten oder hochfliegenden Plänen verwendet werden.
EN: A person who tries to improve the world with their actions; a philanthropist.

Often used implying a pejorative undertone. Can be used with reference to politicians with (supposedly) well-meaning intentions or lofty plans.

**Comment by vrukavina** [comment]
@niklausmueller 
Keyword ID 9251 Konzession finde ich jetzt schon besser. Den zweiten Satz braucht es meiner Meinung nach dann nicht mehr. Er ist genug offen formuliert, aber auch dennoch passend für unseren Kontext. Evtl. würde ich "Erlaubnis" durch "Bewilligung" ersetzen und "lokal" weglassen. 
neu:
Bewilligung, ein Gewerbe zu betreiben oder Bauten zu erstellen, die von der zuständigen Obrigkeit erteilt wird.

Keyword ID 9482 Rotbrüchiger Stahl
Quelle von Franz Nehl anpassen: 
-Nehl, Franz: Die Rotbrüchigkeit kupferhaltiger Stähle und ihre Vermeidung. In: Stahl und Eisen, Heft 30 (1933), S. 779.

Keyword ID 9621 Weltverbesserer
Kleine Änderung "in" anstatt "mit Bezug" und "hochfliegenden" ersetzen und "vermeintlich" streichen.
Wird oft mit abwertendem Unterton verwendet. Kann in Bezug auf Politiker mit wohlmeinenden Absichten oder weitreichenden Plänen verwendet werden.

Quelle anpassen:
Keyword ID 8890 Braunkohle:
Quelle: Brockhaus' Kleines Konversations-Lexikon, fünfte Auflage, Band 1. Leipzig 1911, S. 259. ([Zeno.org](http://www.zeno.org/nid/20000979961), Stand 11.12.2023).

Keyword ID 9044 Feilenschmiede:
Feile ID 8656 und Schmiede ID 9439 taggen im Beschrieb.
Bitte Quelle ergänzen um: Feile. In: Meyers Großes Konversations-Lexikon, Band 6. Leipzig 1906, S. 383 ([Zeno.org](http://www.zeno.org/nid/2000659588X), Stand 11.12.2023).

**Comment by vrukavina** [comment]
Bitte die englischen Übersetzungen im Issue #519 festhalten.

**Comment by niklausmueller** [comment]
Ich habe die Beschreibung Keyword ID 9363 Physiker nochmals angepasst, weil mir die Wendung "Physik erforschen" unschön erscheint:

Person, die [Physik](https://archives.georgfischer.com/keywords/3048) studiert hat oder lehrt, oder die Forschung im Gebiet der Physik betreibt.

Person who has studied, teaches or does research into [physics](https://archives.georgfischer.com/keywords/3048).

**Comment by niklausmueller** [comment]
Ist erledigt und in Anton eingepflegt; die englischen Übersetzungen dieser Beschreibungen sind in [#519](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/issues/519) bereit zur Kontrolle.

@feggimann zur Kontrolle.

**Comment by feggimann** [comment]
Alles super, vielen Dank
