### ISSUE TITLE
Keywords ohne Übersetzung

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#521]
Folgende Keywords bitte anschauen:

- ID 8850 Bogenschütz: wird das verwendet? wenn ja bitte belegen und übersetzen, wenn nein, bitte löschen
- ID 9724 Heustreumaschine: wird das verwendet? wenn ja bitte belegen und übersetzen, wenn nein, bitte löschen

**Comment by NicolauLutz** [comment]
ID 8850 wird nicht verwendet, wurde gelöscht. 

ID 9724: wird verwendet, beibehalten, Valerija hat Beschreib ergänzt, Ich habe englische Übersetzung ergänzt. @ChristopherZoller-Blundell bitte kontrollieren.

**Comment by vrukavina** [comment]
@NicolauLutz Der Beschrieb stand schon dort, wahrscheinlich kommt er von Helena oder Schib. Ich bin gerade dabei das zu kontrollieren und werde den Beschrieb wahrscheinlich noch anpassen und Quellen, Links ergänzen. Dann werde ich den neuen Beschrieb für Chris im Issue #519 festhalten.

**Comment by vrukavina** [comment]
Die Heustreumaschine war ein von Nicolau gesetzter und beschriebener Begriff (nicht von Helena/Schib). Ich habe den genaueren Begriff "Heuwender" gewählt und den Beschrieb angepasst. Die engl. Übersetzung wurde im entsprechenden Issue zur Kontrolle vermerkt. Somit kann das Issue geschlossen werden.
