### ISSUE TITLE
Actor ID 7549 (Friedrich von Württemberg)

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#524]
@NicolauLutz @vrukavina JCF besucht Friedrich 1814, als er schon König ist. Bitte den Text entsprechend anpassen und Name ändern in:

Friedrich I. (Württemberg)

bitte Änderungen am englischen Text an @JSpinatsch weitergeben

**Comment by NicolauLutz** [comment]
Verbessert.

für den englischen Text @JSpinatsch (Änderungen Fett)

"**Of house Württemberg**. As of 1797, known as Friedrich II, the fifteenth ruling Duke of Württemberg; 1803–1806 also Elector; and from 1806 to 1816 Friedrich I, the first King of Württemberg.

During his visit in [Stuttgart](https://gf.tei-publisher.com/en/places/gfa-places-143) in the summer of 1814, Johann Conrad Fischer was the guest of **Friedrich I** at his pleasure palace [Mon Repos](https://gf.tei-publisher.com/en/places/gfa-places-1683) near [Ludwigsburg](https://gf.tei-publisher.com/en/places/gfa-places-1180), where the two men talked about diverse topics for some hours.
"

**Comment by feggimann** [comment]
Bitte Issues offen lassen bis von allen Seiten erledigt. 

@JSpinatsch wenn Englisch angepasst, kannst du es schliessen. Danke.

**Comment by JSpinatsch** [comment]
Erledigt.
