### ISSUE TITLE
Actors ohne Tag in xml Files

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#525]
Diese zwei Actors sind in den xml-Files nicht getaggt. Können sie noch nachgetaggt werden, damit sie in der Edition vorkommen?

- Actor ID 7772 Isambard Kingdom Brunel: nicht getaggt in xml-Files
- Actor ID 7907 Bagyidaw (Birma): nicht getaggt in xml-Files

**Comment by NicolauLutz** [comment]
ID 7907 getaggd 

ID 7772 ist schwieriger. Fischer hat Isambard Brunel nie getroffen oder erwähnt. Die "Brunel"-Stellen beziehen sich nach erneuter Besichtigung ziemlich eindeutig auf den Vater. Eine Möglichkeit wäre, im TB 6 die "SS Great Britain" mit Isambard Brunel zu taggen, da er der Erbauer des Schiffes war.

**Comment by NicolauLutz** [comment]
ID 7772 getaggd
