### ISSUE TITLE
römische Zählung bei gekrönten Häuptern im Englischen vereinheitlichen

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#526]
Die römische Zählung bei gekrönten Häuptern sollte im Deutschen mit Punkt, im Englischen ohne sein:

Bsp. Actor ID 7839
- de: George IV. (Vereinigtes Königreich)
- en: George IV (United Kingdom)

Im Anton schaut die deutsche Schreibweise gut aus. Im Excel mit den englischen Übersetzungen muss das noch vereinheitlicht werden.

@JSpinatsch bitte excel durchsuchen nach "I." / "V." / "X." / "king" etc., um alle zu erwischen, und in allen Spalten die Punkte löschen. (aktuelles Excel von Antonupload downloaden!)

**Comment by JSpinatsch** [comment]
Erledigt.
