### ISSUE TITLE
Actor ID 7756 Wellington

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#527]
@NicolauLutz @vrukavina die Schreibweise des Namens ist nicht wie sonst bei Adligen, zudem in de und en uneinheitlich:

- de: Name: von Wellington, Arthur Wellesley / andere Namensform: Herzog von Wellington
- en: Name: Wellington (Arthur Wellesley) / andere Namensform: Duke of Wellington

Bitte vergleichen mit ähnlichen Fällen/Personen und anpassen. Bitte Änderungen für en an @JSpinatsch weitergeben.

**Comment by JSpinatsch** [comment]
Erledigt.
