### ISSUE TITLE
Place ID 2236 Royal Albert Dock

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#528]
@NicolauLutz Die Übersetzung der Beschreibung fehlt. Bitte übersetzen und an @JSpinatsch geben.

**Comment by NicolauLutz** [comment]
@JSpinatsch Englische Übersetzung: 

"Dock in Liverpool, constructed by Jesse Hartley and opened in 1846."

@ChristopherZoller-Blundell

**Comment by JSpinatsch** [comment]
Erledigt.
