### ISSUE TITLE
Place ID 2173 Messingfabrik Beck & Co.

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#529]
Der Ort heisst auch auf Englisch "Messingfabrik Beck & Co." Sollte wie beim Beispiel ID 2204 (Anchor Works…) auf Englisch übersetzt werden.

@NicolauLutz bitte Name übersetzen und an @JSpinatsch weitergeben.

**Comment by NicolauLutz** [comment]
"Brass manufactory Beck & Co"

**Comment by JSpinatsch** [comment]
Erledigt.
