### ISSUE TITLE
Places: Hinweis zur Karte

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#530]
Es gibt zwei Standardsätze für Orte, die jeweils am Ende der Beschreibung mit "Hinweis zur Karte:..." stehen:
- Orte, die zu JCF Zeiten an einem anderen Ort waren wie heute
- Orte, die nicht eindeutig lokalisiert werden konnten

Die Sätze lassen sich leicht finden wenn im Anton unter Places nach "Hinweis" oder "Hinweis zur Karte" gefiltert wird (118 Treffer).

Im Excel mit den englischen Übersetzungen ist es nicht einheitlich. Der "Hinweis..." ist verschieden übersetzt:
- "Note about the map" (62 Treffer)
- "Note on the map" (45 Treffer)
- "Note on map" (13 Treffer)

Zudem sind auch die Sätze, die danach folgen, nicht einheitlich.

@vrukavina @JSpinatsch bitte zusammen anschauen, damit Excel vereinheitlicht werden kann. 
@JSpinatsch bitte de in Anton mit en in Excel vergleichen, um die zwei zusätzlichen Treffer im Excel zu finden.

**Comment by JSpinatsch** [comment]
Alles auf "Note about the map" angepasst. Places ID 1739 in ENG ergänzt, Hinweis nur auf DEU.

Folgende Places IDs sind noch zu überprüfen, Hinweis nur auf ENG, nicht aber auf DEU:
- ID 1687
- ID 1720
- ID 2153

**Comment by vrukavina** [comment]
@NicolauLutz Weisst du vielleicht, ob wir hier die genauen Koordinaten doch finden konnten und deshalb der Satz bei den deutschen Einträgen nun fehlt?
Korrekterweise sollten die Belege in diesem Fall als Quellen festgehalten worden sein, was aber nicht der Fall ist.

**Comment by NicolauLutz** [comment]
ID 1687: Konnte lokalisiert werden. 

ID 1720 auch. 

ID 2153 auch. 

Ich schaue, ob ich noch Quellen für das Quellenfeld finde.

**Comment by NicolauLutz** [comment]
@JSpinatsch für diese drei IDs den Hinweis in ENG löschen.

**Comment by JSpinatsch** [comment]
@NicolauLutz in ENG gelöscht.
