### ISSUE TITLE
GFD 3/290 Bibliothek

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#532]
Können wir ein anderes Bild nehmen? Z.B. vom Ernst-Müller-Zimmer der Eisenbibliothek :-)

**Comment by vrukavina** [comment]
Erledigt. Stimmt hier die Lizenz so @feggimann ?
Haben wir eigentlich im Archiv (und der EB?) nicht die Lizenz CC BY-**NC** 4.0? Im GFD sind Bilder aus dem Archiv nämlich mit der Lizenz CC BY-**SA** 4.0 gekennzeichnet..

**Comment by vrukavina** [comment]
Beispiel GFD 2/164: https://archives.georgfischer.com/objects/show?parent=124042&sortField=position&perPage=25&search=hunger&sortAsc=1&collection=0&recordgroup=0&fonds=0&index=2

**Comment by feggimann** [comment]
Lizenz geändert für alle Bilder aus dem Konzernarchiv
