### ISSUE TITLE
Keyords fehlende englische Labels

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#534]
Bitte die englischen Labels der Editions-Keywords der 1840er-Tagebücher ergänzen (andere können ignoriert werden):

<img width="1059" alt="Bildschirmfoto 2023-12-11 um 00 18 07" src="https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/dcd685da-58ce-4d70-957f-65bafa7e180b">

**Comment by niklausmueller** [comment]
8646 Glockenguss: bellfounding

8690 Corona: COVID-19

8850 Bogengeschütz: [von Valerija gelöscht]

8693 CERN: CERN

9878 Mobilität: mobility

8689 Montageanleitung: assembly instructions

8686 Messgerät: measuring instrument

9724 Heustreugerät: [Valerija erstellt zunächst noch deutschsprachigen Beschrieb]

8793 Amphitheater: amphitheatre

8794 Ananas: pineapple

9823 Glühspan: mill scale

8694 Künstliche Intelligenz (KI) : artificial intelligence (AI)

8891 Nockenwelle: [gelöscht]

9686 Stahlformguss: crucible steel production

8685 Prüfmaschine: testing machine [von Niklaus in Singular gesetzt]

Manche dieser Übersetzungen wurden schon von Chris und Bronwen kontrolliert und waren bereits eingepflegt. Die anderen habe ich in #519 nochmals aufgeführt zur Kontrolle.

**Comment by niklausmueller** [comment]
Hier gab es ein Missverständnis: Ich hatte nicht verstanden, dass die IDs in obiger Liste mehrheitlich in keinem Zusammenhang mit den 1840er Tagebüchern stehen, und habe darum zu viele Labels übersetzt. Ich habe irrtümlich übersetzten Labels auf Franziskas Bitte hin wieder gelöscht, und aus der Liste der zu kontrollierenden Übersetzungen in #519 gelöscht.

Neu eingepflegt sind damit nur

8793 Amphitheater: amphitheatre

8794 Ananas: pineapple

9823 Glühspan: mill scale

9686 Stahlformguss: crucible steel production
