### ISSUE TITLE
Place ID 2123 / Bigets Hutladen

### ISSUE THREAD

**Issue by JSpinatsch** [GF-Corporate-Archives/gf-johann-conrad-fischer#535]
Kommentar von Bronwen Saunders:

"perhaps change p. 15 of the TB 1845 to read “56, rue Rivoli”?

- Anpassen oder nicht?

**Comment by feggimann** [comment]
@NicolauLutz schaust du dir das bitte an, ob hier etwas angepasst werden soll? War ein Kommentar von Bronwen im Übersetzungsfile der Places

**Comment by NicolauLutz** [comment]
Nicht anpassen. Wir folgen dem Erstdruck. Die alternative Addresse ist im Ortseintrag vermerkt.
