### ISSUE TITLE
Place ID 2194 / Ronheider Rampe

### ISSUE THREAD

**Issue by JSpinatsch** [GF-Corporate-Archives/gf-johann-conrad-fischer#536]
Kommentar von Bronwen Saunders: 

"Unter “Eisenbahnstrecke Aachen-Liège” steht 15. Oktober"

- Eisenbahnstrecke Aachen-Liège = Place ID 2192. Wo anpassen?

**Comment by feggimann** [comment]
@NicolauLutz zwei verschiedene Eröffnungsdaten. Ist das korrekt?

ID 2192 Eisenbahn Aachen Liège 15. Oktober
ID 2194 Ronheimer Rampe 13. Oktober

Ich nehme an, 13. muss in 15. korrigiert werden?

**Comment by NicolauLutz** [comment]
Beide Datumsangaben entsprechen der Information auf der jeweiligen Wikipediaseite. Ich würde es deshalb so stehen lassen. Alternativ können wir auch den Tag streichen und bei beiden nur "Oktober 1843" stehen lassen.

**Comment by feggimann** [comment]
15. Oktober für die Eisenbahnlinie ist sicher korrekt. So ist auch die Gedenkmünze datiert, die im GFD ist. Wenn es dir lieber ist, kannst du bei der Rampe den Tag weglassen.

**Comment by JSpinatsch** [comment]
Nach Absprache mit Nicolau bei der Rampe den Tag weggelassen (DEU und ENG).
