### ISSUE TITLE
Exceltabelle englische Actors: falsche Apostroph ' statt ’

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#538]
In den Beschreibungen folgender Actors bitte Apostroph korrigieren:

ID 298 John Dollond - Feld History
ID 7456 Viktoria d’Orléans - Feld alternative Names
ID 8256 Biget - Feld History

**Comment by JSpinatsch** [comment]
Erledigt.
