### ISSUE TITLE
Recherche: Cäsars Pfahlbrücke über die Themse war gar nicht von Cäsar erbaut?

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#54]
Im TB 1851 schreibt JCF:

> _Wie es vor beinahe 2000 Jahren, als Julius Cäsar seinen Zug nach Britannien unternahm, und unweit dieser Stelle seine Pfahlbrüke über die Themse schlug (einige dieser Pfähle wurden vor circa 50 Jahren herausgezogen, und in dem Leverian Museum aufbewahrt, wo ich sie betrachtete, sie sind von Eichenholz, aber durch und durch schwarz wie Ebenholz, und eben so hart,), mag ausgesehen haben, kann man sich höchstens eine, wiewohl nicht zu verbürgende Vorstellung machen, wenn man die Hütten der Bewohner unserer ganz nördlichen Länder gesehen hat._

Beim Recherchieren ist mir aufgefallen, dass es sein kann, dass diese Brücke gar nicht von Cäsar erbaut wurde. Von einer Pfahlbrücke ist ausserdem allgemein nirgendwo die Rede; nur von Pfählen, die am Ufer und in der Themse aufgestellt wurden. Diese wurden aber ebenfalls nicht von Cäsar, sondern von den Briten hingestellt.
Siehe Wiki: "[...]Nun wollte der römische Feldherr den Cassivellaunus in seinem eigenen Reich heimsuchen und marschierte deshalb zur Themse, fand aber die einzige seichte Furt [...] auf der anderen Flussseite stark verteidigt; außerdem waren Spitzpfähle am Ufer und auch im Fluss in den Boden gerammt worden. Dennoch gelang Caesar der Übergang und schlug die Feinde in die Flucht." (https://de.wikipedia.org/wiki/Caesars_Britannienfeldzüge)
und Wiki en: "[...] The 13th-century French work Li Fet des Romains contains an account of Caesar's invasions based partly on Caesar and partly on Geoffrey. It adds an explanation of how Caesar's soldiers overcame the stakes in the Thames – they tied wooden splints filled with sulphur around them, and burned them using Greek fire. " (https://en.wikipedia.org/wiki/Julius_Caesar%27s_invasions_of_Britain)

Kann es sein, dass JCF sich hier irrt? In diesem Falle würde ich nämlich eine Fussnote setzen, und keinen Antoneintrag erstellen.

(Eine Recherche über das Leverian Museum ist nicht hilfreich, da das Museum 1806 aufgelöst wurde.)

**Comment by NicolauLutz** [comment]
Wenn ich wieder in London bin, kann ich in den Bibliotheken dort etwas zu den Pfählen suchen.

**Comment by vrukavina** [comment]
Recherche war nicht erfolgreich. ID nicht erstellt.
