### ISSUE TITLE
Actor ID 7391 Frederick I (Denmark and Norway) & Englische Monarchennamen

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#540]
Mir ist aufgefallen, dass in der Edition der Englische Titel der Person "Frederick V. (Denmark and Norway)" lautet. 

Müsste man da nicht den Punkt entfernen? 

Ähnlich mit anderen Monarchen in der englischen Version: 

- [Francis II. (HRR) (1768–1835)](https://gf.tei-publisher.com/en/names/gfa-actors-7381)
- [Louis-Philippe I. (France) (1773–1850)](https://gf.tei-publisher.com/en/names/gfa-actors-7478)
- [Napoleon III. (France) (1808–1873)](https://gf.tei-publisher.com/en/names/gfa-actors-7451)

Aber: 

- [Charles X (France) (1757–1836)](https://gf.tei-publisher.com/en/names/gfa-actors-8258)
- [Hery VIII (England)](https://gf.tei-publisher.com/en/names/gfa-actors-7854)

**Comment by feggimann** [comment]
Danke fürs aufmerksame Kontrollieren.

Die römischen Zählungen hat @JSpinatsch heute Morgen bereinigt und überall die Punkte gelöscht, siehe Issue #526 das wird mit dem nächsten Update sichtbar sein.
