### ISSUE TITLE
Actor ID 7710 von Württemberg-Mömpelgard, Georg Leopold

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#542]
Bitte den ersten Teil des Beschriebs im Excel anpassen. Er lautet neu wie folgt:

Reichsgraf von Horneburg und Champvallon. Enkel des Herzogs Leopold Eberhard von von Württemberg-Mömpelgard (heute [Montbéliard](https://archives.georgfischer.com/places/1310)).

**Comment by JSpinatsch** [comment]
Erledigt.
