### ISSUE TITLE
GFD Feld Kopien/Reproduktionen

### ISSUE THREAD

**Issue by feggimann** [GF-Corporate-Archives/gf-johann-conrad-fischer#545]
Kontrollsuche nach Signatur "GFD..." und Feld Kopien/Reproduktionen enthält "Lizenz":

- GFD 1 (Total 248 Signaturen): 246 Treffer
- GFD 2 (Total 300 Signaturen): 300 Treffer
- GFD 3 (Total 311 Signaturen): 311 Treffer

D.h. in GFD 2 und GFD 3 ist Feld korrekt ausgefüllt, aber in GFD 1 ist bei zwei Signaturen dieses Feld leer. Bitte nochmals verifizieren und falsch besetzte Felder zügeln.

![grafik](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/92036071/b714be73-9ab2-42d4-8f4f-c477c73077fb)

**Comment by niklausmueller** [comment]
Entschuldigung für die Unachtsamkeit; die beiden fehlenden Signaturen sind repariert. Mach gerne noch einmal den Test.

**Comment by feggimann** [comment]
Danke
