### ISSUE TITLE
TB 1846: Fisher's original note

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#546]
In journal 6 (1846), there is a footnote that Fisher wrote himself. In this case, the footnote should not appear with a number at the end of the page, but with a star (*). 
Could you please change that?
Here is an exemple from the journal 3: https://johannconradfischer.sources-online.org/de/1825/41

In the xml file of journal 3 it looks like this:
 (Code 1972 and 1973)
![Bildschirmfoto 2023-12-12 um 09 10 00](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/8ab6e7e0-e099-4306-93d6-4c7ecb8f57df)

And in the journal 6 like this:
(Code 48)
![Bildschirmfoto 2023-12-12 um 09 11 35](https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/assets/102786242/e433553e-cb51-41e2-b1b6-23475cafa3df)

**Comment by HelenaSabel** [comment]
Fixed! You can see the examples you mentioned here: https://gf.tei-publisher.com/de/1825/41 and here: https://gf.tei-publisher.com/de/1846/3

**Comment by feggimann** [comment]
Excellent, thank you
