### ISSUE TITLE
Info: Zeitangaben im Itinerar

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#547]
Nicolau scheint manchmal innerhalb des Itinerartags die Zeitangabe mitkodiert zu haben in den von ihm bearbeiteten Tagebüchern (5,6, aber auch 2).
Dies wurde von den Programmierern nicht beachtet und nicht implementiert, da sie nichts davon wussten. Ich habe es auch jetzt erst gemerkt, weil ich das selber nie so kodiert habe.

Es wäre zu umständig und evtl auch kostspielig dies noch zu implementieren. Mein Vorschläge wäre es deshalb, dass dies 'ignoriert' bleibt.

**Comment by feggimann** [comment]
Wir lassen die Anzeige der Datumsangaben ohne Zeitangabe.
