### ISSUE TITLE
Fehlende Beschreibungen Sachschlagworte

### ISSUE THREAD

**Issue by niklausmueller** [GF-Corporate-Archives/gf-johann-conrad-fischer#548]
**9699 Deckprisma**

Prisma mit sechseckiger Grundfläche, das in ein passend ausgeschnittenes Loch auf dem Schiffsdeck wasserdicht eingelassen wurde.

Es streute von oben einfallendes Licht im Unterdeck des Schiffes.

Prism with a hexagonal base, which was inserted tightly into a suitably cut hole on the ship’s deck.

It scattered light from above onto the lower deck of the ship.

+ Quelle: Wilk, Stephen R.: Sandbows and Black Lights. Reflections on Optics. New York 2021, S. 87.

Die Übersetzung wurde von Chris gutgeheissen und ich pflege die Beschreibung auf Anton ein. Die Quelle ist passend.

**Comment by feggimann** [comment]
Es sind keine weiteren Keywords ohne Beschreibung aufgetaucht.
