### ISSUE TITLE
TEI Publisher Tagging App: Suchresultate stimmen nicht & es werden nicht alle relevanten Anton Einträge gezeigt

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#55]
<img width="423" alt="Screen Shot 2022-06-29 at 10 26 04" src="https://user-images.githubusercontent.com/92101460/176673922-09208342-9eb5-45bf-aad2-79d5569a31d1.png">
<img width="418" alt="Screen Shot 2022-06-29 at 10 25 58" src="https://user-images.githubusercontent.com/92101460/176673928-dea200d0-3949-4632-896c-8f956c14da38.png">

**Comment by NicolauLutz** [comment]
Beispiel: Suche nach "london": zeigt nicht alle Einträge an (z. B. Pall Mall (1672))

**Comment by ottosmops** [comment]
@wolfgangmm Kann man einfach mehr Treffer anzeiegen; also z.B. 100

**Comment by ottosmops** [comment]
@NicolauLutz @vrukavina bitte Testen, Wolfgang hat die App geupdated

**Comment by wolfgangmm** [comment]
@NicolauLutz war das der richtige Server? Die aktuelle Version läuft unter https://georg-fischer.tei-publisher.com/. Wir mussten umziehen, da der alte sources-online Server neu aufgesetzt wird.

<img width="622" alt="image" src="https://user-images.githubusercontent.com/607433/179972186-9ef25b1e-5402-4b66-b2ca-d6e96ce24a7a.png">

**Comment by NicolauLutz** [comment]
@wolfgangmm Aktuelle Version auf neuem Server funktioniert, danke.

**Comment by vrukavina** [comment]
Bei mir auch. Allerdings sind alle Tags verschwunden (Tagebuch 1851 ).
