### ISSUE TITLE
Recherche/Interpretation: Myrmidonenwohnungen

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#57]
Im TB 1851 schreibt JCF:

> Auch Manchester ist, wie Birmingham, in eine beständige Rauchwolke eingehüllt, nur mit dem Unterschied, dass wenn in lezterer Stadt nur hohe Kamine, von Zeit zu Zeit Flammen emittirend, daraus hervorragen, in ersterer, noch nebst denselben, sich die 6 bis 7 Stokwerk hohen Spinnereien, mit ihrer unendlichen Fensterzahl, die sonst in den englischen Privathäusern so spärlich ist, von Zeit zu Zeit kund geben, so dass in vielen ihrer Myrmidonenwohnungen, sich per Etage, deren selten dreie sind, nur ein Kreuzstok mit einem Sashwindow (Schubfenster), von drei Schuh Breite, zu sehen ist. Man wird fragen, wie kann aber Helle in diesen Häusern seyn?

Laut der griech. Mythologie waren die Myromiden ein Volksstamm, der von Zeus aus einem Ameisennest erschaffen wurde. Später waren sie Achilles' treueste Krieger.

Möchte JCF hier auf die Grösse/Vielzahl (wie Ameisen?) der Wohnungen verweisen, oder wie würdest du das interpretieren?

**Comment by NicolauLutz** [comment]
Ja, ich denke das ist eine überzeugende Interpretation. Ich denke aber mehr ein Verweis auf die Vielzahl der Arbeiter, statt der Wohnungen. In dem Sinn also Wohnungen für Ameisen., oder Wohnungen wie Ameisennester.

**Comment by vrukavina** [comment]
Perfekt! Vielen Dank.
