### ISSUE TITLE
Recherche: Dampfschiff Najade und Sybille

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#58]
Ich wollte die beiden Schiffe jeweils separat als Sachschlagwörter aufnehmen, aber meine Recherche ergab leider nichts. Wie würdet ihr die Relevanz von diesen Schlagwörtern beurteilen? Sollen diese zwei in Anton aufgenommen werden? Habt ihr andere/neue Recherchepisten?

Sie kommen im TB 1851, S. 38 vor:
> Und es nahm mich wieder ein Boot am Ufer, und mitten in der immer trüben Themse, das schnellgehende Dampfschiff Najade zur Rükfahrt auf, während die Sybille mich hinunter gebracht hatte.

**Comment by vrukavina** [comment]
Die Schiffe sind nirgends verzeichnet worden, weshalb es sich um Kleinboote handeln könnte. Eine weitere Recherche war nicht erfolgreich.

**Comment by ChristopherZoller-Blundell** [comment]
Neue Information: 
- Lloyd's Register of British and Foreign Shipping 1850 & 1851: Es gibt keine Schiffe mit dem Namen Najade oder abweichenden Schreibweisen davon. Es gibt ein Schiff namens Sybil, das in Yarmouth als aufliegend (nicht operativ) aufgeführt ist, und ein Schiff namens Sybilla, das von Bristol nach Jamaika fuhr. Lloyds listete nur Schiffe mit 100 Bruttotonnen oder mehr auf. Wenn es sich bei der Sybille oder der Najade um seegängige Passagierdampfer handelte, hätten sie sehr wahrscheinlich ein höheres Gewicht gehabt. Da keine passenden Schiffe dieser Namen im Register auftauchen, ist es sehr wahrscheinlich, dass JCF über zwei kleine Themse-Fährdampfer mit diesen Namen schrieb.
- Ohne Zwischenmeldung wurde die Anfrage an das Archiv der London Port and River Authority weitergeleitet. Ich habe heute eine Email erhalten. Sie melden, dass die Bestände momentan überprüfen und dass sie die Anfrage in Zusammenarbeit mit dem Bildarchiv des National Maritime Museum in Greenwich anschauen. Für die kleinen Dampfer haben sie noch keine Unterlagen gefunden - diese wurden oft von Privatunternehmen wie der Waterman Steamboat Company betrieben, und es gibt nur wenige bis gar keine erhaltene Dokumente (wie z.B. ein Inventar der Schiffe). Die Boote hatten recht ähnliche Baupläne. Das Bildarchiv des Maritime Museum ist der Meinung, dass sie in der Lage sein sollten, Bilder von der Art von Booten zu finden, über die JCF geschrieben hat. Aufgrund von Personalengpässen können wir erst in den nächsten 20 Tagen mit einer Antwort rechnen...

**Comment by ChristopherZoller-Blundell** [comment]
Weitere Infos über kleine Themse-Fährdampfer https://www.thehistoryoflondon.co.uk/victorian-passenger-steamboats-on-the-thames/

**Comment by vrukavina** [comment]
Vielen vielen Dank für die ausführliche Recherche. Diese Interpretation wird genügen müssen.
Wenn wir auch noch ein ähnliches Bild erhalten, ist das doch super!
