### ISSUE TITLE
Tagebuch 1794: p. 57 und p. 38: Zeichnung verlinken?

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#6]
Fussnote auf S. 38 verweist auf Skizze einer Säule auf letztem Blatt des Buches

**Comment by ottosmops** [comment]
`<ref type="cross" target="xmlId">...</ref>

**Comment by ottosmops** [comment]
@NicolauLutz fig1 fehlt noch, danach schliessen
