### ISSUE TITLE
Recherche: Objekte an der Weltausstellung 1851 in London

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#60]
JCF hat an der Weltausstellung folgende Objekte gesehen:
- Berliner Eisengusswaaren (https://archives.georgfischer.com/keywords/8498)
- Meisterwerk des bayrischen Löwen in Bronze (https://archives.georgfischer.com/keywords/8499)
- Bild der Bavaria (https://archives.georgfischer.com/keywords/8500)
- Wachsfiguren in Lebensgrösse (gleich im Eingangsbereich des Glaspalastes zu sehen) (https://archives.georgfischer.com/keywords/8502)
- Portrait der Königin Victoria (https://archives.georgfischer.com/keywords/8503)
- Unförmliche Stahlluppen von Golconda (https://archives.georgfischer.com/keywords/8504)

Es wäre wirklich toll, wenn wir mehr über diese Objekte erfahren könnten, und evtl. auch ein Bild dazu hätten. Die Kataloge von Tallis und die französischen albums illustrés habe ich schon durchgeschaut, und leider nichts gefunden.
Habt ihr vielleicht noch Ideen, wo man suchen könnte?

**Comment by vrukavina** [comment]
Die zwei Katalogexemplare, die wir in der EB haben, habe ich ebenfalls durchgeschaut. Da konnte ich (nur) eine schöne Illustration des Kristallspringbrunnens finden.

**Comment by ChristopherZoller-Blundell** [comment]
Verzeichnis (Kunst & Skulpturen) Great Exhibition 1851: https://sculpture.gla.ac.uk/view/event.php?id=msib7_1206445129 

Wachsfiguren in Lebensgrösse - 4 Royals als die Jahreszeiten:

HRH the Prince Alfred, as Autumn: https://sculpture.gla.ac.uk/view/object.php?id=msib7_1206450929

HRH the Prince of Wales, as Winter: (https://sculpture.gla.ac.uk/view/object.php?id=msib7_1206450967

HRH the Princess Alice, as Spring: (https://sculpture.gla.ac.uk/view/object.php?id=msib7_1206450703

HRH the Princess Royal, as Summer: (https://sculpture.gla.ac.uk/view/object.php?id=msib7_1206450894

**Comment by ChristopherZoller-Blundell** [comment]
"Official descriptive and illustrated catalogue / Great Exhibition of the Works of Industry of All Nations, 1851 ; by authority of the Royal Commission." (1851 : London, England)

Alle vier Bände sind vollständig digitalisiert und online über die Wellcome-Sammlung verfügbar: https://wellcomecollection.org/works/pdp6m5e3 

Vol 2, P 512: Prince of Wales & Princess Royal (Interessanterweise ist PoW ein Schafhirte, PR ein Sammler - nicht Herbst und Sommer. Es könnte sein, dass es mehrere allegorische Statuen von den Royals gab, die von Thornycroft hergestellt wurden.)

**Comment by ChristopherZoller-Blundell** [comment]
"Meisterwerk des bayrischen Löwen in Bronze"

Colossal Lion by Müller of Berlin (Ausgestellt in der "Bavaria" Abteilung der Ausstellung) in Vol 3, P 187.

**Comment by ChristopherZoller-Blundell** [comment]
"Unförmliche Stahlluppen von Golconda"

Ich werde einen Blick in den Katalog werfen und sehen, was ich hier finde. Ich habe bis jetzt kein Objekt dieser Art gefunden, das unter diesem Ortsnamen in Bezug auf die Ausstellung aufgeführt ist, obwohl Golconda allgemein für gehämmerte Stahlprodukte (z. B. Schalen) bekannt zu sein scheint (vllt. "unförmlich" weil sie gehämmert wurden?). Aufgrund des Spektakels, das der in Golconda gefundene Kohinoor-Diamant ausgelöst hat, könnte es sein, dass er Golconda irrtümlich verwendet hat und in Wirklichkeit Hyderabad, die Region, in der Golconda liegt, meinte. Hyderabad war der Sitz der Mogulmacht in Indien. Der persische Stahl, der von den Moguln nach Indien gebracht wurde, gehörte zu den frühesten bekannten Edelstahltypen und wurde durch Chrom rostfrei gemacht. Es gab aber zu Fischers Zeit keine allgemeine Bezeichnung für solche Legierungen (sie kam erst später Anfang des 20. Jahrhunderts). Stahl aus Golconda könnte Fischers Art sein, auf eine solche Legierung hinzuweisen.

**Comment by ChristopherZoller-Blundell** [comment]
"Portrait der Königin Victoria"

Dies ist schwieriger zu finden. Auch hier werde ich im Katalog der Great Exhibition nachsehen, ob es einen Hinweis auf den Künstler gibt. Der Zeitpunkt des ersten Entente Cordial würde das Porträt auf das Jahr 1843 datieren. Es gibt ein berühmtes Bild von Victoria aus dem Jahr 1843, aber es ist ein Gemälde von Franz Xaver Winterhalter. Offenbar hält Victoria den Rekord als Monarchin mit den meisten offiziell in Auftrag gegebenen Porträts in der britischen Geschichte. Dass dieses Werk von König Louis-Philippe von Frankreich in Auftrag gegeben wurde, dürfte seine Auffindbarkeit erleichtern, aber bis jetzt habe ich keine Hinweise auf ein lebensgrosses Porträt auf Porzellan gefunden (nichts derart gelistet in der Sammlungen der Royal Collection oder National Portrait Gallery).

**Comment by ChristopherZoller-Blundell** [comment]
"Berliner Eisengusswaaren"

Prussia No. 197 A.F. Lehmann, Vol. 3, P 112 (Vol 3: https://wellcomecollection.org/works/pdp6m5e3/items?workId=pdp6m5e3&langCode=eng&manifest=3&canvas=1). 

Eines der Produkte, ein gusseiserner Springbrunnen im orientalischen Stil, ist abgebildet auf Seite 115 in Vol. 3.

**Comment by ChristopherZoller-Blundell** [comment]
"Bild der Bavaria"

Vol. 3, P. 189: Abbildung einer Skulptur, die Bavaria auf einem von Löwen gezogenen Streitwagen (Quadriga) darstellt. Sie wurde für das Siegestor in München angefertigt (1945 zerstört, nach dem Krieg wiederaufgebaut und rekonstruiert als Friedensdenkmal). Die Statue wurde nach London 1851 geschickt, um dort ausgestellt zu werden, bevor sie auf dem Tor montiert wurde (https://de.wikipedia.org/wiki/Siegestor).

Auf wikimedia commons gibt es ein sehr schönes Bild eines einzelnen Löwen der Skulptur während des Transports zur Ausstellung in London. Dies könnte durchaus derselbe Löwe sein, über den JCF in seinem Tagebuch berichtet.
https://commons.wikimedia.org/wiki/File:L%C3%B6we_Siegestor_M%C3%BCnchen.jpg

**Comment by vrukavina** [comment]
> "Bild der Bavaria" & "Meisterwerk des bayrischen Löwen in Bronze"
> 
> Vol. 3, P. 189: Abbildung einer Skulptur, die Bavaria auf einem von Löwen gezogenen Streitwagen (Quadriga) darstellt. Sie wurde für das Siegestor in München angefertigt (1945 zerstört, nach dem Krieg wiederaufgebaut und rekonstruiert als Friedensdenkmal). Die Statue wurde nach London 1851 geschickt, um dort ausgestellt zu werden, bevor sie auf dem Tor montiert wurde (https://de.wikipedia.org/wiki/Siegestor).
> 
> Auf wikimedia commons gibt es ein sehr schönes Bild eines einzelnen Löwen der Skulptur während des Transports zur Ausstellung in London. Es ist das gleiche wie die Löwenstatue, die auf S. 187 von Band 3 des illustrierten Ausstellungsführers abgebildet ist. Ich denke, es ist ziemlich sicher, dass dies die Statue ist, über die Fischer schreibt. https://commons.wikimedia.org/wiki/File:L%C3%B6we_Siegestor_M%C3%BCnchen.jpg

Bei dem Löwen bin ich mir auch ziemlich sicher, dass dieser gemeint ist.
Es könnte sehr wohl möglich sein, dass auch dieses Abbild der Bavaria gemeint ist. Ich war wohl bei der Recherche zu sehr darauf fokussiert, dass es ein Bild, also ein Gemälde, war, aber beim erneuten Lesen des Textes habe ich gemerkt, dass dies nicht der Fall ist.
Vielen vielen Dank!

**Comment by vrukavina** [comment]
> "Berliner Eisengusswaaren"
> 
> Prussia No. 197 A.F. Lehmann, Vol. 3, P 112 (Vol 3: https://wellcomecollection.org/works/pdp6m5e3/items?workId=pdp6m5e3&langCode=eng&manifest=3&canvas=1).
> 
> Eines der Produkte, ein gusseiserner Springbrunnen im orientalischen Stil, ist abgebildet auf Seite 115 in Vol. 3.

Das könnte sehr gut möglich sein. Ich glaube in den Katalogexemplaren, die wir in der EB haben, mehrere Auflistungen von Eisengusswaren Berliner Hersteller gesehen zu haben (habe es mir aber leider nicht notiert). Aber ich werde die Fussnote entsprechend formulieren. Danke!

**Comment by vrukavina** [comment]
> "Unförmliche Stahlluppen von Golconda"
> 
> Ich werde einen Blick in den Katalog werfen und sehen, was ich hier finde. Ich habe bis jetzt kein Objekt dieser Art gefunden, das unter diesem Ortsnamen in Bezug auf die Ausstellung aufgeführt ist, obwohl Golconda allgemein für gehämmerte Stahlprodukte (z. B. Schalen) bekannt zu sein scheint (vllt. "unförmlich" weil sie gehämmert wurden?). Aufgrund des Spektakels, das der in Golconda gefundene Kohinoor-Diamant ausgelöst hat, könnte es sein, dass er Golconda irrtümlich verwendet hat und in Wirklichkeit Hyderabad, die Region, in der Golconda liegt, meinte. Hyderabad war der Sitz der Mogulmacht in Indien. Der persische Stahl, der von den Moguln nach Indien gebracht wurde, gehörte zu den frühesten bekannten Edelstahltypen und wurde durch Chrom rostfrei gemacht. Es gab aber zu Fischers Zeit keine allgemeine Bezeichnung für solche Legierungen (sie kam erst später Anfang des 20. Jahrhunderts). Stahl aus Golconda könnte Fischers Art sein, auf eine solche Legierung hinzuweisen.

Ich finde beide Interpretationen plausibel, aber die letztere scheint mir noch passender zu sein. Fischer hat sich bei der Beschreibung der Ausstellungsobjekte äusserst Mühe gegeben, und deshalb glaube ich eher weniger, dass er sich den falschen Ortsnamen notiert hat. Ich werde in einer Fussnote dennoch beide Interpretationen festhalten, da wir wahrscheinlich genauere Hinweise nicht finden werden. Herzlichen Dank!

**Comment by vrukavina** [comment]
> Verzeichnis (Skulpturen) Great Exhibition 1851: https://sculpture.gla.ac.uk/view/event.php?id=msib7_1206445129
> 
> Wachsfiguren in Lebensgrösse - 4 Royals als die Jahreszeiten:
> 
> HRH the Prince Alfred, as Autumn: https://sculpture.gla.ac.uk/view/object.php?id=msib7_1206450929
> 
> HRH the Prince of Wales, as Winter: https://sculpture.gla.ac.uk/view/object.php?id=msib7_1206450967
> 
> HRH the Princess Alice, as Spring: https://sculpture.gla.ac.uk/view/object.php?id=msib7_1206450703
> 
> HRH the Princess Royal, as Summer: https://sculpture.gla.ac.uk/view/object.php?id=msib7_1206450894

Es können nicht diese Figuren gewesen sein, denn im TB schreibt Fischer auf S. 17-18: "Das Zweite was meine Betrachtung eine Zeit lang in Anspruch nahm, waren die Wachsfiguren in Lebensgrösse, und mit ihrem Schmuk angethan, von einem Indianer und seiner Frau aus den Urwäldern Amerika’s von den sogenannten Rothhäuten. Eine solche Menschenraçe gibt es also noch, im Gegensaz zu denen von der höchsten Kultur. Man sieht es auf den ersten Anblik, dass es ganz getreue Abbildungen sind [...]"

**Comment by ChristopherZoller-Blundell** [comment]
> "Das Zweite was meine Betrachtung eine Zeit lang in Anspruch nahm, waren die Wachsfiguren in Lebensgrösse, und mit ihrem Schmuk angethan, von einem Indianer und seiner Frau aus den Urwäldern Amerika’s von den sogenannten Rothhäuten. Eine solche Menschenraçe gibt es also noch, im Gegensaz zu denen von der höchsten Kultur. Man sieht es auf den ersten Anblik, dass es ganz getreue Abbildungen sind [...]"

Ich habe gesucht und noch kein Bild von diesen Indianer gefunden. Das ist eine ziemlich verwirrende Beschreibung. Die Indianer, die üblicherweise als Rothäute bezeichnet werden, kamen aus Nordamerika, aber aus den Great Plains und nicht aus den Urwäldern. Ich werde in den Katalogen nachsehen, welche Exponate von Mexiko oder vielleicht Brasilien geschickt wurden. 
Ich bin mir jedoch ziemlich sicher, dass es Bilder des Wachsfigurenkabinetts irgendwo gibt. Ich habe Hinweise auf andere Wachsfiguren gefunden, die Jahrzehnte später geschaffen wurden, aber die Wachsfiguren von 1851 als Inspiration nahmen. 

"Shortly thereafter the staff of this Museum began experimenting in the creation of life-sized human figures to interpret the appearance of primitive peoples. They studied the techniques employed with considerable success in Europe—Castan's “Panopticum” in Berlin, and Madam Tussuad's [Tussaud] popular wax museum in London. **They were influenced also by the representations of the races of mankind at Sydenham [Great Exhibition of 1851 in the Crystal Palace]** and the Swedish peasant figures exhibited at the Centennial Exposition in Philadelphia in 1876."

https://www.tandfonline.com/doi/abs/10.1080/08949468.2014.884896

**Comment by ChristopherZoller-Blundell** [comment]
Neue Information: Ich habe keine Hinweise auf Wachsfiguren der Urwaldindianer in Brasilien gefunden.
 Im Ausstellungsführer sind aber zwei Skulpturen nordamerikanischer Indianer, beides Wachsarbeiten, als Teil von Dioramen ausgestellt. Beide wurden von (Richard) Napoleon Montanari geschaffen. 

Sie haben ziemlich schreckliche Namen:

- North American Indian preparing to scalp a white traveller (https://sculpture.gla.ac.uk/view/object.php?id=msib7_1206618797)

- Indian carrying away a white child (https://sculpture.gla.ac.uk/view/object.php?id=msib7_1206618957)

Ich habe bis jetzt keine Bilder von den Dioramen gefunden.

**Comment by vrukavina** [comment]
So wie JCF fasziniert über sie schreibt, würde ich mich nicht wundern, wenn sein Wissen bezüglich der "Rothäutern" nicht so umfangreich war. Ich kann mir vorstellen, dass er irrtümlicherweise von Urwäldern spricht, aber sicher werden wir nie sein können.

**Comment by ChristopherZoller-Blundell** [comment]
Das denke ich auch.

**Comment by vrukavina** [comment]
> Neue Information: Ich habe keine Hinweise auf Wachsfiguren der Urwaldindianer in Brasilien gefunden. Im Ausstellungsführer sind aber zwei Skulpturen nordamerikanischer Indianer, beides Wachsarbeiten, als Teil von Dioramen ausgestellt. Beide wurden von (Richard) Napoleon Montanari geschaffen.
> 
> Sie haben ziemlich schreckliche Namen:
> 
> * North American Indian preparing to scalp a white traveller (https://sculpture.gla.ac.uk/view/object.php?id=msib7_1206618797)
> * Indian carrying away a white child (https://sculpture.gla.ac.uk/view/object.php?id=msib7_1206618957)
> 
> Ich habe bis jetzt keine Bilder von den Dioramen gefunden.

Die Namen sind schrecklich, aber in diesem Falle ausschlaggebend. JCF spricht von Figuren eines Mannes und einer Frau. So wie JCF das Gesehene auf der Ausstellung immer beschreibt, würde ich sagen, dass er bestimmt erwähnt hätte, wenn noch andere Figuren Teil davon wären, also den "white traveller" und das "white child". Deshalb habe ich das Gefühl, dass es nicht diese zwei Skulpturen von Montanari gewesen sein könnten.

Ich würde vorschlagen, dass ich im Sachschlagwortseintrag in Anton (ID 8592, https://archives.georgfischer.com/keywords/8502) die Figuren mit dem Zitat von JCF beschreibe. Falls wir irgendwann einmal diese zwei identifizieren können, oder sogar Bilder dazu finden, können wir direkt im Eintrag die Infos aufschreiben.
