### ISSUE TITLE
Recherche: Eröffnung der Schelde & Brand in Londoner Papierfabrik

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#61]
In TB 1851 schreibt JCF (S. 46): 

> Uebrigens ist es bekannt, in so fern es zum Zeitungsartikel wurde, dass der grosse Pitt, als es sich unter seiner Staatsverwaltung um die Eröffnung der Schelde handelte, frug, where is that d. Escaut? — wo ist denn diese verdammte Schelde?

Mit "grosser Pitt" ist sehr wahrscheinlich der Politiker William Pitt der Ältere (1708-1778; ID 7503) gemeint. Ich habe aber Mühe herauszufinden, auf welche Eröffnung JCF hier deuten möchte. 

Ausserdem wäre es eventuell noch interessant dieses Ereignis aufzunehmen (S. 37):
> Seit gestern Abend um 3 Uhr schon wüthete auf dem entgegengesezten Ufer ein Brand der in einer Papierfabrike ausgebrochen war, auch noch mehrere Hopfenmagazine ergriffen hatte, und in den heutigen Zeitungen schon der Schaden für die verschiedenen Assekuranzen 200,000 Pf. Sterling oder 240,000 Gulden angegeben wurde. Um diesen Brand bekümmerte sich kein Mensch als die Sprizenmänner und die Polizeimannschaft, wer etwa nicht aus Neugierde sich ein wenig verweilte. Merkwürdig war dabei, dass, als die Magazine Nr. 1 und 2 mit einer Vehemenz brannten, die fast keine Annäherung zuliess, Nr. 3 gerettet und des Feuers Meister war, dasselbige auf einmal in Nr. 4 ausbrach. Der englische Ausdruk darüber war: „it was the fiend who did it,“ was auf Brandstiftung hindeutet. Fiend ist mit Satan gleichbedeutend. 

Der Brand entfachte sich am 23. Juni 1851 und dauerte min. 2 Tage an. Welche Zeitungen, dass JCF hier meint ist unklar. Im Internet konnte ich keinen kostenlosen Zugriff (Abo notwendig) auf digitalisierte Ausgaben in den Archiven erhalten.
Hast du Nicolau da besser/günstiger Zugang als Student? Für einen Besuch vor Ort ist das Ereignis sehr wahrscheinlich doch zu zeitaufwendig und irrelevant.

**Comment by ChristopherZoller-Blundell** [comment]
Er muss William Pitt den Älteren meinen. Die Frage der Schelde und des Zugangs zur Mündung des Flusses für den Handel war eine internationale politische Frage. Der Zugang zum Fluss war Gegenstand eines kurzen Konflikts während des Kesselkriegs von 1784 und kurz danach während der Französischen Revolution. Im Jahr 1792 wurde der Fluss wieder geöffnet. Laut Wikipedia, nachdem Belgien 1830 seine Unabhängigkeit von den Niederlanden erlangt hatte, wurde im Scheldevertrag festgelegt, dass der Fluss für Schiffe, die belgische Häfen ansteuerten, zugänglich bleiben sollte. Dennoch verlangte die niederländische Regierung bis zum 16. Juli 1863 von den durchfahrenden Schiffen eine Maut.

**Comment by vrukavina** [comment]
Aber zu dieser Zeit hat Pitt der Ältere gar nicht mehr gelebt. Kann es also doch sein, dass JCF sich irrt und hier der Jüngere gemeint ist? Oder ist es durchaus möglich, dass die Eröffnung der Schelde auch zu Lebzeiten des Älteren diskutiert worden war?

**Comment by ChristopherZoller-Blundell** [comment]
Auch Pitt der Jüngere war bereits seit 1806 tot. Es ist verwirrend geschrieben - der grosse Pitt könnte der ältere Pitt oder sein Sohn sein, der als einer der bedeutendsten politischen Führungskräfte der britischen Geschichte galt (und immer noch gilt). Ich denke, dass JCF möglicherweise auch in seinen Gedanken unklar war. Wahrscheinlich ist es am besten, es bei einem offenen Fragezeichen zu belassen und zu sagen, dass es sich auf beides beziehen könnte. 

Eine Frage ist, ob der Zeitungsartikel, den JCF gelesen hat, korrekt war. Ich kann aber keine Artikel über die Schelde im British Newspaper Archive finden. Da die Schelde während der Regierungszeit von Pitt der Ältere erneut zum Thema wurde (ein Thema seit dem 16. Jahrhundert*), würde es passen, wenn er derjenige wäre, der sich nach dem Standort der Schelde erkundigt hätte. Der jüngere Pitt wusste wahrscheinlich, wo sich die Schelde befand. Es war immer noch Thema zu seiner Amtszeit und die Scheldefrage so bekannt, dass sie die Pointe einer Karikatur über die Versuche der Regierung Pitt war, die Niederländer zum Krieg gegen das revolutionäre Frankreich zu bewegen. https://commons.wikimedia.org/wiki/File:John_Bull_in_a_rage_forcing_Nic_Frog_to_fight_against_his_will._(BM_1917,1208.4098).jpg

*Die Schelde war bis nach dem Ersten Weltkrieg immer wieder ein Problem für die internationale Politik. Es gibt einen britischen Bericht aus dem Jahr 1920, der die ganze aus der Sicht der Historiker des Aussenministeriums zusammenfasst. Die Library of Congress hat ihn hier digitalisiert... https://www.loc.gov/item/a22000889/

**Comment by vrukavina** [comment]
Genau. Bei jeder Interpretation kann sowohl der eine als auch der andere Pitt gemeint sein. Ich belasse es dann bei einer nicht vollständig möglichen Identifikation.
Vielen vielen Dank für die Hilfe!

**Comment by NicolauLutz** [comment]
In so einem Fall würde ich beide Interpretationsmöglichkeiten in einer ```<note></note>```darlegen.
