### ISSUE TITLE
Gendanken zum Itinerar

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#62]
Grundgedanke: 
Die Tagebücher enthalten mehr Information zu JCFs Itinerar, als durch einfaches Ort- und Zeittagging reproduziert werden kann. Stichwort Geonarrative. 

Beispiel: 
- Serien: Wir wissen von der Reihenfolge, in der JCF eine Anzahl von Orten besucht hat: Beispiel Stockholm S. 46-47: “Hernach giengen wir”; "Von dem Giesshause giengen wir”; "Von da besuchten wir”
- Zeitspannen: Wir wissen, wie lange JCF an einem Ort war: Beispiel: sechs Monate in Frankfurt
- TPQ und TAQ: wir wissen den Terminus post quem und Terminus ante quem für einen Ort. Beispiel: Frankfurt: Ankunft TAQ: Kaiserkrönung 1792-07-14
- Umgangssprachliche Zeitausdrücke: Beispiel: Frühjahr, Winter

Um das meiste aus den Tagebüchern zu machen, sollte man diese Information möglichst früh berücksichtigen, insb. wenn es um das Design der Website geht (Zeitleisten, Karten). 

Weitere Schwierigkeiten: 
Manchmal Spricht er von der Zeitdauer, in der er an einem Ort weilte. Aber um ein Itinerar zu konstruieren brauchen wir einen Zeitpunkt (Ankunft_Abreise) 
Beispiel: 1794 Frankfurt XIII

Unterschiede in der Dichte der Itinerare:
Makro: Europa, Meso: England Mikro: Birmingham. Ein Itinerar in einem TB kann an verschiendenen Stellen verschieden “Dicht” auftreten. Es wäre möglicherweise sinnvoll, von verschiedenen Itineraren zu sprechen (insb. im TB 1794). 
Daher die nächste Frage: Sollen die Itinerare verschieden getaggt werden? Beispiel: 1794: type=“itinerar_Deutschland” type=“itinerar_Skandinavien”
Problem dabei: wie umgehen mit Places, die zu mehr als einem Itinerar gehören?
Beispiel: 1794: Schaffhausen: Anfang von Itinerar Deutschland und Itinerar Wanderjahre insgesamt 

Andere Frage: 
Kommen Regionen auch ins Itinerar? Wie wird das auf der Karte dargestellt? 
Beispiel: 1794 Hessen, Thüringen
Vielleicht kann man in der Darstellung unterscheiden zwischen gesicherten und möglichen Routen?

**Comment by ottosmops** [comment]
Regionen könnten auch schon mal ausgezeichnet werden und in Anton aufgenommen werden. Allerdings werden im Moment nur Punkte gespeichert. D.h. diese Punkte könnten dann etwas merkwürdig im Itinerar sein, aber das würde ich auch erst dann anschauen, wenn wir erste Itinerare auf einer Karte sehen können.

**Comment by ottosmops** [comment]
Mögliche Routen: ist möglich, aber was bringt es? Wir müssten dann "mögliche Orte und Zeiten" im Text markieren, das könnte über die Anmerkungen natürlich gemacht werden.
