### ISSUE TITLE
Anton: Karte verschwindet nicht, nachdem Geonames vom Eintrag gelöscht wurde

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#65]
Beispiel: Ort_ID 1751

**Comment by ottosmops** [comment]
sollte aber? die geokoordinaten werden aus geonames in die anton DB übernommen ich kann sie vermutlich von Hand löschen, wenn das gewünscht wird

**Comment by ottosmops** [comment]
Habe die Koordinaten bei beiden IDs gelöscht
