### ISSUE TITLE
Anton/Oxygen: In einem TB ein anderes TB erwähnt + "gelber Stahl"

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#66]
JCF schreibt im TB 1851:

> Indessen ist mir diese Verbindung in allen Verhältnissen schon im Jahr 1814 gelungen, und ich machte sie in dem Tagebuch meiner Reise nach England im Jahr 1814, gedrukt 1816 bei H. Remigius Sauerländer in Aarau, unter dem Namen gelber Stahl bekannt.

1. Werden wir die TBs als Sachschlagwörter aufnehmen?
2. Nicolau, hast du auf Anton schon einen Eintrag zu diesem Stahl erstellt? Evtl. unter einem anderen Namen?

**Comment by vrukavina** [comment]
Lösungsvorschlag FE: Das TB als Sachschlagwort aufnehmen. Wie andere Publikationen behandeln.

**Comment by vrukavina** [comment]
Könntest du Nicolau das TB 1814 bitte als Sachschlagwort aufnehmen? Vielen Dank! :)

**Comment by NicolauLutz** [comment]
Eintrag für TB 1794 und TB 1814: 

 https://archives.georgfischer.com/keywords/8519  

Im Kommentar muss noch das TB ergänzt werden, wo das Keyword verwendet wird.

**Comment by vrukavina** [comment]
Super, vielen Dank! Habe ich entsprechend ergänzt.

**Comment by NicolauLutz** [comment]
Eintrag zu Gelbem Stahl ist übrigens auch gemacht:

 https://archives.georgfischer.com/keywords/8522
