### ISSUE TITLE
Taggen in Fussnoten

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#67]
Ich würde gerne im TB 1851 eine Fussnote erstellen und in dieser dann etwas Taggen.
Konkretes Beispiel auf S. 14: 

> [...] sondern durch die im Brennofen erzeugten Kochsalzdämpfe Selterkrugartig verglast sind [...]

Es gibt auf Anton schon einen Eintrag zum Selterwasser. Deshalb würde ich bei "selterkrugartig" eine Fussnote setzen und dort dann aufs Selterwasser verweisen.
Wird das dann später auch so visualisiert werden können wie beim "normalen" Taggen im Text?

**Comment by ottosmops** [comment]
Also da gibt es ja im Moment zwei Möglichkeiten oder? Ohne genaueres Nachschauen wie wir es dann ganz korrekt machen:

```xml
<term id="gfa-terms-...">Kochsalzdämpfe Selterkrugartig</term>
```

Oder 

```xml
Kochsalzdämpfe Selterkrugartig<note>Fussnotentext... <term id="gfa-terms-...">Selterwasser</term>  weiterer Fussnotentext </note>
```

**Comment by ottosmops** [comment]
Ah ok, ja in der Fussnote kann das genauso gemacht werden wie im Text (Popup mit Erläuterung oder Link auf Registerseite mit Erläuterung)
