### ISSUE TITLE
Anton: GFD Laufzeit lässt sich nicht löschen

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#69]
Beispiel: GFD 3/25

Ich habe versucht, die Laufzeit zu löschen, aber wenn ich die Änderung speichere, dann steht immer noch die alte Laufzeit da (ca. 1820)

**Comment by NicolauLutz** [comment]
Link: https://archives.georgfischer.com/objects/127189

**Comment by ottosmops** [comment]
Sorry habe bei mir lokal geschaut. Ich habe das Ereignis (Erstellung) ganz gelöscht, dann ist die Laufzeit weg.
