### ISSUE TITLE
Nicht Wiki Commons, aber trotzdem gute Quelle?

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#70]
Es handelt sich um ein Bild der Maschinenfabrik Karlsruhe, das auch zeitlich sehr passen würde: https://stadtlexikon.karlsruhe.de/index.php/Datei:Ins-0094.jpg

Was denkt ihr, ist diese Seite (Stadtlexikon) als Quelle in Ordnung?

**Comment by NicolauLutz** [comment]
Ich würde sagen schon, insbesondere da der Standort des Originals bekannt ist (Stadtarchiv Karlsruhe).

**Comment by vrukavina** [comment]
Gut. Dann werde ich das Stadtarchiv noch wegen den Bildrechten anschreiben. Danke!
