### ISSUE TITLE
Itinerar/Auszeichnungen

### ISSUE THREAD

**Issue by ottosmops** [GF-Corporate-Archives/gf-johann-conrad-fischer#72]
@vrukavina @NicolauLutz 

Könntet Ihr bitte die Auszeichnungen vereinheitlichen.

- Reiseabschnitte in `<div type="day">` das ein `<date>` mit `@type="travelday"` enthält (das so beibehalten, auch wenn es mehr als ein Tag ist)
- Orte im Itinerar: `<placename>` mit `@type="itinerar"`; wenn die Reihenfolge der Orte an einem Tag nicht der Reihenfolge im Text entspricht, dann `@n` setzen. Wenn der Tag des Ortes nicht eindeutig ist, etwa weil der Reiseabschnitt mehrere Tage enthält, dann auch `@when` bei allen Orten dieses `<div type="day">` setzen
- Bei Personen können wir die erwähnten Personen von den getroffenen Personen unterscheiden. Z.B. mit dem Attribute `@type="met"` 
- Bitte achtet auf Whitespaces. In den Elementen sollten nur die gewünschten Werte stehen. Keine Leerzeichen, Punkte o.ä. am Anfang und keine am Schluss: 

```xml
Den <date when="1851-06-21" type="travelday"> 21. Juny. </date> Nach
```
 Müsste wir folgt aussehen:
```xml
Den <date when="1851-06-21" type="travelday">21. Juny</date>. Nach
```

**Comment by NicolauLutz** [comment]
Wiki angepasst.

**Comment by ottosmops** [comment]
Immer `@n` setzen wenn Ort im Itinerar

**Comment by feggimann** [comment]
inzwischen erledigt
