### ISSUE TITLE
Logo, Schriften Farben

### ISSUE THREAD

**Issue by ottosmops** [GF-Corporate-Archives/gf-johann-conrad-fischer#73]
@feggimann Bitte hier Unterlagen, Vorgaben und/oder Vorstellungen bzgl. CI / Design ablegen.

- Sollen wir das GF Logo unterbringen?
- GF Farben?
- GF Schriften?

Was müssen wir sonst beachten?

**Comment by feggimann** [comment]
Es ist im Moment noch nicht klar, ob sich das Layout am GF CD orientiert oder "frei" ist. Das muss zuerst noch intern besprochen werden.

**Comment by ottosmops** [comment]
OK, Farben und Arial können wir aber sicher schon mal einsetzen. 

- Logo für die Edition? Evtl. Unterschrift?
- Logo GF evtl. in Fusszeile mit e-editiones Logo?

**Comment by feggimann** [comment]
alles in neuem Design geklärt
