### ISSUE TITLE
TB 1814, S. 10: Folgende Länder Taggen als Places oder Keywords (Feldzüge)?

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#76]
"Uebrigens interessirte mich das Schicksal eines unterwegs angetroffenen, seinen Habersack tragenden französischen Offiziers, dem wir aus Gefälligkeit einen Platz in der Kutsche einräumten. Er war nach Ausweis seines Abschieds sechsunddreissig Jahre alt, hatte zweiunddreissig Dienstjahre (weil die Feldzüge doppelt zählen) und neun Wunden; **war in Egypten, Deutschland, Spanien und Russland gewesen**, und bei allem dem noch Unterlieutenant."

**Comment by vrukavina** [comment]
Ich glaube, wir hatten an einer Sitzung abgemacht, dass wir solche Orte nicht als Ortsschlagworte aufnehmen, da es sich um eine reine Aufzählung handelt und sie JCF nicht betrifft. Aber auch aus der Perspektive des Lesers würde ich meinen, dass es interessanter wäre diese Orte als Feldzüge, also unter Keywords, aufzunehmen.
