### ISSUE TITLE
TEI Publisher: Tagging-Probleme

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#79]
Ich bin auf drei Probleme gestossen beim Tagging auf dem https://georg-fischer.tei-publisher.com/. 

1. Beim erstmaligen Laden der Datei wurden die Tags verschoben angezeigt. Ein erneutes Laden der Webseite hat das Problem behoben: 
<img width="1280" alt="Screen Shot 2022-08-04 at 10 45 19" src="https://user-images.githubusercontent.com/92101460/182819129-2ba794fe-377c-4bed-87bc-879e015da294.png">

2. Die Tags, die schon eingebaut waren wurden richtig angezeigt, aber wenn man darauf klickte, wurde nicht die Anton-Seite geöffnet, sondern https://undefined/ 

3. Ich versuchte ein neues Keyword zu taggen. Die Suchfunktion hat das richtige Keyword im Anton gefunden, doch nach dem Bestätigen kam folgende Fehlermeldung: 
<img width="579" alt="Screen Shot 2022-08-04 at 10 51 41" src="https://user-images.githubusercontent.com/92101460/182819456-37075a45-36f1-47cb-8739-fbc4bc5f48f4.png">

**Comment by NicolauLutz** [comment]
Ich habe gerade ein Place getaggd und das hat funktioniert.

**Comment by wolfgangmm** [comment]
Das Problem mit den verschobenen Tags verschwindet im übrigen auch, wenn man das Browserfenster ein kleines bisschen verkleinert/vergrössert. Manchmal ist der Browser beim initialen Laden nicht schnell genug.  Hatte schon mehrfach versucht, das zu beheben, aber noch keinen 100%igen Ansatz gefunden.
