### ISSUE TITLE
1814: S. 24 Hohl oder Hoch

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#80]
"Der Wind war ganz ungünstig, wurde gegen Abend heftig, und die See ging sehr **hohl**."

Ist das wohl ein druckfehler für "hoch"?

**Comment by vrukavina** [comment]
Hast du schon bei Schib geschaut?

**Comment by NicolauLutz** [comment]
Schib schreibt "hoch".
