### ISSUE TITLE
TEI Publisher: Fehlermeldung beim Downloaden einer Datei als XML

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#82]
<img width="448" alt="Screen Shot 2022-08-04 at 12 58 34" src="https://user-images.githubusercontent.com/92101460/182845369-763d62a2-14ab-48fc-8333-73bdad1cdcf5.png">

![Uploading Screen Shot 2022-08-04 at 12.58.34.png…]()

**Comment by NicolauLutz** [comment]
-"document exist / apps / eXide not found"

**Comment by ottosmops** [comment]
Welchen Browser benutzt Ihr? Für die annotations wäre Chrome vermutich das beste. @wolfgangmm kannst Du das allenfalls anschauen

**Comment by NicolauLutz** [comment]
Ich benutze Firefox 78.15.0esr (64-bit).

**Comment by ottosmops** [comment]
Hast Du mal Chrome ausprobiert; wobei das nach einem Serverfehler aussieht. Ich habe @wolfgangmm benachrichtigt

**Comment by wolfgangmm** [comment]
Dieses Problem lässt sich leider nicht ohne Eingriff in die dahinterliegenden Komponenten beheben, wodurch wiederum zunächst ein Release eben dieser Komponenten notwendig wäre.

Vorübergehend habe ich dies nun so gelöst, dass der Link das XML direkt im Browser anzeigt.
