### ISSUE TITLE
Anton/GFD: Bildrecht, wenn nichts angegeben?

### ISSUE THREAD

**Issue by vrukavina** [GF-Corporate-Archives/gf-johann-conrad-fischer#84]
Ich habe diese Karte (https://www.davidrumsey.com/luna/servlet/detail/RUMSEY~8~1~296071~90067565:Birmingham?qvq=q:pub_title%3D%22The%20Illustrated%20Atlas%2C%20And%20Modern%20History%20Of%20The%20World%20Geographical%2C%20Political%2C%20Commercial%20%26%20Statistical%2C%20Edited%20By%20R.%20Montgomery%20Martin%2C%20Esq.%20...%20The%20Maps%20Drawn%20%26%20Engraved%20By%20J.%20Rapkin.%20H.%20Warren.%20J.%20Rogers.%20J.%20%26%20F.%20Tallis%2C%20London%20%26%20New%20York.%22;lc:RUMSEY~8~1&mi=179&trs=198) für Birmingham heruntergeladen (GFD 2/39, https://archives.georgfischer.com/objects/129116?parent=124042&sortField=position&perPage=25&sortAsc=1&index=39). Bei der Originalseite, wo ich die Karte gefunden habe, besteht die Möglichkeit das Bild herunterzuladen etc. aber ich finde nirgends genauere Informationen zu den Bildrechten. Nur zuunterst auf der Seite steht das typische Copyright etc.
Hattest du schon einen solchen Fall? Hast du es dann benutzt? Oder soll ich sicherheitshalber lieber ein anderes suchen?

**Comment by NicolauLutz** [comment]
Beim Copyright stand ein Link der auf folgende Seite verlinkt: (https://www.davidrumsey.com/about/copyright-and-permissions). Hier tönt es eigentlich nach einem Creative Commons copyright (CC BY-NC-SA 3.0)

**Comment by vrukavina** [comment]
Stimmt, vielen Dank!
