### ISSUE TITLE
Geonames: Wood Street falsche Koordinaten

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#85]
Die Wood Street bei Cheapside ist nicht die Wood Street Overground Station auf Geonames.

 https://archives.georgfischer.com/places/1726  

https://www.british-history.ac.uk/old-new-london/vol1/pp364-374

**Comment by feggimann** [comment]
@NicolauLutz ist das erledigt?

**Comment by feggimann** [comment]
@NicolauLutz ist das erledigt? bitte schliessen

**Comment by NicolauLutz** [comment]
Die Koordinaten im Anton sind die korrekten.
