### ISSUE TITLE
Tagebuch 1794: Correct factual inaccuracies? How to annotate?

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#9]
Beispiel: 

- JCF war in 1792 in Frankfurt, nicht in 1793 p
- Admiral Howe 1. Juli Schlacht war im Atlantik und nicht in der Nordsee p20

**Comment by ottosmops** [comment]
`<note>Anmerkung von uns</note>`

**Comment by ottosmops** [comment]
`<note n="*" type="original">Text...</note>
