### ISSUE TITLE
Wiki: Liste für Institutionelle Bildquellen

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#90]
Ich habe eine Wiki-Seite eingerichtet, um Lizenz- und Copyrightbestimmungen von grösseren institutionellen Bildprovidern zu sammeln (Tate, British Museum, Science Museum):

https://github.com/GF-Corporate-Archives/gf-johann-conrad-fischer/wiki/Bibliografien,-Bildquellen,-etc.

**Comment by feggimann** [comment]
Danke! Super! Bitte noch Lizenzart dazuschreiben.
