### ISSUE TITLE
Lizenz: cartorum.fr

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#92]
Verstehe ich das richtig, dass wir die Bilder auf der website gemäss CC BY-SA verwenden dürfen?

https://cartorum.fr/cgu.html

**Comment by ChristopherZoller-Blundell** [comment]
Ich denke, ja. Alle Bilder stehen unter CC BY-SA, es sei denn, die Person, die sie auf die Website hochgeladen hat, etwas anderes unter dem Bild deklariert hat.
