### ISSUE TITLE
Anton: Fatal Error!

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#93]
![Screen Shot 2022-09-06 at 14 25 09](https://user-images.githubusercontent.com/92101460/188646896-d378b2f1-15c1-45fd-b07c-63843f53154d.png)

Ich wollte den Bilddatensatz auf <https://archives.georgfischer.com/objects/129185> verlinken mit <https://archives.georgfischer.com/places/1616>  über das "manual imput"-Feld und bekam eine Fatal Error Meldung. Beim zweiten Versuch geschah dasselbe.

**Comment by ottosmops** [comment]
Hat bei mir problemlos funktioniert
