### ISSUE TITLE
Anton: Fatal Error

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#94]
Ich bekam eine "Fatal Error" Nachricht als ich bei ID 8602 auf "Bearbeiten" klickte. Beim erneuten Laden der Seite kam ich dann auf das Bearbeitungs-Feld.

**Comment by NicolauLutz** [comment]
Erneute "Fatal Error" Nachricht als ich bei ID 8603 auf "Bearbeiten" klickte.

**Comment by ottosmops** [comment]
Also einmalig?

**Comment by NicolauLutz** [comment]
Ja, einmalig. Jetzt scheinen beide IDs keine Probleme zu haben.
