### ISSUE TITLE
Anton: Fatal Error

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#96]
Fatal error Nachricht nach Speichern von manual imput entry (wikipedia (en)) bei Orte ID: 1790.

Auch beim erneuten Laden der Seite kommt die Fatal Error Nachricht.

**Comment by ottosmops** [comment]
Bitte noch die Eingabe schicken, damit ich das reproduzieren kann
