### ISSUE TITLE
Geonames: Neue Einträge werden nicht auf Anton angezeigt

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#97]
Neue Einträge auf Geonames werden nicht durch die Anton Suchmaschine erfasst. 

Beispiel: Etruria Hall 
Geonames: (https://www.geonames.org/12493822/etruria-hall.html)
Anton: (https://archives.georgfischer.com/places/1780)

**Comment by ottosmops** [comment]
Wann hast Du den den Eintrag gemacht? Das kann 4 bis 6 Wochen dauern. Liegt aber an Geonames.

**Comment by NicolauLutz** [comment]
Ok. Es war vor etwa 4 Wochen. Wird man Benachrichtigt, nachdem ein Eintrag
validiert wurde? Oder soll ich es einfac in ein paar Wochen wieder
versuchen?

Am Mi., 21. Sept. 2022 um 17:57 Uhr schrieb anton ***@***.***

**Comment by ottosmops** [comment]
Nein keine Benachrichtigung. Das liegt wohl daran, dass die die neuen Eunträge nur sehr selten auf die Server verteilen. Ich hoffe, dass es bald klappt.
