### ISSUE TITLE
Alle itinerar placenames sollten ein @n haben

### ISSUE THREAD

**Issue by ottosmops** [GF-Corporate-Archives/gf-johann-conrad-fischer#98]
placeName vom Typ "itinerar" ein @n Attribut haben, aus dem die Reihenfolge der besuchten Orte hervorgeht.  Idealerweise sollte das Datum zusätzlich immer im placeName/@when angegeben sein, falls es nicht im selben div ein <date type="travelday"> gibt (manchmal steht das nur in einem vorangegangenen div).

**Comment by NicolauLutz** [comment]
Das sollte im TB 1794 (TB_1), und TB 1851 so sein. TB 1814 soll bis Ende
nächste Woche mit kompletten Itinerar ausgestatted sein.

Am Do., 22. Sept. 2022 um 07:56 Uhr schrieb anton ***@***.***
