### ISSUE TITLE
Recherche: Hydrostatischer Blasebalg

### ISSUE THREAD

**Issue by NicolauLutz** [GF-Corporate-Archives/gf-johann-conrad-fischer#99]
TB 1814, S. 156: 
"Das Prinzip dieser Presse beruht auf dem sogenannten hydrostatischen Paradox, und wenn man die Maschine und die Einfachheit der dabei in Ausführung gebrachten Idee sieht, so geht es einem, wie den Spaniern mit des Columbus Ei: man wundert sich, dass die Sache nicht schon längst erfunden worden, da man etwas Aehnliches in der Physik, nämlich den **hydrostatischen Blasebalg**, schon früher kannte, als diese Maschine". 

Ich habe bis jetzt nichts dazu gefunden. Bei Krünitz wird ein hydrostatischer Blasebalg nicht erwähnt. Bei [Webster](https://www.thefreedictionary.com/Hydrostatic+bellows) von 1914 findet man unter "Hydrostatic bellows" folgendes: 

"an apparatus consisting of a water-tight bellowslike case with a long, upright tube, into which water may be poured to illustrate the hydrostatic paradox."

Der Beschreibung nach handelt es sich wohl um ein Modell aus der Physiklehre, um das hydrostatische Paradox zu veranschaulichen, und nicht um einen industriellen Apparat (wie z.B. eine [Wassertrommel](https://de.wikipedia.org/wiki/Wassertrommel_(Bergbau))).

**Comment by ChristopherZoller-Blundell** [comment]
Hier ist eine Abbildung und Beschreibung (stammt aus einer Veröffentlichung von 1850). https://etc.usf.edu/clipart/28200/28242/hydraulic_28242.htm

**Comment by NicolauLutz** [comment]
Ah super! Vielen Dank.
